### ISSUE TITLE
Allow user to select number of differentially expressed genes

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1003]
Currently the differential analysis is limited to the top 10 genes. It would be nice if the user could input a number for the max number of genes they would like to select.

**Comment by colinmegill** [comment]
Related to https://github.com/chanzuckerberg/cellxgene/issues/994

**Comment by alokito** [comment]
Related to #95

**Comment by bkmartinjr** [comment]
Closing as duplicate of #681.
