### ISSUE TITLE
selecting two values of categorical metadata should allow display of p-value

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1006]
This is to assist users in determining the significance of the difference in expression in the mini-histograms from #827 . Currently it is hard to assess the significance of a difference between the histograms for two values of categorical metadata (i.e. two clusters) when a gene is selected.
Admittedly I don't know what a decent UI for this would look like.

**Comment by alokito** [comment]
see also #1005

**Comment by colinmegill** [comment]
cc @seve

**Comment by signechambers1** [comment]
Closing as a duplicate of #915
