### ISSUE TITLE
When adding a gene while differential expression is active, show the fold change and p-value

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1007]
Currently it just shows the histogram for the gene, would be nice if it showed the stats for the currently selected clusters.

**Comment by signechambers1** [comment]
This is available now, although there is an [outstanding bug](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1888) affecting some results.
