### ISSUE TITLE
Which methods should be “default” when an engine doesn't have a method for a given analysis? 

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#101]
For example, scanpy doesn't provide any methods for differential expression. It sounds like there will be a handful of custom methods for cellxgene to fall back on. How are these being selected? I'm happy to help explore methods and performance here if helpful.

**Comment by bkmartinjr** [comment]
UX Review topic

**Comment by bkmartinjr** [comment]
removing from MVP as it is not an issue for the ScanPy-focused first release.

**Comment by bkmartinjr** [comment]
obsolete, closing.
