### ISSUE TITLE
keyboard [enter] when creating new category throws error

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1010]
Using keyboard Enter key to submit a new category create causes the action to be dispatched with a null string category name, resulting in an Exception "user annotations require string name" thrown by the an error check in the Universe state management code.

Root cause:  in categorical.js, Categories.onSubmit() assumes it will get an onBlur (and save the name to the component state variable newCateogryText) *before* the submit event is received.

This is not true when the user hits [Enter] -- no blur is received.

To reproduce:
1. start with annotations enabled
2. click Create new Category
3. Type a name *and hit Enter*  (do not click the submit button or otherwise use the mouse -- ie, no blur event)

**Comment by bkmartinjr** [comment]
universe.js:53 Uncaught Error: user annotations require string name
    at Universe (universe.js:53)
    at eval (cascade.js:33)
    at save (undoable.js:165)
    at eval (undoable.js:256)
    at dispatch (redux.js:220)
    at eval (index.js:12)
    at Categories.handleCreateUserAnno (categorical.js:44)
    at onSubmit (categorical.js:125)
    at HTMLUnknownElement.callCallback (react-dom.development.js:347)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:397)

**Comment by colinmegill** [comment]
@bkmartinjr I do get this error, but I get it when clicking as well. I also don't see `blur` in that categorical.js but `onChange`, and console logging the state variable newCategoryText demonstrates it is captured `onChange`, which is a keypress.

![image](https://user-images.githubusercontent.com/1770265/68281242-1212bb80-002c-11ea-8561-6dfcd190c232.png)

Before I dig in, do you have an alternate explanation?

**Comment by bkmartinjr** [comment]
You are right - it happens in both paths. 

I did a bit more debugging for you - it looks like the action is being dispatched twice, first with the correct category name, then with an empty category name.

I suspect your form submission is causing the `handleCreateUserAnno()` callback to be called twice.  Once for the button `onClick`, and once for the form `onSubmit`.

If you break in the `handleCreateUserAnno()`, you will see it get called twice.  Because the first call clears the component state, the second call dispatches the same action but with an empty category name.
