### ISSUE TITLE
annotations variously uses 'unassigned' and 'unknown' tag - should be consistent

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1013]
The UI uses both terms for "not yet assigned a label". We should pick one of `unassigned` or `unknown` and then ripple it through the UI.  

See snip below which shows 'unassigned' in the categories, and 'unknown' in the menu:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/fc2c9dee-00ce-4bc2-b298-6656738a456c)

**Comment by bkmartinjr** [comment]
I will fix the example above while fixing #972

**Comment by liaprins-czi** [comment]
I think we should use the term `unassigned` throughout. It seems more agnostic to the user's labeling process (e.g. user may or may not "know" the type but we can always be correct by calling the ones without a label yet `unassigned`).

**Comment by bkmartinjr** [comment]
I actually think that the only case of using `unknown` was in the above screenshot, which is fixed as part of #972.   I'm going to close my own bug as a duplicate!

Thanks @liaprins-czi
