### ISSUE TITLE
App minimum width 1240px 

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1022]
When shrinking the window, the application shouldn't shrink horizontally past 1240px, a scrollbar should appear. This is complicated by our use, to this point, of fixed positioning.

**Comment by seve** [comment]
How would the scroll bar interact with zoom/pan interaction mode?

**Comment by colinmegill** [comment]
cc @liaprins-czi

**Comment by colinmegill** [comment]
@seve hoping we can find a solution upstream of that... should behave normally and stop responding to horizontal browser resize at some point, but otherwise behave normally. Am I missing something significant?

**Comment by liaprins-czi** [comment]
I agree^^^. The main vis area can still exhibit normal zooming behavior. Once the window size gets to 1240px, then the UI width stops shrinking. Instead it would stay the same width (1240px) and user would need to side-scroll to see the right edge.

If that doesn't make sense then I can show you or look for example sites that behave this way, just let me know, @seve ! Thanks!

**Comment by colinmegill** [comment]
This may mean we are moving to `position: absolute` from fixed for the right and left edge of a div which takes up the whole viewport, rather than using the viewport itself. I'm not sure it's possible to accomplish what we want and keep `position: fixed`
