### ISSUE TITLE
Upon cell selection, show gene expression plots split into distributions for (1) the selection and (2) all other cells

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1024]
This was a suggestion from Alejandro Jimenez from the Pe'er lab. Below is a very rough mock of what that could look like (if we switched to using KDEs instead of histos), with the two distributions shown at once. Green in this example could represent the cell selection, grey represent the remaining cells. 

We'd need to think more about how to differentiate and communicate the two distinct distributions. E.g. if by color, which color(s) to use? And how to attach that color to the cells they represent (e.g. legend, etc).

We could keep the genes in the order that user had added them, but we might also want to consider ability for them to sort by highest (total/accumulated?) gene expression for the cell selection.

Also this could be optional, e.g. user can turn it off/on via toggle or similar interaction.

![Screen Shot 2019-11-06 at 8 29 53 AM](https://user-images.githubusercontent.com/53277128/68317237-a2bebb00-006f-11ea-9195-8bab8c8e9e60.png)

**Comment by signechambers1** [comment]
Closing as a low priority for now
