### ISSUE TITLE
Add RNA velocity visualization to cellxgene

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1031]
This information is stored in the [layers](https://icb-anndata.readthedocs-hosted.com/en/stable/anndata.AnnData.layers.html) attribute of the anndata object.
![Screen Shot 2019-11-08 at 10 44 47 AM](https://user-images.githubusercontent.com/789030/68489404-033b2d00-0215-11ea-96ef-4d094de022c8.png)

Links:

- https://www.nature.com/articles/s41586-018-0414-6
- http://velocyto.org

**Comment by dburkhardt** [comment]
### What is RNA velocity?

Copying the description from the #cellxgene-users

RNA velocity is a separate method from pseudotime trajectories. The goal of pseudotime methods is to generate an _ordering_ of cells from an early developmental stage to late. There can be multiple orderings corresponding to different paths of differentiation.

The goal of RNA velocity is to estimate the future state of each individual cell by estimating the _rate of transcription_ for each gene in each cell based on the ratio of spliced:unspliced genes. The result is a prediction of gene expression for cell X at some future time point.

### scVelo
You also should look into using this new tool from Fabian Theis's group: scvelo. It's faster with better assumptions.

https://github.com/theislab/scvelo
https://www.biorxiv.org/content/10.1101/820936v1

**Comment by signechambers1** [comment]
Closing this issue for now but if we get more requests for this functionality in the future we will reconsider!
