### ISSUE TITLE
new right-hand layout clips histogram axis

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1042]
The new right hand layout for continuous metadata will sometimes clip the axis legend/tick numbers

Example:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/ab4cb452-4a21-4f9b-a2ff-3d588429f87a)

this was from loading our example dataset.

**Comment by colinmegill** [comment]
I think this was the case on leftsidebar as well, needs padding

**Comment by bkmartinjr** [comment]
Reassigning to Matt who is looking for a starter bug.  Thanks Matt!

**Comment by colinmegill** [comment]
This problem is not specific to the right sidebar. cc @liaprins-czi 

https://tabula-muris-senis.ds.czbiohub.org/lung/droplet/

![image](https://user-images.githubusercontent.com/1770265/71686099-1965f500-2d4f-11ea-838f-4b14078628d8.png)
