### ISSUE TITLE
re-projecting cells after subsetting

### ISSUE THREAD

**Issue by chenlingantelope** [chanzuckerberg/cellxgene#1047]
I have been using cellxgene for the TabulaSapiens dataset. I am having difficulty balancing having all the cells in one object v.s. being able to visualize small subsets of cells. Distinct clusters can be squished together on 2D map as an artifact of too much other variation. If I supply cellxgene with the full latent space (10-30 dimensional), then cellxgene could in theory re-runs UMAP to generate 2D maps that only contain the cells that are subsetted, and the visualization can make much better use of the space available on the projection. 

I would really appreciate this functionality if possible!

**Comment by colinmegill** [comment]
Thanks @chenlingantelope! We really love this feature idea as well and have been discussing ways to do it since very early in cellxgene's development. 

What kind of access to parameters would you want from the user interface?
