### ISSUE TITLE
New label dialog resizing when entering text

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1050]
Empty textbox:
![image](https://user-images.githubusercontent.com/8716829/69100596-59c51a00-0a12-11ea-8e81-26c57fff546b.png)

After entering text:
![image](https://user-images.githubusercontent.com/8716829/69100610-634e8200-0a12-11ea-97f4-9175755351ef.png)

![image](https://user-images.githubusercontent.com/8716829/69100994-46ff1500-0a13-11ea-8870-3e802e828819.png)

**Comment by bkmartinjr** [comment]
I believe @colinmegill is fixing this as part of his work on #970
