### ISSUE TITLE
docs: tabula muris senis link in docs doesn't work

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1054]
In the docs "Data" page is a curl download link for the Tabula Muris Senis data.

When I use the curl command, it gets an S3 error back (the pbmc3k curl command works fine).

From the docs:
```
curl -O https://cellxgene-example-data.czi.technology/tabula-muris-senis.h5ad.zip
```

**Comment by sidneymbell** [comment]
Fixed via #1030
