### ISSUE TITLE
annotations edit - no way to cancel

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1055]
When I edit a category or label name (user annotations), there is no way to cancel the edit.   There must be a cancel in addition to submit/accept.

**Comment by liaprins-czi** [comment]
NOTE: For 0.14 when we add ability to have ontology suggestions, we end up changing the edit state to happen in a pop-up modal (like when create a new category or label), which would fix this problem anyway. If we don't put edit state into the same sort of pop-up modal (which has a cancel button), then I will work on a design for this.
