### ISSUE TITLE
Feature request: specify differential expression cutoff

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1059]
Would like the ability to specify the cutoff for differentially expressed genes, either as an fixed number of p-value cutoff

Cc: @alokito 

Related to #681

**Comment by colinmegill** [comment]
Related to #994

**Comment by liaprins-czi** [comment]
Also related from Angela:
"for differentially expressed genes, can you return top 5  and bottom 5 instead of top 10"...

**Comment by sidneymbell** [comment]
Updates:

1 - We already return the N genes with the greatest _magnitude_ of difference between the two groups (regardless of which population they are 'higher' in). 
2 - The current log fold change threshold is functionally broken #1159 
3 - From conversation with @aopisco, the ideal would be to export the full list of diffexp genes (#1158), but being able to set a higher number of genes to return would be a good stopgap.

Thus, I'd propose the following [self-assigning]: 
1 - Add a CLI arg to specify the number of genes returned, N (capped at something reasonable like 100)  
2 - Change the behavior in `diffexp.py` such that we return **up to** N genes that also meet the log fold change threshold  
3 - If there are less than N genes that meet the lfc threshold, return fewer than N genes; if there are more than N genes that meet the lfc threshold, return the top N with the greatest lfc.

**Comment by aopisco** [comment]
@sidneymbell I'd use a hard-coded lfc threshold, something like 0.7, and not having that as a parameter of choice for now given our discussion about best practices for scDGE. When you then build a more robust DGE analysis as part of cellxgene you can increase the flexibility without compromising the accuracy. For now I'd say we can emphasize this analysis is indicative and should be used to derive hypothesis, not to draw conclusions

**Comment by alokito** [comment]
Would it be possible to add a UI to the application to change the criteria (i.e. N genes, or threshold value) while cellxgene is running? That way you wouldn't have to restart to adjust this.

**Comment by signechambers1** [comment]
We have increased the number of differentially expressed genes to 50 highly expressed genes in each selection in the cellxgene 0.17.0 release. We hope this is helpful! We aren't planning to prioritize allowing a user to specify the cutoff at this point so I am closing this issue but please let us know if the latest functionality in 0.17.0 is not adequate.
