### ISSUE TITLE
Improve continuous selection tool

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#106]
![image.png](https://images.zenhubusercontent.com/5588c9564f7a08fbb7f35803/f1b22045-454c-4e62-a41e-c60fa269c977)

**Comment by colinmegill** [comment]
So a couple ideas here... log Y axis and a control to flip back and forth between lin and log. Opening issue for discussion.

**Comment by sidneymbell** [comment]
This looks awesome! Thanks, @colinmegill. A few thoughts:  
1 - Putting the y on a log scale does make it way more interpretable (for starters, you can actually see the bars on the right :D)   

2 - Only minor concern is that people may expect to see the x axis (expression) on a log scale, but are probably expecting a linear scale on the y (N cells). I think this is OK as long as it's clearly labeled?  
Curious to hear your thoughts here, @freeman-lab.  
(FWIW, based on what Josh has recently found re: log scale and differential expression, IMO it's still very ambiguous whether or not expression _should_ be on a log scale anyways).    

3 - How many instances are there where it's clearly more interpretable to have a log scale for one variable (i.e., values are far apart), but a linear scale for another (i.e., a log scale is deceptive or needlessly confusing)?  
Trying to figure out if we even need the little button to change the scale. I like that you added little visual hints in the form of icons! Mildly worried it would eventually become a bit cluttered with many plots. If we can just make a decision behind the scenes, I think it's maybe OK to omit them as long as all the y axes are the same (both limits and scale)?
