### ISSUE TITLE
experimental-annotations-file

### ISSUE THREAD

**Issue by Jon-bioinfo** [chanzuckerberg/cellxgene#1065]
When I run cellxgene (0.13.0) with the --experimental-annotations and --experimental-annotations-file flag the file I specify doesn't seem to be created.

If I give --experimental-annotations-file a file with annotations which already exists, those annotations are loaded but then never edited / updated.

Running --experimental-annotations alone, or --experimental-annotations and --experimental-annotations-output-dir work as expected.

EDIT:
Reading a bit more, maybe this is by design for a hosted environment.

So it's not possible for multiple users to edit the same annotation set, or view other users annotations (without going and merging them into the h5ad file)?

**Comment by sidneymbell** [comment]
@Jon-bioinfo thanks so much for flagging this! 

You are correct that by design, the annotations in the CSV are meant to be individual and temporary. However, as you illustrate, this is currently confusing.

Can you share a bit more about this part of your issue? This isn't expected behavior.
>If I give --experimental-annotations-file a file with annotations which already exists, those annotations are loaded but then never edited / updated.

1 - What command where you using to launch cellxgene?  
2 - What do you see in the directory where the input CSV was located?

**Comment by Jon-bioinfo** [comment]
I think the problem was due to my lack of understanding or confusing docs, because I'm using a hosted environemnt.

On a hosted environment if I run `cellxgene launch data.h5ad --experimental-annotations --experimental-annotations-file test_anno.csv` then the annotations from that file are visible in the browser but if they are updated in the browser, the csv file is not updated, and no other files are made/changed.

The larger issue I was looking at solving was collecting cell annotations from an external collaborator, thinking about the option of hosting an instance of cellxgene on our server, and then collecting the annotation csv file afterwards.
I suppose this is also possible, if I find the name_randomID.csv file they they have used.

**Comment by sidneymbell** [comment]
Hi @Jon-bioinfo --

Your use case is exactly what we'd like to address! The short answer is
that yes, you should run with `--experimental-annotations-output-dir` and
look for each collaborators file, `name-userID.csv`.

My understanding is that you'd like to:
1 - You launch a hosted cellxgene instance with a specific file path
specified (existing or empty csv, `collaborator-annotations.csv`)
2 - Collaborator1 makes annotation edits in cellxgene, saved in
`collaborator-annotations.csv`
3 - Collaborator2 makes annotation edits in cellxgene, saved in
`collaborator-annotations.csv`
4 - You look in `collaborator-annotations.csv` for the contributions of
both collaborators

The tricky part here, though, is that if they're writing to the same file,
the edits made by Collaborator2 will _overwrite_ those made by
Collaborator1.

I've [updated the docs](
https://github.com/chanzuckerberg/cellxgene/blob/fcf56c20b2a3309a5fda5bc9d78fefbbf4dbc683/docs/posts/annotations.md)
to
clarify the difference between single-user and multi-user annotation modes.
Please take a look at either (1) close the issue if this solves your
problem or (2) let me know how I can help.

Sidney Bell, PhD
Computational Biology
Chan Zuckerberg Initiative

she, her | twitter <https://twitter.com/sidneymbell> | github
<https://github.com/sidneymbell> | calendar
<https://calendly.com/sidneymbell>

**Comment by Jon-bioinfo** [comment]
Your steps of 1,2,3,4 were my initial thought, now I understand that if they were to access the instance at the same time they would just overwrite eachother. Thanks.
