### ISSUE TITLE
Request for comment: gene list functionality & data structure

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1069]
## Data structure  
* Lists are **not mutually exclusive**: a gene may be present in multiple lists  
* Lists are **nonredundant**: a gene may only be present once in a given list
* Lists are **ordered**: gene position in a list is meaningful
* Lists are **nonexhaustive**: not every gene will appear in a list  
* Lists have **variable length**
* Lists names are strings that follow the same conventions as category names  
* Feature names (i.e., genes) are present in `var_names`

e.g., 
```
{'cardiomyocyte_markers' : ['gene1', 'gene2', 'gene3', 'gene0'],
'microglia_markers': ['gene1', 'gene7, 'gene4']}
```

## Loading gene lists    
We should load gene sets from three places:  
1 - `adata.uns['rank_genes_groups']` 
These are the results of precomputed one-vs-all differential expression, and include the log fold change and adjusted p-values.
 
Input: structured arrays as described [here](https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.rank_genes_groups.html)  
Output: gene set with title `name vs. all`, contents are gene histograms as rendered for differential expression (i.e., include log fold change and p-values), ordered by log fold change  

2 - any `.uns` field specified at the command line  
`--gene-sets-field [Default: None`]
`Name of field in adata.uns to look for gene set definitions; expects a dictionary of lists or a dictionary of sets.`

Input: dictionary of lists, tuples, or sets. Aligns with scanpy [specification of marker genes](https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.marker_gene_overlap.html#scanpy.tl.marker_gene_overlap).
Output: gene set with the title `key`, contents are gene histograms rendered in the order they were provided (if list or tuple) or alphanumerically sorted (if set)

* from a CSV that mirrors the cell annotations data format  
Example prepared [here](https://gist.github.com/sidneymbell/af2e54dcf3b282f550a4f6292dfffe41)  
 
## Interacting with gene lists  
Core functionality:  
* Add and remove genes from lists    
* Color by & select by overall expression of all genes in a list (method TBD)  
* Duplicate existing lists (similar to existing cell annotation affordances)   
* Move and copy individual genes between lists (e.g., drag and drop)  

## Saving gene lists  
**Still noodling on this; open questions**  
1 - JSON (easier merge and more 'correct') vs CSV (easier to edit, ship around and deal with)  
_Current thinking: CSV_
2 - Autosave to separate file as for cell annotations?
_Current thinking: yes!!_
3 - Mutable vs nonmutable groups as for annotations?  
_Current thinking: ???_

## Implementation plan
[MVP -> full CRUD cycle](https://drive.google.com/open?id=17UhMdorfgxjJ3eKDJDvH0zl4S2u9YCGwmXMoIIFvB-Q)

**Comment by seve** [comment]
What will happen when a gene list is loaded which holds genes not present in the dataset? If the answer is to not error and load the gene list, what will happen when the user mutates this gene list?  Are we going to allow user-created gene lists to hold genes that are not present in the dataset?

**Comment by sidneymbell** [comment]
@seve -- great questions! I'm not sure on this one. My initial thought:

If a listed gene is not in the dataset, we should warn them in the UI (but not error). A lot of genes get filtered out in preprocessing, but this can vary quite a bit depending on what parameters you used upstream. I.e., I expect this to be a common occurrence, and no one likes having to dig through a csv to figure out which item(s) are wrong; it'd also confuse a lot of folks.

@liaprins-czi -- do you have time this week to noodle together on what the output data structure / flow should be? I'd love your input on this!

**Comment by liaprins-czi** [comment]
Great question @seve and thankd for bringing my attention to this, @sidneymbell ! I am trying to finish some things for the DCP browser this week, but let's talk about this at our 1:1, Sidney, and see how far we get.

My first thought is that in the UI, within the gene list, we should somehow list at the end the genes that could not be loaded. But that is just addressing within the UI anyway, so we can go over what else there is to consider

**Comment by liaprins-czi** [comment]
For reference, here is my first thought for how to indicate in the UI when listed gene list genes are not available:

<img width="284" alt="Screen Shot 2020-02-14 at 1 49 17 PM" src="https://user-images.githubusercontent.com/53277128/74570264-26225f00-4f31-11ea-851e-bbd144484925.png">

**Comment by ambrosejcarr** [comment]
> Lists are ordered: gene position in a list is meaningful

I understand that we would like lists generated by cellxgene to be meaningful. How would we deal with user-generated lists? Will we expect them to have saved them in ordered form? 

> > What will happen when a gene list is loaded which holds genes not present in the dataset? If the answer is to not error and load the gene list, what will happen when the user mutates this gene list? Are we going to allow user-created gene lists to hold genes that are not present in the dataset?
>
> If a listed gene is not in the dataset, we should warn them in the UI (but not error). A lot of genes get filtered out in preprocessing, but this can vary quite a bit depending on what parameters you used upstream. I.e., I expect this to be a common occurrence, and no one likes having to dig through a csv to figure out which item(s) are wrong; it'd also confuse a lot of folks.


I think this is a super interesting question with a lot of interesting edge cases that would influence the design of our UX. Apologies if @sidneymbell has already thought through this somewhere. 

* All filtered. Potential cause: incompatible gene lists
* A few filtered. Potential cause: gene filtering during analysis reduces dataset feature number, capitalization issues in gene set or data set, imperfect user-attempted translation between one of the many different genomes/gene sets, gene set and data aligned to different genome version, ...

Gene sets _could_ carry some simple metadata (genome version, gene ID type) that would help resolve some of these issues, but it seems likely that most users with legacy gene sets will be missing these information.

**Comment by signechambers1** [comment]
Closing, tracking implementation work [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/64)
