### ISSUE TITLE
Need UX to handle non-unique gene names

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1081]
Many datasets will have easy-to-use, human-friendly gene names labeling the count matrix columns, as well as unique accession ids (eg, an ensembl ID).    These "common names" are not necessarily unique.  Our current app will only let users search by a unique gene "name", which is problematic for datasets containing duplicate human-readable names.

Ideally, users would like to:
* Search by an accession ID when they want to be very specific (eg, 'ENSG000....')
* Search by a human-friendly common name most of the time (eg, 'MATR')

I suspect that in the second case, users will want to know that the dataset contains multiple columns for the common name, as these may be only slightly different.

Concrete example:  the standard count matrices from the HCA index each column with an accession ID (which is unique), and store a human-readable gene name in a non-unique gene column.    These roughly follow the [Loom conventions](https://linnarssonlab.org/loompy/conventions/index.html#row-attributes).

Here is an example of the gene (var) annotations for a couple of columns:
```
>>> ad.var[ad.var.Gene == 'CD99']
                       Gene chromosome  featureend             featurekey  featurestart     featuretype genus_species  isgene
index                                                                                                                        
ENSG00000002586        CD99       chrX     2741309        ENSG00000002586       2691179  protein_coding  Homo sapiens       1
ENSG00000002586_PAR_Y  CD99       chrY     2741309  ENSG00000002586_PAR_Y       2691179  protein_coding  Homo sapiens       1
```

Another:
```
ENSG00000015479  MATR3       chr5   139331677  ENSG00000015479     139293648  protein_coding  Homo sapiens       1
ENSG00000280987  MATR3       chr5   139331671  ENSG00000280987     139273752  protein_coding  Homo sapiens       1
```

For comprehensive, reference datasets, this non-uniqueness will be common -- per Marcus, biomart shows ~2500 gene names with multiple ensembl IDs.

CC: @mckinsel - feel free to augment this with more information if I missed anything important.

**Comment by signechambers1** [comment]
Closing per conversation with @mckinsel, "we've transitioned to requiring feature labels that are both human-readable and unique in the hosted/remixed data."
