### ISSUE TITLE
Histogram bars are often different widths and each histogram has a different number of bars

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1082]
#1042 may be relevant

Bar widths, sizes, and position inconsistent across histograms, particularly post-clipping.
- Left most bar is cut off, needs margin
- Right most bar is sometimes larger than others
- ↓ Sometimes bin count appears to be different between different histograms 

![Screen Shot 2019-08-22 at 2 26 10 PM](https://user-images.githubusercontent.com/53277128/71686055-fafff980-2d4e-11ea-9ac8-bc0c25451830.png)

**Comment by mweiden** [comment]
One clue: this seems to be an issue with the way that the bins are actually generated rather than how they are rendered.

**Comment by bkmartinjr** [comment]
I looked at this a long time ago, and if memory serves, it is a d3 behavior (or how we use d3).   That said, we should definitely fix it.
