### ISSUE TITLE
Swatch mismatch

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1091]
I have not reproduced this error, and it is likely connected to #1090. 

When hovering over a duplicated label, let's say this is a new category duplicated from mouse gender and the hovered value is female and the swatch is purple. Green dots lit up in the graph. Likewise, hovering on orange lit up purple. 

This resolved on refresh, once unassigned was present. It seems more likely this is connected to unassigned being missing than to the hovering code which has been solid.

**Comment by bkmartinjr** [comment]
To clarify - was the hover-over color mismatch on the category you duplicated, or the newly created category?  Ie, on the source category, or the copy/new category?

**Comment by bkmartinjr** [comment]
after more investigation, I don't see an obvious link between this symptom and the root cause of #1090.   I'll leave this open for a while on the chance you find a reproducible test case.
