### ISSUE TITLE
Info menu should not show hover states for items that aren't links

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1093]
When I open the info menu from the top right, then hover on the dataset's filename, or on "MIT License" they both have a hover state just like the links out to the docs above them. However, when I click on the dataset's filename or on "MIT License" they don't take me out to any linked page. It would be better if they don't have a hoverstate at all.

**Comment by bkmartinjr** [comment]
Good catch - we should not assume all values are present in the app configuration, and should make the presentation optional.

**Comment by signechambers1** [comment]
Closing as won't fix
