### ISSUE TITLE
Labels + their assigned colors should have a more meaningful sort order

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1095]
- [ ] When a category is toggled open, the labels within it should appear in alphabetical and/or numeric order (alphabetical if letter characters, numeric if number characters) similar to how they are today, but with one update: Any label called `nan` (or `Nan`, `NaN`, etc) _or_ called `Unassigned` should go down to the very bottom. (Currently the `nan` labels are sandhiched between label starting with an "m" and label starting with "o".)

- [ ] Also, the colors assigned to labels should follow this sort order, so they look like they are in a rainbow spectrum from top to bottom.

**Comment by bkmartinjr** [comment]
Root cause is that we do not apply the same presentation sort order for label rendering and label color assignment.  It makes a lot of sense that they would be consistent.   Will fix.
