### ISSUE TITLE
Intentionally sort the order of the embedding choices

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1097]
Currently we do not intentionally sort the embedding choices which appears as a list when user clicks to change the embedding. We should put them in an intentional order: string (unicode) sort should work (as @bkmartinjr suggests) because the list is usually short and the names are fairly simple.

**Comment by colinmegill** [comment]
Linking to #1020

**Comment by bkmartinjr** [comment]
@colinmegill - #1020 is a completely unrelated issue.  This issue is just the order of the names in the drop-down menu.
