### ISSUE TITLE
Better handling for too many labels

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1100]
Currently we do a hard (relatively arbitrary) cutoff when there are way too many labels for a given category: that is, only the "top" X number of labels are shown, as determined by our default sorting mechanism. The user cannot access the labels that were cutoff, meaning they cannot see their names or colors (when colored by), they cannot hover over them to see where they occur in the main vis, and they cannot turn them on or off with the checkboxes, because they are not visible.

We need a better way to handle too many labels, and one that gives the user more control ideally.
Here are some initial ideas:

- Allow label order to be sortable, e.g. alphanumeric A -> Z, alphanumeric Z -> A, most to least number of cells per label, least to most number of cells per label (those are the only I can think of). 
**Implications:** Does color assignation stay stuck to initial/default sort order? Also, allowing resorting does not necessarily fix everything we'd need it to ... if the list is sufficiently long, the user may never see the labels in the "middle" of either sorting parameter. However, allowing user sorting could still be helpful in general, especially if we tied it to the dots z-stacks: #1020 

- "Show more" buttons at the bottom of each currently shown chunk of the whole ... if we default to showing top 50, then clicking the "Show more" button would lengthen it to top 100, with another "Show more" button at the bottom of that, which clicking would in turn lead to showing top 150. We'd also need a "Show less" button that would return to the default view...
**Implications:** Not very elegant, but it gives the user the control to see more or all if they choose, while still keeping the default view simplified. 

- Mimic the gene add method: let users add the labels they want by searching for them, aided with an autosuggest list limited to the remaining (not shown) labels for that category. We could limit the number of labels shown at any time to just the most recently added/searched for X labels if we needed to minimize the number of labels shown in the UI.

**Comment by signechambers1** [comment]
This is an issue but closing as a low priority for development in 2021.
