### ISSUE TITLE
No valid layout data (...malformed shape or data type: umap)

### ISSUE THREAD

**Issue by mxiang128** [chanzuckerberg/cellxgene#1118]
Hi,

I created an very simple AnnData object following the "Data format requirements" in the documentation but when I tried to run cellxgene launch I got the following message:

cellxgene launch test.h5ad 
[cellxgene] Starting the CLI...
[cellxgene] Loading data from test.h5ad, this may take a while...
[cellxgene] Warning: Ignoring layout due to malformed shape or data type: umap 
server.app.util.errors.PrepareError: No valid layout data.

Compared with the pbmc3k.h5ad umap, still couldn't figure out the cause...

Data is here: https://www.dropbox.com/s/usy6d910dk18j7h/test.h5ad?dl=0

Thank you,
Menglan

**Comment by bkmartinjr** [comment]
Hi @mxiang128 - thanks for trying cellxgene

Your X_umap embedding contains NaN values.  cellxgene expects all embedding coordinates to be real (finite) numbers.  If you set those NaNs to a finite number, the data should load.

Example:
```
>>> import anndata as ad
>>> t = ad.read_h5ad('test.h5ad')
>>> t.obsm['X_umap'][172:180][:]
array([[        nan,         nan],
       [ 5.97423356,  0.27516306],
       [ 4.26222519, -3.65122441],
       [-7.6325557 ,  0.11134613],
       [-7.0981499 , -2.93385764],
       [ 4.06184186,  4.50896895],
       [        nan,         nan],
       [-8.20056641, -0.92848175]])
```

CC: @sidneymbell
