### ISSUE TITLE
resolve pinned anndata package requirement

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1123]
AnnData 0.7* is not compatible with cellxgene at the moment. The 0.14 release will pin the dependency to the 0.6.22post1 version of anndata.

We need to resolve the incompatibilities and then remove the pinned dependency.

Related: #917

**Comment by alokito** [comment]
This bit me this morning when we redeployed a server... between this and the h5py issue, might be worth pinning all dependencies, at least for released versions.
