### ISSUE TITLE
server error when running

### ISSUE THREAD

**Issue by mAGLAVE** [chanzuckerberg/cellxgene#1128]
Hi,
I have an internal server error when I run the example:

`~$ cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3h5ad`
[cellxgene] Starting the CLI...
[cellxgene] Loading data from adata_test.h5ad, this may take a while...
[cellxgene] Warning: Scanpy data matrix is sparse, but not a CSC (columnar) matrix.  Performance may be improved by using CSC. 
[cellxgene] Launching! Please go to http://127.0.0.1:5006 in your browser.
[cellxgene] Type CTRL-C at any time to exit.

And when I click on the adress:
[2020-01-27 11:42:58,253] ERROR in app: Exception on /api/v0.2/config [GET]
Traceback (most recent call last):
TypeError: Object of type Version is not JSON serializable

On the browser:
e.universe is null
Unexpected HTTP response 500, INTERNAL SERVER ERROR -- {"message": "Internal Server Error"} 

The same problem occurred with my own dataset.

**Comment by bkmartinjr** [comment]
The most recent AnnData release broke compatibility with cellxgene.  We are working on a fix. 

In the meantime, there is a workaround in #1125 

Please reach out if this does not resolve the problem.

**Comment by mAGLAVE** [comment]
I saw that before. I made this test with the good version of annData:
`anndata                   0.6.22.post1               py_0    bioconda`

**Comment by mAGLAVE** [comment]
I found the problem: I re-installed scanpy and it's work. I worked with scanpy before the installation of cellxgene and maybe is not the same version.
Thank you very much for your help!
