### ISSUE TITLE
Opening a dataset on hosted should default to coloring by the first category in LSB

### ISSUE THREAD

**Issue by jenzopr** [chanzuckerberg/cellxgene#1135]
Hi cellxgene-Team!

A small, but effective addition would be to allow a cell label to be colored by default. This would aid a user that visits the (hosted) instance for the first time by directly pointing him/her to an important aspect of the data (e.g. coloring by a _celltype_ label). 

Along this line, the toggle to show labels (btw an amazing addition from `0.14`!) could be allowed to be switched on by default as well.

Let me know what you think! 

Best,
Jens

**Comment by colinmegill** [comment]
Love this idea!

**Comment by bkmartinjr** [comment]
Would this be better solved by picking a better start-up default for the UI?  In other words, rather than starting the app with "nothing selected, no labels shown", start the app with "color by first category, with labels shown"?

What heuristic could be used to pick the category used?  (first in the category list?)

I'm reluctant to adding a CLI parameter to do this, as it is just another hard-to-discover feature that many users will not use.

**Comment by jenzopr** [comment]
@bkmartinjr that's a good idea! In Python, the column order of `adata.obs` can be specified - so colouring by the first column in the list would be fine for me (reminder: there needs to be some logic for a numeric column being first in the list).

**Comment by bkmartinjr** [comment]
@mweiden - please chat with @liaprins-czi on UX design before we implement

**Comment by liaprins-czi** [comment]
In the initial request, it sounded like the idea was to be able to color a single celltype label, rather than coloring by the entire category. Just curious if coloring by an entire category, wherein each label gets its own color, meets the original need? If not, can you explain the need for a single celltype being colored alone, @jenzopr ? Thank you!

**Comment by mweiden** [comment]
@bkmartinjr definitely

**Comment by colinmegill** [comment]
@liaprins-czi @jenzopr I interpreted the request as, in visual form: "one of the paint swatches / color by category buttons should be 'on' by default when a user loads the app up, and I want to be able to specify which one."

![image](https://user-images.githubusercontent.com/1770265/73677390-fe96e100-466a-11ea-9240-69ef26e80bdd.png)

**Comment by jenzopr** [comment]
Pardon my "semantic" inaccuracy @liaprins-czi. I indeed meant coloring by an entire category by default. Thanks for clarification!

**Comment by liaprins-czi** [comment]
Thanks @jenzopr ! I just wanted to be sure :)

**Comment by liaprins-czi** [comment]
Okay, I have been thinking about this a lot. Given that the goal is to help a first-time visitor (and anyone else, really!) to see initial value and functionality right off the bat, via the coloring of a category, I think we should just default to having the top-most category in the list be colored by default. I think this is great default functionality to have overall!

If user has to add a CLi flag to do this, it is likely to _not_ be used by a first-time user.

I do not think it's necessary to have the centroid labels be able to be turned on via the CLI, though. I think it's just as easy (easier, really) to do that with the button we currently have.

**Comment by colinmegill** [comment]
1. I support default colorby being 'on' for the first category in the list
2. But not for ontologies. There are too many edge cases like the one below, that would make the app look quite bad for users on load — we lose quality control of how it looks. If ontologies are going to be on by default in the publication use case, we have to have a setting (and maybe we hold off on this as configuration enabled in the cloud version where all CLI params become 'buttons and dropdowns') where the owner of the dataset specifies which category should be colorby/ontology

![image](https://user-images.githubusercontent.com/1770265/73900119-93543700-4843-11ea-95ad-c50c9b9aad1f.png)

**Comment by liaprins-czi** [comment]
@colinmegill I am not sure what you mean when you say ontologies? Do you mean if the first category happens to be based on cell ontologies? If so, how can we know this without making massive assumptions (if the category came in with the h5ad, that is)?

Or did you mean centroids instead of ontologies?

**Comment by colinmegill** [comment]
Gha! I did mean (and edited my comment to reflect) `centroids`. When I was writing it, I was thinking not about our `ontologies` feature but just as categorical metadata as an "`ontology`" for cells, in the abstract. Super unclear. Sorry!

**Comment by colinmegill** [comment]
I believe, if I read your comment correctly, that we agree the centroids should be controlled by the user rather than the CLI for now (ie., cloud might change this as a nice to have config option)

**Comment by jenzopr** [comment]
Hi both! Having a CLI switch for centroid labels being turned on by default would be a plus, but if your decision is to have default coloring by the first category in the list, then that alone would be great and you'd have made me very happy😃  Thanks for the nice discussion and thinking this through together!

**Comment by liaprins-czi** [comment]
Thanks @jenzopr ! Can you elaborate a bit on why you'd want to be able to turn on centroids via a CLI flag rather than simply using the button in the UI? Just curious if we're not considering something. Thanks!

**Comment by jenzopr** [comment]
I'd love to, @liaprins-czi 🚀 ! Currently, my role as computational biologist is more like a provider, *providing* data sets with cellxgene for "my" users, which are biologists or medical doctors. They have a strong drive towards exploring the data on their own, but many are inexperienced with data (analysis) from single-cell experiments. In my view, a first-time visitor of cellxgene that is "greeted" with a familiar-looking UMAP dimension reduction with the same colors and labels as in Figure 2A of the paper will be just happy. Not so much with a bunch of grey points without labels.
Speaking about me, I am happy with Jupyter notebooks or the command line. So, maybe the catch is to distinguish between different cellxgene user roles or user levels - and for me, deciding on the looks (category to color by, labels on by default) and "capabilities" (enabled/disabled differential expression, enabled/disabled custom annotations) of the apps that I will provide to "my" users is what I'm currently looking for. I hope I didn't kill you with too much elaboration 😇

**Comment by jenzopr** [comment]
We can of course discuss and elaborate more on your slack channel, if this goes too off-topic!

**Comment by liaprins-czi** [comment]
Thanks for your in-depth response, @jenzopr. At this point the labels/centroids feature is very new, so maybe we can keep an ear out for how people end up using it, before we decide to make a flag for it in the CLI. Thanks again for your ideas!
