### ISSUE TITLE
it appears the labels do not adjust when panned or zoomed

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1137]
I noticed this in 0.14.0 after a pip install.

my steps:
virtualenv tempcxg
source tempcxg/bin/activate
cd tempcxg
pip install cellxgene
which cellxgene # verify the correct one is in my path
cellxgene --version # verify it is 0.14.0
cellxgene launch ~/data/pbmc3k.h5ad

Now label the cells and then pan the view,  the labels do not move.

**Comment by jenzopr** [comment]
True for me as well. See below (I moved the cells, but labels stayed on their initial position)
<img width="967" alt="image" src="https://user-images.githubusercontent.com/8362850/73433949-1f4af800-4346-11ea-8c30-9653b3548a3e.png">
