### ISSUE TITLE
branding: become cellxgene

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#114]
- [x] Repo name
- [x] documentation
- [x] front-end
- [x] back-end (help, Py package, etc)

**Comment by csweaver** [comment]
The only location currently not all lowercase is the window object: window.CELLXGENE. I'm ok with this. Any objections @colinmegill @bkmartinjr ?

**Comment by bkmartinjr** [comment]
OK w/ me

**Comment by colinmegill** [comment]
I like all caps for that
