### ISSUE TITLE
AnnData 0.7

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene#1142]
Hello!

I've been running into some trouble with using cellxgene along with AnnData 0.7. I'm a little surprised by this since I didn't seem to run into issues using pre-release version of anndata, and files it wrote. Issues often look like:

```
[2020-02-05 15:13:31,778] ERROR in app: Exception on /api/v0.2/config [GET]
Traceback (most recent call last):
TypeError: Object of type Version is not JSON serializable
```

* Any idea what's up? Did we break something?

**Comment by bkmartinjr** [comment]
There is an incompatibility between cellxgene and the 0.7.* AnnData.  We pinned the dependency until it is resolved.   Historically there has also been a required number of performance work-arounds for the various array storage types (sparse, etc) so it may take a while to validate given the magnitude of the 0.7 changes.

There is an initial work-around in our master branch if you want to play with that.

**Comment by bkmartinjr** [comment]
Apologies - I accidentally closed this!

@ivirshup - we also are having trouble with the regression in compatibility with h5py described in theislab/scanpy#832.

**Comment by ivirshup** [comment]
> There is an incompatibility between cellxgene and the 0.7.* AnnData. We pinned the dependency until it is resolved.

FWIW, everything seems to be working fine with these versions:

```
scanpy                            1.4.5.post3.dev15+g78125e6
anndata                           0.7.2.dev5+ge4581ab
cellxgene                         0.14.1
h5py                              2.10.0
pandas                            1.0.1
```

It's unclear to me what combinations of versions were causing problems previously.

> Historically there has also been a required number of performance work-arounds for the various array storage types (sparse, etc) so it may take a while to validate given the magnitude of the 0.7 changes.

I'm wondering if it would be worth running tests against each others development and release versions so we can be aware of major incompatibilities before they make it into a release. I believe a number of the pydata ecosystem projects do this.

> I am seriously thinking about moving to pinned dependencies for scanpy/anndata/h5py so we can have a more stable release process. Any thoughts or comments on that?

It really depends on how you're interacting with the anndata object and where issues are cropping up. If you are relying on internals (things that aren't documented or have not been confirmed to be API features), then yes. If not, incompatibilities are likely a bug in `anndata`.

As a user, I think pinned dependencies would definitely make sense for a provided server image. I think it might be too much of a restriction for a `pip` distributed package.

**Comment by vals** [comment]
@ivirshup For the combination that you found working, do you know if the `H5AD` file you were using was saved with `AnnData' 0.7 or an earlier version?

**Comment by bkmartinjr** [comment]
This points out another issue with pinned versions I had not considered -- AnnData does not guarantee forward compat with data, only backward compat.   So if we pin to an older version of AnnData, datasets created on newer ScanPy/AnnData may not be able to load.   That seems like a pretty serious loss of function, at least during the time it takes us to validate/fix the incompatibilities.

> I'm wondering if it would be worth running tests against each others development and release versions so we can be aware of major incompatibilities before they make it into a release. I believe a number of the pydata ecosystem projects do this.

We might be open to it, as we have repeated instances of needing to hot patch our software after a major AnnData release (no implication of who caused the issue -- I'm sure we share blame :-).   I'm not familiar with how other teams accomplish this - do you have pointers or info on the means by which this is accomplished?

**Comment by bkmartinjr** [comment]
@ivirshup - the other thing that might help is if anndata had a more robust set of unit tests.

**Comment by ivirshup** [comment]
@vals both are working for me. Are they not for you?

> AnnData does not guarantee forward compat with data, only backward compat

That's a good point, and I'll have to think more about it. I would like to maintain forwards compatibility within a major (or "minor" pre 1.0) release. I don't think we're currently set up to test for this or guarantee it, but it's something we should look into. I think the versioning of the elements in the anndata could help with this, especially if you only need access to some parts of the data.

> I'm not familiar with how other teams accomplish this - do you have pointers or info on the means by which this is accomplished?

A large scale example would be Julia's [PkgEval](https://github.com/JuliaComputing/NewPkgEval.jl). Numba also does tests against many backends. IIRC the `holoviz` packages have integration tests with other packages, but I'll have to check my PRs to be sure I'm not thinking of something else.

I think being able to add a CI task where your test suite for the most recent release is run with anndata master installed would be sufficient. We could add a prerelease process for testing against development versions as well. I'd want help writing with writing the config files for these.

> the other thing that might help is if anndata had a more robust set of unit tests.

This is something we're definitely working on (I think we run >10x the tests we did this time last year). I'm a little unsure of what happened to make things break here though, so I don't know what to test. Was it mainly just `anndata.__version__` being a `Version` instead of a `str`?

**Comment by bkmartinjr** [comment]
> Was it mainly just anndata.__version__ being a Version instead of a str?

This was definitely an issue.  The other is where we were using private types to try and detect anndata modes of behavior (yes, bad practice, but at the time, the only way we found to work around issues with the module).

**Comment by bkmartinjr** [comment]
linking to comment thread in #1132

**Comment by bkmartinjr** [comment]
xref #1155 for the suggested CI improvements
