### ISSUE TITLE
feature: re-embed selected cells

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1150]
Subset of #280 

Add a feature to allow users to create a new embedding/layout on a subset of the cells in a dataset.   Basic story:
* user selects sub-population and does a subset operation in the UI
* user says "make me a new embedding, of type umap" (may be more options in future to pick algo and params, but initially just super simple)
* new embedding created on backend (may be async, ie, may take a while).  Error generated if it takes too long.
* new embedding given an automatically generated name (eg, "umap_20200214"), downloaded and made visible.  Embedding will now be in the embedding menu.

Open issues/work:
* We will need to assign some default coordinate to cells not in the subset, in case the user resets back to all cells, and wants to display the embedding.   (eg., all cells not in the subset are assigned an embedding position if [-1,-1]).
* We will also need to identify the default algorithm and parameters.   @sidneymbell @aopisco it would be great if you could collaborate on a notebook for this.

---

From @aopisco:
> A couple of thoughts here:
> 1. The most common user case will be the user wanting to subset a group of cells.
> 2. The user selects the cells they're interested in and click to subset. That should trigger re-embedding by running sc.tl.umap(adata_subset).
> 3. If the user is doing annotations using cellxgene, then the user can select a smaller group within the subset and annotate those and so one
> 4. At the moment because there is no re-embedding after subsetting it's impossible in many applications (like when there are T cells and NK cells) to get a finer look at the data which is limiting the potential of the subsetting function

**Comment by sidneymbell** [comment]
So excited this is happening! 

I put together some very preliminary mocks for a very basic MVP. Feedback welcome, especially from @liaprins-czi @colinmegill and @bkmartinjr 

## User story (with a few adaptations):
0 - Default parameters are (optionally) set on the CLI

1 - User selects sub-population and does a subset operation in the UI, such that `world` has `<N cells`. I will get you a number for this by EOD based on extensive previous benchmarking. 

2 - Once the user has subset to < N cells and selected UMAP as the current embedding, enable the "recompute UMAP" button. This will only be enabled when we heuristically believe it should take <10seconds, 20 tops. 

3 - This kicks off a job on the backend to recompute the embedding. While it is computing, disable the graph (or at the least, disable "subset" and "embedding choice" to prevent them changing which cells are in `world` while the new embedding is being computed.

4 - The new embedding is stored in `X_umap_temp` and added to the embeddings list.

5 - When the user resets the view, the new embedding is removed from the internal data structure and the embeddings list. This is fine for an MVP.

## Comp bio work to be done:
Note that UMAP is downstream of running PCA -> computing neighbor graph -> UMAP. 
For a quick MVP, I'd suggest we just choose a low enough N that it's reasonable to recompute all three (PCs, neighbor graph, UMAP) on the subset in <10-20 seconds. I've previously identified conditions necessary for reuse of PCs +/- neighbor graph for subsets of the data, but implementing this logic would be a slightly bigger lift.

_MVP_
- [ ] Define reasonable N cutoff for rerunning PCs, neighbor graph and UMAP on a subset of size N in <10-20 seconds
- [ ] Define default parameters for UMAP (if not specified by the user on the CLI)

_Extensions_
- [ ] Test validity of re-using neighbor graph  
- [ ] Test validity of re-using PCs (UMAP is usually run on the output of PCA, removing the number of genes as a factor in benchmarking)  
- [ ] Investigate the new Python UMAP release and other JS-based UMAP implementations to see if there's a better option than the current scanpy implementation.

**Comment by sidneymbell** [comment]
For reference, previous work on the neighbor graph subsetting is [here](https://github.com/chanzuckerberg/cellxgene-compbio-methods/blob/master/method-testing/neighbor-subgraph-comparison.ipynb). The punchline is that **so long as the neighbor graph subset that's being selected is contiguous (i.e., a lasso selection in the UMAP embedding), it can be reused which saves a significant amount of time on recompute**.

**Comment by sidneymbell** [comment]
cc @bkmartinjr 
Preliminarily, from my [previous work benchmarking these methods](https://github.com/chanzuckerberg/cellxgene-compbio-methods/blob/master/method-testing/scanpy-method-profiling.ipynb), up to ~10,000 cells is totally feasible for recomputing PCA -> neighbor graph -> UMAP in ~10-15 seconds on a standard macbook. I will rerun these numbers with the newest version of scanpy and update this comment.

![image](https://user-images.githubusercontent.com/12618847/74386897-0150af00-4dac-11ea-8f5d-48d78c30038a.png)

**Comment by sidneymbell** [comment]
Looking at the [scanpy UMAP implementation](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.tl.umap.html), I recommend the following parameterization.

__Configurable on the CLI__
For parameter values, I would suggest adding two command line arguments for key parameters:
```
--umap-min-dist (default = 0.5)
--umap-spread (default = 1.0)
```

__Fixed__
```
min_dist=0.5
spread=1.0
n_components=2
maxiter=None
negative_sample_rate=5
init_pos='X_umap'  # initialize the algo at the current UMAP positions
random_state=0 # fix the random state
a= # as per umap defaults: https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L1158
b=# same; see umap defaults
method='umap'
alpha = 1.0 # we may want to surface this on the CLI; will poke around and update
gamma = 1.0 
```

**Comment by sidneymbell** [comment]
For PCA, I recommend using all the scanpy defaults.

**Comment by sidneymbell** [comment]
For neighbors, I recommend CLI configurable
```
--umap-n-neighbors (default = 15)
```

With all others default

**Comment by aopisco** [comment]
I agree, we run most of the analysis using default parameters anyway. Choosing the number of neighbors would be great (and likely required when this is officially released) but not essential for testing/experimental mode.

**Comment by aopisco** [comment]
Thinking ahead when trajectory analysis make it into cellxgene `--umap-init_pos` will be something you might wanna expose

**Comment by bkmartinjr** [comment]
@sidneymbell, two thoughts.

1. No commit to do this yet. Just to look at it. I have already discussed this with @aopisco and @colinmegill, and they understand it may not disrupt our other priorities. 

2. There will be cases where the dataset does not have prerequisite data, and the feature will be entirely disabled.

3. As proposed, this will reintroduce a dependency on scanpy, which we previously excised. That may cause some ripple. 

Thanks for doing all the legwork here.  I plan to look at it by end of month. Exciting stuff...

**Comment by bkmartinjr** [comment]
One more item of note, cc @aopisco @sidneymbell 

The API & performance issues I am untangling with the anndata/scanpy team happen to intersect this.  Their work-around for that issue (see theislab/anndata#317 and #1142) is to delete `adata.uns["neighbors"]`.

If we use Sidney's proposed "re-run PCA->neighbors->umap", then this will be a non-issue.  If we want to re-use neighbors, we'll need to hack around it (which seems doable).

@sidneymbell - am I correct that you are proposing a full re-run of everything (PCA, neighbors, umap) on the data subset?

Also, you seem to imply we must have a hard cutoff (ie, a number above which we refuse to perform the compute).  We do not do this with differential expression, which can also take a "long time" - why introduce this now, on this particular compute?   It will certainly make the implementation take longer.    My own recommendation, if this is going to be an experimental feature, is that we skip this for now and see how things work without it.

**Comment by aopisco** [comment]
@bkmartinjr I agree with taking the simplest approach

re-run PCA->neighbors->umap + no hard cutoff

@sidneymbell as part of re-running neighs, perhaps exposing this would be useful:

`--neighs-rep (default = None)` to allow e.g.
`sc.pp.neighbors(adata, use_rep="X_scvi")`
