### ISSUE TITLE
Use categorical colors from anndata object 

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene#1152]
Fairly related to #446, but I didn't want to pollute that conversation too much.

In scanpy, we store colors for categories in `adata.uns["{category}_colors"]`, so that plots are consistent after subsetting. Could `cellxgene` use those colors for the categories if they're present?

To get a mapping of categories to colors, you would do:

```python
dict(zip(adata.obs[cat].cat.categories, adata.uns[f"{cat}_colors"]))
```

**Comment by prete** [comment]
Unstructured Annotations (`adata.uns`) are note part of the [current schema](https://github.com/chanzuckerberg/cellxgene/blob/master/server/app/scanpy_engine/scanpy_engine.py#L194). Adding them could simplify the whole _custom-palette_ discussion, but the option to use them or not should be provided as an extra flag when launching cellxgene, for example if you want that behaviour to be the default one, add an option to override, something like `--ignore-uns-colors`.

Once `uns` are added to the world/schema, you'll only need to change [createColorsByCategoricalMetadata](https://github.com/chanzuckerberg/cellxgene/blob/ac13b31e13e03c00c531cae2541b177eb4e9c0b0/client/src/util/stateManager/colorHelpers.js#L39) scale to  

```javascript
const { categoriesColors } = world.schema.annotations.unsColorByName[accessor];
const scale =
    categoriesColors
    ?
    d3.scaleOrdinal(categoriesColors).domain([0, categories.length]);
    :
    d3.scaleSequential(interpolateRainbow).domain([0, categories.length]);
```

**Comment by bkmartinjr** [comment]
We want the app to remain agnostic to the backend data storage system, so this will also require adding plumbing to handle non-anndata cases.

**Comment by bkmartinjr** [comment]
@ivirshup - can you point me at the docs for this?  I'm wary of using these interfaces inappropriately, or having them only be supported by some of the past releases.  In particular, what is the full set of syntax supported by the uns[*_colors]?  My quick skim suggests that it can accommodate almost anything matplotlib supports?  

We definitely do not want to import matplotlib into cellxgene. Would it still be useful if we only supported the simple #rrggbb, and _maybe_ a best-effort attempt to map names between the matplotlib world and web?   "red" may not mean exactly the same thing in both, and some names may not translate at all.

**Comment by prete** [comment]
https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.pl.umap.html

```
palette : str, Sequence[str], Cycler, None (default: None)
Colors to use for plotting categorical annotation groups. The palette can be a valid ListedColormap name ('Set2', 'tab20', …), a Cycler object, or a sequence of matplotlib colors like ['red', '#ccdd11', (0.1, 0.2, 1)] (see is_color_like()). If None, mpl.rcParams["axes.prop_cycle"] is used unless the categorical variable already has colors stored in adata.uns["{var}_colors"]. If provided, values of adata.uns["{var}_colors"] will be set.
```

**Comment by ivirshup** [comment]
AFAIK it's documented in the `palettes` argument for the embedding plotting functions:

```python
palette : typing.Union[str, typing.Sequence[str], cycler.Cycler, NoneType], optional (default: None)
    Colors to use for plotting categorical annotation groups.
    The palette can be a valid :class:`~matplotlib.colors.ListedColormap` name
    (`'Set2'`, `'tab20'`, …), a :class:`~cycler.Cycler` object, or a sequence of
    matplotlib colors like `['red', '#ccdd11', (0.1, 0.2, 1)]`
    (see :func:`~matplotlib.colors.is_color_like`).
    If `None`, `mpl.rcParams["axes.prop_cycle"]` is used unless the categorical
    variable already has colors stored in `adata.uns["{var}_colors"]`.
    If provided, values of `adata.uns["{var}_colors"]` will be set.
```

@fidelram might be able to say if this is documented more.

**Comment by mweiden** [comment]
@ivirshup @fidelram Would you consider adding--or do you already add--colormap information for continuous variables into your anndata files? If we had this information, this standard would have everything we need to enable custom colors in cellxgene.

@prete agreed on the disable flag.

**Comment by ivirshup** [comment]
@flying-sheep may also have some thoughts on this.

We would have to decide on a specification for this. Is there a broadly accepted (ideally universally) specification format for continuous color maps?

**Comment by mweiden** [comment]
@ivirshup None that I know of. At it's simplest, it could be a mapping of variable names to common colormap names like those offered by [matplotlib](https://matplotlib.org/tutorials/colors/colormaps.html) and [d3](https://github.com/d3/d3-scale-chromatic).

**Comment by ivirshup** [comment]
I think this gets pretty complicated with continuous color maps. There are a lot of settings that can be applied here like: max, min, and middle values, dynamic cutoff values, scaling, and binning. I'm not sure how useful saving or sharing the color maps would be if these options weren't transferred as well.

This could maybe be accomplished with [vega-lite `Scale` objects encoded as json](https://vega.github.io/vega-lite/docs/scale.html). It does seem like a lot of work to support though.

**Comment by mweiden** [comment]
@ivirshup wow, that's a lot of functionality. In your opinion, what parts of this are essential for scanpy use? All of it?

**Comment by ivirshup** [comment]
I think it's all pretty essential for choosing a continuous color palette. My main concern when adding features to scanpy is that I don't want to make it easy to misrepresent your data. I think telling people the continuous colors will transfer, but possibly generating very different visualizations could do that. Also, because of the way matplotlib and scanpy work, I'm not sure if we can always tell what color map was used at raster time.

In general I think that transferring continuous color palettes between plotting libraries is a hard problem to solve, and not one that is a priority for us.

My preference would be to only save categorical colors for now, unless someone else solves this problem well.

**Comment by mweiden** [comment]
@ivirshup that sounds reasonable. We'll scope the custom color RFC to just categorical colors then.

**Comment by fidelram** [comment]
To answer a couple of questions:

In adata.uns['*_color'] the valid colors are the ones accepted by matplotlib although frequently what is used is only the 'hex' color codes. And those colors, unless set manually by the user, are obtained from the 'palettes' described earlier. Thus, a mapping of matplotlib color names  to a color code should be enough. I think that matplotlib internally has all those mappings and can easily adapted.

Regarding the colormaps. scanpy has a 'default' colormap that is saved into `matplotlib.rcParams`, but I think this is rarely used.  

```PYTHON
sc.set_figure_params(color_map = 'viridis')
print(rcParams['image.cmap'])
'viridis'
```

**Comment by mweiden** [comment]
@fidelram @ivirshup thanks for the clarification. I just merged an implementation for categorical colors that should handle the standard matplotlib colors as input.

More on color maps coming in the future...

**Comment by jeanettejohnson** [comment]
Has there been any updates on this?

**Comment by jeanettejohnson** [comment]
Found a workaround I didn't see anywhere online so I'm just posting it, sorry if it's obvious!

Where majorCluster is a list of annotations for each cell (can be categorical, must be same length as # of cells)

`adata.obs['majorCluster']=list(majorCluster)
sc.pl.umap(adata, color=["majorCluster"])`

I think the scanpy documentation should probably be updated to clarify this because I think they think it's obvious but it took me like 2 days to figure it out lol
