### ISSUE TITLE
color-by on truncated category causes browser hang

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1156]
If you load a dataset with a very large obs categorical annotation (eg, immune_bone_marrow test dataset, cell_names category), and click the "droplet" color-by icon, it will hang the browser.

It is likely creating a separate color for each category.  It should bail out due to the excessive size of this category (just like the categorical menu in the LSB does)

Suggested fix - one of:
a)  if a category has more than some cut-off number, disable color-by
b)  or, just color-by the same list of categories shown in the truncated drop-down list

**Comment by mweiden** [comment]
@bkmartinjr I can't replicate this issue, though I think that I understand where to look to set a limit.
