### ISSUE TITLE
diffexp should not return values with log fold change < threshold

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1159]
Currently, we return genes such that:

 >return top N abs(logfoldchange) where lfc > diffexp_lfc_cutoff
If there are not N which meet criteria, augment by removing the logfoldchange threshold requirement.

In practice, this is equivalent to just not having a threshold :)

I'll add it to my list of diffexp-related issues to overhaul.

**Comment by signechambers1** [comment]
@MaximilianLombardo can you check if this is still happening? If so I'll prioritize and we can fix.

**Comment by signechambers1** [comment]
@MaximilianLombardo is this something we still need to fix?

**Comment by bkmartinjr** [comment]
The bug description isn't _exactly_ correct -- the code selects the top N by t-statistic, not log fold change, so there are cases where the code branches are not equivalent.  But in practice, we never have datasets with < N genes/features, so the threshold is more-or-less never ignored.

I think the decision should be made on which parameter has precedence:  always return at least N, or always apply the cut-off.  Either seems reasonable to me, but given our current UI (lfc cutoff not exposed), the current implementation is probably less surprising to the end user.

**Comment by MaximilianLombardo** [comment]
Thanks @signechambers1 @bkmartinjr 

Agreeing with Bruce's comment here. My 2c is that we should be returning genes based on the t-statistic threshold (probably up to a max number of genes). If there are no genes that meet that threshold, then I'm not sure returning top N genes is useful for a user since the markers that would be returned aren't "statistically significant" and hence not high quality.

**Comment by MaximilianLombardo** [comment]
UI considertation - are we concerned about returning too many genes as differentially expressed for very different populations?

This issue is also dependent on [#2211](https://github.com/chanzuckerberg/cellxgene/issues/2211)
