### ISSUE TITLE
Don't remove genes from workspace upon reset

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1171]
cc @aopisco 
"STOP LOSING THE GENE LIST IF I RESET" (currently using 'undo undo undo' to get back to `universe` instead of using `reset` because of this)

This is consistent with the proposed gene sets work in #1069

**Comment by aopisco** [comment]
this would rather be an enhancement but eventually would be good to be able to select which genes to maintain. the scenario here is we want to keep all the manually inputted genes but DGE genes might no longer be useful; on the first version reset could remove all DGE (particularly when those start being ~100) and keep the manually inputted genes; on the second version the user could select any DGE of interest to keep on its "gene exploratory analysis" list

**Comment by seve** [comment]
@colinmegill Should we consider persisting the redux store in local storage as a solution for this until we address gene sets?

**Comment by bkmartinjr** [comment]
> @colinmegill Should we consider persisting the redux store in local storage as a solution for this until we address gene sets?

The right solution would be to refine the UX design of reset so it has a better set of side effects.   There is no need to hack around it - it is our current UI design that is deliberately deleting the gene list - we can just change it to do what we want.

**Comment by colinmegill** [comment]
The reason we did this, initially, is that once the user has subset, `cell set 1` and `cell set 2` for diffexp may no longer reflect cells on screen in `world` 

The fix for this is to remove `cell set 1` and `cell set 2` in favor of accomplishing diffexp via label selection. 

This is captured in #729 and also facilitates #99

**Comment by bkmartinjr** [comment]
@colinmegill - are you advocating for not doing a short term fix? 

I find the current behavior _worse_ than having "disconnected genes" as it results in information loss.

**Comment by colinmegill** [comment]
I'm fine with not clearing diffexp as a stopgap

**Comment by mweiden** [comment]
I've spoken with Lia about this and we came up with the following desired behavior:
1. If you add a gene and then press "Undo" that removes the gene. If you then press "Redo" the gene is added back.
2. If you add a gene and then press "Reset," the gene is not removed.

Notice that both mirror the undo/redo/reset behavior of adding a category on the left-hand side.
