### ISSUE TITLE
The terminal connectting Remote Server Usage 

### ISSUE THREAD

**Issue by honghh2018** [chanzuckerberg/cellxgene#1187]
Hi all,
     Thank for developing the great tools for scRNA-seq anslysis.
      I had one question about using the cellxgene tool.
      How can i browse the data using IE in my computer terminal that connect to The Remote Server installed the cellxgene software in miniconda?
       Any advices and comment should be grateful.
       Thanks!

**Comment by mweiden** [comment]
Hi @honghh2018 👋,

If I understand you correctly, you've installed `cellxgene` via miniconda and would like to browse your data using IE.

Have you tried the going through the steps outlined in the [Launch cellxgene with your dataset](https://chanzuckerberg.github.io/cellxgene/posts/launch) documentation? If so, what issues did you encounter?

Thanks for raising your issue.

**Comment by honghh2018** [comment]
Thanks for your advice.
    I had solved this issue for your vignette last day.
    As i executed the cellxgene with parameter --host, it demonstrated the information that i using it into IE to browse my data. 
    Thanks

**Comment by mweiden** [comment]
OK, great! Glad you're up and running.
