### ISSUE TITLE
Prompt for collection name upon engaging with annotations feature

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1193]
Now that we're moving annotations out of experimental mode, it's super confusing to be prompted for a filename if I'm not, in fact, creating annotations. If needed, the file naming dialog should only appear when I first click "create category," rather than on launch.

**Comment by sidneymbell** [comment]
cc @liaprins-czi

**Comment by colinmegill** [comment]
@sidneymbell disagree that it's super confusing — and if it is, I think we just need better messaging to say 'annotations is enabled for this dataset, so you need to create a file...', rather than making a bigger change here.

**Comment by sidneymbell** [comment]
@colinmegill -- can you help me understand why it's better to have it pop up on launch, rather than just when I click the "create category" button? (implementation annoyingness is a totally valid reason, just want to make sure I understand :)

**Comment by colinmegill** [comment]
Believe this was implementation related, @bkmartinjr can confirm

**Comment by MDunitz** [comment]
Additionally we dont want to prompt for a collection name in the hosted version as it will give users the impression that we are storing their annotations under that collection name (and that they can have multiple collections for one dataset) which is incorrect. 

Discussed with @colinmegill and it should be fairly simple to set it t o default or remove it completely in the hosted version

**Comment by seve** [comment]
Closing this issue and breaking out @MDunitz 's comment into separate issue
