### ISSUE TITLE
Corner case -- confusing duplicate filenames in annotations

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1194]
Corner case: 

1 - I make a new annotations file with just `cellxgene launch mydata.h5ad`. This makes a new file, `cwd$myannotations-UUID.csv` 
2 - I then relaunch with `cellxgene launch mydata.h5ad --annotations-output-dir savehere`
This then makes ANOTHER file, also named `myannotations-UUID.csv`, but in the `savehere` dir. This has the same name, but is in a different place and has different contents, which is super confusing.

Can we always prompt for a filename if they run with `output-dir`?

**Comment by bmccandless** [comment]
Hi @sidneymbell 
In the case of multiple users it makes sense to provide an output dir and not an output file.  In that scenario, each user gets their own file that is placed in that output directory. 

Perhaps it would be less confusing to always require an output-dir if annotations are turned on.

**Comment by bkmartinjr** [comment]
@bmccandless is right - this is all in support of the multi-user scenarios that are required by our users, and which were jointly designed by the two of us as the simplest solution :-)

@sidneymbell, I suggest we meet f2f to discuss if you have strong concerns.   While I don't have alternative design ideas, perhaps we can brainstorm a bit about how to make this single- vs multi-user mode more explicit or overt?

**Comment by maniarathi** [comment]
I believe solving #1235 will solve this ticket, so closing. (It says so explicitly but please reopen if I am wrong!)
