### ISSUE TITLE
hosted cellxgene improvements/bugfixes

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1210]
Currently the static assets are not found on the ec2 instance.

**Comment by bkmartinjr** [comment]
are you configuring the static asset location for deployment by the proxy?

Ref: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-staticfiles.html

this can be set in the default config (don't need to go to the console) using `aws:elasticbeanstalk:container:staticfiles`
