### ISSUE TITLE
add "hosted" learnings to EB README

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1233]
add any learnings/lessons from the pilot hosting exercise to the README, so provide guidance for other teams wanting to do the same.

**Comment by bkmartinjr** [comment]
@bmccandless - this is finished, right? If yes, could you close the ticket? thanks!

**Comment by bmccandless** [comment]
Yes, it's finished.  We have a documented procedure, a wiki, and a process for lessons learned.
