### ISSUE TITLE
Update design for annotations file naming and creation flow for single and multi-user cases

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1235]
The solution for this issue should address #1193 and #1194 , and takes into account:
- How/if to treat single users differently than users part of a group:
   - Should single users' files have hashes
   - Consider including a default file name (that user can change)
- When should the modal appear: upon launch of app, or wait until user clicks to create their first annotation

After meeting with @bkmartinjr earlier, I am going to build out flows for the single user experience and the multi-user experience below. From there it will be easier to assess this hypothesis.

**Single user:**
- By default, we auto-name the annotations file based on the dataset name + `-annotations.csv` (and without the `.h5ad` extension of the dataset file)
- However, user can change the name of the file in the CLI
- If a single user calls `annotations-dir` it should give an error

**Multi-user:**
- Within CLI, flag can be added to specify multi-user (i.e. by IT/admin person for multi-user group who handles specifying their dataset, etc)
- Along with that flag, require specification of a directory within which to save annotations files of all users
- When one of these multiple users is in the cellxgene UI and clicks to create their first annotation, the annotation-file-naming modal will appear to ask them to name their annotations file; this is appended with a hash unique to this user-dataset combo. Then when they click to save the file name, it repopulates the modal with the category-naming content.

**To do:**
- [x] Quick rough sketch of flows
- [x] Build more legible version in digital 
- [x] Create Figma prototype mapping to flows
- [ ] Get feedback
- [ ] Devise error messaging (e.g. if I haven't entered the multi-user flag but I enter the annotations-dir command, and if the location I specify for annotations-file doesn't exist, maybe character warnings for names not allowed?)

**Comment by liaprins-czi** [comment]
Here is my rough first pass at the flow; next will convert it into digital version
![IMG_0355-small](https://user-images.githubusercontent.com/53277128/76898762-8caddc00-6853-11ea-9c05-6af10f8f1c73.jpg)

**Comment by liaprins-czi** [comment]
Here's the digital version of the flow diagram. @bkmartinjr @sidneymbell @colinmegill I know you all are busy with very important things, but if you're interested have a look and add any thoughts as comments here. Thanks!

https://drive.google.com/open?id=1yt_HX9wQXmPVEMYL26mJcnTFy7sRABi8

[annotations-files.pdf](https://github.com/chanzuckerberg/cellxgene/files/4346103/annotations-files.pdf)

Next I'll work on the Figma prototypes for this to make it more clear what it'd actually be like for these users.

**Comment by liaprins-czi** [comment]
Here's the Figma prototype for the **single user who sticks with the default name**; I'll add prototypes for the other scenarios (single user who changes to a custom file name, and multi-user) as I finish them.
https://www.figma.com/proto/9crSG2iq4zuOzOFcg4YeSZ/Annotations-file-naming?node-id=1%3A2&viewport=791%2C316%2C0.5&scaling=min-zoom

**Comment by liaprins-czi** [comment]
Figma for **single user who changes to a custom file name:**
https://www.figma.com/proto/9crSG2iq4zuOzOFcg4YeSZ/Annotations-file-naming?node-id=20%3A1&viewport=-3932%2C316%2C0.5&scaling=min-zoom

**Comment by liaprins-czi** [comment]
Figma for **multi-user**:
https://www.figma.com/proto/9crSG2iq4zuOzOFcg4YeSZ/Annotations-file-naming?node-id=25%3A3&viewport=-5762%2C392%2C0.5&scaling=min-zoom

**Comment by mweiden** [comment]
@liaprins-czi @bkmartinjr Should users in a multi-user deployment be able to see each other's annotations? If so, how are annotations from multiple users displayed?

Motivating scenario:
> I'm part of a team annotating a dataset at a lab. We we want to parallelize the annotation of a single dataset. Part of this is being able to view the annotations of my collaborators so that we can discuss and, potentially, not duplicate work.

(Though getting more than one annotation for a given cell and then getting a consensus view might be its own use case)

**Comment by liaprins-czi** [comment]
Thanks for the input @mweiden. I think that's something we should think about for down the road, e.g. maybe possible with a hosted version at some point? For now we are just trying to minimally accommodate users we know are working on a shared system that they have put together themselves.

**Comment by mweiden** [comment]
@liaprins-czi makes sense. Just clarifying scope for this feature.

**Comment by signechambers1** [comment]
@colinmegill do you know if this work is still necessary? if so, would you prioritize highly?

**Comment by signechambers1** [comment]
Closing as designs are complete.
