### ISSUE TITLE
HTTP security headers / setup CSP headers

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1237]
@nacin recommendation:

_At a minimum, we’d want HTTPS enforced with HTTP Strict Transport Security enabled. Tablestakes:_

```
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
```

**Comment by brianraymor** [comment]
Response from @bkmartinjr:

_This needs to be configurable, as we can't turn these on in the default (CLI, local app) case.
@bmccandless - can you think about how we might do this in a modular way - ie, config driven?_

**Comment by brianraymor** [comment]
For CSP headers:

[Mozilla TLS Observatory](https://github.com/mozilla/tls-observatory/blob/master/README.md) and ​Google’s [CSP Evaluator](https://csp-evaluator.withgoogle.com/)​ are excellent guides.

**Comment by bkmartinjr** [comment]
blocked by lack of HTTP support in deployment
