### ISSUE TITLE
User Sessions: session cookie for annotation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1238]
@nacin noted:

_I see cellxgene dropping a session cookie (via flask/werkzeug) to support the [annotation feature](https://github.com/chanzuckerberg/cellxgene/blob/1e8d89f8f2b67494c447977a7efd6c8ce1e14b4e/docs/posts/annotations.md#how-do-you-remember-my-unique-id-to-match-my-cellxgene-session-with-my-annotations-file). If that feature will be enabled in this deployment, I think it opens up some new technical and trust questions, such as:_

- _How are sessions stored? It’s not just a cookie getting dropped with information, it appears to be actual stateful sessions stored thanks to Flask-Session (though I’m not positive I went far enough down this rabbit hole to confirm how this is configured)._
- _Terms of service re: this cookie & session and what it’s used for._
- _Having a `Set-Cookie` header on what seems to be every pageload may complicate a CDN configuration depending on the current plan there._

**Comment by brianraymor** [comment]
@bkmartinjr responded:

_This entire feature should be disabled in the hosted (near term config).  @bmccandless is working making sure the route is disabled (see #1229), but you are right that we need to kill the cookie (and a few other things)_

**Comment by bkmartinjr** [comment]
@bmccandless - I am fairly confident you already fixed this with the configuration changes PR.  Because annotations is deconfigured in the WSGI server, no cookie will be set.  Please close if you agree.   I did a spot check against the DEV server and it does not appear to be sending a session cookie.
