### ISSUE TITLE
User Sessions: Configuring Flask's secret key uniquely

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1239]
@niacin wrote:

_We also need to make sure we are configuring Flask’s secret key uniquely using the CXG_SECRET_KEY environment variable in our production environment ... in terms of tasks: you probably should still set CXG_SECRET_KEY to something random in production, just so it isn’t a gotcha (much) later on_

**Comment by bkmartinjr** [comment]
we need:
- [ ] a config hook for this in the app
- [ ] the secret to be set & managed securely in our deployment
