### ISSUE TITLE
UI for Terms of Service & Cookie confirmation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1241]
Per the March 17 _Hosted Cellxgene / Shared Infra Sync_:

- [x] Sarah Gordon to provide Terms of Service.
- [x] Add mechanism for a footer/link for Terms of Service in the UI.

We should also do:
- [ ] Add mechanism for cookie dialog (sufficient for worldwide use)

---
Note: There needs to be language in the TOS and a cookie dialog when Google Analytics is enabled. 

---
Note: we should make these build-time (configurable) options as they will only be integrated/used in hosted environments, and will have unique language/text for each deployment.

**Comment by brianraymor** [comment]
Sarah has drafted the _Terms of Service_ which is in review. This will be provided in HTML when approved. Target date is March 27 *latest*.

**Comment by bkmartinjr** [comment]
Resolved by #1300
