### ISSUE TITLE
HTTP (flask) route parameter verification and argument checking

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1245]
@bkmartinjr wrote:

_The top-level routes take a variety of parameters (both query params and post bodies (eg, filters).   I am not sure we have sufficient error handling in all cases to avoid deliberate probing of these routes._

- [ ] The underlying data structures are immutable, so the actual ability to cause side-effects should be minimal, **but we should configure so it only has read perms to the S3 bucket**.

- [ ] The remediation is a scrub of the entry points for the routes, to validate params and reject anything unexpected.

- [ ] While we are at it, we should check for proper decoding of params

**Comment by bkmartinjr** [comment]
Resolved by #1297 and #1293
