### ISSUE TITLE
health check route

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1247]
Need a top-level server health-check route.

- [ ] round-trip read to dataroot to ensure access to datasets

CC: @parthshahva

**Comment by parthshahva** [comment]
Are there any tiledb checks that can be run as part of this healthcheck?

**Comment by bkmartinjr** [comment]
I don't think so, unless we assume an always-present dataset (which we could do - we could build the health check around a fixed dataset if we want to do so).

tiledb is an embedded DB - ie, just a module we import.  No external services or instances other than S3
