### ISSUE TITLE
ci/cid pipeline

### ISSUE THREAD

**Issue by parthshahva** [chanzuckerberg/cellxgene#1251]
From slack:

Parth Shah  8:46 AM
So I don't like to deploy via terraform. Terraform will manage the infra but won't manage versions of the environment being deployed. Its not really built to handle this type of situation well
8:47
Best solution here is to have a CI/CD pipeline (running in gitlab or travis) that auto deploys master > dev on merge after running a suite of tests (edited) 
8:47
And have a one button deploy to Prod so that step (for now) requires human review

**Comment by MDunitz** [comment]
Notes from call w/ @parthshahva 
Using gitlab actions
[ ] dev has hook into head of cellxgene master branch, CICD runs when master is updated
[ ] requirements file pins production version of cellxgene, CICD runs when that is manually updated
[ ] functional tests auto run after a deploy
[ ] cellxgene configuration updates run automatically

**Comment by MDunitz** [comment]
how to differentiate between hosted versions and local versions?

**Comment by MDunitz** [comment]
Colin is writing tests that will run against deployments

**Comment by MDunitz** [comment]
Currently relying on team to not push to master on tuesday/wednesday (unless its needed in the release)

**Comment by MDunitz** [comment]
We can tag master on Tuesday and then use that version when promoting to prod

**Comment by MDunitz** [comment]
rerun tests on all config changes
