### ISSUE TITLE
DoS issue

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1259]
DoS which can be executed from any machine, the following will disable the service for 60s:

curl http://<URL>/ -X GET --data 'a' -H "Content-Length: 2" done

and can be repeated for permanent effect. What happens here is the server hangs and expects more data which never comes.

**Comment by arcz** [comment]
A little update, single curl will just fill one connection, it takes at least 15 concurrent connections to fill the whole pool:
```for i in `seq 1 15`; do curl http:/// -X GET --data 'a' -H "Content-Length: 2" & done```

**Comment by MDunitz** [comment]
@bkmartinjr and @parthshahva is this solved with the cloudfront default 30 second timeout?

**Comment by bkmartinjr** [comment]
Not fully.  The timeout and CDN help a lot, but I need to do a bit more exploration before I'm willing to close it (and I need to review with infosec).   Feel free to remove yourself from assignees and leave it on my plate.

**Comment by bkmartinjr** [comment]
We have resolved this as far as we will.  There may be future improvements if we are able to migrate long-latency routes (eg, /diffexp) to an async notification model, but that is beyond the current planning horizon.
