### ISSUE TITLE
Remove "Name cannot be blank" annotations collection error message

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1261]
Currently when I am asked to create a name for my collection of annotations, it automatically appears with an error message right off the bat, telling me the field cannot be empty, before I've even had a chance to start typing. We should not give this error, we should just disable the "Create annotations collection" button until there is at least one legal character in the field. 

<img width="506" alt="cxg bug" src="https://user-images.githubusercontent.com/53277128/77200371-a5aecb00-6aa7-11ea-8c15-a23c4fbf06ff.png">

Also, with the new solution for #1235 we should allow user to exit/cancel without creating a name if they want. Since in that design they cannot create an annotation category until they've first created a collection/file name, that would be fine: they can leave the file naming modal without creating a name but if they subsequently click to create an annotation it will again first ask them for a collection name.

**Comment by signechambers1** [comment]
Let's clean this up for desktop while we implement for hosted so that users on either desktop or hosted do not see this warning when the field is blank.

**Comment by tihuan** [comment]
When do we want to show the error message "Name can't be empty"? When the input field loses focus or something?

**Comment by signechambers1** [comment]
As discussed in refinement a couple weeks ago, this error message can be removed entirely since the "Create annotations collection" is disabled when the field is blank.

**Comment by signechambers1** [comment]
Closing as low priority
