### ISSUE TITLE
Propose new redux state model - write a spec

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#128]
There are several drivers:
- clean up the diverse set of reducers, which have a lot of redundant state
- cleanly separate UI state from server-side (cell) state
- cleaner abstraction for cell index/ID
- abstraction for expression matrix data access:
    + sub-matrix access (move beyond simple array)
    + on-demand sub-matrix fetch
- rethink universe/world split - can we do something cleaner?
- proper support for saving/reloading the view parameters (cell selection, viz params, other transformations) so that we can support view sharing (perhaps via deep linking or dropping a "config" file), and to allow the application to "explain" how it got to its current view.

**Comment by colinmegill** [comment]
* When we add a gene - #85 - we'll want to brush exactly as we would with other continuous metadata. This will mean storing the expression levels for each cell on the client in redux, and interacting with the crossfilter behavior dynamically

**Comment by bkmartinjr** [comment]
This is essentially done except for thinking through differential expression data.   Not clear it needs a change.
