### ISSUE TITLE
consider integrating LGTM

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1284]
From @austinylin we should probably look at enabling https://lgtm.com/#explore

**Comment by mweiden** [comment]
@bkmartinjr ah! I've used this and it is good. Agree we should add it.

**Comment by signechambers1** [comment]
@maniarathi can you make a recommendation on priority here?

**Comment by maniarathi** [comment]
Ohh this would be nice to have. This would involve a discussion and I don't think it's high priority (and doesn't fall under our engineering excellence epics at the moment). Perhaps Q1 of next year though. Marking as a P3.

**Comment by maniarathi** [comment]
Recommended course of action is codeql now: https://chanzuckerbergteam.slack.com/archives/C94RQ5SBV/p1606238470333100?thread_ts=1606230396.332000&cid=C94RQ5SBV

**Comment by maniarathi** [comment]
Closed via #1991
