### ISSUE TITLE
category name truncation not working during data load

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1290]
Category names are not ... truncated during data load.  See the busy (loading) and loaded pics below.  I suspect that the `renderIsStillLoading()` method was not updated in category.js.

Busy loading:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/f7e70934-d09e-4b4d-b668-269dddee491d)

Completed loaded:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/dbd51930-1d2e-4693-9f08-00770f6474e8)

**Comment by liaprins-czi** [comment]
This issue is still happening to me; I just re-checked out `master`:

![Screen Shot 2020-03-26 at 10 39 17 AM](https://user-images.githubusercontent.com/53277128/78708452-053e1080-78c7-11ea-83b4-62ad486f02b2.png)

**Comment by seve** [comment]
@liaprins-czi could you link me the dataset?

**Comment by bkmartinjr** [comment]
I think Colin just fixed this in a recent PR

**Comment by seve** [comment]
Talked to Lia and it is no longer happening
