### ISSUE TITLE
clean up ToS & privacy content

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1308]
we should do a styling pass over the static content for ToS/privacy

**Comment by liaprins-czi** [comment]
[tos-privacy.zip](https://github.com/chanzuckerberg/cellxgene/files/4416441/tos-privacy.zip)

Here's the zipped folder with the updated files. I am also reaching out to Sarah Gordon (@bmccandless says she is our legal point of contact for this) to have her take a look, and am also goingto review the CZI brand guide to see if/how it recommends displaying two logos together (CZI and cellxgene; I have them both in the header area now but can update if there's a better way to show them together).

**Comment by liaprins-czi** [comment]
[tos-privacy.zip](https://github.com/chanzuckerberg/cellxgene/files/4416936/tos-privacy.zip)
Updated version with relative links to prevent breakage!

**Comment by liaprins-czi** [comment]
[tos-privacy.zip](https://github.com/chanzuckerberg/cellxgene/files/4417889/tos-privacy.zip)

Final version with mini updates from legal included.

**Comment by bkmartinjr** [comment]
This looks resolved. Please close if you agree :-)
