### ISSUE TITLE
Implement dataset properties UI

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1319]
Dataset and Collection metadata will be helpful context for users to understand the data and additional information about the collection. 
Please include the following config fields in the data overview drawer on both desktop and hosted: 

Title

Dataset Metadata
* organism, organism_ontology_term_id
* assay, assay_ontology_term_id
* tissue, tissue_ontology_term_id
* cell type, cell_type_ontology_term_id
* disease, disease_ontology_term_id
* ethnicity, ethnicity_ontology_term_id
* development_stage, development_stage_ontology_term_id
* sex
* layer_description

Collection Metadata
* project_name (Collection Name)
* project_description (Collection Description)
* publication_doi or preprint_doi
* contributors
    * Name
    * Institution
    * Email
* project_links
    * Link Name
    * Link URL 
    * Link Type

If any fields are not populated, please exclude. 
Out of scope: verifying publication information by hitting the crossref API.

Old Notes:
Most likely this would be data sourced from H5AD `.uns` or Loom `/attrs/`.  We will need some backend convention for specifying which are to be displayed and in what way.

Implementation: Where's the data found to fill this drawer? 
* `corpora-config-props`
* properties moving over from the left sidebar.
* But to get journal name AFTER publication, might need to hit crossref API to get correct information. (backend)
* will need a test in cxg to ensure we don't break data existing in `config-props`
* only expected to work cleanly for remix datasets, should work for all data sets.
* move singletons out into sidebar all the time (not just corpora)

**Comment by colinmegill** [comment]
https://github.com/chanzuckerberg/cellxgene/issues/1533

**Comment by colinmegill** [comment]
<img width="1282" alt="Screen Shot 2020-08-27 at 12 14 30 AM" src="https://user-images.githubusercontent.com/1770265/91383535-5a3cdd80-e7fa-11ea-8bfd-d2d4ee753e86.png">

**Comment by ambrosejcarr** [comment]
@mckinsel could you comment on what if any metadata are missing from this mock that should be present, based on the schema?

**Comment by ambrosejcarr** [comment]
@colinmegill I'm interested to know where you imagine the user clicking to see this overview.

**Comment by mckinsel** [comment]
- We have the required ontology ids/labels: organism, assay, tissue, disease, ethnicity, development_stage, sex. You could put those here and pull them out of the LSB when they're singlets.
- There are more links. Right now cellxgene only displays the "summary" link as the about link in the upper left, but datasets usually have more: more ways to access raw data, a link to the lab website, a github repo with some of their analysis code, etc.
- In the mock, authors are presented as an attribute of the dataset. But, I think the right model is datasets may have an associated preprint or publication, and authors are an attribute of that. There's a little more info you might want to drop in from the crossref API them: title, journal info, publication date
- Distinct from authors, we have a notion of "contributor". This is the person(s) who actually gave us the data and is the best contact for data questions. We usually get their name, email, institution.
- Datasets are members of collections (née projects), which have a name and description, so maybe like "A part of ...."

**Comment by mckinsel** [comment]
Here's what I would do:

First check if `config["corpora_props"]["corpora_schema_version"]` exists and equals `1.0.0`. If it doesn't don't do any of this.

- Title for the big heading is in `config["corpora_props"]["title"]`
- If `config["corpora_props"]` has key `publication_doi`, then you want Publication: `<doi_value>` and make that a link. It should look like `https://doi.org/....`
- Same for `preprint_doi`.
- Organism: `config["corpora_props"]["organism"]`
- There is an array of objects at `config["corpora_props"]["contributors"]`. Each should at least have `name` and may have `institution` and `email`. You want to show those under a "Contributors" heading.
- There is an array of objects at `config["corpora_props"]["project_links"]` with keys `link_name`, `link_url`, and `link_type`. Ignore the one where `link_type` is `SUMMARY`, but for the others you should make a list of links.

**Comment by seve** [comment]
We identified that we want to pull singleton categories into the info drawer regardless of hosted/cli.  In these cases are these values the only things populating the info drawer or should we also be pulling in the dataset title and about link?

**Comment by signechambers1** [comment]
@colinmegill should this overview work on both desktop and hosted cellxgene?

**Comment by signechambers1** [comment]
@colinmegill I updated this issue with the fields we'd like to include (thanks Ambrose and Marcus!). Over to you for final design, I added an appetite of 2 for this design task, let me know if you disagree.

**Comment by tihuan** [comment]
@colinmegill @seve I see the estimate of this ticket is currently a 2, not sure if that was for design or implementation!

If it's for design, please help update the estimation for implementation now 🙏 Thanks so much!

CC: @signechambers1

**Comment by seve** [comment]
@tihaun Since this ticket is migrating over to implementation work I think it's best to tweak the estimate to a 4.  

@colinmegill How does that align with what you have in mind?

**Comment by tihuan** [comment]
Awesome! Thanks for the updated estimation @seve and @colinmegill ! Just updated the points

Next time please feel free to update it yourself 🤩💪
