### ISSUE TITLE
when zooming on a trackpad the window attempts to scroll

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1331]
When zooming in or out on my MacBook trackpad, the app attempts to scroll up/down respectively. This behavior is not present when using the scroll wheel on a mouse.

**Comment by liaprins-czi** [comment]
This is also an ask from our users pneuhoef@stanford.edu and ktrav@stanford.edu from Angela's group. Basically we need to accommodate a way to scroll  that doesn't require a scrolling mechanism at all (i.e. UI buttons). As surfaced by our users:
- Some computer mice (that they use) do not have scrolling ability
- Sometimes they use iPads, even phones to view the group’s cellxgene-on-browser version and cannot zoom: Kyle said about 20% of his cellxgene time on a mobile device for him

**Comment by maniarathi** [comment]
Hey @seve , do you have a sense on whether this is a new feature or if this is a bug to fix?

**Comment by maniarathi** [comment]
@colinmegill and I looked into this today - this behavior is macbook trackpad specific and working as expected.
