### ISSUE TITLE
incorrect naming conventions in categorical selection

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1332]
In `createCategoricalSelection()` of `controlHelpers.js` there are a number of terms used in substitute of the correct terms used by cellxgene.
These are:

category - a named, enumerated annotation (ie, each cell has a label, from a finite list of labels). This is variously called 'metadata', 'category', 'categorical', etc.
label - the actual label value on the cell. This is variously called 'annotation', 'value', 'category', etc.

**Comment by maniarathi** [comment]
Was gutted during refactor.
