### ISSUE TITLE
CLI MVP pre-release smoke testing and validation

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#134]
- [ ] Back-end platform test: build, install, run on test data set
    - [X] Write [test plan](https://github.com/chanzuckerberg/cellxgene/wiki/Release-Validation-Recipe#backend-test)
    - [ ] test: MacOS, Mojave
    - [x] test: Win10 latest using WSL/Ubuntu 16.04
- [ ] Front-end compatibility smoke tests:
    - [X] Write [test plan](https://github.com/chanzuckerberg/cellxgene/wiki/Release-Validation-Recipe#frontend-compatibility-test)
    - [ ] test: Firefox, latest version, Win10
    - [ ] test: Chrome, latest version, Mac
    - [x] test: Chrome, latest version, Win10
- [x] End-to-end UI feature validation by subject-matter expert (eg, Sidney), on a single platform.  
    - [ ] Write [test plan](https://github.com/chanzuckerberg/cellxgene/wiki/Release-Validation-Recipe#e2e-functional-test)
    - [x] testing done
- [ ] Review and confirm repo docs:
    - [x] Readme
    - [ ] Install / getting started
    - [ ] Contact / issue / help information
    - [x] License
    - [ ] Contribution guidelines
    - [ ] Clean, reviewed & validated REST API documentation and Swagger spec
- [x] Sample data sets for demo & test
    - [x] T.Muris
    - [x] PBMC 30K
    - [X] 1.3M 10X neurons
    - [x] _any others?_
- [x] Performance validation (1M+ cells) on "typical" laptop
    - [x] data set selected / available
    - [x] Chrome-latest / Win10/WSL/Ubuntu perf acceptable
- [ ] code cleanliness
    - [ ] `npm run lint` clean
    - [ ] `npm run build` clean
    - [ ] `pip install` clean
    - [ ] `flake8` clean
    - [ ] Documented build & install process is clean
    - [ ] Remove dead branches from github repo
- [x] Version number bumped
    - [x] package.json 
    - [x] setup.py
- [ ] Documentation in repo & reasonable quality
    - [ ] CLI --help
    - [x] REST 0.2 spec

**Comment by bkmartinjr** [comment]
@fionagriffin could you also review and improve this list?  thanks!

**Comment by bkmartinjr** [comment]
@csweaver, @colinmegill - I have made a start at the test plans (saved to the wiki, so we can reuse them).   Can you have a look and edit/improve as you see fit?    For now, I'm keeping them pretty sketchy - just covering the basics, and written with the assumption that the person executing the plan knows what correct behavior looks like....

**Comment by fionagriffin** [comment]
@bkmartinjr - @csweaver and I talked about splitting out some of this list into their own issues. Are you alright with that or would you prefer it stay within this issue?

**Comment by bkmartinjr** [comment]
Am completely fine if you restructure this.   My only request is that we have easy access to tracking issue(s) so we can review where we are at....

**Comment by bkmartinjr** [comment]
@csweaver, @neuromusic  - this is largely complete, at least as much as we intend to resolve for the near term.  Propose closing this issue.  Any concerns?

**Comment by csweaver** [comment]
I looked at it yesterday, and agree it should be closed
