### ISSUE TITLE
Incorrect x axis tick label for continuous metadata histogram

### ISSUE THREAD

**Issue by nh3** [chanzuckerberg/cellxgene#1349]
The tick label for the last (rightmost) tick can sometimes be incorrect. For example, the rightmost tick should be 150m for the 1st plot and 250m for the 2nd plot below. Also, showing "xxxm" seems rather non-intuitive compared to "0.xxx".

![image](https://user-images.githubusercontent.com/421523/78509086-6957bc00-7783-11ea-83ec-7401c8fdfe55.png)

![image](https://user-images.githubusercontent.com/421523/78509119-a328c280-7783-11ea-9d64-e82b3433f110.png)

**Comment by nh3** [comment]
Just to update, the bug applies to continuous variables with values above 1 too and is not restricted to the rightmost tick.
![image](https://user-images.githubusercontent.com/421523/78545843-60530300-77f4-11ea-8c91-b40056f04569.png)

**Comment by prete** [comment]
Seems to happen with other continuous variables as well
![image](https://user-images.githubusercontent.com/4153651/78562583-8b981b00-7811-11ea-8529-f81b3b3e6d2e.png)



Live example [here](https://www.covid19cellatlas.org/lukassen20-hbec/).

**Comment by bkmartinjr** [comment]
@nh3 - can you confirm you are also running the 0.15 release?

**Comment by nh3** [comment]
Confirmed it's 0.15 release.
Screenshots taken from https://www.covid19cellatlas.org/litvinukova20/ and https://www.covid19cellatlas.org/lukassen20-hbec/

**Comment by mweiden** [comment]
@prete @nh3 does this solution look reasonable to you? https://github.com/chanzuckerberg/cellxgene/pull/1363

Pardon the commit thrash. Had to try out a few things before finding a solution I was happy with.

**Comment by prete** [comment]
Looks reasonable for me. However, @nh3 has more user-side knowledge than me.

Perhaps adding `~` to the d3.format (`.2~e`) could help to clear up a bit the X axis when trailing zeros are not needed?

**Comment by nh3** [comment]
Looks reasonable to me too. Thanks @mweiden !
