### ISSUE TITLE
User-defined parameters for re-embedding

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1354]
When meeting with Angela's group, I learned that re-embedding was ab essential tool for several users' annotation creation processes; having this tool allowed many of them to switch to at least consider using cellxgene for their annotation creating.

However, they want to have more control over the parameters involved, like which latent space to run the calculation on (currently cellxgene only does UMAP).

It would also be helpful to them to have better documentation around this feature (even in its current state).

Thanks to chenlingantelope@gmail.com, ktrav@stanford.edu, camillee@stanford.edu for this feedback!

**Comment by signechambers1** [comment]
Closing as a low priority for 2021
