### ISSUE TITLE
User-changeable left sidebar width

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1355]
Several users from Angela's group have asked for the ability to change the width of, or hide, the left sidebar (thank you pneuhoef@stanford.edu, jonesbob@stanford.edu, ktrav@stanford.edu).

They prefer to control the width, the ellipsis shortening solution isn't sufficient for a couple of reasons:
- Some of their category names are long enough and similar enough that they still look identical post ellipsis-shortening
- Some users do view their group's browser-hosted cellxgene instance on iPads and phones in which the sidebars take over the whole screen and they can't see the viz at all

See also #1022

**Comment by signechambers1** [comment]
This is an issue but closing as a low priority for development for 2021.
