### ISSUE TITLE
Better touchscreen-device support

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1356]
See also #1355 #1331 #1022 

A few users in Angela's group use mobile and iPad support, to view the group's browser hosted version of cellxgene. I suspect there are others we don't know about (or would be if this experience was better), and this number (or potential number) is bound to grow when we release a hosted version of cellxgene.

- One of the main issues is that our two sidepanels sit on top of the main viz and cover it entirely when the screen gets small enough.
- Zooming (or lack of ability to do so) is also an issue

For context if the device usecase:
ktrav@stanford.edu often uses his phone or to quickly look at gene expression, especially when in meetings or reading a paper.

**Comment by signechambers1** [comment]
Closing as a low priority, mobile is a small percent of our hosted usage right now. we should reconsider if this number grows.
