### ISSUE TITLE
Color-by gene expression while simultaneously viewing centroids for a category

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1358]
User camillee@stanford.edu wants to be able to have centroids turned on for a category of choice (for usecase context, this would usually be one for which the labels closely mapped to the visible clusters), while at the same time coloring by a gene. 

This would help to more quickly identify the labels in which a gene of interest is especially highly (or lowly) expressed.

**Comment by nh3** [comment]
I think some older versions had this behaviour that when colouring by a continuous variable (e.g. expression of a gene), the centroids labels remain those of the last chosen categorical variable (e.g. cell type), which I found very handy. If having the labels of categorical variable of choice is not easy, bring that old behaviour back would be good enough for me.

**Comment by signechambers1** [comment]
@colinmegill or @seve is there a way to see if we had a regression here?

**Comment by signechambers1** [comment]
Closing as a low priority.
