### ISSUE TITLE
View multiples of the same dataset and same embedding, but each colored by a different gene

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1359]
See also #1026 

Thanks to camillee@stanford.edu for the suggestion:
Want to see several of the same dataset and same embedding, but each colored by a different gene
- Says it’s easier to compare this way than what we currently enable: clicking on different gene’s color-by buttons in succession
- Wants to check if gene expressions she’s interested in are surfacing in the same clusters

**Comment by signechambers1** [comment]
Closing as a low priority
