### ISSUE TITLE
Add label to layout axes

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#136]
What "space" are we in? I generally don't care how many "umap units" things are from each other, but I do want to know I'm operating in "umap space" / that I'm looking at a umap representation of the data.

 E.g., 
![image](https://user-images.githubusercontent.com/12618847/43163652-9efe15cc-8f43-11e8-989c-818628b8e4f9.png)

**Comment by signechambers1** [comment]
Closing as not a priority
