### ISSUE TITLE
When a gene of interest is colored-by, show bar plot with AVERAGE gene expression across a category’s labels

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1361]
Specifically, the suggestion from demorree@stanford.edu of Angela's group is to show mean expression as y-axis, with each label / cluster on x-axis.

Compared to tiny histograms next to labels when a gene is colored by, thinks his idea is “more intuitive; in tiny histograms I don’t see number of cells, all are scaled up to top”. As he gets more used to looking at the plots in cellxgene though, it becomes more intuitive; he was used to seeing the plots the other way in other software. He said he does like to gate by a gene expression and move the slider box to see the cells expressed turning on/off.

**Comment by signechambers1** [comment]
Closing as a low priority
