### ISSUE TITLE
View broad overview of gene expressions for several genes at once

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1362]
Thanks to ktrav@stanford.edu of Angela's group for the suggestion.

Wants a way to see a broad overview of gene expression per cell and also cell count/percentage of cells expressing a gene, for several genes at once.

Kyle’s specific ask: dot plot or heatmap, or violin plot for a small number of genes at once
For dot plot, value (darkness) = expression, size of dot = percentage of non-zero cells expressing that gene.

![Screen Shot 2020-03-25 at 4 24 36 PM copy](https://user-images.githubusercontent.com/53277128/78608496-e29fef00-7815-11ea-9443-750a5bb8c952.png)

Another method, per gene (if only need to show a few genes) suggested is a violin list of cell types (each dot is a cell). Dot plot per gene is paired with the list of violin plots. NOTE: We visualize this same data as the gene histograms currently. Can see broad overview this way.

![Screen Shot 2020-03-25 at 4 27 47 PM copy](https://user-images.githubusercontent.com/53277128/78608596-0fec9d00-7816-11ea-8037-a524b43b6079.png)

See also #762

**Comment by cornhundred** [comment]
Hi @liaprins-czi we're working on a WebGL heatmap that might be useful for this type of visualization: https://github.com/ismms-himc/clustergrammer-gl (JavaScript library)  https://github.com/ismms-himc/clustergrammer2 (Python widget). Let us know if you would like to discuss.

**Comment by ambrosejcarr** [comment]
Would use the same underlying data structure as #632 

@ademorree requested this feature: 

> when selecting cells by gene expression level for a differential gene expression analysis, it can be really hard to evaluate the results, simply because you cannot see which were the cells that were selected and where they are in the bigger cluster. A visualization like for example two histograms plotting the genes in the selected vs unselected cells, or a way to bring out the selected cells in the umap would be helpful
