### ISSUE TITLE
Re-embed button is wonkily sized

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1367]
![Screen Shot 2020-03-25 at 3 08 34 PM](https://user-images.githubusercontent.com/53277128/78707332-50efba80-78c5-11ea-9df8-09460b9acde2.png)

Screenshot taken while a user in Angela's group shared their screen (not sure what device they were using but may have been a PC).

**Comment by maniarathi** [comment]
@seve Is this reproducible? Otherwise, perhaps close?

**Comment by colinmegill** [comment]
Confirmed this is no longer present on @bkmartinjr's reembed branch, closing.
