### ISSUE TITLE
adding a gene already in the RSB gives ambiguous error

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1396]
If I use bulk add to add a set of genes, some of which are already in the RSB, I get a series of error toasts that are not super helpful. For example:

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/6fd60a3c-32f1-40e3-9e4a-915cd83bc360)

Leaves me wondering:
* which genes are already there?
* why bother telling me if they are already present?
* did you add the others, or refuse to do anything?
etc.

**Comment by liaprins-czi** [comment]
I've come up with a design that integrates the message more near to the gene add/search widget so it's more in context. Also, when using bulk add, the message would ideally group together all genes that are entered but already exist. Here is the prototype of the design:
https://www.figma.com/proto/ek7rWdkQoZHog0oqugwfjt/1396-Gene-add-error?node-id=2%3A0&viewport=-2652%2C656%2C0.5&scaling=min-zoom

@seve I know you'd been planning to start working on combining the individually add and bulk add functionalities. Would this fix make sense to fit in with that?

**Comment by signechambers1** [comment]
Closing, this will no longer be an issue when we remove bulk adding genes in favor of gene sets.
