### ISSUE TITLE
REST API issues / potential areas of improvement - tracking issue

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#14]
This is a tracking thread for ideas/debate about improvements to the cellxgene REST API.    Please add your own thoughts and/or reactions.

Starter list of issues/ideas:
* Semantics of `/cells` response object:
   1. API mixes together external (submitter) cell ID and the API-internal data structure cell id.  These should be separate concepts.   We should separate these concepts, and use a much more compact "ID" for the API internals.
   2. cellids are encoded into external metadata (with name 'CellName' - this pollutes the namespace)

* `/cells` OTA performance:
   1. don't transmit cellids more than once per cell (currently `/cells` transmits each ID three times)
   2. API internal (response) data structure should use much small encoding for a cellid (eg, a number, or make it implicit)
   3. Current metadata encoding works best for sparse metadata, but wastes a lot of bandwidth if metadata is not sparse (the metadata field names are re-transmitted for each cell).   We could cut response size dramatically by using different data structures for sparse and dense metadata.

* `/initialize`:
   1. better documentation of the schema model used for `schema` field in `/initialize`.  Ie, what are the types, what are their characteristics, etc.
   2. `schema` sub-object should only contain data model info (`include` is a UI hint, and should be not be in the the data schema).

* naming is inconsistent, eg, /cells uses `CellName`, and /expression uses `cellname`
* it would be very helpful if all endpoints, when recieving an unqualified request, returned cells 
in the same order and with the same dimensionality, so that cellname / cellid doesn't have to be
explicitly used to link the two (position in the array is sufficient)
* For regraphing, there is a lot of overhead in using /cells, as it returns all metadata as well as the new graph.  We should have /metadata, and /graph, and get rid of /cells.   If we need the grouping information (`options`), that could be a separate endpoint as well.   Much more flexible for the front-end.

Note on API chattiness (OTA bandwidth): this will only be an issue when the back-ends are much faster.  Currently, most of the "download" time is actually waiting for the back-end to respond (time-to-first-byte).   This is true for both the EM2 and ScanPy back-ends.

**Comment by csweaver** [comment]
Notes from meeting:
- lower priority than local other performance since 1 mil cells takes only a few seconds to download.

Filter
Add a persistent (or ephemeral) filter with takes cellids, etc. and stores them as a url shortener.

/cells
Remove ranges from cells endpoint - implying that we can compute this on the client-side
+ see above

**Comment by bkmartinjr** [comment]
@csweaver I think this is largely complete with the  proposed 0.2 REST API spec.  If you agree, we could close this.

**Comment by csweaver** [comment]
agreed
