### ISSUE TITLE
Lasso FSM error on init

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1413]
## Behavior

The lasso tool issues an FSM error on first use in the app.

## Steps to reproduce

1. OS: MacOS
1. Browser: Chrome
1. Install via repo (`make build-for-server-dev install-dev` or `make pydist install-dist`)
1. Open browser to `localhost:5005`
1. Open developer tools to javascript console
1. Make a lasso selection

## Resulting console errors

```
react_devtools_backend.js:6 FSM error [event: "graph lasso end", state: "init"] Jg {state: "init", states: Set(11), events: Set(22), graph: Map(22), onError: ƒ}
```

Stacktrace:
  | r | @ | react_devtools_backend.js:6
-- | -- | -- | --
  | (anonymous) | @ | (index):188
  | next | @ | (index):188
  | uy.actionFilter | @ | (index):188
  | (anonymous) | @ | (index):188
  | d | @ | (index):188
  | (anonymous) | @ | (index):188
  | handleLassoEnd | @ | (index):188
  | call | @ | (index):157
  | (anonymous) | @ | (index):188
  | apply | @ | (index):157
  | qn | @ | (index):157
  | a | @ | (index):188
  | m | @ | (index):188
  | (anonymous) | @ | (index):157

**Comment by bkmartinjr** [comment]
Very likely a dup of #695

**Comment by bkmartinjr** [comment]
@mweiden - I am unable to reproduce this on master with pbmc3k.h5ad test dataset.  Can you still reproduce, and if so, can you give me a more detailed test case?

**Comment by mweiden** [comment]
Heisenbug! I can't reproduce this off master either. I will close this for now and reopen it if I can reproduce it again.
