### ISSUE TITLE
new monovalued annotations need improvement

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1417]
The new monovalued cell annotations are great, but need a few tweaks.  See image below:

1) the third item shows that they do not wrap well - ie, become multi-line in an ungraceful manner.  
2) when they are ellipsis abbreviated/truncated (eighth item) there is no tooltip to make the entire annotation name or value visible.

In addition:
3) as you can see in the second image, some of the expandable categories line wrap (see very last item where the chevron appears on the second line)

---

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/8f343f52-c19b-4de9-921b-905ebab9325c)

and

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/b4e27b64-2278-4277-8886-2611e8ff9789)

**Comment by signechambers1** [comment]
Closing as no longer relevant, singletons are pulled in to the dataset info drawer now
