### ISSUE TITLE
Hosted cellxgene looks... interesting in Safari

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1421]
## Application behavior

* Scatterplot doesn't render
* Fonts seem off
* Buttons are visible but style isn't correct

<img width="1226" alt="Screen Shot 2020-04-22 at 2 54 33 PM" src="https://user-images.githubusercontent.com/538456/80039856-a7581e00-84ad-11ea-8f7b-27d88b712dd4.png">

## Steps to reproduce

Open in Safari https://cellxgene.dev.single-cell.czi.technology/d/pbmc3k.cxg/

**Comment by bkmartinjr** [comment]
@mweiden - I believe this is resolved.  Could you confirm and close if true, or update with more info if not?

**Comment by mweiden** [comment]
@bkmartinjr resolved!
