### ISSUE TITLE
smoke tests are failing

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1432]
in the CI pipeline, smoke tests are failing on most (all?) branches, when run on github actions. They seem to work fine elsewhere.

See for example, PR #1425

**Comment by mweiden** [comment]
PR #1425 is a separate issue. That's failing because I've been hacking on our dependency installation code...

https://github.com/chanzuckerberg/cellxgene/pull/1425/checks?check_run_id=616858354

**Comment by bkmartinjr** [comment]
mmm...well, maybe this is my fault!   I'll add myself to the assignees and try to have a look at it in a few days.

**Comment by bkmartinjr** [comment]
@mweiden - I am pretty sure this is fixed.  Can you close if that is true?
