### ISSUE TITLE
After subset + undo subset, selection (and subsequent subset) ignores lasso boundaries (unless in UMAP)

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1433]
To reproduce:

1. Switch to a non-UMAP embedding
2. Subset to a selection (doesn't matter if selection was made via lasso or categories, not sure about continuous selection). This should work just fine.
3. Undo the subset so it returns to all cells being selected
4. Lasso some cells...

_This_ is when the bug happens: it doesn't properly select the lassoed cells. Instead some cells within the lasso boundaries are selected, and some are not:
![second time subset ignores lasso in all but UMAP 1](https://user-images.githubusercontent.com/53277128/80424211-18287d00-8896-11ea-9a7b-122a9afb0011.gif)

Furthermore, if you subset, it will subset to the cells that are (incorrectly) turned on, not the ones within the lasso's bounds:
![second time subset ignores lasso in all but UMAP 2](https://user-images.githubusercontent.com/53277128/80424276-3b532c80-8896-11ea-951b-9b85f80a8e69.gif)

Here is a possible clue, though... The GIFs from above were taken while using master. However, I first discovered this when testing a PR for Matt's fixed-width fix today. In that branch, for some reason, when I switch back to UMAP embedding after the following steps described above, the selection does not clear (it does on master, currently, which is not necessarily the expected state, though ... see #1192 which I am working on right now). In that branch, the subset cells remain instead of resetting back to all. And this reveals that when I switch back to UMAP, the subset cells fit perfectly into where the lasso had been!
![lasso ignores embedding type 1](https://user-images.githubusercontent.com/53277128/80424678-14492a80-8897-11ea-800d-dacee601f63e.gif)
![lasso ignores embedding type 2](https://user-images.githubusercontent.com/53277128/80424708-1f03bf80-8897-11ea-80b1-3f071af5ef5b.gif)

**Comment by liaprins-czi** [comment]
UPDATE: That last behavior is happening on Master too. Sometimes switching embeddings will undo subset but sometimes not. It's inconsistent, just like the lasso cell recognition. I am addressing what the correct behaviors should be in #1192

**Comment by mweiden** [comment]
I _think_ that I get what's going on here. I think the action of changing the embedding isn't changing the lasso selection layer (they're different). For some datasets, if you switch back to the default embedding, the selection seems to capture the relevant points.

**Comment by liaprins-czi** [comment]
@mweiden Not sure if you were the one I should have assigned this to, but I know you'd worked on changing the subset/undo-subset functionality originally, so that is why I did. Feel free to re-assign if you are not the right one for this.

**Comment by mweiden** [comment]
I've figured out the problem: when selection is deselected the world is reset to the universe the crossfilter is reset, including the embeddings in the `layout_XY`. However, the embedding selection stays the same. If the embedding selected is not the default, the embedding shown to the user will be different than the embedding `layout_XY` in the crossfilter, causing lasso selections to be made against the wrong embedding coordinates.
