### ISSUE TITLE
Occupancy render artifact

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1455]
Occupancy is showing a render artifact that could be misleading and imply information. This would be especially easy to miss if there were many categories rendered.

![image](https://user-images.githubusercontent.com/1770265/81094724-f0f33080-8ed1-11ea-8bfc-760c65c0d4a7.png)

**Comment by colinmegill** [comment]
There are only 4 categories, but there are more colors (small, 1px or .5px areas)

**Comment by signechambers1** [comment]
Closing as a low priority for 2021
