### ISSUE TITLE
dump-default-config not a launch option

### ISSUE THREAD

**Issue by antvalencia** [chanzuckerberg/cellxgene#1465]
Server's Elastic Beanstalk README notes a configuration file can be created with the [command](https://github.com/chanzuckerberg/cellxgene/blob/5947306ca05bc5a3104388af0b7fb11cac349c15/server/eb/README.md#3-configuring-cellxgene):

`cellxgene launch --dump-default-config > myconfig.yaml
`

however, this option no longer seems to be available.  the output i get is:

```
~/ws/cellxgene$ cellxgene launch --dump-default-config
Usage: cellxgene launch <options> <path to data file>

Error: no such option: --dump-default-config
```
is there another way to create this configuration file?  i looked at the list of launch options, but nothing stood out.  thanks!

**Comment by bmccandless** [comment]
Hello @antvalencia .  The --dump-default-config is a new option, available off master.   Perhaps you have an earlier version of cellxgene installed.

**Comment by antvalencia** [comment]
what version was this introduced in?  i'm running `[cellxgene] Version 0.15.0`.

**Comment by bmccandless** [comment]
Hello @antvalencia.   
The dump-default-config was introduced after 0.15.0 was released.  If you did a pull from master recently, then you should have it.    You can verify like this: 
```grep dump-default-config server/cli/launch.py```
That should return something.
If it is there, then I suspect that an earlier version of cellxgene is in your path.

**Comment by antvalencia** [comment]
pulled again.  working now.  thanks, and my apologies for the report!

**Comment by antvalencia** [comment]
pulled again. working now. thanks, and my apologies for the report!
