### ISSUE TITLE
Re-embedding does not use batch-corrected latent space

### ISSUE THREAD

**Issue by chenlingantelope** [chanzuckerberg/cellxgene#1466]
I used batch correction method to get a latent space where all the cells share a common space, however after running subsetting and re-embedding the cells separates out by batch again. I assume that this is because re-embedding re-runs PCA on the subset of cells. Would it be possible to select a high-dimensional latent space to only run UMAP on for the re-embedding option? 

Thank you!

**Comment by signechambers1** [comment]
Closing since we will not be supporting reembedding functionality in our cellxgene 1.0 release. Thank you!
