### ISSUE TITLE
DE doesn't prevent me from running (with relatively large selections), but then it times out

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1474]
DE won’t run on some relatively large selections, but it doesn’t prevent me from starting to run it with the warning tooltip and red DE button. It still lets me start to run it, but it times out. The smallest selections I made that this happened on were for group 1: **2490 cells** and group 2: **9631 cells** (although there could be smaller selection totals for which this happens, too, I can do some more tests).

I think this one could be fixed by lowering the maximum total cell selection for DE. However, it may just be something going wrong with DE, and it should be able to handle that many? The current maximum looks like it is 50,000 cells, which this is much below.

Here is a screenshot with the console:

![Screen Shot 2020-05-13 at 10 33 14 AM](https://user-images.githubusercontent.com/53277128/81847124-01299200-9508-11ea-8d21-a72f324f91a4.png)

And here is what it should be doing when I select too many cells for DE to run (and prevent me from clicking the button to run):

![Screen Shot 2020-05-13 at 10 54 41 AM](https://user-images.githubusercontent.com/53277128/81847233-2ae2b900-9508-11ea-9b88-143ec0dde78e.png)

**Comment by brianraymor** [comment]
Per @ambrosejcarr - closing because the root problem will be addressed and a warning not required.
