### ISSUE TITLE
Large datasets make scatterplot cells look unselected due to tiny-ness (and actual unselected ones are invisible)

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1475]
When I plot genes on the scatterplot, the unselected cells are too tiny to show up in the scatterplot (and the selected ones are also very tiny, the size of unselected ones in the main vis. I am testing with a large dataset when this happened, and it is probably related to #1325 Colin made wherein the main vis dots disapper for large dataset in small window. I do not think this one is enough of an issue to stop the release. Here is a screenshot showing how difficult it is to even see the selected cells in the scatterplot, and how they look “unselected” due to their tinyness:
![Screen Shot 2020-05-13 at 10 17 51 AM](https://user-images.githubusercontent.com/53277128/81847561-9d539900-9508-11ea-8431-5d62dd84ea57.png)

Probably related to #1325 .

I was testing with this dataset:
https://cellxgene.dev.single-cell.czi.technology/d/HumanTissueTcellActivation.cxg/

**Comment by liaprins-czi** [comment]
My recommendation from design perspective would be to ensure that the unselected cells never get smaller than 1px. Then to keep them apart from the selected cells, the selected cells should never be smaller than 2px.

**Comment by signechambers1** [comment]
This is an issue on the 4m cell dataset, see https://chanzuckerbergteam.slack.com/archives/C018B64J3HN/p1605215186088800 for link

**Comment by signechambers1** [comment]
Closing as a low priority for 2021 development but we can reopen if this keeps coming up (and it probably will)
