### ISSUE TITLE
better error display for unsupported browsers

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1477]
We see occasional users attempt to use cellxgene with unsupported browsers (eg, IE on Win 7).  It would be nice if the front-end could present the user with something other than a hard failure.

**Comment by colinmegill** [comment]
MDN has a thoughtful article on feature detection vs user agent detection: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

If we decide to go the user agent route, `ua-parser-js` https://www.npmjs.com/package/ua-parser-js seems serviceable.

**Comment by colinmegill** [comment]
Todo: add hard page refresh to trigger Google Analytics, so that we know how many people are seeing the page

**Comment by seve** [comment]
As of now, what browsers are confirmed unsupported?

**Comment by bkmartinjr** [comment]
Candidates likely to be outside of design scope or not work:
* any version of IE due to missing features
* small form-factor devices
This will require some research on the basic mechanism is built, eg, https://caniuse.com/

Suggest starting with the known failures we have, eg, the old IE that doesn't have required feature suppot.

**Comment by tihuan** [comment]
For context, Meta uses `nomodule` attribute on `<script />` tag to show a custom message to unsupported browsers. I think we got the inspiration from [this post](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/)

The gist is that older browsers don't recognize `nomodule` attribute, so it will execute the custom message script, while modern browsers won't.

The actual PR is here: https://github.com/chanzuckerberg/khepri/pull/3825!

**Comment by seve** [comment]
`babel-preset-modern-browsers`defined most, if not all, of our incompatibilities(https://github.com/christophehurpeau/babel-preset-modern-browsers)

**Comment by tihuan** [comment]
It seems like we just want to have a better error message for browsers we don't support, instead of showing a blank page or something?

If so, I think https://github.com/chanzuckerberg/cellxgene/issues/1477#issuecomment-644443794 would solve the problem, and for the versions of modern browsers we support, we could do the same as Meta?:

```
"browserslist": [
    "Chrome > 60",
    "Safari >= 10.1",
    "iOS >= 10.3",
    "Firefox >= 60",
    "Edge >= 15"
  ],
```

Then we just need to make sure to transpile our code down to ES6 and things should just work!

**Comment by bkmartinjr** [comment]
We don't support small form factor devices.  So we want to catch that as well.  My primary requirement is that we show a clean page, with a friendly "sorry" message, if it is a device we don't support.

**Comment by tihuan** [comment]
Ahh viewport size! I see that iPad's viewport size is 1024x768. So do we just add another requirement that the viewport needs to be above that (and explicitly say that in the message too)?

And we will also show the sorry message if someone resizes their laptop browser to be below the threshold too?

**Comment by seve** [comment]
![image](https://user-images.githubusercontent.com/8716829/86947486-b17ad780-c100-11ea-8ecd-ef8261301bd1.png)
Looks like the `TextDecoder` API is unsupported by < Edge v83.0.0
https://sentry.prod.si.czi.technology/sci-sc/hosted-cellxgene/issues/7558/?environment=prod

**Comment by seve** [comment]
@tihuan Looks like Meta's supported browser list includes Edge versions 15-18 which don't support `TextDecoder`.  Since Edge 14+ supports ES6 it would pass through the `nomodule` attribute.  Is there a way we could tweak Babel to polyfill `TextDecoder`?

**Comment by tihuan** [comment]
Ooh awesome catch, @seve ! 🥇 🎉 

I was looking at https://stackoverflow.com/a/36949791, it seems like https://github.com/anonyco/FastestSmallestTextEncoderDecoder is the library recommended by MDN!
