### ISSUE TITLE
make build-for-server-dev error in windows

### ISSUE THREAD

**Issue by Donaldpherman** [chanzuckerberg/cellxgene#1478]
Hi,

    When I run make build-for-server-dev in windows I get the follow error.

PS C:\Users\donal\source\repos\cellxgene> make build-for-server-dev                                                     "C:\ProgramData\chocolatey\lib\make\tools\install\bin\make.exe": Interrupt/Exception caught (code = 0xc0000005, addr = 0x79535c73)

thanks for any yelp.

**Comment by bkmartinjr** [comment]
At the moment, our current build does not support building on Windows native, and we don't have any contributors who work in that environment (we actively support build on Linux and macOS).  We do have contributors who build using Windows/WSL (essentially Linux user space and tools).

You are welcome to submit PRs/fixes, but given that we don't actively maintain a Windows build environment, they will likely degrade over time without attention.

I suggest working around this by using Windows WSL. This is known to work, and building on Linux is actively supported.

I'm going to close this issue as it is not a build platform we intend to support, but please feel free to re-open if I have misunderstood the issue.  Thanks!

**Comment by Donaldpherman** [comment]
Thanks for the reply back.  I got Cellxgene to build on windows a few months ago.  Maybe it was just a coincidence that it worked.  I'll try the WSL.

**Comment by bkmartinjr** [comment]
That makes sense.   We have been reworking our build system recently, as we work on the hosted/WSGI variant of cellxgene.  Because we don't actively support or test a windows build, we probably regressed.

Sorry about that!
