### ISSUE TITLE
Consolidate text truncation into a unified component

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1489]
Text truncation has become common and widespread enough that keeping our approach consistent has become difficult.  The app would benefit from having a `SmartTruncate` component that handles truncation in a smart and consistent fashion.

**Comment by colinmegill** [comment]
Loose threads: 

https://www.npmjs.com/package/react-container-dimensions
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
https://medium.com/trabe/measuring-non-rendered-elements-in-react-with-portals-c5b7c51aec25

`<SmartTruncate width={x}> {childcontent} </SmartTruncate>`

If the left sidebar width (currently a constant) changes, content should dynamically update. On a 4k monitor, we have more width to work with and might in the future expand the sidebar width. This component should account for / anticipate that.

**Comment by seve** [comment]
Separate approach: https://www.npmjs.com/package/string-pixel-width

**Comment by colinmegill** [comment]
@seve `string-pixel-width` would first have to be rewritten to support our font of choice, and if the browser didn't load or couldn't display our font or we changed it in the future, this would respectively fail or need to be rewritten, correct?

**Comment by colinmegill** [comment]
We can also expect to use this component on the right sidebar, for geneset names. 

![image](https://user-images.githubusercontent.com/1770265/82492111-ab2e8e80-9ab3-11ea-92df-4680b3526d29.png)

**Comment by colinmegill** [comment]
To be explicit, the reason this bit of engineering is necessary is that this problem is still not handled in app:

![image](https://user-images.githubusercontent.com/1770265/82492280-ed57d000-9ab3-11ea-9b6d-1fc3b999725c.png)

**Comment by seve** [comment]
> `string-pixel-width` would first have to be rewritten to support our font of choice, and if the browser didn't load or couldn't display our font or we changed it in the future, this would respectively fail or need to be rewritten, correct?

The library has an API for importing custom fonts which we would need to use to support Robotto Condensed as well as our fallback fonts
