### ISSUE TITLE
metadata selection controls state does not update correctly when switching left sidebar view

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#149]
If I have an active set of metadata selections in the left side bar (LSB) controls -- either continuous or categorical, and switch to Expression LSB view, and then back to Metadata, the controls do not correctly show the current selection state.

To reproduce:
1. load some data
2. make some metadata selections in the LSB
3. Click `Expression` to change the LSB view to expression
4. Click `Metadata` to change LSB view back

note that all of the previously selected controls show the wrong state -- they do not reflect the selection made in step 2 (and currently active).

**Comment by bkmartinjr** [comment]
Root cause is a latent issue with how _.get() was incorporated.   See PR #148

**Comment by bkmartinjr** [comment]
@colinmegill - this issue is still present, even though #148 was fixed.  So the root cause comment above is incorrect.

This seems like a significant issue with histograms (and potentially other selection widgets), which we need to fix before ship.

**Comment by colinmegill** [comment]
This is caused by the components unmounting when the tabs are switched. Two solutions:
* Remove the metadata tab, so the components are all mounted
* Store state in redux rather than in `this.state`, and reconstitute the state of the brushes when flipping back and forth.

**Comment by bkmartinjr** [comment]
obsolete.
