### ISSUE TITLE
Load another data set by URL to replace the initial one after cellxgene launch

### ISSUE THREAD

**Issue by baohongz** [chanzuckerberg/cellxgene#1498]
Is it possible load different data set on the fly after cellxgene launch by providing a link to a h5ad file without downloading data and launching cellxgene again from the command line?

e.g.

https://cellgeni.cog.sanger.ac.uk/tissue-stability/tissue-stability/spleen.cellxgene.h5ad

**Comment by bkmartinjr** [comment]
The only way to do this with the local (desktop) cellxgene is to restart the application.  The app assumes it is a single-dataset viewer.

We are working on a multi-dataset capable version of cellxgene, primarily for hosted use, which will support access to multiple datasets.  This has not yet been finished and released, but earlier version are available in the github master branch if you are comfortable working from the source directly.  Check out the `--dataroot` option.

Closing as this is a question, but please feel free to reopen if you have additional comments or questions.  Thanks!
