### ISSUE TITLE
Custom colormaps for continuous variables

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1507]
## Context

See source discussion in https://github.com/chanzuckerberg/cellxgene/issues/446

## Need

Summarizing the user stories outlined here:
* As a user of cellxgene, I want to optionally select the colormap for continuous variables from a short list of common [perceptually uniform sequential colormaps](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html), so that I can better perceive the differences in expression in my dataset.
* ~As a user of cellxgene, I want to optionally select from a short list of common [divergent colormaps](https://github.com/chanzuckerberg/cellxgene/issues/446#issuecomment-554393436) for differential expression, so that I can more easily see differences in expression between two populations of cells.~

**Comment by colinmegill** [comment]
See also: https://github.com/chanzuckerberg/cellxgene/issues/546

**Comment by mweiden** [comment]
@colinmegill oh, pardon. Didn't know about that one. I will scratch the divergent user story from this issue.

**Comment by signechambers1** [comment]
Closing as a low priority for 2021
