### ISSUE TITLE
CXG conversion supports Corpora automated pipeline

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1515]
Adapt the CXG conversion process to work within the data processing pipeline for corpora.

**Comment by signechambers1** [comment]
Closing in cellxgene repo, tracking data processing pipeline design here: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/305
