### ISSUE TITLE
Corpora deployment integrated with Corpora auth

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1521]

**Comment by tihuan** [comment]
Questions:

1. I'm assuming the deployment integration needs to be done for all environments? Dev, staging, prod

2. What needs to be done in this ticket? Assuming Auth0 integration has been done, is it just configuring BE to use the right Auth0 tenant per environment?

**Comment by tihuan** [comment]
Dup of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/481undefined! Closing
