### ISSUE TITLE
user annotations backend supports both anonymous and authenticated user sessions

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1526]

**Comment by MDunitz** [comment]
@bmccandless can we close this once your auth work ships?

**Comment by bmccandless** [comment]
@MDunitz definitely part of this is the auth work.   It depends on when that is done and the hosted annotations feature is done.

**Comment by MDunitz** [comment]
Closed -- work duplicated in other tickets
