### ISSUE TITLE
back-end routes support import & export of user annotations

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1527]

**Comment by MDunitz** [comment]
Closing -- work described in tickets #[1687](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1687) and #[1688](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1688)
