### ISSUE TITLE
user annotations at feature parity on all deployments

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1528]

**Comment by mweiden** [comment]
@MDunitz This sounds more like an Epic (collection of user stories for SaaS cellxgene annotations). Could you describe the delta that we're currently at between SaaS cellxgene and CLI cellxgene? Perhaps we could then make this more of a checklist of the individual features that we must implement before we _reach_ feature parity.

Thoughts?

**Comment by MDunitz** [comment]
Closing because work described in [epic](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1529)
