### ISSUE TITLE
Changing label name doesn't update colors until refresh

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1534]
To reproduce: 

Create a new category by duplicating another, change a label, colors mismatch. Hard refresh colors update.

<img width="1317" alt="Screen Shot 2020-06-04 at 12 59 44 PM" src="https://user-images.githubusercontent.com/1770265/83788782-be209180-a663-11ea-8cd6-529999c08f15.png">

**Comment by bkmartinjr** [comment]
Fixed by #1571
