### ISSUE TITLE
Categorical differential expression - read-only categories

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1536]
Add the new categorical differential expression feature for read-only categories (ie, does not include user-defined/created annotations).

Included in this epic:
1. Compute the mean/variance of each group/label from the matrix file
2. Intermediate results are persistent/cached for acceleration
3. Introduce new categorical diffexp UI into front-end UI (maintain existing ad hoc UI)
4. Update the diffexp code to make use of precomputed results
5. Rework the diffexp REST API to use categories, rather than cell indices to dramatically reduce data sent form client to server.

**Comment by signechambers1** [comment]
Closing this epic as we are not prioritizing this work as stated here.
