### ISSUE TITLE
Gene sets - interaction

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1538]
Initial work on gene sets, primarily focused on the interaction model, but lacking persistence.

1. Users can create gene sets, edit the set name, remove the set add genes, remove genes
2. Users can see a mini histogram of the gene expression while gene is in collapsed state
3. Users can expand a gene to make a brush selection
4. Users can link a gene set to a label within a category, a click on the category name (currently unused) will scroll to and blink the gene set name
5. Unify gene name entry UI with new multi-input/autosuggest/pill component (remove extraneous modalities in UI)

**Comment by brianraymor** [comment]
Completed epic. Closing during PM triage.
