### ISSUE TITLE
User annotations - desktop DB refactor

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1540]
Refactor desktop user annotation store to improve performance and have full feature parity work with hosted.  Likely will move to embedded DB.

**Comment by ambrosejcarr** [comment]
@MDunitz how does this relate to work in chanzuckerberg/single-cell#20?

**Comment by MDunitz** [comment]
This would be a future optimization of the desktop version of annotations. I'm not sure if its really necessary.

**Comment by ambrosejcarr** [comment]
From discussions with @MDunitz , this anticipates a potential future optimization and will come up logically in the future if there is advantage to optimizing the desktop database.
