### ISSUE TITLE
Gene sets - sharing

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1541]
1. Users can create gene sets quickly from existing CSVs — create one set, create multiple sets (import, effectively, and probably drag and drop)
2. Users can import/export gene sets as CSVs from the UI
3. CLI users can specify gene set "autoexport" to CSV, as a convenience feature for local user.

**Comment by brianraymor** [comment]
Also see [Gene Set Formats](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#Gene_Set_Database_Formats)

**Comment by brianraymor** [comment]
Per @signechambers1 - closing during PM triage. Appears to duplicate other issues.
