### ISSUE TITLE
coexpression heatmaps

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1542]
1. Users can create heatmap for:
   * geneset * geneset (coexpression)
   * geneset * category (which labels express which genes)
   * category * category (coexpression)
2. heatmap view (subset, pan/zoom) is sychronized with other views

includes heatmap/scatterplot component projects

**Comment by signechambers1** [comment]
Closing as a duplicate of https://github.com/chanzuckerberg/cellxgene/issues/632
