### ISSUE TITLE
Lustre/FSx

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1543]
Data access performance improvement for the Corpora deployment
1. Configuration needed to add security groups, and launch commands to mount the lustre filesystem
2. Process to manage how data is managed between S3 and Lustre 

May require feature update to AWS FSx for data management workflow to become practical.

**Comment by signechambers1** [comment]
@bmccandless or @mckinsel is this ticket still relevant?

**Comment by bmccandless** [comment]
@signechambers1 it's an approach to improving performance when reading datasets from storage.   It is something we can still do and benefit from.

**Comment by maniarathi** [comment]
@bmccandless Can you please link in the documents that you created while investigating FSx as well as add a brief description in the ticket of your findings?

**Comment by bmccandless** [comment]
@signechambers1 @maniarathi Here is the link:  https://docs.google.com/document/d/1fDSRpgFGHN2dpevwxen5xQPw2mPPOYd7dRQJRrIgYXk/edit?usp=sharing

**Comment by bmccandless** [comment]
Here was my conclusion from the doc:

Conclusion:  we may need more information about the final design of the cellxgene compute tier to understand how the lustre filesystem may fit in.   Clearly there are benefits for higher bandwidth for the overall performance of the system, including the user experience.   However, different design choices may reduce the need to rely on lustre.   Certainly cost will be a factor in deciding to adopt this for production.

**Comment by signechambers1** [comment]
Thanks @bmccandless ! Closing this ticket in favor of [1843](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1843). Once the design is finalized we can reopen or create new tickets based on the design doc.
