### ISSUE TITLE
asynch compute operations

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1546]
Support improved UX for long-running async computes that must interact with the user.

Front-end:
1. Users can start one ore more long-running compute from the UI, without the UI blocking (eg, reembedding)
2. Users are notified when a long-running compute is complete, and can view results
3. Users can cancel long-running compute
4. Users can observe status of all pending compute

Back-end:
1. A long running compute job can be launched async on a dedicated tier, based upon user request
2. Notification of completion, status upates, queuing, etc.
3. Async front-end notification protocol

**Comment by signechambers1** [comment]
Closing as a low priority for 2021. Labeling with "reembedding" so we can find this issue in the future if needed. May also be relevant for DE conversations.

**Comment by bmccandless** [comment]
@signechambers1,  async compute operations are also needed for differential expressions.  Anything that might take more than 30 seconds will require an async interface between the frontend and backend to avoid a request timeout.
