### ISSUE TITLE
Cell selection via a category with truncated list of labels isn't working properly

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1556]
![cell selection not working correctly for truncated category](https://user-images.githubusercontent.com/53277128/84298952-cf0a5080-ab04-11ea-8766-c1ad7d9598d8.gif)

https://cellxgene.dev.single-cell.czi.technology/d/GSE60361.cxg/

A few weird things are happening here:

1. Strange that after I lasso a selection, all of the labels within the first category (which is a truncated category list) happen to stay checked on. This is unusual because each label is a single cell in this example. It seems unlikely that all of the lasso'd cells would just happen to be the ones listed in the top of the category's list of labels. However, when I checked this for other category types (e.g. with just two labels), when I select cells that I know are only in one label ,the other labels stay checked on. I think this is a bigger design issue than this bug. If zero of a given label's cells are selected via lasso or other means, shouldn't its label become unchecked?

2. Unselecting one label, which in the example case shown in the GIF above is one cell, should mean only one dot gets turned off (if it happens to be within the lasso'd area). However, instead an unpredictable amount of cells within the lasso'd area are turned off.

3. This happens again when lasso is unselected: instead of returning to all cells selected like they were prior to any lassoing, an unpredictable amount of cells are selected. All visible/non-truncated labels in the top category are shown as checked on.

I think the cells that are shown as turned on are the ones visible in the truncated list, because when I click to add them to cell group 1 for DE, it says there are 200 (I believe that is the number of labels we default show in a truncated list?).

**Comment by bkmartinjr** [comment]
Great bug @liaprins-czi ! 

To clarify, the category label checkboxes should not select/unselect in response to the current lasso.  They are fully independent, as are all other selections (eg, histograms don't auto-brush select based on lasso).

The single point select/unselect bug is very real, and has been there a long time.  Great find.
