### ISSUE TITLE
/schema route is returning illegal schema data type

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1582]
The CXG back-end returns an undefined data type (float64) for the layouts/embeddings.  The following was pulled directly from PROD today, and shows a "float64" type, which is an unknown/undefined type in the protocol/API.  The current REST API (ie, the flatbuffer schema) only supports 32 bit floats, and types of:  `string`, `boolean`, `int32`, `float32` and `categorical`.  

This has not caused issues yet, but could as the FBS encoder forces all floats to an IEEE 32 for transmission over the wire.   The incorrect schema (I removed all of the extraneous information, leaving only the buggy part):

```
$ curl -X GET https://cellxgene.cziscience.com/d/pbmc3k.cxg/api/v0.2/schema | jq
{
  "schema": {
    /* ... SNIP ... */
    "layout": {
      "obs": [
        {
          "dims": [
            "draw_graph_fr_0",
            "draw_graph_fr_1"
          ],
          "name": "draw_graph_fr",
          "type": "float64"
        },
        {
          "dims": [
            "pca_0",
            "pca_1"
          ],
          "name": "pca",
          "type": "float32"
        },
        {
          "dims": [
            "tsne_0",
            "tsne_1"
          ],
          "name": "tsne",
          "type": "float64"
        },
        {
          "dims": [
            "umap_0",
            "umap_1"
          ],
          "name": "umap",
          "type": "float64"
        }
      ]
    }
  }
}

```

Looking at the code, it appears we are failing to observe the schema protocol in `cxg_adaptor.py`.  Inside `_get_schema()`, it has code for embedding schema which bypasses the helper functions which map between numpy and API type systems:
```
    for ename in embeddings:
        A = self.open_array(f"emb/{ename}")
        obs_layout.append({"name": ename, "type": A.dtype.name, "dims": [f"{ename}_{d}" for d in range(0, A.ndim)]})
```
Rather than using `A.dtype.name`, which is the numpy type, it should be using the helper function `dtype_to_schema` as is used a few lines earlier for other array data.

If you refer to the old anndata adaptor, it does things correctly.

**Comment by bmccandless** [comment]
It looks like the value for type should just be hard coded to "float32" .  The normalize_embeddings function in data_adaptor converts to float32, and the anndata adaptor also hard codes the type to float32.   dtype_to_schema will throw an exception if float64 is passed in.
