### ISSUE TITLE
Centroid styling on lasso select

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1583]
Currently, centroids have a deselect styling mode when their value is deselected on the left-sidebar. 
![image](https://user-images.githubusercontent.com/8716829/85596225-650ea280-b5fe-11ea-8f5c-ecd4729fe348.png)

This same styling _is not_ present when a value is deselected via the lasso
![image](https://user-images.githubusercontent.com/8716829/85596419-8d969c80-b5fe-11ea-8ae5-5cdae0fb52a6.png)

Should the behavior be extended across selection methods?

**Comment by seve** [comment]
CC: @colinmegill @liaprins-czi

**Comment by liaprins-czi** [comment]
Good catch, I think they should deselect, and this should also happen whether centroids are turned on or not, which I also brought up in #1556 9first bullet).

**Comment by signechambers1** [comment]
Closing as a low priority, @colinmegill if you disagree please reopen and let me know what priority you think it should be.
