### ISSUE TITLE
Brushable histogram has difficult to find interaction status

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1584]
When working with numerous continuous fields on the right sidebar, it can become hard to find which, if any, histogram(s) is/are currently being brushed.
![Kapture 2020-06-24 at 9 49 36](https://user-images.githubusercontent.com/8716829/85598080-16fa9e80-b600-11ea-9f50-3f723082f38a.gif)

**Comment by baohongz** [comment]
We developed [cellxgene VIP (Visualization in Plugin)](https://github.com/interactivereport/cellxgene_VIP) to generate violin, stacked violin, stacked bar, heatmap, volcano, embedding, dot, track, density, 2D density, sankey and dual-gene plot in high-resolution SVG/PNG format. There is a function to show exact brushing values on the right panel and in a table.

<img width="1014" alt="Screen Shot 2020-08-31 at 4 59 45 PM" src="https://user-images.githubusercontent.com/15882624/91768394-874b1080-ebab-11ea-9856-449aabdb0afc.png">

**Comment by brianraymor** [comment]
@signechambers1 advises that this is not a 2021 priority. Closing until there is further consumer research.
