### ISSUE TITLE
Error opening .h5ad file

### ISSUE THREAD

**Issue by GiacomoMa** [chanzuckerberg/cellxgene#1587]
When opening an .h5ad file in 2 different computers (both MacOsX 10.14.6) with the updated version of cellxgene, I receive the same error message:
Error: 'dict' object has no attribute 'dtype' - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.

The input is the same I successfully used 1 week ago.
Could you suggest me a possible solution?
Many thanks for the attention.

**Comment by bkmartinjr** [comment]
Hi @GiacomoMa - there has been no updated release of cellxgene for a few months, so something else has changed in the past week.  If you can provide more info, I'll help diagnose.

To start, can you provide the output of `pip freeze` on the systems where it fails (if you are using virtual environments, please make sure you activate that before running `pip freeze`).

**Comment by GiacomoMa** [comment]
Hi bkMartinjr,
thanks for the swift reply.

I am running from the terminal, so no virtual environment
Here the outcome of pip freeze:

Error: 'dict' object has no attribute 'dtype' - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.
(cellxgene) phg17ma23:~ Giacomo$ pip freeze
aniso8601==8.0.0
anndata==0.6.22.post1
botocore==1.17.9
cellxgene==0.15.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cycler==0.10.0
decorator==4.4.1
docutils==0.15.2
fastobo==0.8.2
Flask==1.1.1
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-Cors==3.0.8
Flask-RESTful==0.3.7
flask-server-timing==0.1.2
flatbuffers==1.11
fsspec==0.6.1
h5py==2.9.0
idna==2.9
importlib-metadata==1.1.0
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.10.0
joblib==0.14.0
kiwisolver==1.1.0
llvmlite==0.30.0
MarkupSafe==1.1.1
matplotlib==3.0.3
mock==3.0.5
more-itertools==8.0.0
natsort==6.2.0
networkx==2.4
numba==0.46.0
numexpr==2.7.0
numpy==1.17.4
packaging==20.4
pandas==0.25.3
patsy==0.5.1
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
requests==2.24.0
s3fs==0.4.2
scanpy==1.4.4.post1
scikit-learn==0.22
scipy==1.3.3
seaborn==0.9.0
six==1.13.0
statsmodels==0.10.2
tables==3.5.1
tiledb==0.6.3
tqdm==4.40.0
umap-learn==0.3.10
urllib3==1.25.9
Werkzeug==0.16.0
zipp==0.6.0

**Comment by bkmartinjr** [comment]
you should use Python virtual environments - they will help prevent this kind of error. [Link](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)

This is likely an incompatibility with the h5py or anndata modules.  Couple of more questions:
* what changed over the past week (since the same H5AD worked)?  Did additional python modules/apps get installed?
* any chance you can share the h5ad file with me for testing?

**Comment by bkmartinjr** [comment]
Addendum - as a test, I suggest creating a new python virtual environment, installing cellxgene anew, and retrying.

Briefly, cd to your work directory, and:
```
$ python3 -m venv ./test-venv
$ source ./test-venv/bin/activate
$ pip install cellxgene
$ cellxgene launch something.h5ad
```

**Comment by GiacomoMa** [comment]
Ok, I will try.
- I tried first on my laptop and it worked smoothly. I did add labels inside cellxgene, and found the csv file on my home folder. Yesterday I tried it on my computer at work, and did not work. I updated cellxgene (pip cellxgene --updated) but nothing changed. I went back to my laptop, and also there it did not work any longer. I tried the file located either locally on the cloud, but same error.

I did not install any update in any computer, except the weekly Microsoft update... .

Here the link for the file:
https://syncandshare.lrz.de/getlink/fiGWs11Cw1euVodHfvUXS5et/15062020_ml_adata_for_giacomo_cellxgene_2.h5ad

thanks!

PS
I will try what you have just suggested.

**Comment by GiacomoMa** [comment]
I created a new python environment and it worked.

thanks!

I delete the file then.

Best,
Giacomo

**Comment by bkmartinjr** [comment]
OK, great!  I am fairly certain the environment on the work computer has an package incompatibility somewhere, but I haven't tracked it down yet.   This frequently occurs when you install many apps/packages into the same python environment.  Virtual environments solve this, allowing you to keep the package dependencies separate.   The inconvenience they incur is the need to activate/deactivate (my second step above) before running the app.

I will close this issue as resolved, but feel free to reopen it as needed.
