### ISSUE TITLE
404 errors after PROD deployment

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1602]
Immediately after this weeks PROD promotion, I'm getting 404s on the `main` JS file.

```
GET https://cellxgene.cziscience.com/static/main-befc7f5a61095257409c.js net::ERR_ABORTED 404
```

The most likely scenario:
* during build & deploy, the main.js name changes (this week, it changed from `main-befc7f5a61095257409c.js` to `main-69e23efba67629af29a4.css`), and the HTML points to the new asset
* the cache header on all assets, _including_ the main HTML route, is set to a long TTL

So the browser still has the old HTML, pointing to the old (now deleted) main.js.  

This is confirmed by doing a hard refresh, forcing the browser to reload the HTML, which now points to the right main.js name.

Suggested fix: our HTML is small (~1KB) - we should not cache it.  Back-end cache headers on this route should change.

**Comment by mweiden** [comment]
@bkmartinjr I believe we've solved the issue with our patched deployment. Following up on plans for the next deploy in the ops channel.

**Comment by mweiden** [comment]
Fix for reference https://github.com/chanzuckerberg/cellxgene/pull/1603

**Comment by mweiden** [comment]
We're still seeing errors. I think that I've recovered the missing hashes. Will try to deploy again today.

**Comment by mweiden** [comment]
Deployed with the missing hashes. There are still a trickle of 404s, but we've done what we can here.
