### ISSUE TITLE
Design review of caching

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1612]
## Need

We need to perform a design review of the cellxgene's caching design for SaaS deployment.

### Context

The caching layers of cellxgene interact with two lifecycles:

1. Data roots - creating/updating/deleting datasets
1. The build/deploy/release process - creation and retiring static assets in the deployment artifact such as the `js` SPA, `css`, `html` templates

This system was built incrementally and, to date, has not had a comprehensive review.

## Definition of done

- [ ] Conduct a survey of the design, focusing on the two lifecycles above (including interactions with CDN)
- [ ] Add missing documentation if appropriate
- [ ] Gather any any recommendations for improvements and put them into new issues

**Comment by signechambers1** [comment]
Closing, not a priority right now
