### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1613]
## Need

When the single page application fails to load, users currently see a blank page. They then have no immediate steps to remediate the issue.

## Approach

cellxgene should fall back to an error page that tells users how to feed back issues to the development team and/or fix common issues on their own.

**Comment by mweiden** [comment]
@pdugan20 could you help us with the user flow and design for this?

**Comment by pdugan20** [comment]
Yeah! Will get started on a quick design and drop it in here.

**Comment by mweiden** [comment]
ty!

**Comment by pdugan20** [comment]
![01](https://user-images.githubusercontent.com/1837100/88073692-79ce4f80-cb44-11ea-8fda-90a92becd7e4.png)

What about something like this where we dynamically pass in the error code and give them the option to return home or contact us? Ignore the placeholder banner up top for now.

**Comment by signechambers1** [comment]
Closing as a low priority for 2021
