### ISSUE TITLE
Clients' browsers should cache the javascript SPA longer

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1614]
## Need

Extending the TTL on the JS SPA bundle would have the following advantages:

* Loading the page would go faster
* Fewer requests to the CDN / server
* Decreased likelihood of cached documents containing references to expired static assets resulting in 404s against the CDN

## Approach

Amend the cache control header as suggested by @tihuan:

```js
// (thuang): Cache static assets to avoid unnecessary requests from the client side.
// https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2
res.setHeader('Cache-Control', `public, max-age=${YEAR_MS}`)
```

**Comment by bmccandless** [comment]
Decided that 1 week is good enough.  closing the issue.
