### ISSUE TITLE
UI Request: Adding sections to histogram plots

### ISSUE THREAD

**Issue by andr-kun** [chanzuckerberg/cellxgene#1623]
Hi cellxgene devs,

I wanted to put in a suggestion to create sections for the histogram view on the right hand side of the cellxgene browser. I think it would be helpful to indicate if the histogram shown comes from the metadata, differential expression or user-selected genes. Moreover, it would be great if we can then show/hide different sections as the histogram plot list can end up being quite long if we have a lot of continuous metadata and/or user-selected genes (on top of the genes from differential expression analysis).

With regards to the implementation, I was thinking having tabs (with each tab corresponding to different section) would be great as it would allow for quick toggling between different sections. Alternatively, having collapsible sections (similar to the collapsible discrete annotation) should work as well.

Kind regards,
Andrian

**Comment by colinmegill** [comment]
Hi Andrian, thanks so much for the issue. We agree. The right hand sidebar will soon be a list of lists, where the top level is a named gene set and its contents are genes. Along with this, we'll probably move continuous fields which aren't genes back to the left hand sidebar, collapsed, under one heading 'continuous metadata'. 

You can take a look at issues like #1539 and other 'gene set' issues to follow along

**Comment by andr-kun** [comment]
Thanks for the update Colin! I'm looking forward for the features you mentioned to be implemented.

**Comment by signechambers1** [comment]
Closing this issue in favor of gene set functionality, now tracking here: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/64
