### ISSUE TITLE
embedding improvements

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1657]
Epic to capture work to finish embeddings after the recent state factor:

* improve UX around what dataset or subset of dataset is being displayed
* support viewing of embedinds which only contain subset of dataset
* re-implement re-embedding (generate embedding on a subset)

If PCA and UMAP, for instance, have equivalent cells, don't clear subsets. Only clear subsets if the cell sets are disjointed.

**Comment by colinmegill** [comment]
* If PCA and UMAP, for instance, have equivalent cells, don't clear subsets. Only clear subsets if it's disjointed.
