### ISSUE TITLE
Checkbox selection moves to wrong category

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1668]
Go to https://cellxgene.cziscience.com/d/cell_atlas_of_thymic_development-14.cxg/

Expand Anno_level_2
Expand Anno_level_3

Unselect "DP" in Anno_level_3

Instead of doing that, it unselects DP in Anno_level_2

This takes lots of forms, where it looks for a matching category label from the top rather than the one you're clicking.

**Comment by maniarathi** [comment]
@seve @colinmegill Are either of you the right person(s) here to take a look?

**Comment by bkmartinjr** [comment]
Believed fixed by redux refactor.  Confirmed in staging.
