### ISSUE TITLE
Hosted Annotations - [US0] When a dataset is added to cellxgene, a representative row is created in the relational db

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1684]
As a user I want to be able to link my annotations to a dataset

Done
- [x] Create relational db in aws
- [x] Create DB schema/orm
- [ ] Create function to add a dataset to the db
- [ ] test functionality (unit with local db and integration with elastic beanstalk)

**Comment by mckinsel** [comment]
Hey who's doing the adding in this scenario? Thinking about how this fits into the ingestion process.

Also, what's a representative row?

**Comment by MDunitz** [comment]
A representative row is just a row in the dataset table in the relationaldb. It has a uuid and a name (the full uri of the dataset)

I've been considering three options 
1. When creating an annotation check the pull the dataset path off the data adaptor and check if it exists in the db. If it doesnt exist create it. Not ideal from a performance perspective but we could probably cache it.
2. Run a daily cron job to check all the dataroots for any new datasets (Doesnt work if we add new dataroots)
3. Manually add it as a part of the ingestion process. 

I'm leaning towards option 1.

**Comment by bmccandless** [comment]
@mckinsel This issue only refers to user hosted annotations.  For ingest, the author's annotations are stored in the dataset as it is done now.

**Comment by Bento007** [comment]
It sounds like all you are doing is adding a row to the DB when a dataset is added to cellxgene. Can you add a definition of done to scope down the deliverable. I don't imagine this actually have any user facing consequences initially.

**Comment by tihuan** [comment]
DONE!
