### ISSUE TITLE
Hosted Annotations - [US1 & 2] Annotations are stored in TileDB

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1685]
## What
As a user I can create categories of annotations and I can create labels within categories.

### Creation
- Convert pandas dataframe of annotations that is autosaved by the front end to a tiledb array
- Store the array in s3
- Record the uri of the new array in the relational db along with the user's id and the dataset id

Update 8/19
- include deletion of all versions other than 10 latest (from db and s3)
- use a queue to ensure that there is no impact on performance for application users

**Comment by tihuan** [comment]
Questions:
1. Does this issue involve both FE and BE, or just FE or BE? 
2. I see we have "what" defined already (yay!) Can we have "how" in the issue description as well? I think that will help with estimation!

For example, when a user performs Create/Delete/Edit actions in the UI, does the FE hit their corresponding action's API endpoint for our DB persistence? Or how are we gonna persist the state from the user actions?

Thank you!

**Comment by MDunitz** [comment]
Auto save of annotations has already been setup, so this should just be a matter of implementing the backend routes. Because the files are immutable what looks like editing to the user will actually be creating a new set of annotations. 
We may want to add an option on the frontend/backend to delete all of the users annotations for a dataset but I think that is outside the scope of this ticket.

**Comment by tihuan** [comment]
SGTM! Thanks so much for the explanation 🎉 !

So this one is the CUD of CRUD, and the other is R 👍 Got it 😄 !

**Comment by tihuan** [comment]
Thanks so much for updating the description for this issue, Madison! This is so clear and easy to understand 🙏 This should be the role model issue 🤩👏🎉

**Comment by bmccandless** [comment]
@MDunitz aren't you storing the tiledb object names in the database.  Can't you use that as the data structure to use instead of a queue.    There may be many servers getting the obs put api request for the same user/dataset so you have to make sure whatever solution you use it doesn't depend on local state in the eb server.

**Comment by MDunitz** [comment]
Looked into the sqs limits. Message size is limited to 256kb or you can use the java extension which ups the limit to 2gb by storing it in s3. As an extremely rough estimate a 100k dataset with 5 categories w/ an avg label length of 12 chars would be 6 megabytes.
Discussed with @maniarathi, we decided to leave the save function as is and add deletion functionality via a queue. See [1690](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1690) for more details.
