### ISSUE TITLE
Hosted Annotations [US 5] Create routes to retrieve annotations from tiledb

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1686]
As a user I want to be able to retrieve/view the most recent version of annotations I have previously created

When retrieving annotations, the most recent set of annotations will be identified based on the timestamp.
To select the most recent annotation for a given user/dataset the query will look something like this
SELECT tiledb FROM annotations
WHERE user==user_id
AND dataset==dataset_id
ORDER BY timestamp ASC
LIMIT 1;

**Comment by tihuan** [comment]
Questions:

1. Does this involve both BE and FE?
2. How is FE going to retrieve the most recent annotation for the user? Is there an API endpoint to hit? Is the FE part gonna be done in this issue as well, or just the BE part of creating the API endpoint and querying TileDB?

Thank you!

**Comment by MDunitz** [comment]
As I understand the front end work is already done as the feature is available in the desktop version of cellxgene. There may be some updates to the configuration that are necessary to make it available in the hosted version but the logic to check for user annotations and merge with the dataset are already in place.

**Comment by tihuan** [comment]
Ahh got it! Thanks so much, @MDunitz ! So this is a pure BE ticket 👍

**Comment by Bento007** [comment]
Is the API for this route already define, or is that part of the work?

**Comment by MDunitz** [comment]
its already defined

**Comment by maniarathi** [comment]
This work has already been completed earlier and the paths are available for use. Given that there is no further work on this ticket to be done, closing.
