### ISSUE TITLE
Hosted Annotations - [US5] Automatically garbage collect old versions of annotations

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1690]
Asa user I want cellxgene to quickly retrieve the latest version of my annotations for a given dataset. To achieve this all but the 10 latest versions should be garbage collected from both the relational db and tiledb 

To delete from relationaldb
DELETE FROM annotations
WHERE user == user_id
AND dataset == dataset_id
AND id NOT IN ( 
SELECT id FROM ( 
SELECT id FROM annotations
WHERE user==user_id
AND dataset==dataset_id
ORDER BY timestamp DESC LIMIT 10)
);

Any tiledb annotation arrays not referenced in the relationaldb should be deleted

**Comment by MDunitz** [comment]
From discussion with team -- consider following path of local annotations, when writing a new annotation check how many exist, if greater than 10 delete oldest

**Comment by MDunitz** [comment]
From discussion with Bruce -- including network calls to get # of annotations and then delete them has potential to unnecessarily slow down route for arguably no feature gain.

Considering sending a message to sqs and then handling there?

**Comment by brianraymor** [comment]
@maniarathi - per August 16 Refinement - discuss "garbage collection" design with Bruce and Madison.

**Comment by MDunitz** [comment]
per my discussion with Bruce this should not be a part of the save function

**Comment by MDunitz** [comment]
Discussed with @maniarathi the save/write function will be updated to use a queue which will allow it to garbage collect and write to tiledb in a way that doesnt impact the performance of the app. See https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1685 for more details

**Comment by MDunitz** [comment]
Reopening after discussion with @maniarathi detailed on ticket [1685](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1685). 

## What
- Delete from s3 and relational db all but the 10 latest versions of an annotation for a user/dataset

## How
- when saving a new annotation send a deletion message to a queue with the user and dataset id
- the deletion event will trigger a function that queries the db for the number of annotations stored for the given user/dataset and will retrieve the annotation ids and the tiledb uris for all but the ten latest. It will then delete those from s3 via the uri and from the relational db via the annotation id.
- Events from the queue should be processed one at a time. Any parallelization in the future should be for different datasets or users to ensure there are never any consistency issues with a query and a deletion of the same user/dataset being processed at the same time.

## Why 
- This implementation should prevent consistency issues due to multiple overlapping deletion events 
- This implementation separates the slower deletion event from the faster creation event ensuring the user experience is not impacted by the slower event.

**Comment by bmccandless** [comment]
The implementation above makes it harder for anyone else to use the hosted tiledb annotations feature.  They would have to do quite a bit more infra setup.   The simple solution is just to do the delete within the save if the number of annotations is larger than a cutoff.   I'm concerned we doing premature optimization and designing in a lot of complexity.  

The save happens in the background,  there should be no impact to user experience.   Also, the cost of sending the annotations over the network is likely larger than the time it takes to process then in the server.

If we start with the simple solution, we could then at least measure if there is a performance issue.  Likely that implementation would be fairly trivial (~1 day).

**Comment by bmccandless** [comment]
Also, if s3 deletes did take too long, you could just run it in the background, something like this:

```
def remove_anno(uri):
   try: 
      tiledb.remove(uri)
   except TileDBError:
     # may have been simultaneously deleted by another server
     pass

uri = get_oldest_annotation(...) # if there are more than 10, remove the oldest one
t = threading.Thread(target=remove_anno, args=(uri,))
t.start()
```

**Comment by brianraymor** [comment]
Per September 1 Refinement, @maniarathi and @signechambers1 to close on a decision.

**Comment by maniarathi** [comment]
Removing from epic and closing. The cost of keeping all versions is very small in terms of storage costs and the solution is unclear as to whether to introduce new infra to handle deletion. We can revisit garbage collection later down the line as an optimization if there are potentially performance issues but this seems unlikely at least in the near future.
