### ISSUE TITLE
[BUG] cellxgene does not working when query parameters are passed in the URL

### ISSUE THREAD

**Issue by GeorgeSabu** [chanzuckerberg/cellxgene#1699]
**Describe the bug**
We have set up a docker in which the data set to be visualized is passed through the URL as a query parameter like 
http://localhost:8000/?dataset_id=xyz
And inside the docker, we translate the xzy to a downloadable dataset and pass it to cellxgene.
But when the query parameters are passed cellxgene throws an error.

**To Reproduce**
1. run locally cellxgene locally. Instead of going to http://localhost:5005 go to http://localhost:5005/?xyz=abc 
This will give an error and the API requests when I checked with --verbose flag looks like this 

 [cellxgene] Type CTRL-C at any time to exit.
 * Serving Flask app "server.app.app" (lazy loading)

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5007/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /?xyz=abc HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /static/fonts/RobotoCondensed-Regular.ttf HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /?xyz=abcapi/v0.2/config HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /?xyz=abcapi/v0.2/schema HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /favicon.png HTTP/1.1" 200 -

**Expected behavior**
The log should be somewhat like this

[cellxgene] Type CTRL-C at any time to exit.
 * Serving Flask app "server.app.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5007/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /?xyz=abc HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /static/fonts/RobotoCondensed-Regular.ttf HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /api/v0.2/config HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /api/v0.2/schema HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2020 02:02:15] "GET /favicon.png HTTP/1.1" 200 -

**How it got solved**
When I went through the code saw that if we make [this](https://github.com/ElucidataInc/cellxgene/commit/7a89beca88dbe24691d368acf21426024c14658e) change everything seems to work fine

Thanks for the great tool.

**Comment by maniarathi** [comment]
Hi @GeorgeSabu , thank you for the detailed bug report and fix! We are taking a look at putting in a PR to fix this and are taking a look at your recommended change. Thanks for the suggestion!
