### ISSUE TITLE
cellxgene.cziscience.com can't be read on mobile

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1704]
![image](https://user-images.githubusercontent.com/145417/89223305-67fc9b80-d58b-11ea-8993-f2f5ba4ccc49.png)

**Comment by maniarathi** [comment]
@signechambers1 Can we close this since we've switched over to the new portal?

**Comment by signechambers1** [comment]
Closing since mobile is a low priority
