### ISSUE TITLE
Invite users to host their own datasets in cellxgene cloud

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1715]
Currently, users who visit a hosted cellxgene dataset aren't aware of what their options are. This should be made more formal at a minimum by linking to a landing page re: available hosted features.

**Comment by signechambers1** [comment]
Closing in favor of broader design ticket https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1887
