### ISSUE TITLE
[BUG] Obsolete Browser HTML + JS is broken due to CSP

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1725]
**Describe the bug**
The inline scripts and improperly served images causes CSP issues and does not function correctly

What's been done:
1. @seve has created an HTML template for the obsolete browser notification and also set up FE code to detect obsoletely browsers

2. @thuang has manually created a new Cache Behavior for hosted-cellxgene-prod CloudFront to forward some images the template requires to the hosted-cellxgene-prod S3 bucket

What's left to be done:
1. @thuang is working on translating the manual AWS config into Terraform

**Additional context**
We need to self-host the browser icon images and add a hash for the obsolete browser inline script

**Comment by tihuan** [comment]
Working on the Terraform part now!

**Comment by seve** [comment]
closed by #1745
