### ISSUE TITLE
Sunset Heroku Click to Deploy 

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1727]
The team has decided to sunset our experimental "Click to Deploy" Heroku button in favor of maintaining our provided Dockerfile for self-host needs.  In order to carry this out without friction the following needs to occur:

- [x] Removal of Heroku related files
- [ ] Test Deployment to Heroku using Dockerfile
- [ ] Documentation to support Heroku deployment via Dockerfile
- [ ] Communicate sunsetting to existing users

**Comment by tihuan** [comment]
Should be done before this Friday
