### ISSUE TITLE
Gene sets design & implementation staging

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/cellxgene#1732]
**Appetite: 10**

**Requirements:**
- [x] Completed design that enables stories in chanzuckerberg/single-cell#15 (refine & update stories if needed)
- [x] First two implementation stages are outlined as sub-epics
- [ ] Reviewed and approved by product

Existing issues:
- chanzuckerberg/cellxgene#1538
- chanzuckerberg/cellxgene#1539
- chanzuckerberg/cellxgene#1540
- chanzuckerberg/cellxgene#1541

Design work: 
- [Google Drive Folder](https://drive.google.com/drive/u/0/folders/1pou50RQX5lq6FFiHv7httfdwpFIQuQZn)

**Comment by colinmegill** [comment]
Workspace use case

<img width="1536" alt="Screen Shot 2020-08-26 at 6 33 07 PM" src="https://user-images.githubusercontent.com/1770265/91363427-9bb59480-e7ca-11ea-9d07-fe621a708e2c.png">

**Comment by ambrosejcarr** [comment]
What does the "create new gene set" flow look like? 

I think you mentioned before that the + and ... might be hidden until mouseover -- I think I prefer that; this looks a bit busy relative to the left sidebar.

**Comment by ambrosejcarr** [comment]
Comment from Jonah: 

> My curiosity is about how/if we can precompute some standard gene sets (whether they be cells or pathways) that can be quickly referenced or imported. For example, many people want to see where myc signaling is active or Wnt ligands target genes etc. Heard him say that sharing is a future feature and this admittedly falls in the intermediate area.

**Comment by signechambers1** [comment]
Great demo during sprint review @colinmegill! A few questions for you or @ambrosejcarr:

1. If a user wants to add a single gene (eg the current workflow in the right sidebar), is the expected workflow now to create a gene set with one gene in it?

2. You mentioned a user can reorder genes within a gene set, can the user reorder the genesets? This might be more of a heatmap use case (thinking back to our convo with the Krasnow lab yesterday) and something we would tackle then.

3. If we expect ~100 lists of ~100 genes each, I think a search function for genesets and genes would be helpful, what do you think?

4. Downloading a gene set seems like a less common use case but I could imagine it (ie sharing a geneset with collaborators, importing into other tools, etc.). Has this come up in discussions at all?

**Comment by ambrosejcarr** [comment]
Great questions @signechambers1. For this one: 

> 4. Downloading a gene set seems like a less common use case but I could imagine it (ie sharing a geneset with collaborators, importing into other tools, etc.). Has this come up in discussions at all?

Your intuition is good. The explanation for why it's missing is procedural. I only requested Colin mock up the first two use cases so we don't get too far ahead of the implementation team. If you check the second comment in this issue, Import & export are the third, followed by linking to differential expression, and finally on-platform sharing.

**Comment by ambrosejcarr** [comment]
@colinmegill I believe this issue closes #1538, #1539, #1541, #571, and #852. Do you agree?

I think #923 relates to both the question Signe and I asked about what happens to "add genes" and how does a user creates a new gene set, and can be closed when those questions are answered. 

How do you propose to address multi-brushing of gene sets (#1584)? Track which genes have been brushed and disable re-brushing with some kind of visual cue to let the user know? I think the publication use case will need to address this issue. 

Do you intend for users to be able to re-order genes within gene sets, and gene sets in the workspace use case in one of these use cases or reserve it for later? Where should I put that requirement?  When that requirement is accounted for, I believe #1069 can be closed.

**Comment by colinmegill** [comment]
@signechambers1 great questions! 

1. Yes, that's correct. All genes have to be in a gene set to make the sidebar skim-able and collapse-able. Feedback from users was that we should optimize for many large sets, which does slightly de-optimize for 'quick look', though it's not much slower.

2. Hadn't considered re-ordering genesets! I assume that'd be useful. I expect users will want to break them into sections and give them headings, as well. In the case of Tabula Muris and the mocks above: 

<img width="362" alt="Screen Shot 2020-08-31 at 11 13 31 AM" src="https://user-images.githubusercontent.com/1770265/91735974-0a07a780-eb7b-11ea-9171-eba56cd0ea57.png">

It would mean a heading and sets something like: 

**Fat**
immune_nk
immune_b
mesenchymal_progenitor

**Heat and Aorta**
...

3. 
* I think of this less as search than as filter, but yes, I agree. 
* I think this is a later convenience feature (alphabetical sort lets the brain filter quickly). 
* This probably is a fuzzy search on set name and membership 
  * (ie., I can type `atrpd` and get sets with `Aorta` or `APOD`) that would reduce the gene sets that are visible — for an example, see Spotify's search within playlist, though their filter is not as forgiving to errors as I'd like for this given how complicated the names are. 
* Would probably be an ever-present, though thin, search bar below the `Create new gene set` button but above the first set, Spotify also a nice model for that

4. Yes, scientists want both ingress and egress via csv drop in and see set / csv download.

**Comment by colinmegill** [comment]
A note: I don't think the data structure should encode the display, so I would still propose we persist gene sets as lists of lists even if we have a heading. The client side could sort them by heading or alphabetically by looking at a `heading` attribute on the geneset, but I would rather that attribute exist on the geneset.

**Comment by colinmegill** [comment]
@ambrosejcarr re: what issues are closed, yes, all of those, except #1541 and #1584, which will need to be addressed separately.

**Comment by colinmegill** [comment]
Creating a gene set:

<img width="837" alt="Screen Shot 2020-08-31 at 1 03 30 PM" src="https://user-images.githubusercontent.com/1770265/91746316-6920e880-eb8a-11ea-980f-aef305cceb76.png">

Adding a gene will also occur in a modal, triggered by the plus button on a gene set: 

<img width="370" alt="Screen Shot 2020-08-31 at 5 05 42 PM" src="https://user-images.githubusercontent.com/1770265/91768837-3daef580-ebac-11ea-9ae8-db8d5838dd21.png">

It will need to encompass adding genes singularly and in bulk, and nice error handling when adding 100's of genes with multiple types of errors.

**Comment by colinmegill** [comment]
Figma: https://www.figma.com/file/mvGRRSx0fcgBKkLAm3cMJk/Gene-Sets-v0.1?node-id=0%3A1

**Comment by signechambers1** [comment]
Closing out design portion from Sprint 1, Colin has linked final figma design above.

Decisions made:
The following features that are out of scope for initial staging:
1. Search/filter functionality for genes and gene sets (Spotify search bar is an example)
2. Re-ordering gene set
3. Providing way for a user to enter info and view info about why a gene is included in a gene set

Open product questions to answer in a future sprint:
1. Do we calculate the expression rate of a gene set based on average count (original idea) or provide other options? (Valentine Svensson example - he could include his own distribution as part of the dataset)
2. How are we persisting gene sets? (completely in browser, as part of a cookie, or requires login)
3. What is the workflow for uploading gene sets in bulk in hosted cellxgene?
