### ISSUE TITLE
Hosted Annotations - Update and Delete Categories and Labels

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1736]
## Need
As a user I can edit and delete annotations I have previously created 

### Editing
- Check relational db for an annotation for the user/dataset
- If exists retrieve, merge with dataset and return to the frontend
- User updates will be sent to the backend and stored 

### Delete
- will act as an edit making an empty category or label

**Comment by maniarathi** [comment]
This work is no longer relevant since update and deletion of categories are already handled by the automatic saving of new annotations every three second (i.e. they extensions of the creation of an annotation which is already implemented).
