### ISSUE TITLE
Hosted Annotations - Performance testing

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1738]
## Need
As a user I want to be able to create and edit annotations of datasets with minimal latency

### Repeatedly save/edit sets of annotations with 10+ categories and record time
- check the backend performance of a small dataset (10k cells)
- check the backend performance of a medium dataset (100k)
- check the backend performance of a large dataset (1 million cells)

## Questions
- do we have any established benchmarks?

**Comment by mckinsel** [comment]
Just throwing out some ideas:
- might depend on number of categories, number of annotations
- for sizes, we have a 3k, 40k, 600k, and 4000k, which should be a reasonable spread
- would be nice to see what happens in higher latency scenarios, PUTs never complete in the interval time, stuff like that

**Comment by MDunitz** [comment]
Notes from discussion with Bruce
- saving/writing new annotations 
- read back the schema route
- read back a single column (annotation_obs_get) --- merging user and dataset annotations

Paramaters
- number of cells
- number of annotations (columns) and types -- should be all strings
- number of unique strings per category 

Benchmark all 3 routes
- 10k
-100k
- 1 million cells

1, 10 and 100 annotations
sane set of enumerated values/category (going to be network bandwidth limited) random string generator should be avg 10-20 chars

Caching
- writing a new one every time -> cache is irrelevant need to ensure benchmark is always creating a new one

**Comment by brianraymor** [comment]
@maniarathi - per August 16 Refinement - synchronize with Bruce and Madison to understand whether earlier prototypes have de-risked performance concerns. Otherwise, smaller prototypes may need to be created to validate.

**Comment by ambrosejcarr** [comment]
Performance thresholds and guidelines: Per operation (create, category, add label, ... etc), 1000ms upper bound, 100ms desired.

**Comment by brianraymor** [comment]
Arathi responded in meeting notes: _I vetted the design and can confirm that the architecture will not likely cause performance issues. The frontend does not ping the server to access the latest annotations. The backend is only hit to create and store the tiledb array in S3 so the primary component hit repeatedly is S3 which will be fine under heavy load._

**Comment by MDunitz** [comment]
From discussion with @ambrosejcarr 
- For a dataset with 4 million cells we would expect to have a max of 10,000 unique labels (200 labels per tissue with 50 tissues in an atlas)
- max 200 unique labels for a 100k cell dataset
- max 50 unique labels for a 10k cell dataset

**Comment by MDunitz** [comment]
Update on limits found so far
-  a 4 million cell dataset with 100 categories hits the flatbuffer limit (2GB) when trying to create the annotations data object
`flatbuffers.builder.BuilderSizeError: flatbuffers: cannot grow buffer beyond 2 gigabytes`

- a 10k cell dataset with 100 categories returns a 504 gateway timeout when trying to send a put request to `/api/v0.2/annotations/obs` but it will work with 85 categories with up to 200 unique labels/category

-80k and 140k datasets are successful with 1 & 10 categories but fail at 100 categories (more testing is needed to find actual failure point) with up to 200 unique labels/category

**Comment by bmccandless** [comment]
Thanks @MDunitz 

There are a few ideas for fixes.  (I think these came up with our discussion with Bruce on performance).

The client sends a flat buffer that contains a label for every category for every cell.
So, the size if proportional to the number of categories * number of cells * average label length:

possible solutions:
1. We can make a list of label names, then just send the list and index of the label for each cell/category instead of the label name.    We can most likely get that to ~2 bytes per entry (65536 labels).
2. Send updates for only the categories that have changed.  The most likely scenario is that only one category changed at a time.   Potentially further reduce space by only sending the cells that changed.
3. See if compressing the flatbuffer helps

**Comment by MDunitz** [comment]
Thanks! I'm looking into a couple different compression algos. I was thinking we could also make a dict of the labels and a shortened version of the label (1-2 chars depending on total # of labels) and then replace the labels with the shortened version. I'm testing with labels of 10-20 chars so that could add a substantial saving as well.

**Comment by signechambers1** [comment]
@MDunitz would you mind clarifying for your testing on the 600K dataset (Human Cell Landscape) if it succeeds with 1 and 10 categories with 200 labels in each category?

Second question, will we be able to track if a user hits these errors? (will sentry help here?)

**Comment by MDunitz** [comment]
@signechambers1 The Human cell landscape succeeds with 1&10 categories with 200 unique labels in each category

**Comment by MDunitz** [comment]
Notes from meeting with Bruce about performance updates:
limits are not unexpected, the architecture was originally designed to run locally with minimal bandwidth concerns. We  have a few different options to improve, can stack options
- Use gzip or other compression software to compress data (2-5x compression)
   -  there may not be a a performant javascript option
   - Bruce currently working on some Web Assembly code to do this quickly in the browser
- Application specific compression (update the fbs to encode label names)
  - currently matrix_fbs flattens categorical info into a flat array of strings, this could be improved. 
  - this would potentially improve the latency in other parts of the app
- Incremental updates
   - Instead of sending all the annotations on every save, send a category at time when updated (can eventually send just the updated cells)
   - This will require significant refactoring on the backend (and frontend?)
   - This will be a huge performance boost, it will remove all limitations on number of categories. Latency will be determined solely by the number of cells in the dataset
   - Some concern about keeping state in sync, how to ensure updates are received in order, how to handle dropped updates or mismatched state
@signechambers1 happy to chat about this more!

**Comment by signechambers1** [comment]
@MDunitz thank you! based on your testing, I do not think that these performance issues block our initial release of annotations since smaller datasets and fewer annotations are supported, we can track the 504 errors if the happen, and we don't have a full understanding of the annotations use case on a public dataset.

For private datasets/collections, we will want to consider the performance updates you suggested / the warning you considered in 1906. I'll set up some time with you @MDunitz to discuss!
