### ISSUE TITLE
Swapped x and y gene labels in scatterplot [BUG]

### ISSUE THREAD

**Issue by andr-kun** [chanzuckerberg/cellxgene#1749]
**Describe the bug**
The x and y gene labels in scatterplot of gene expression are swapped around so that the name of the gene selected for plotting in the x and y axis are instead shown in the y and x axis, respectively.

**To Reproduce**
1. Add at least 2 genes in the right sidebar.
2. Select 1 gene to plot in x axis and another gene to plot in y axis.
3. See swapped label in scatterplot.

**Expected behavior**
The gene label for the x axis should be correctly placed in the x axis and similarly for the y axis.

**Screenshots**
![Screenshot_2020-08-14 cellxgene(1)](https://user-images.githubusercontent.com/5274310/90250306-c3ecdd00-de33-11ea-86ae-929e3c37d2fa.png)

**Version (please complete the following information):**
 - Desktop or hosted?: desktop and hosted
 - Browser (if hosted) [e.g. chrome, safari]: firefox and chrome
 - Version [e.g. 0.13.0]: 0.16.0

**Additional context**
N/A

**Comment by maniarathi** [comment]
Thank you so much for the bug report. We are looking into this now!

**Comment by colinmegill** [comment]
Reproduced, thanks @andr-kun
