### ISSUE TITLE
OSError: [Errno 101] Network is unreachable, or Error:

### ISSUE THREAD

**Issue by selifeski** [chanzuckerberg/cellxgene#1750]
Dear,

Maybe it is not the correct place to ask. I am a new linux user, so please refer me if this issue is not related to cellxgene.

I followed the quick tutorials. However I cannot launch demo datasets. In one try it gives this error:

`cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad`

> [cellxgene] Starting the CLI...
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host cellxgene-example-data.czi.technology:443 ssl:default [Network is unreachable]

In another try with differen URL it gives this error: (nothing, just blank)

`cellxgene launch https://github.com/chanzuckerberg/cellxgene/blob/main/example-dataset/pbmc3k.h5ad`

> [cellxgene] Starting the CLI...
> [cellxgene] Loading data from pbmc3k.h5ad.
> Error: 

I also install aoihttp, but did not helped. I have Google Chrome (not sure if it would be the source of problem) What should I do in this situation?

**Comment by maniarathi** [comment]
Hi @selifeski, thank you for the report. Could you please run `curl -X GET https://cellxgene-example-data.czi.technology/pbmc3k.h5ad --output pbmb3k.h5ad` in the same terminal and see if it downloads the dataset? I'm trying to see whether it might be a network error on your end, or something cellxgene related.

**Comment by prete** [comment]
Hi @selifeski and @maniarathi 
I think the error is that the URLs should use raw.githubusercontent.com instead of just GitHub links. Try this:
`cellxgene launch https://raw.githubusercontent.com/chanzuckerberg/cellxgene/main/example-dataset/pbmc3k.h5ad`

**Comment by selifeski** [comment]
Hi @maniarathi, 
now it gave this error (by the way I have updated cellxgene to 0.16.2):

`curl -X GET https://cellxgene-example-data.czi.technology/pbmc3k.h5ad --output pbmb3k.h5ad`

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to cellxgene-example-data.czi.technology:443

**Comment by selifeski** [comment]
Hi @prete,

It worked this way! Thanks!

**Comment by selifeski** [comment]
> Hi @maniarathi,
> now it gave this error (by the way I have updated cellxgene to 0.16.2):
> 
> `curl -X GET https://cellxgene-example-data.czi.technology/pbmc3k.h5ad --output pbmb3k.h5ad`
> 
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> > curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to cellxgene-example-data.czi.technology:443
