### ISSUE TITLE
Smoke tests for AuthN with mocked BE

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1764]
What:
We need to write cellxgene E2E smoke tests for the whole AuthN flow in loca, dev, staging, and prod env. This ticket is now split into two tickets:

1. Assert AuthN features with mocked BE
2. AuthN integration tests for single-cell-infra as deployment Github Action checks

How:
1. Set up cellxgene FE smoke test to run on `https`
2. Assert AuthN related features work (e.g., when logged in, see log out button. When logged out, see sign up/log in buttons)

**Comment by tihuan** [comment]
Ah yes, Colin and Arathi asked me to help fill out the details, so I'll do that now! Thank you!

**Comment by tihuan** [comment]
Updated description! PTAL @colinmegill @maniarathi @seve @bmccandless if you think this is enough to cover cellxgene AuthN flows 🙏 Thank you!

**Comment by tihuan** [comment]
cellxgene repo will only have UI smoke test that mocks BE authN reponse: 3

Integration: Optional test in cellxgene repo, but only turn on in single-cell-infra GH Action deployment flow: 4

**Comment by brianraymor** [comment]
Per September 1 Refinement - @tihuan will be responsible for estimating and decompose into separate issues.

**Comment by tihuan** [comment]
@brianraymor Tickets created and estimated!

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1807
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1764

Thank you 🙏

**Comment by seve** [comment]
After discussions with @maniarathi + @signechambers1, decided to drop this ticket out of the sprint as it is blocked by some future UI tweaks in #1830
