### ISSUE TITLE
[BUG] Dockerfile fails to build

### ISSUE THREAD

**Issue by prete** [chanzuckerberg/cellxgene#1776]
**Describe the bug**
Current Dockerfile fails to build for cellxgene version 0.16.0. Main error involves llvlmlite installation. 

**To Reproduce**
1. `git clone https://github.com/chanzuckerberg/cellxgene.git`
2. `cd cellxgene`
3. `docker build -t cxg .`
```python
 Failed building wheel for llvmlite
    Traceback (most recent call last):
      File "/tmp/pip-build-oaerx6ns/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-oaerx6ns/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-oaerx6ns/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
```

**Expected behavior**
Dockerfile should build without errors.

**Version (please complete the following information):**
 - Desktop
 - cellxgene Version 0.16.0

**Additional information**
Update llvm to 10 fixes the issue. I worked around that by adding llvm-10 to apt-get install packages list and then export LLVM_CONFIG=/usr/bin/llvm-config-10 before installing cellxgene using pip3. Not sure that's the best way to solve it. 
Instead of going that way I believe it's cleaner if the base image is upgraded to Ubuntu Focal which also solves the issue as proposed on PR #1775

**Comment by LustigePerson** [comment]
My docker build workes on Friday and the same Dockerfile failed with your error today. So it seems like some dependency changed.

**Comment by prete** [comment]
llvmlite is a dependency of numba and numba version 0.51.0 got released on Friday [1](https://pypi.org/project/numba/#history), perhaps that's where the issue comes from ?

**Comment by jenzopr** [comment]
Confirmed. My build from today did also fail with the exact same error.

**Comment by maniarathi** [comment]
Thank you so much for the bug report and the accompanying PR! We are taking a look now.
