### ISSUE TITLE
[Integration][E2E] Authentication in the deployment

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1778]
A few minor issues have already come up with authentication working on the dev deployment, and other issues
may arise.  This is a placeholder for work that might need to be done to get authentication working end to end on
the dev deployment.

**Comment by mweiden** [comment]
@bmccandless seems like this should incorporated in our estimates as part of the standard ~20-30% estimate buffer, no? Can we close this or am I missing a critical bit of info here?

**Comment by bmccandless** [comment]
It doesn't really matter to me how the work is split into tickets.   I can reopen one of the other tickets, maybe #1519.   Or I can treat anything that comes up as a bug.   I created this ticket just to capture troubleshooting work that I know will need to be done, so we can plan for it next sprint.

**Comment by tihuan** [comment]
Thanks for the bug ticket, @bmccandless !

It seems to me that there are two components to this ticket:

1. There are already minor bugs discovered
2. Likely there will be some more bugs we will discover in Sprint

I think for easier estimation, maybe we can dedicate this bug ticket to Item 1, and we'll create a another AuthN bug ticket for Item 2 if they do arise?

If that sounds good, then we just need Brian's help to add more details about the minor bugs, so it's easier for the Team to estimate the scale/complexity of the bugs

What do you both think? Thank you!

**Comment by tihuan** [comment]
Adding #502 (api.cellxgene.cziscience.com) as a blocker, since I remember that's what we said in the Sprint Planning lol But if it's not, please feel free to take that out! Thank you!

@bmccandless

**Comment by lesliecodes** [comment]
deploy away!
