### ISSUE TITLE
[BUG] FE attempts to access userinfo when authentication is disabled.

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1780]
Run cellxgene with authentication_enabled: false
And user_annotations/enabled : false
The FE will get an error and lot load the page:

Here is the error message
```
controls.js:30 TypeError: Cannot read property 'userinfo' of null
    at index.js:46
    at async Promise.all (:5005/index 3)
```

When authentication is not enabled, the config endpoint does not return an authentication section.

**Comment by seve** [comment]
The userinfo endpoint is always fetched on initial data load:

```javascript
const doInitialDataLoad = () =>
  catchErrorsWrap(async (dispatch) => {
    dispatch({ type: "initial data load start" });

    try {
      const [config, schema] = await Promise.all([
        configFetch(dispatch),
        schemaFetch(dispatch),
        userColorsFetchAndLoad(dispatch),
        userInfoFetch(dispatch),
      ]);
...
```

**Comment by bmccandless** [comment]
> The userinfo endpoint is always fetched on initial data load:

Thanks @seve.  So some options:

1.  either the FE needs to handle the case when the userinfo endpoint return null (when the server is configured to have authentication disabled)
2. or,  the FE needs to wait for the config endpoint to complete, and check if an authentication is enabled before before fetching the userinfo.

**Comment by bmccandless** [comment]
Once this issue is complete, then the dev deployment config file needs to be updated.
authentication type -> oauth
default dataset config:  authentication -> disable
