### ISSUE TITLE
[BUG] Some Ident colors in key don't match data

### ISSUE THREAD

**Issue by GHAStVHenry** [chanzuckerberg/cellxgene#1784]
**Describe the bug**
Some Ident colors in key don't always match the color on data. For some Ident groups, all the cluster colors match... and for some, only some of the clusters are wrong.

**To Reproduce**
1. Load
2. look at different ident groups

**Expected behavior**
Key color to match color on data

**Screenshots**
Here you see Cluster 4 of Ident group Integrated_snn_res.0.4 is orange in the key but green on the plot
![image](https://user-images.githubusercontent.com/38675268/90669969-18b79b80-e218-11ea-8f9b-e2d9674c71f3.png)

**Version (please complete the following information):**
 - Desktop or hosted?: hosted (cellxgene-gateway)
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: 0.16.2

**Additional context**

**Comment by maniarathi** [comment]
Thank you @GHAStVHenry ! We're taking a look!

**Comment by GHAStVHenry** [comment]
@maniarathi accessible example for you:
https://cellxgene.cziscience.com/d/dd811609-3d83-4bdb-801f-d6c6c93d1a9e.cxg/
tested on:
* PC Chrome: mismatched colors
* iPad Chrome: correct colors
* Android Chrome: correct colors

I don't know what is wrong with my local laptop that is causing an inconsistency with the rendering colors.
