### ISSUE TITLE
Do not prompt for collection name on hosted cellxgene

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1785]
From @MDunitz:

We dont want to prompt for a collection name in the hosted version as it will give users the impression that we are storing their annotations under that collection name (and that they can have multiple collections for one dataset) which is incorrect.

Discussed with @colinmegill and it should be fairly simple to set it t o default or remove it completely in the hosted version

**Comment by brianraymor** [comment]
@seve - was this issue approved for the Sprint Backlog by @maniarathi ? The Sprint is limited to issues in the Sprint Backlog.

**Comment by tihuan** [comment]
Quick update: Sorted out with BrianR and Arathi, this ticket is now officially in the Sprint!

**Comment by seve** [comment]
I should have connected this from the source issue, sorry! #1193

**Comment by maniarathi** [comment]
Is this complete now that the PR is merged in?

**Comment by MDunitz** [comment]
yes
