### ISSUE TITLE
[Refactor] Split AppConfig into 4 separate config classes

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1790]
As a first step to refactoring the config, `app_config.py` will be split into 4 classes `AppConfig`, `BaseConfig`, `ServerConfig`, and `DatasetConfig`. Unit tests will be written for each class to especially cover any complexity in the config such as dependencies or type checks that depend on config values.

--- Previous ticket explanation ---
The app_config file is approaching 1000 lines of code. It contains the default config, configuration relating to the server a default dataset config and dataset specific configuration as well as logic around the client config and its  parameters with limited documentation. Variables can be passed in via the cli, passed in via a config file or pulled from the secrets manage. AppConfig also contains methods related it initialization, type checking, modification and config access. There are a few "gotchas" related to the dataset aspects of the config which can be overridden based on the url the dataset was accessed by. As we add more features (annotations, auth) it becomes more comlex/difficult to follow. I think we should break the config up and better document all aspects of it.

**Comment by brianraymor** [comment]
Per September 1 Refinement - this requires a definition of done. Arathi to refine this issue.

**Comment by lesliecodes** [comment]
@MDunitz is this ready for prod deploy?

**Comment by MDunitz** [comment]
yes
