### ISSUE TITLE
Add more testing to the re-embedding feature

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1794]
re-embeddings only have one simple test.  
Other things to test:
  matrix will small number of columns (<50)
  different filter options
  matrices with Nans?

**Comment by bmccandless** [comment]
We've discussed writing a utility to generate test matrices.  There is one I wrote for diffexp, and I think @maniarathi has one she's started.  If this utility to generate test datasets were fully featured, then it would aid in writing tests like this.

**Comment by signechambers1** [comment]
Closing as low priority for 2021
