### ISSUE TITLE
categorical group check boxes state

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#18]
The group check-boxes for categorical metadata don't quite work right and can show conflicting states:

Pick any category group, eg.,  EM2Cluster:
1. test 1 - deselect the group, and then select a few of the options --> the group-level checkbox is unselected
2. test 2 - select the group, then deselect a few options --> the group-level checkbox is selected

this is confusing -- the group level checkbox can be in either state when some options are selected.   If it is only present to provide group-level actions, perhaps it should be replaced by separate [all] and [clear] actions?

**Comment by colinmegill** [comment]
@freeman-lab I think previously we had select all and select none in words, is that correct? This was a UX you'd proposed in its place? Just wanted to revisit in light of this issue, it's trivial to change if we want to.

**Comment by colinmegill** [comment]
Gmail:

![screencaptureproject8](https://user-images.githubusercontent.com/1770265/41067143-7a30e424-69b2-11e8-81a1-b5532b531b93.gif)
