### ISSUE TITLE
[BUG] reembeddings get a server error if scanpy is not installed

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1811]
**Describe the bug**
If scanpy is not installed, and the server is run with reembeddings, cellxgene fails with a server error when the reembeddings feature is exercised. 

Instead, if reembeddings is enabled, we should check on startup if scanpy is installed, and exit early with a clear message if it is not.

**Comment by maniarathi** [comment]
@bmccandless Thanks for adding this. Mind adding the estimate as well? Helps us guestimate our weekly bug expenditures :)

**Comment by bmccandless** [comment]
> @bmccandless Thanks for adding this. Mind adding the estimate as well? Helps us guestimate our weekly bug expenditures :)

I estimated it as 1, because it did not let me put 0.02.  :)
