### ISSUE TITLE
Docker container hangs for some h5ad files

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1817]
Steps to reproduce 

create docker image from 0.16.4
docker build . cellxgene:0.16.4
run docker
docker run --name dunitz-test7 -v "$(pwd)/datadir":/datadir -v $ANNOTSDIR -p 37004:37004 cellxgene:0.16.4 launch --open --verbose --host 0.0.0.0 --port 37004 --title MYTITLE --annotations-dir annots datadir/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad

test w/ .cxg and .h5ad
cellxgene will hang for krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad but it works fine for krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.cxg

It works fine for tabula_muris_skin.h5ad and cxg
It is unclear if this is an issue with the particular dataset or an issue with dataset size or something else.

**Comment by bmccandless** [comment]
Hi @MDunitz.

With h5ad, it needs to read in the entire file before starting.   For cxg, it just opens the arrays, basically, then starts.  Do you know how long you waited for the h5ad?   Possibly if you wait long enough it will succeed, assuming it fits in memory.
How long does the h5ad file take to start running normally, outside of docker?
I don't think docker has any limits on cpu or memory by default.

**Comment by MDunitz** [comment]
@bmccandless 
I let it run for ~10 minutes. It hangs for a while and then just exits
```(venv) mdunitz@czirwc1macos2835 single-cell-infra % docker run --name dunitz-test12 -v "$(pwd)/datadir":/datadir -v $ANNOTSDIR -p 37004:37004 cellxgene:0.16.4 launch --open --verbose  --host 0.0.0.0 --port 37004 --title MYTITLE --annotations-dir annots datadir/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad 
[cellxgene] Starting the CLI...
[cellxgene] Loading data from krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad, this may take a while...
(venv) mdunitz@czirwc1macos2835 single-cell-infra % 
```
Outside of docker (with the same h5ad dataset) takes about 15 seconds to launch

**Comment by signechambers1** [comment]
Closing since @bmccandless is working on dockerizing cellxgene in this sprint
