### ISSUE TITLE
Create Dataportal/Cellxgene sandboxes for testing

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1823]
## Need
- to give developers more environments to test changes in (without needing to worry about dev instability or stepping on each others toes)

## Approach
- Create 2 sandboxes including
 - [ ] data portal infra
 - [ ] cellxgene infra
 - [ ] deploy dp
 - [ ] deploy cellxgene
 - [ ] point to dev s3 bucket (or create new one with copies of datasets)
 - [ ] copy subset of prod data to new db
 - [ ] sandbox sign up in devops channel?
 
## Question 
- how to ensure env is in healthy state for testing? auto deploy from prod daily? expectation that dev resets it when done?

**Comment by ambrosejcarr** [comment]
@MDunitz [cellxgene-gateway](https://github.com/Novartis/cellxgene-gateway) application enables multi-dataset hosted cellxgene. If we complete our roadmap, we will enable a superset of the features of this application. 

How much would it increase the scope of this ticket to centralize the documentation of how we deploy? It would fine to note where we use central CZI infra to do things. It'd still be helpful as a reference for what would need to be investigated/explained if we wanted to enable an external group to stand up their own version of our hosted system.

**Comment by MDunitz** [comment]
I think we would need to open source our terraform (the single-cell-infra repo) in order for it to be useful at all. Otherwise for deployment instructions it would just be to add the new environment to the fogg.yml and run make fogg and then run make apply

**Comment by ambrosejcarr** [comment]
Thanks, that's helpful context! Dropping a note here for myself that I'd like to learn more about how this works when this ticket gets prioritized.

**Comment by MDunitz** [comment]
It might be easiest to learn if you ride along for a deployment with infra changes. I can zoom with you the next time I deploy if that would be helpful.

**Comment by ambrosejcarr** [comment]
That would be great. Thanks.

**Comment by MDunitz** [comment]
The happy path work by the infra team should provide most/all of what we need -> Closing
