### ISSUE TITLE
Improve loading speed of dataset properties drawer

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1824]
Currently the dataset properties drawer waits for all categories to load before it can display anything. This is because it wants to show categories that only have a single value, and it doesn't want to show partial information.

If we want to speed that up, we could include the singleton categories in `/config` and populate that during `cellxgene convert`

**Comment by maniarathi** [comment]
I believe we fixed the dataset properties drawer speed already (it is pretty speedy now). Closing this.
