### ISSUE TITLE
Enable users to authenticate in Prod environment

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/cellxgene#1828]
## Need

We need to complete the trust review until rolling out authentication in prod.

**Comment by signechambers1** [comment]
Blocked on trust review, will update when this is no longer blocked

**Comment by bmccandless** [comment]
The remaining work for this is covered in other tickets:
Basically, configuration changes for data portal, cellxgene, aws, auth0, and google.  

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1851
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-infra/178

**Comment by bmccandless** [comment]
List of work to do:

custom domain (login.cellgene.cziscience.com)
- [ ] Terraform the route53 record domain:  login.cellgene.cziscience.com -> corpora-prod.auth0.com
- [ ] Google Cloud Platform:  cellxgene project / Credentials:  Update the URIs to use the custom domain
- [ ] Auth0 setup the Custom Domain in the corpora-prod
- [ ] update the data portal config (secret) api_base_url to use the login.cellxgene.cziscience.com
- [ ] update the cellxgene data portal config for oauth_api_base_url to use login.cellxgene.cziscience.com

add / apply terraform for the api routes
- [ ] the api routes: api.corpora.cziscience.com/[cellxgene|dp]
- [ ] the annotations database
- [ ]

make sure all the secrets have the correct configuration
- [ ]   hosted-cellxgene-prod
- [ ]   corpora/backend/prod/auth0-secret

make sure the cellxgene configuration is correct in single-cell-infra
- [ ]  annotations, authentication, api_base_url / web_base_url

**Comment by brianraymor** [comment]
@bmccandless - can this be closed based on your [comment](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1828#issuecomment-696420207) _remaining work for this is covered in other tickets_? Definitely felt like there was a duplicate between this and #178.

Matt Weiden and I requested that @sbeara review Auth* in staging today, since we're preparing to deploy.

**Comment by bmccandless** [comment]
Yes, we can lose this one.
