### ISSUE TITLE
UI auth tweaks for authentication workflow

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1830]
A few changes to make for auth launch with annotations that Colin and I discussed to free up space in main window and keep all info and account management in the left upper corner:

- [x] Remove door icon from log in button
- [x] Move log in and info buttons from the top bar to in line with the cellxgene icon and dataset name
- [x] Hover over on login button should say "Log in to cellxgene"
- [x] Once a user logs in, "log in" button should be removed. Instead the drop down from the info button should say "Logged in as {email_address}" and show a "log out" option.

Ping @colinmegill for any design questions.

**Comment by lesliecodes** [comment]
er bad bot! This shouldn't be closed yet. Moving back...

**Comment by signechambers1** [comment]
This passes my QA on dev
