### ISSUE TITLE
reorganize the cellxgene API

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1837]
The current cellxgene API endpoints locations have some history.  Some reorganization may now be in order.

1.  originally it was 
webpage: <server>/
api: <server>/api/v0.2/...

2. then when multi datasets came along, the API became this, which had the advantage that it did not require
any frontend changes to introduce.
webpage:  <server>/<dataroot>/<datasetname>
api:  <server>/<dataroot>/<datasetname>/api/v0.2/...

3. Now that we have the ability separate the backend (api server), and frontend (SPA application), it looks like this:
webpage:  <web_base_url>/<dataroot>/<datasetname>
api:  <api_bas_url>/cellxgene/<dataroot>/<datasetname>/api/v0.2/...

It now may be time to reorganize this:

For example:

webpage (no change):   <web_base_url>/<dataroot>/<datasetname>. (no
api:  <api_base_url>/cellxgene/v0.2/....?dataroot=<dataroot>&dataset=<datasetname>

If we make that change then we should also bump the version number from v0.2.
This can lead to more flexibility in the future, as different arguments can be easily added to the api uri, such as for 
feature flags.
This is also the format that the data portal uses.

**Comment by signechambers1** [comment]
@maniarathi I'm closing this since we've rewritten the APIs but please reopen if relevant.
