### ISSUE TITLE
Better error handling if attempting to edit user annotations when not logged in.

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1838]
Current behavior:

Log into cellxgene, then create a second tab.
You are logged into both tabs, as expected.
Now logout of one tab, then go to the second tab.
That tab will stay say logged in.
If you modify the user annotations, instead of saying "Saved" in the bottom right of the screen,
it will say "Autosave Error: HTTP Error 401"
The user annotation will be changed in the client, but not saved on the server.

Can we do better?

The user may not notice that the annotations are not being saved in this case.
The client side and server side are our of sync.

Options:
1.  say this is a corner case and the current error message is sufficient.

2. have the client periodically poll to see if the user is still logged in, then
  a. reset the page if not.
  b. open a dialogue box if not.

3. Instead of just printing the 401 error when annotations are changed, where it might not be noticed, create a dialogue box explaining they are no longer logged in (like 2b, but only when they try and do something that requires authentication).

**Comment by bmccandless** [comment]
Another option.

4. When the user attempts to do something that requires authentication in the second window, the client will get a 401 return code from the server.  It will then do a logout.

Advantages: This option is pretty easy to implement, and I checked that Amazon works in this way, maybe other websites.

Disadvantage:   It is possible that the user does work on the first tab, after logging out of the second tab.  In this case, the work is lost when adding a user annotation (for example).  Option 2 would have mitigated this more.  Although this scenario is a bit of a corner case, and I don't think it's worth adding complexity to handle it.

**Comment by Bento007** [comment]
I think 2 is the way to go. As far as polling it could be as simple as setting and unsetting a value in local storage during login and logout. The advantage of using local storage is it's accessible to the webapp and doesn't require an API call to check of the user is logged in.

**Comment by signechambers1** [comment]
With @Bento007 's suggestion, is 2 more effort to implement than 4? I'd like to reduce the risk of a user losing work if it's the same or less work to implement.

**Comment by tihuan** [comment]
A another potential solution is to use browser tab's focus event to trigger a log in check, but we need to think a little more if it covers all the cases a user might not be logged in and still doing annotation

**Comment by bmccandless** [comment]
Another option that @tihuan suggested was to do the check when the focus changes back to the cellxgene page.
This is simpler than the polling idea.  This is also how meta solved the problem.

**Comment by tihuan** [comment]
@bmccandless @signechambers1 do we have a sense of the priority of this ticket? P1~4 😄

CC: @lesliecodes 

Thank you!

**Comment by signechambers1** [comment]
@tihuan just labeled as a P2. Thanks!

**Comment by MDunitz** [comment]
low priority -> closing
