### ISSUE TITLE
Dataset overview drawer changes from prod QA review

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1839]
* Remove book icon from dataset title
* Change book icon in info drop down to info icon
* Remove "Contributors" and Affiliations per Trust decision ( we aren't currently saying we will use this publically when gathering the data)
* Include the ontology value in a separate column. Something like:
 Assay: Smart-seq2		EFO:0008442
 Disease: Normal		        PATO:0000461
 Ethnicity: Unknown
 Region: Normal

**Comment by signechambers1** [comment]
fyi @seve just heard back from Trust, we should remove the Contributors and Affiliation info from the drawer until we properly disclose this when we gather it from our users. I updated the body of the ticket to reflect this.

**Comment by seve** [comment]
@colinmegill @signechambers1 Do we still want to right align the dataset name or do we want to put it back where it originally was, pre-infodrawer?

![image.png](https://images.zenhubusercontent.com/5cf012346757146a9c288b38/a824a7b1-0bff-4937-bfc2-373a5dec4be5)

**Comment by colinmegill** [comment]
Right aligned is great
