### ISSUE TITLE
Add text to encourage users to authenticate if they intend to use annotations

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1840]
The authentication feature requires a redirect away from the cellxgene page, and then a redirect back.
Any client side state will be lost. To avoid surprises, we decided to give the user a warning.
(This is option 2 in this document:  https://docs.google.com/document/d/1IwvemUlVvAGLs8kBYRkwe4chkw6kwMSFEFxReICa7rc/edit?usp=sharing)

When the page loads, if authentication is enabled, but the user is not authenticated then:

1. create a pop up window with this wording and [this design](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/480):  
"Log in now to save your annotations. They’ll be here the next time you view this dataset. Please note, logging in later will refresh this page and you may lose progress."

2. Add "Log In" button and "Cancel" button to make the window go away.

3. Add a check box option that says "Do not show me this message again", where the answer is stored in local storage.

**Comment by lesliecodes** [comment]
@signechambers1 this is ready for QA! Thank you.

**Comment by tihuan** [comment]
Thanks so much for moving this, @lesliecodes !

@signechambers1 please kindly QA this in staging:

https://cellxgene.staging.single-cell.czi.technology/experimental/pbmc3k.cxg/

`dev` env is currently out of sync, so the feature is not available there! (@bmccandless is helping us to fix it 🙏 Thanks, Brian!)

Thank you!
