### ISSUE TITLE
[Spike] Determine how to handle versioning of CXG format

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1844]
We need to figure out how we want to handle CXG versioning changes in the future and what our deprecation/migration policy should be when we don't want to support older versions of CXG. Note that CXG is currently an internal-only file format.

**Definition of Done**: a migration policy written down in the cellxgene dev-docs.

**Comment by mweiden** [comment]
From the 2020-09-22 Refinement discussion:
Ideas
* Support just the latest version
* Support two latest versions (for deprecation and allowing developers to migrate)

Core concerns
* Don’t want to migrate all datasets forward

Synthesis?
* We migrate between versions of the encoding
* We (ideally) don’t want to migrate for changes in metadata
