### ISSUE TITLE
[BUG] The /health endpoint is incorrect

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1846]
**Describe the bug**

The /health endpoint is incorrect after the webpage / api URL separation.
health should be on the api_base_url.
The current behavior is the /health is not accessible (except when directly accessing the eb servers).

**Comment by bmccandless** [comment]
The first half of this has already been done (making the new endpoint).
Once prod is deployed again, we can do the second part (remove the old health endpoint)

**Comment by maniarathi** [comment]
@bmccandless , what do you think about adding this to the Auth epic so that completing the epic is contingent on also cleaning this up? It can be pulled into bug budget so you can freely add the estimate as well.

**Comment by bmccandless** [comment]
@maniarathi it's more a bugfix to the change we did to consolidate data portal and cellxgene to the same domain.  
It's not really related to auth.

**Comment by maniarathi** [comment]
OK. I'd still remove the estimate me! label though. This falls under our bug budget which means that it can be estimated ad hoc before it gets worked on.

**Comment by bmccandless** [comment]
That's fine.  So when I'm ready to work on it (after the next prod deployment), do I just move it into "In progress" and give it a time estimate?

**Comment by maniarathi** [comment]
Yep! If it's not the Sprint Backlog already, feel free to move this in there now.
