### ISSUE TITLE
[BUG] Continuous features (right-hand-panel) missing in 0.16.4

### ISSUE THREAD

**Issue by GHAStVHenry** [chanzuckerberg/cellxgene#1848]
**Describe the bug**
Some continuous features not displaying on 0.16.4 (right hand bar)

**To Reproduce**
1. run https://cellxgene.cziscience.com/d/6a2facf2-ea03-407b-b73b-82d582da3930.cxg/ data in 0.16.4

**Expected behavior**
Data displayed with Commit 437fd5fedae4e312d510ef80592bb9f05c6cdb62 shows 5 features (nCount_RNA, nFeature_RNA, percent.mito, percent.ribo, Stress1)
Data displayed with 0.16.4 shows only 2 features (nCount_RNA, nFeature_RNA)

**Screenshots**
* Expected: 437fd5fedae4e312d510ef80592bb9f05c6cdb62
![image](https://user-images.githubusercontent.com/38675268/93499670-e9f51980-f8d8-11ea-8d1a-aba234250576.png)

* Actual: 0.16.4
![image](https://user-images.githubusercontent.com/38675268/93499726-f8dbcc00-f8d8-11ea-9757-822be4481581.png)

**Version (please complete the following information):**
 - Desktop or hosted?: hosted and desktop
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: 0.16.4

**Additional context**
Worked in 0.16.2 and older... and works in Commit 437fd5fedae4e312d510ef80592bb9f05c6cdb62 which is newer than 0.16.4

**Comment by maniarathi** [comment]
Currently vetting the test pypi release before pushing it out! https://test.pypi.org/project/cellxgene/0.16.5rc0/

**Comment by signechambers1** [comment]
This passes QA! the correct values show up and i can brush on the right side bar which selects cells.

**Comment by maniarathi** [comment]
Hi @GHAStVHenry we just pushed out the 0.16.5 release to PyPI so should be fixed now! Thanks for your patience!

**Comment by GHAStVHenry** [comment]
confirmed, the features are visible and can be brushed
