### ISSUE TITLE
Launching cellxgene with an h5ad fails but suceeds with the cxg version of the dataset

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1849]
For certain datasets running 
`cellxgene launch dataset_name.h5ad` will fail with 404 http errors 
but if you pre convert with 
`cellxgene convert dataset_name.h5ad`
and then launch with
`cellxgene launch dataset_name.cxg` it succeeds 

Issue raised while working with @wariobrega. Note to let him know when this is fixed

**Comment by MDunitz** [comment]
The successful cxg conversion required passing in the flags `--disable-custom-colors` and `--disable-corpora-schema`

**Comment by ambrosejcarr** [comment]
Linking to novartis/cellxgene-gateway#31

**Comment by maniarathi** [comment]
Hey @MDunitz , do we have a dataset that we own that we can use to repro this? I'm worried that this is going to be quite tricky to fix if we can't repro on our end.

**Comment by MDunitz** [comment]
I dont know if we have a dataset we own. I can reach out to @wariobrega again about getting access to the dataset he ran into this issue with.

**Comment by maniarathi** [comment]
Closing this for now as a low priority bug. If we run into this situation again, can re-open!
