### ISSUE TITLE
Genesets API

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1850]
~~1. Where do we want the user to put the genesets for us to ingest — this could be `uns` in the h5ad~~
2. What is the API endpoint (likely, we attach this to schema, follow Bruce's pattern for user anno)
~~3. What's the data format (what are we sending over, and in what shape, and how much customization will the user be able to accomplish)~~

```
{
  genesets: [
    {
       geneset: covidGenes, 
       genes: [Apod, Cd7], 
       expressionMean: [65, 3456, 34, 56], /* vector of expression by cell by mean */
       userExpressionMetrics: [45,322,324] /* vector of expression by cell by a custom metric, or obj of named vectors */
    },
    {...},
  ]
}
```

4. Do we preload genes or not? (refinement would be: what are the extreme cases? & would prefetch require backend to do anything differently?)

Related ticket: https://github.com/chanzuckerberg/cellxgene/issues/1069

Definition of Done:
- RFC merged into single-cell repo

**Comment by signechambers1** [comment]
Gene sets can also be a way we allow users to export differential expression results. Can the data format support exporting DE results as a gene set with corresponding p-values for each gene?

**Comment by MDunitz** [comment]
Based on feedback in design meeting on 11/16 I am going to update the design to 
- separate the creation of gene sets from the addition of genes to a geneset -- to allow users to click experiment within the browser, the creation of a gene set (in the database) will only occur when the user explicitly saves a gene set 
- add an update/PUT route
- add a deletion route
To prevent confusion/the unexpected deletion of work users will not be able to upload a csv or save a gene set without logging in
The most challenging part of this will be ensuring consistency between the client, server and database. 

During a discussion with @signechambers1 @mckinsel and @colinmegill on 11/17 we decided to first ship the desktop version with csv upload and gene sets saved to the file system in the csv format. Gene sets in the hosted environment will require a plan for consistency and will be shipped with some planned updates to the differential expression feature. 
Later we also plan to include the ability to make a geneset public and (much later) the ability to privately share a geneset within a group of users. 
We also need to further consider how the owner of a dataset could upload and publish gene sets with the published dataset
