### ISSUE TITLE
auth for google:  setup production keys and register application 

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1851]
The current auth0  configuration is making use of Auth0 development keys for connecting to the various providers (Google, Facebook, Github).  In fact Facebook does not work with the Auth0 development keys.
We will want to register our application with each of the Identity Providers in order to obtain a Client ID and Client Secret. 

Some background:  https://auth0.com/docs/connections/social/devkeys

Using identify provider keys has some advantages.
We can customize the sign on pages at Google, Facebook, Github, etc to have our logo and 
other application information (like terms of service, privacy links).

**Comment by bmccandless** [comment]
Steps:

dev/staging
- [x] create the app in google (ask infra)
- [x] setup app in google developer's console (logo, tos, privacy, email, callbacks)
- [x] update auth0 with app's production keys
- [ ] get the app verified

prod:
- [ ] create the app in google (ask infra)
- [ ] setup app in google developer's console (logo, tos, privacy, email, callbacks)
- [ ] update auth0 with app's production keys
- [ ] get the app verified

**Comment by mweiden** [comment]
Waiting for Google to approve the new logo at this time.

**Comment by bmccandless** [comment]
Done for prod.   Any reason to do it for staging/dev?  If not we can mark this as done.

![Screen Shot 2020-10-06 at 8.29.25 AM.png](https://images.zenhubusercontent.com/5e31be33ed0cb222843df04c/e3cf6bea-fbf1-4396-9ab4-cbbec5f3d250)

**Comment by bmccandless** [comment]
I'll close this, since it's working on prod.
