### ISSUE TITLE
auth for github: setup production keys and register application

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1856]
Should be similar to how google was setup, see #1851

**Comment by MDunitz** [comment]
QA approved by @signechambers1 after updating the user description/profile picture
![Screen Shot 2020-10-28 at 12.32.04.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/cd2ea789-61ba-4c5a-8fd6-e292b4dff766)
