### ISSUE TITLE
Fix compatibility tests

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1865]
**Need**: now that the compatibility tests are running, they are rightfully failing. Specifically, we import the function `concat` which is only available in newer versions of anndata. We need to also support the same code path using the `concatenate` function if the version of `anndata` is less than 0.7.0.

Link to a sample failing compatibility test: https://github.com/chanzuckerberg/cellxgene/runs/1156703272?check_suite_focus=true

**Definition of Done**: Compatibility tests are passing.

Update 10/23
- [x] change requirement to `anndata>=0.7`
- [x] add warning for cli users
- [x] update version tested in compatibility tests

**Comment by MDunitz** [comment]
Update on progress on this ticket
Currently running into issues reproducing this locally. Using anndata v 0.6.21 does cause the tests to fail but not for the reason described above. The main error I am currently seeing is 
```
server.common.errors.DatasetAccessError: File must be in the .h5ad format. Please read https://github.com/theislab/scanpy_usage/blob/master/170505_seurat/info_h5ad.md to learn more about this format. You may be able to convert your file into this format using `cellxgene prepare`, please run `cellxgene prepare --help` for more information.
```
Followed by a tuple format error

**Comment by MDunitz** [comment]
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(71)<dictcomp>()->{}
-> passkwargs = {k: v for k, v in kwargs.items()
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(74)_wrapreduction()
-> if type(obj) is not mu.ndarray:
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(75)_wrapreduction()
-> try:
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(76)_wrapreduction()
-> reduction = getattr(obj, method)
(Pdb) 
AttributeError: 'tuple' object has no attribute 'prod'
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(76)_wrapreduction()
-> reduction = getattr(obj, method)
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(77)_wrapreduction()
-> except AttributeError:
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(78)_wrapreduction()
-> pass
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(87)_wrapreduction()
-> return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

**Comment by MDunitz** [comment]
Notes:
```
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/anndata/readwrite/read.py(523)_read_key_value_from_h5()
-> value = h5py._load_h5_dataset_as_sparse(ds, chunk_size)
(Pdb) ds
<HDF5 dataset "names": shape (100,), type "|V1600">
(Pdb) c
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/anndata/readwrite/read.py(492)_read_args_from_h5ad()
-> print(e)
(Pdb) e
ValueError('invalid shape in fixed-type tuple.')

```

Issue may be from names?

**Comment by MDunitz** [comment]
Problem coming from
```
        for k in f[key].keys():
            try:
                _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
            except Exception as e:
                import pdb
                pdb.set_trace()
                print(e)
```
Which is called inside of `_read_key_value_from_h5`
```
(Pdb) h5py.Group
<class 'anndata.h5py.h5sparse.Group'>
(Pdb) f[key]
<anndata.h5py.h5sparse.Group object at 0x138253a58>
(Pdb) k
'names'
(Pdb) f[key]
<anndata.h5py.h5sparse.Group object at 0x138253a58>
(Pdb) f[key].keys()
<KeysViewHDF5 ['names', 'params', 'scores']>
```

**Comment by MDunitz** [comment]
Store
```
 def _read_key_value_from_h5(f, d, key, key_write=None, chunk_size=6000):
(Pdb) f
<anndata.h5py.h5sparse.File object at 0x13ad66dd8>
(Pdb) d
*** Newest frame
(Pdb) key
'uns/rank_genes_groups/names'
(Pdb) key_write
'names'
(Pdb) chunk_size
6000
```

**Comment by MDunitz** [comment]
```
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/anndata/readwrite/read.py(515)_read_key_value_from_h5()
-> if isinstance(f[key], h5py.Group):
(Pdb) f[key]
<HDF5 dataset "names": shape (100,), type "|V1600">
(Pdb)  h5py.Group
<class 'anndata.h5py.h5sparse.Group'>
```
```
-> passkwargs = {k: v for k, v in kwargs.items()
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(74)_wrapreduction()
-> if type(obj) is not mu.ndarray:
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(75)_wrapreduction()
-> try:
(Pdb) 
> /Users/mdunitz/Desktop/cellxgene/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py(76)_wrapreduction()
-> reduction = getattr(obj, method)
(Pdb) 
AttributeError: 'tuple' object has no attribute 'prod'
```

**Comment by MDunitz** [comment]
Final update 
I narrowed it down to an issue where `_read_key_value_from_h5 `recursively calls itself, the issue seems to appear first when the key is `names` (it may appear after that as well)
I think the issue might be coming from a `getattr` call in numpy but I'm not 100% sure.

As scanpy is now requiring anndata>=0.7 we feel comfortable doing that as well
