### ISSUE TITLE
Dockerize cellxgene

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1866]
Need: Dockerizing cellxgene gives a few nice things. First, it provides an easy way for users who want to host their own cellxgene to fetch and deploy the cellxgene docker image. Second, it allows us to easy switch our deployment orchestration service. Currently we are using Elastic Beanstalk but this won't be true in the medium-term future as we will likely switch over to one of ECS or EKS once we get some guidance from Infra. 

Definition of Done:
- (REMOVED) Dockerized cellxgene is available on Elastic Container Service.
- (REMOVED) Deployment of cellxgene is updated so that the docker image is uploaded to ECS.
- [ ] Deployment of cellxgene is updated so that EB uses the uploaded docker image.

Open question: how will this play with the compute tier that is being built?

**Comment by bmccandless** [comment]
Update the definition of done:

We will hold off on using ECS directly, and use EB with a Dockerfile instead.

**Comment by bmccandless** [comment]
Progress:
The Dockerized EB is in main.
Next step is to deploy in dev, apply terraform, and re-deploy.  Verify there is no downtime, and dockers are actually used.
