### ISSUE TITLE
Add a GithubAction to perform a locust stress test scheduled every Sunday

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1868]
Need:

A big part of cellxgene's value comes from the speed with which one can interact with large datasets. We need to know when we've introduced code that takes a hit on the interactive speed.

cellxgene already has a locust stress test available to run; we can create a GithubAction that runs per PR merged into `main` to ensure that the performance does not take a hit.

Definition of Done:
- [ ] Validate that the locust test suite is comprehensive in terms of the APIs that we offer today. If not, add them in.
- [ ] Add the MCF7 dataset to the dataset list in locust (dataset path is `d/Single_cell_drug_screening_mcf7-44.cxg/`, config file is `server/test/locust/config.py`).
- [ ] GithubActions is setup to run every Sunday.

**Comment by tihuan** [comment]
Do we need to define benchmarks for the stress test, so we can fail the stress test given the threshold? Or the benchmarks are defined already? Thank you!

**Comment by Bento007** [comment]
This sounds more like performance testing. We are seeking to run a test that will verify the performance of the system is acceptable under a specific load. A stress test implies we are pushing the system to its point of failure, and verifying the outcome. Please change the language of the ticket to be a performance test.
