### ISSUE TITLE
Left side bar displays all metadata first and then removes singletons from the rendering

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1869]
![Screen Shot 2020-09-24 at 8.55.35 AM.png](https://images.zenhubusercontent.com/5c537006f3a9152a2050f2ad/8125793d-d075-4156-957f-46111a6794be)

When a dataset is loading in cellxgene, all of the singleton metadata first shows up in the left side bar and then disappears after a filtering step removes the singletons. Instead the singletons should never store the left side bar.

A possible mechanism to fix this is to store the singletons separately in the annomatrix.

**Comment by colinmegill** [comment]
Alternate proposal: add a new property `label_count` to `config` for each bit of categorical metadata.

**Comment by bmccandless** [comment]
The categories and labels are already part of the schema.   The frontend has all the information it needs when it gets the schema to know how many labels exist in each category. 

For example:  `curl https://api.cellxgene.staging.single-cell.czi.technology/cellxgene/e/Single_cell_drug_screening_k562-43-remixed.cxg/api/v0.2/schema | jq `

You can see that "disease" only has one value, so it should go in the drawer (don't add to left).

```

          {
            "categories": [
              "normal"
            ],
            "name": "disease",
            "type": "categorical",
            "writable": false
          }, 
```


and something like "dose" has more than one, so it should go to the left:
```
          {
            "categories": [
              0,
              10,
              100,
              1000,
              10000
            ],
            "name": "dose",
            "type": "categorical",
            "writable": false
          },

```

**Comment by ambrosejcarr** [comment]
QA'd in dev.
