### ISSUE TITLE
[BUG] drawer gives an error if there are user defined annotations

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1870]
**Describe the bug**

If a user has created user defined annotations, the drawer features says "Failed to load info"

**To Reproduce**

Log in
Make an annotation category
Check the drawer

**Comment by maniarathi** [comment]
@seve Can you pop in an estimate for this bug please?

**Comment by signechambers1** [comment]
QA'd and fixed on dev! Thanks @seve!
