### ISSUE TITLE
Time point histogram is not loading

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1873]
Steps to reproduce:
1. Chrome
2. Go to https://cellxgene.cziscience.com/e/Single_cell_drug_screening_a549-42-remixed.cxg/
3. Look at RSB, time point histogram does not load

Can we add a test to check for loading for the default histograms in the RSB?

**Comment by maniarathi** [comment]
Whoever takes this ticket, please point before beginning thanks! :)

**Comment by MDunitz** [comment]
Discussion with @seve 
This  isn't necessarily a bug, its intended to not display a histogram for single value continuous fields, but it's definitely a UX failure since a lot of people have been asking about that.
IMO, it's a info drawer use case


Options
 - display the single value as a histogram
- move into the info drawer

@signechambers1 @ambrosejcarr any preference?

**Comment by signechambers1** [comment]
Ah I see, since time point is a numerical data type in the obs dataframe it is showing up in the right side bar even though it only has one value, 24, for all observations (like the categorical singletons we pulled into the info drawer).

For any numeric singleton, the histogram wouldn't provide the user any value (ie no distribution to see, nothing to brush on) and takes up a lot of real estate so I am also leaning towards the data drawer (where as columns are described in [1874](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1874) time point would be in the Field column and 24 would fall in the label column, Ontology ID would be null ).

Time point in this instance (and probably other numeric singletons?) doesn't seem to be as salient information as the other dataset metadata in the dataset drawer so I would put this info at the below the other metadata.

fyi @colinmegill if you disagree let us know, otherwise agree with @MDunitz about pulling time point into the info drawer

**Comment by colinmegill** [comment]
Info drawer sounds great.

**Comment by lesliecodes** [comment]
@MDunitz can you point this? Thanks.

**Comment by MDunitz** [comment]
Notes from discussion
- We dont want to update the info drawer past the first render to avoid issues with continuous vars selected down to one value appearing in it
- We do need to make sure that the info drawer is populated by non selected (original) annoMatrix
- We dont want to rerun summarize or reload data
## Solution
- create a reducer, make the checks in the RSB, add the removed histograms to the redux state, and then in the info drawer just pull the values from the redux state
- this puts all the checks in one place and allows us to (re)remove the async code from the info drawer

**Comment by lesliecodes** [comment]
@MDunitz is this ready for QA?
