### ISSUE TITLE
Data drawer final round of prod QA fixes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1874]
Final round of tweaks for the dataset drawer:

- [x] Relabel button in LSB to truncated version of LONG data set name instead of short data set name
- [x] Include organism in the Dataset Metadata section, not as its own section 
- [x] Add column headers to the Dataset Metadata section: Field, Label, Ontology ID
- [x] Move preprint to the bottom, as the last section in the drawer (only relevant for users once they’ve reviewed the metadata)

**Comment by maniarathi** [comment]
@signechambers1 Ready for QA

**Comment by signechambers1** [comment]
@seve I don't see the changes on dev, let me know when I should take a look?

**Comment by maniarathi** [comment]
I think the deployment just took a while -- I see it on dev now @signechambers1. Thanks!
