### ISSUE TITLE
Create Architecture Diagram for Hosted Cellxgene/Data Portal

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1875]
## Need
As a developer I want to discuss the current architecture and determine how new features will fit into the existing architecture. I also want to be able to explain to a new engineer or PM how the system works at a high level.

## Definition of Done
- [ ] Use Lucidchart (or equivalent) to model the infrastructure of the services for cellxgene and the interactions between the services. Add the diagram to the `single-cell` repo as an RFC (get the RFC approved by the engineering team). Add text as needed to explain the architecture.
- [ ] Use Lucidchart (or equivalent) to model the infrastructure of the services for Data Portal and the interactions between the services. Add the diagram to the `single-cell` repo as an RFC (get the RFC approved by the engineering team). Add text as needed to explain the architecture.

**Comment by signechambers1** [comment]
@maniarathi is this a priority or ok to close?

**Comment by maniarathi** [comment]
Yep, this is OK to close. We'll be doing this for Data Portal/Explorer which Andrew will be tackling this quarter.
