### ISSUE TITLE
Document the parameters of the default config yaml file (outside of the file)

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1879]
## Need
- As a user I want to understand the configuration variables passed in when I launch cellxgene (locally or if I host my own). Because many of the variables depending on each other/are determined by what other variables are set this can get quite confusing. Ideally I'd like a simple to understand page documenting what each variable does and what it depends on, along with some example config files I can copy and try out.

**Comment by signechambers1** [comment]
Going to close as this is a lower priority, users can use cellxgene launch -h and reach out to us if they want additional help.
