### ISSUE TITLE
AppConfig:  Ability to pass in more than one config file

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1884]
**Need:**

The hosted cellxgene has three config files (dev, staging, and prod).  These files are mostly duplicates of each other, with small changes.  This can lead to errors when applying the same change to three places, or can lead to the deployments diverging accidentally.

**Proposed Solution:**

Add a feature to read in multiple config files.  

For example:
```
cellxgene launch -c common_config.yaml -c dev_config.yaml
```

Where in this case, the `common_config.yaml` would contain the configuration common to all three deployments.  Anything provided in that file would be overwritten by the contents of the next file specified (`dev_config.yaml` in this case).

**Comment by maniarathi** [comment]
@bmccandless I think this ticket actually needs further refinement. There are nuances that we should probably sort out regarding overlapping configs, ordering, how it compares to other ways to pass in configs. 

There might be alternatives to passing in multiple config files. I need to do more research on config best practices, but this ticket to me is actually adding complexity to our config mechanisms rather than simplifying it. I'd like to discuss it in person first before scheduling/pointing this ticket.

**Comment by bmccandless** [comment]
There may be other ways to handle it than the proposed solution.

But, the multiple config concept shouldn't have any ambiguity or complexity.
Actually we already do it.  We implicitly read in the default config file, then we read in the user's config file. 
Anything in the user's config file overwrites what was already there.
Then if there are command line arguments, those are set, overwriting anything in the config files.

So in the case of multiple user config files, you'd do these steps:
- [ ] add "multiple=True" to the click option for config file.
- [ ] now "config_file" is a list, ordered in the way the user ordered them on the command line

In fact, here is the complete diff of my proposed change (not include a test case):

```
--- a/server/cli/launch.py
+++ b/server/cli/launch.py
@@ -239,12 +239,13 @@ def launch_args(func):
     @click.option(
         "--config-file",
         "-c",
         "config_file",
         default=None,
         show_default=True,
+        multiple=True,
         help="Location to yaml file with configuration settings",
     )
     @click.option(
         "--dump-default-config",
         "dump_default_config",
         is_flag=True,
@@ -363,13 +364,14 @@ def launch(
     # app config
     app_config = AppConfig()
     server_config = app_config.server_config
 
     try:
         if config_file:
-            app_config.update_from_config_file(config_file)
+            for cfile in config_file:
+                app_config.update_from_config_file(cfile)
 
```

**Comment by bmccandless** [comment]
@maniarathi forgot to tag you in my previous comment.

**Comment by MDunitz** [comment]
low priority -> Closing
