### ISSUE TITLE
Spike to figure out stories needed for a successful TS migration

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/cellxgene#1886]
The goal of this spike is to produce tickets we need to implement for a successful TS migration!

I'm thinking 3 points should be enough to complete the spike 👌

**Comment by tihuan** [comment]
The goal of this spike is to produce tickets we need to implement for a successful TS migration!

I'm thinking 3 points should be enough to complete the spike 👌

**Comment by maniarathi** [comment]
Closing since we have a plan outlined [here](https://docs.google.com/document/d/1zN-x6LxA3krR-PiOO_OFuIwKOOWLGcEb-ChjkTpsg1c/edit#heading=h.44vqg821e4b5).
