### ISSUE TITLE
Design for navigation between data portal from cellxgene

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1887]
On hosted cellxgene, users should be able to navigate back to https://cellxgene.cziscience.com/ from exploring a dataset. We want this to feel like a connected product. There may be other navigational functions that would be helpful, see [1715](https://github.com/chanzuckerberg/cellxgene/issues/1715). We should also consider the different paths users will take to a hosted data set (direct link, from covidatlas or other external site, from the data portal).

Navigating back to the portal is under discussion [here](https://chanzuckerbergteam.slack.com/archives/C736J4S15/p1601315758014300).

Ideas from the thread:
1. Navigate to a landing page from cellxgene logo which offers links to docs or datasets
2. Navigate to github page from cellxgene logo
3. Navigate to data portal from cellxgene logo
4. Link to data portal through info drop down

**Comment by brianraymor** [comment]
This should also cover the _discovery_ case where the user is redirected from an external portal to hosted cellxgene and then is offered the ability to explore other datasets through the CZI portal.

**Comment by brianraymor** [comment]
@signechambers1 - can we close this issue since it's addressed in [cellxgene (portal and explorer) offers a consistent and seamless experience for consumers](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/143) ?

**Comment by signechambers1** [comment]
Yup! Closing.
