### ISSUE TITLE
excessive GPU utilization

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#19]
Current webgl code runs the GPU constantly if the application is an active tab.   This will eat laptop batteries for lunch and generally thrashes my laptop.

We should look at ways to only render when necessary.

**Comment by bkmartinjr** [comment]
@freeman-lab has volunteered to prototype a possible solution

**Comment by bkmartinjr** [comment]
@csweaver - I think we need to prioritize this for our initial release, as the app will be anti-social without this fix.

**Comment by bkmartinjr** [comment]
Discussed with @freeman-lab - he will prototype a solution, and either Colin or I will integrate into the app.

**Comment by bkmartinjr** [comment]
@freeman-lab has provided the proto - @colinmegill will integrate.  Reassigning the issue.

**Comment by colinmegill** [comment]
After experimentation/testing & conversation, a few notes to capture, will add more as necessary.

**Refreshing with categorical, continuous, brushing**:

It does not seem to add significant overhead to fire `regl.refresh()` each time graph updates. As the brush moves across a continuous filter, the graph is re-rendered and componentWillReceiveProps fires. We should watch this at higher scales to ensure this holds true with larger numbers of cells.

**Zooming**:

Zooming is the tricky bit. We can either turn rendering back on when the zoom icon is clicked, or we can try to capture mouse events. For the first pass, we're going to turn rendering (which drains battery) on when the zoom icon is clicked, and back off again. We could, in the future, time it out as well.
