### ISSUE TITLE
Mismatch in custom categorical colour shown in left sidebar and main canvas

### ISSUE THREAD

**Issue by andr-kun** [chanzuckerberg/cellxgene#1901]
**Describe the bug**
There seems to be a mismatch in the custom (anndata specified) categorical colour shown in left sidebar and main canvas when the number of groups in the category is greater than 10.

**To Reproduce**
1. Run the [colourise_pbmc3k.py](https://gist.github.com/andr-kun/a42e635045df38c8822c576510d7723f) script on the pbmc3k.h5ad sample data to create 2 new categories - groupings10 and groupings11 - containing 10 and 11 groups, respectively, which are randomly assigned to each cell. The script will also assign pre-determined categorical colours for each of the newly created categories.
2. Launch the cellxgene browser and use the groupings11 category as the colour scale.
3. You should notice that the first two category will have the correct colour in both the left sidebar and main canvas, but the remaining categories have incorrect colour in the left sidebar.

**Expected behavior**
The colour in the left sidebar should match the colour in the main canvas for all categories which have more than 10 groups.

**Screenshots**
<img width="1680" alt="cellxgene_0 16 4_pbmc3k" src="https://user-images.githubusercontent.com/5274310/94954851-9510f000-04e1-11eb-8c33-2a43a78d4a12.png">

**Version (please complete the following information):**
 - Desktop or hosted?: both
 - Browser (if hosted) [e.g. chrome, safari]: firefox, safari and chrome
 - Version [e.g. 0.13.0]: 0.16.4

**Additional context**
This bug seems to have been introduced in the latest version of the cellxgene (0.16.4) as the previous version of the cellxgene (0.16.2) does not seem to have this issue.
<img width="1680" alt="cellxgene_0 16 2_pbmc3k" src="https://user-images.githubusercontent.com/5274310/94955600-bc1bf180-04e2-11eb-8b7e-c01adcd58aa2.png">

**Comment by seve** [comment]
@maniarathi was #1792 included in 0.16.4?

**Comment by andr-kun** [comment]
@seve seeing the pull request you linked, I think I have an idea for the reason behind this bug. I think it may be due to the fact that you are now sorting the object keys using the default (alphanumeric) sort, which breaks the natural ordering of element when there are numbers in the object key. This actually explains why only the groups from 2 to 10 are affected in the groupings11 category and why the mismatch in colour have offset of 1 since we have 10 groups, which after sorting will become `0,1,10,2....`.

**Comment by maniarathi** [comment]
Hi! Sorry to drop the ball on this, but I took a look and was able to replicate on our latest version. Putting a fix out for this ASAP. Thank you for your patience and for reporting the bug!

**Comment by lesliecodes** [comment]
Passes my QA. See slack thread: https://chanzuckerbergteam.slack.com/archives/GQGPP7925/p1602629370273500
