### ISSUE TITLE
Audit and document cellxgene cookie usage

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/cellxgene#1902]
Context:

According to Sara from info-sec team, an audit of cookies should be conducted and verified to match the cookie banner and policy/table. Best Practices should be used: Secure, HttpOnly, Samesite flags

What:
1. We need to figure out what cookies our web app collects and what they are used for, verify that it matches our cookie banner, [Terms of Service](https://cellxgene.cziscience.com/static/cellxgene/deploy/tos.html) and [Privacy](https://cellxgene.cziscience.com/static/cellxgene/deploy/privacy.html) page claims, and document them. [Meta example](https://help.meta.org/hc/en-us/articles/360032354812-How-does-Meta-use-third-party-cookies-)

2. Note that we also need to check Auth0 login page (https://login.cellxgene.cziscience.com/login), since Auth0 drops quite a bit of cookies in user's browser, like `OptimizelyEndUserId`. (NOTE: Per Sara in comment below, even though Auth0 is the one injecting these cookies, since Auth0 is the service we choose, we need to document the cookies they use too!)

![Screen Shot 2020-10-05 at 10.24.13 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/4e469b6c-0358-43e2-91ae-0d3f22d2d1c2)
![Screen Shot 2020-10-05 at 10.25.29 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/f869d596-2ab1-4504-9423-6057c7f3d1cc)

**Comment by tihuan** [comment]
@sbeara @brianraymor For #2 in the ticket description, I mentioned that we need to check cellxgene's Universal Login Auth0 page and see what cookies Auth0 injects. But my question is, since technically Auth0 is the one injecting the cookies, but the domain is ours (cellxgene.cziscience.com/login), do we need to document their cookies and usage in our documentation?

For example, Auth0 injects `optimizelyEndUserId` (Optimizely) and `ajs_anonymous_id` (Segment), because Auth0 use Optimizely and Segment, so that's out of our control. But since the login page is on our domain, do we need to add those cookies in our cookie table?

Thank you!

**Comment by sbeara** [comment]
My gut check is 'yes.' It's our third party auth system so any cookies it drops in performing the services we need fall under us.

**Comment by tihuan** [comment]
I feel the same! Thanks Sara!! 😄 👍

**Comment by brianraymor** [comment]
No longer required with the transition to plausible.io. Auth is only exposed to funded curators.
