### ISSUE TITLE
Create category limit warning for larger datasets

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1906]
## Need
Performance testing has established some of the limits on the number of annotation categories a user can successfully create for a given dataset size (see [1738](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1738)). Until we can improve those limits we need some way to communicate them to users so they dont get frustrated by failures/lose data they've created.

**Comment by brianraymor** [comment]
Per PM triage - closing since user annotations are not on the 2020 roadmap for hosted cellxgene.
