### ISSUE TITLE
Annotations Race Condition

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1912]
Demonstrated by @tihuan in a [slack thread](https://chanzuckerbergteam.slack.com/archives/C736J4S15/p1602019461085600)

The browser automatically sends annotations to the backend every 3 seconds (if they have changed since the last put). These are processed in the backend, stored in s3 with a row in the relational db linking the s3 uri, user and dataset. When the annotations are retrieved the database identifies s3 uri of the most recent set of annotations and sends that set of annotations to the browser. We are now seeing an issue where rows in the db are saved out of order resulting in the wrong set of annotations being identified as the most recent and sent to the browser resulting in a use's most recent changes not being displayed (although they are stored in s3).

This may be fixed by utilizing a lock on the relational database.

**Comment by brianraymor** [comment]
Per PM triage. Closing since user annotations is not on the 2021 roadmap for hosted cellxgene.

**Comment by MDunitz** [comment]
closed with delete dataset work
