### ISSUE TITLE
CZI specific code should be removed from the open source cellxgene application

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1913]
## Need 
- as a developer I want a clear separation between application and infrastructure code

Cellxgene is used as a both an open source locally deployed application and as an application hosted by czi. In order to optimize for both use cases we need to keep code related to the application and code related to hosting the application separate. We do this by storing code for the application itself in the cellxgene repo and for hosting in the single-cell-infra repo. Lately some code related to performance testing and elastic beanstalk deployment has made its way into the cellxgene repo. 

## Appraoch
- move code from cellxgene/server/test/performance into the single-cell-infra repo
- move code from cellxgene/server/eb into the single-cell-infra repo

**Comment by maniarathi** [comment]
Kinda done based on backend split and renaming effort.
