### ISSUE TITLE
Annotations Performance Enhancement -- Application specific compression

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1916]
## Need
- As a user I want to be able to annotate medium-large datasets on the hosted version of cellxgene

- In order for hosted cellxgene to reach parity with the desktop version users need to be able to create annotations with 10+ categories for medium to large datasets (100k+ cells)
- Currently this is limited by the size of the data being sent from the browser to the server with each save. 

## Approach 
- Update the flat buffer schema to compress categorical variables instead of turning them into arrays of strings, this should provide 2-5x compression (dependent on the size of the cell labels being compressed)

**Comment by tihuan** [comment]
@MDunitz Would using `zlib` in BE and `pako` in FE help here too? The [experiment branch](https://github.com/chanzuckerberg/cellxgene/compare/zlib?expand=1) was able to shred an example request from content length 68744 to 1348 (98% reduction or ~51x compression) 😄 Thank you!

**Comment by MDunitz** [comment]
Covered by https://github.com/chanzuckerberg/cellxgene/pull/1980
