### ISSUE TITLE
Annotations -- Usage stats

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#1918]
## Need
- as a PO I want to know the usage rate of the annotations feature

## Approach
- write a script to pull data from the cellxgene database around number of users and number of annotations/dataset
@signechambers1 -- let me know if there is any other stats you'd like

NOTES:
1. Please also create report for new accounts related stats!

**Comment by signechambers1** [comment]
I also want to know how many new accounts are being created.

**Comment by MDunitz** [comment]
Can use auth0 api to get user/signup stats - https://auth0.com/docs/api/management/v2?_ga=2.141364082.154011553.1604427788-637818375.1604427788#!/Stats/get_daily

**Comment by MDunitz** [comment]
We are planning on moving away from hosted annotations --> Closed
