### ISSUE TITLE
Design for aggregate gene set functionality

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1921]
A user should be able to brush on a gene set in order to subset to a group of genes based on the overall gene set.
A user should be able to plot a gene set on x or y in the scatter plot in order to visualize the correlation between a gene set and an individual gene or another gene set.

@colinmegill is planning to do this in figma (doesn't make sense to implement as a prototype w/o data from the backend).

**Comment by colinmegill** [comment]
v0.3

![image.png](https://images.zenhubusercontent.com/5588c9564f7a08fbb7f35803/086790f4-e2e3-4254-89c2-b99ef6f54cee)

**Comment by maniarathi** [comment]
Demo-ed October 23rd!
