### ISSUE TITLE
[BUG] The re-embedding features stopped working between 0.16.4 and main

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1922]
**Describe the bug**

When I enable re-embeddings, and do a small test, I get 400 errors from the server.

**To Reproduce**

Run the server like this:
cellxgene launch ~/data/pbmc3k.h5ad  -o -v  --experimental-enable-reembedding

Then sub select the cells, and attempt to make a new embedding.
After it computes for a while, you will see 400 errors.

**Expected behavior**
The new embedding is displayed.

**Comment by bmccandless** [comment]
There is one server side test that is passing.
I'm not sure if we have an end to end test of this yet.

**Comment by bmccandless** [comment]
0.16.4 works.  0.16.5rc0 fails.

**Comment by maniarathi** [comment]
Pulling in this bug in order to push a community release out either this week or early next.

**Comment by signechambers1** [comment]
This passes QA on 0.16.5rc2

**Comment by maniarathi** [comment]
Pushed out PyPI 0.16.5 release so closing!
