### ISSUE TITLE
Harden re-embeddings for desktop cellxgene and remove the `experimental` word from the CLI launch option

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1937]
Need: the re-embedding feature of cellxgene is a pretty highly used feature that is currently accessible via using the `--experimental-enable-reembeddings` flag while launching the cellxgene server. Given that we've seen a number of bugs come up around the feature, and users notice when it is broken, it seems like a good time to set the default to be true and flip the flag to instead be `--disable-reembeddings`. This ticket will capture the work necessary to complete before the change can be made.

Definition of Done:
- [ ] E2E unit tests on the frontend that ensures that reembeddings works as expected.
- [ ] Additional unit tests for the backend `scanpy.py` to ensure that UMAP works as expected.
- [ ] Renaming of `--experimental-enable-reembeddings` flag to `--disable-reembeddings` (default is False).

Potentially others..

**Comment by maniarathi** [comment]
cc @signechambers1

**Comment by signechambers1** [comment]
Closing as a low priority for 2021
