### ISSUE TITLE
Design for creating, editing, deleting and exporting a gene set

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#1940]
This ticket covers the design for the following user stories in [this epic](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/15): WAITING FOR COLIN

This will be delivered in <<figma? or prototype?>>

**Comment by brianraymor** [comment]
Per @signechambers1 - closing. Will reuse epic for designs.
