### ISSUE TITLE
cellxgene handles schema 1.1.0

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1961]
Currently cellxgene checks for schema version 1.0.0, but soon we'll have 1.1.0.

### Definition of Done
Adjust the client code that checks for exactly "1.0.0" in InfoFormat and LeftSideBar. There will soon be cxgs with version 1.1.0. I don't think the client actually has to do anything different, it just needs to accept the string "1.1.0".

**Comment by mckinsel** [comment]
The client checks for exactly "1.0.0" in `InfoFormat` and LeftSideBar. There will soon be cxgs with version 1.1.0 .

I don't think the client actually has to do anything different, it just needs to accept the string "1.1.0".

**Comment by maniarathi** [comment]
Server and converter code needs to be added which bumped this up to a 2.
