### ISSUE TITLE
[Spike][Analytics][Prod] Google Analytics CSP Error

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/cellxgene#1964]
@tihuan commented on [Mon Nov 02 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/681)

**Context:**

@bkmartinjr (thanks again, Bruce :D!!) identified that, if you use Chrome Beta or Chrome Canary, you'll get Google Analytics CSP error on prod link, such as:

https://cellxgene.cziscience.com/e/Single_cell_drug_screening_a549-42-remixed.cxg/

```
Refused to connect to 'https://www.google-analytics.com/j/collect?v=1&_v=j87&aip=1&a=1454218184&t=pageview&_s=1&dl=https%3A%2F%2Fcellxgene.cziscience.com%2Fd%2Fddc82c9f-3f2a-4516-8208-93b8ac223175.cxg%2F&ul=en-us&de=UTF-8&dt=cellxgene&sd=24-bit&sr=3440x1440&vp=1749x1323&je=0&_u=QACAAEABAAAAAC~&jid=&gjid=&cid=1606325184.1594184029&tid=UA-164217286-1&_gid=1314368515.1604366634&_slc=1&z=334316614' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.cellxgene.cziscience.com sentry.prod.si.czi.technology".
(anonymous) @ VM116:1
(anonymous) @ trycatch.ts:163
(anonymous) @ instrument.ts:267
wd @ analytics.js:37
pe @ analytics.js:36
Sa @ analytics.js:41
Ha.D @ analytics.js:39
pc.send @ analytics.js:71
X.b.<computed> @ analytics.js:51
Z.v @ analytics.js:85
Z.D @ analytics.js:84
N.N @ analytics.js:87
rc @ analytics.js:79
z @ analytics.js:79
(anonymous) @ analytics.js:87
(anonymous) @ analytics.js:87
```

![Screen Shot 2020-11-02 at 5.29.43 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/ddb273d4-91fa-4298-b09a-2f0b8d971f1b)

**What:**
Given that the CSP error happens on Chrome Beta already, it's very likely the same error will start showing up on regular Chrome soon, so we should fix this error in Chrome Beta/Canary as soon as possible

Thanks all!

**Comment by tihuan** [comment]
@signechambers1 @colinmegill @seve PTAL!

I temporarily added P1 label for this, since it feels it's something we should address in either this sprint will next sprint, otherwise it will likely affect analytics once the error starts showing up in regular Chrome. Please let me know what you think!

Thank you!

**Comment by tihuan** [comment]
@tihuan to do quick research on this

**Comment by tihuan** [comment]
reproducible on reg Chrome now!

**Comment by maniarathi** [comment]
Closing since we will be deprecating GA.
