### ISSUE TITLE
Diffexp `up_and_down` regulated genes

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1970]
We want to be able to return not only top 50 genes but also upregulated and downregulated genes, 25 of each. In other words, return both the 25 genes with the smallest p-values and positive log fold change, and 25 genes with the smallest p-values and negative log fold change.

This should be a flag passed from the client on cellxgene to the python server when the diffexp call is made. This may need to return hierarchical data for sorting by similar vectors, but that may not be necessary in the initial implementation.

**Comment by colinmegill** [comment]
This would facilitate reproducing: 

![Uploading image.png…]()

https://community.jmp.com/t5/Discussions/Single-legend-for-Hierarchical-clustering-heat-map/td-p/49350

**Comment by colinmegill** [comment]
Note: we may do hclust as a part of #632 because the hclust may be subset dependent and not global

**Comment by signechambers1** [comment]
@signechambers1 to clarify requirements here given we will act on feedback to output results into two different gene sets.

**Comment by signechambers1** [comment]
Closing in favor of #2179
