### ISSUE TITLE
[FEATURE REQUEST] Type the lower limit when selecting on histogram

### ISSUE THREAD

**Issue by aopisco** [chanzuckerberg/cellxgene#1977]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to control the lower limit of the selection in terms of gene expression

**Describe the solution you'd like**
Type the value for the lower and upper limit for the selection

**Describe alternatives you've considered**
Sequential selections, which become tedious very quickly

**Additional context**
Feature requested by @angelussong

**Comment by signechambers1** [comment]
Hi @angelussong and @aopisco, thanks for the feature request! Would our clipping functionality work for you? You can test it out by clicking the bar graph icon.

**Comment by signechambers1** [comment]
Closing this ticket for now, if clipping does not work please feel free to comment and reopen.
