### ISSUE TITLE
User annotations fail on larger datasets

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1979]
When a user creates or edits a user-defined annotation, the client makes a PUT request to the backend with the full set of labels associated with the category.

If the body of the PUT request is > 1MB, the backed returns a 413, and the user's annotations are silently not recorded.

It is very easy for the request body to exceed 1MB. To reproduce, go to https://cellxgene.staging.single-cell.czi.technology/e/Single_cell_drug_screening_a549-42-remixed.cxg/ , log in, and create a new annotation.

Open the network tab, see the request body is 1859316 bytes, and the backend returns 413.

Now, select all the cells and set the label to "test". The PUT request is now 1003788 bytes and succeeds.

Change the label name to "tests". The PUT request is now 1146376 bytes and fails.

**Comment by mckinsel** [comment]
A possible mitigation is setting `client_max_body_size` to something bigger in our nginx settings. But this just kicks the can a very short distance down the road.

**Comment by MDunitz** [comment]
I think this is somewhat addressed by [Creating a category limit](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1906undefined)
[better compression](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1916undefined)
and 
[Incremental updates](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/638undefined)

**Comment by maniarathi** [comment]
Landed in prod today.
