### ISSUE TITLE
Hosted cellxgene backend scales _down_ when a big dataset is opened

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1983]
We have a load balancer that points at a target auto-scaling group. The ASG scales out or in based on NetworkOut. The scaling alarm doesn't trigger for two minutes. An instance takes about 6-8 minutes to become healthy after it starts. So you get something like:

12:00 - User opens big dataset, plays around with it. NetworkOut increases. We have four healthy instances: A,B,C,D
12:02 - ASG scales out by two instances. We have four healthy (A, B, C, D) two unhealthy (E, F).
12:04 - Suppose the user is now all client-side. NetworkOut drops and ASG scales in choosing instances nearest to billing hour. So we have two healthy (C, D) and two unhealthy (E, F).
12:10 - E and F become healthy.

So the net result of the scale out alarm is to decrease the number of hosts the LB will route to below the minimum capacity limit. That's the opposite of what we want! Especially if the user start making user annotations on this dataset.

**Comment by MDunitz** [comment]
ToDo
- [ ] update client side request retries to include exponential backoff & jitter
- [ ] Add HealthCheckGracePeriod to prevent health checks prior while instance is spinning up
- [ ] add cooldown period to prevent back to back scaling actions (particularly scaling while newest instances arent in a ready state)

**Comment by mckinsel** [comment]
FYI, request backoff is in a separate ticket.

**Comment by maniarathi** [comment]
Landed in prod.
