### ISSUE TITLE
User annotation PUTs return 400s

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1984]
We see 400 responses to PUTs to the user annotations endpoint sometimes. You can trigger one this way:

1. Go to https://cellxgene.dev.single-cell.czi.technology/e/Single_cell_drug_screening_mcf7-44-remixed.cxg/
2. Create a new category initialized from "rt_well"

Seems like something with how types are being handled in the TileDB code, see https://sentry.prod.si.czi.technology/sci-sc/hosted-cellxgene/issues/109814/ for example.

There's also a reasonable chance there's a scaling issue as well, but we can rule that in or out better once we've resolved the type issue.

**Comment by maniarathi** [comment]
Fixed went into prod today.
