### ISSUE TITLE
main graph doesn't render on viewport change

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1998]
Bug was introduced in performance changes regarding buffer and regl render calls

**Comment by maniarathi** [comment]
@signechambers1 Can you QA this? @seve Can you provide a few more details on how Signe can verify that this is working in dev?

**Comment by maniarathi** [comment]
Oh my -- this is actually a pretty serious bug that made it into prod. Launching cellxgene and then resizing makes the canvas shrink and stretch in weird ways until you refresh the page in the new size and it looks fine. 

@seve Is there a way we could add a test to ensure that this bug doesn't occur again?

**Comment by maniarathi** [comment]
Verified in prod; closing
