### ISSUE TITLE
How to find a port that is NOT in use

### ISSUE THREAD

**Issue by dfermin** [chanzuckerberg/cellxgene#2004]
Hello.

I've successfully installed cellxgene on an AWS EC2 instance.
I've tried to launch the interface with this command:

`cellxgene launch --host <AWS_IP_ADDRES_HERE>  --port 6000  --verbose ./my_data.h5ad`

However it never runs. I consistently get this error:
`Error: The port selected 6000 is in use, please configure an open port.`

This error happens regardless of what port I pick. 
I've disabled the firewall just in case that was the issue but I continue to get the same error. 

Any suggestions on how to find a port that will work?
The AWS EC2 instance is only running SSH.

Thanks

**Comment by bmccandless** [comment]
Hello @dfermin,

Which AWS_IP_ADDRESS_HERE did you use?  

You will need to use the private IP address of the instance.
You can instead use "0.0.0.0" as the host, which means allow connections on any interface.

Also, to make this work you will need to add a security group to your ec2 instance that
has inbound rules that allow traffic to that port.

Hope that helps,
  Brian

**Comment by dfermin** [comment]
I've tried the "0.0.0.0" and that seems to start the server running.

`cellxgene launch --host 0.0.0.0 --port 6000 --verbose ./my_data.h5ad`

However when I go to the web address on chrome: `http://external_facing_AWS_ip:6000` all I get is that the site can't be reached. 

The AWS security group allows inbound and outbound from port 6000.

**Comment by bmccandless** [comment]
@dfermin ,
I think I understand now.   You got unlucky with your choice of port 6000.  It is one of the ports that browsers consider unsafe:  https://neo4j.com/developer/kb/list-of-restricted-ports-in-browsers/

I was able to reproduce your issue when I used port 6000.  I verified that 6001 works.  

  Brian

**Comment by dfermin** [comment]
Thanks! 
I was able to get it to work with port 5005.
