### ISSUE TITLE
[QUESTION]Is there a means to hide observation columns from the h5ad object

### ISSUE THREAD

**Issue by ddemaeyer** [chanzuckerberg/cellxgene#2005]
At the moment we are adding a large amount of metadata on our h5ad objects. Is there a means to filter the observations that are loaded into cellxgene.

**Comment by ambrosejcarr** [comment]
@mckinsel @seve we have some code that filters metadata columns in the hosted version for the metadata drawer, right? 

Do you have a sense of how complex it would be to port that solution to the desktop version of cellxgene? For example, could it support a CLI argument like `--drop_cols <column_a>, ... <column_n>`?

**Comment by ddemaeyer** [comment]
To give some background, we are currently using h5ad as a standard format in our scRNA-seq pipelines and are uploading to cellxgene for interactive analysis. The object can become rather large since we are integrating quite a lot of samples (+5Gb range) and are also providing a large amount of metadata on the object (e.g. we are merging vdj data to the object from scirpy which can quickly bloat the objects metadata). To allow for easy visualization, I was thinking about a mask column. So a boolean value for each obs column which would load the columns that are required.

As such every h5ad with a boolean array field in uns of dimension n_obs can be filtered during conversion on this field. 

So code changes in my view: 

Add optional command line argument to the launch command specifying the field in the uns slot that contains the information. Put the argument in the app config. In server/data_anndata/anndata_adaptor.py replace 
` def get_obs_columns(self):
        return self.data.obs.columns` 

with code that uses the appconfig to filter the columns. This of course would not work with the other datatypes.

@mckinsel @seve Any thoughts/comments as I do not know your guys code base yet, would be happy to fork and implement if you can have some input on this one.

**Comment by ambrosejcarr** [comment]
That explanation makes sense, thank you for the context. @ddemaeyer we think you'd be able to filter columns using our dataset config. [This is what it could look like.](https://github.com/chanzuckerberg/cellxgene/compare/mckinsel/drop-columns)

**Comment by signechambers1** [comment]
@ddemaeyer I'm closing this issue but please let us know if you have additional questions!
