### ISSUE TITLE
Mismatch in custom categorical colour shown in left sidebar and main canvas

### ISSUE THREAD

**Issue by andr-kun** [chanzuckerberg/cellxgene#2007]
**Describe the bug**
There seems to be a mismatch in the custom (anndata specified) categorical colour shown in left sidebar and main canvas, with the custom colour shown on the left sidebar being offset by 1 (resulting in the first category having no colour). This seems to occur when the naming of the category starts with 1 rather than 0. 

**To Reproduce**
1. Run the updated [colourise_pbmc3k.py](https://gist.github.com/andr-kun/a42e635045df38c8822c576510d7723f) script on the pbmc3k.h5ad sample data to create 2 new categories - groupings0-9 and groupings1-10 - containing 10 groups which are randomly assigned to each cell, with the groups being numbered 0-9 and 1-10 respectively. The script will also assign the same set of pre-determined categorical colours for the two newly created categories.
2. Launch the cellxgene browser and use the groupings1-10 category as the colour scale. 
3. You should notice that the first category seems to have no colour assigned and the rest of the category are assigned the colour for the previous category (as correctly shown when using groupings0-9 category as the colour scale).

**Expected behavior**
The colour in the left sidebar should match the colour in the main canvas.

**Screenshots**
<img width="1680" alt="Screenshot 2020-12-17 at 19 17 04" src="https://user-images.githubusercontent.com/5274310/102532867-87104b80-409c-11eb-915c-cf6f295fd695.png">

**Version (please complete the following information):**
 - Desktop or hosted?: both
 - Browser (if hosted) [e.g. chrome, safari]: firefox, safari and chrome
 - Version [e.g. 0.13.0]: 0.16.6

**Additional context**
This bug seems to have been introduced after the bugfix for bug #1901, which fixed the ordering of the colour for categories with more than 10 groups. The older version of the cellxgene (0.16.2) does not seem to have this issue.

<img width="1680" alt="Screenshot 2020-12-17 at 19 21 29" src="https://user-images.githubusercontent.com/5274310/102533279-1ae21780-409d-11eb-8226-8de846e595c0.png">

**Comment by bkmartinjr** [comment]
The fix for #1901 (introduced by PR #1929) was incorrect and added the failure modes documented here.  Working on a fix.

**Comment by bkmartinjr** [comment]
@andr-kun - I am close to having a fix.  Would you like to review the PR before I land it?
