### ISSUE TITLE
Identify single value (continuous and categorical) fields during dataset curation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#2010]
@MDunitz commented on [Thu Oct 15 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/643)

## Need
- As a user I dont want to see histograms or placeholders for histograms for categories that only contain a single value. 

## Approach
To avoid needing to check all of the data on the frontend (which is slow and leads to the display of category names in the rsb that we wont create histograms for) we would like to identify continuous variables as categorical when they only contain a single value. This should be done when retrieving the schema (there should be no changes to the actual dataset)

---

@MDunitz commented on [Wed Oct 28 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/643#issuecomment-718322786)

Update from discussion with @maniarathi @mckinsel @seve @signechambers1 @colinmegill 
We will add a check when creating the schema in the data adaptor, if a continuous variable stores the same value for all of the cells it will be redefined as a categorical variable. 

This may require recreating the schemas for datasets already in hosted cellxgene

---

@mckinsel commented on [Thu Oct 29 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/643#issuecomment-718867536)

Wait I thought it was not going to require recreating schemas. You just stick in some logic around [here](https://github.com/chanzuckerberg/cellxgene/blob/main/server/data_cxg/cxg_adaptor.py#L373) that detects single-valued continuous variables (and similarly in the anndata adaptor).

---

@maniarathi commented on [Thu Oct 29 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/643#issuecomment-719072946)

+1 to what Marcus said -- there shouldn't be any recreating of schemas. The API response for get schema is the only thing that should change.

---

@MDunitz commented on [Thu Oct 29 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/643#issuecomment-719080110)

Sorry misunderstood, I updated the ticket description

**Comment by signechambers1** [comment]
@MDunitz @colinmegill @bkmartinjr @mckinsel I'm not seeing this issue in ~1/2 the datasets I checked in prod so this doesn't seem like a high priority to me. I recommend closing unless there is an eng reason to change this?

**Comment by brianraymor** [comment]
Closing per Signe's comment.
