### ISSUE TITLE
[BUG] leftside color code is not matching the layout

### ISSUE THREAD

**Issue by z5ouyang** [chanzuckerberg/cellxgene#2011]
**Describe the bug**
The color on the leftside is NOT matching the layout plot.

**To Reproduce**
1. cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad
2. Color code by "leiden"
3. Only select cluster '2'
4. The color on the left side is NOT matching the layout.

**Expected behavior**
The color code (legend) on the left side is matching the color in the layout

**Screenshots**
![image](https://user-images.githubusercontent.com/30639029/103120617-5ea0c800-462d-11eb-8ec9-7ca4492802e7.png)

**Version (please complete the following information):**
 - hosted
 - Browser chrome
 - Version [e.g. 0.13.0]:
 - Name: cellxgene
Version: 0.16.6
Summary: Web application for exploration of large scale scRNA-seq datasets
Home-page: https://github.com/chanzuckerberg/cellxgene
Author: Chan Zuckerberg Initiative
Author-email: cellxgene@chanzuckerberg.com
License: MIT
Location: /home/zouyang/anaconda3/envs/cellxgeneTest/lib/python3.8/site-packages
Requires: click, flatbuffers, Flask-Compress, Flask, pandas, fastobo, anndata, Flask-Cors, requests, tiledb, boto3, flask-server-timing, numpy, packaging, gunicorn, sqlalchemy, flask-talisman, numba, fsspec, flatten-dict, scipy, h5py, PyYAML, s3fs, Flask-RESTful

**Additional context**

**Comment by longfeili5170** [comment]
The same problem. But in my data set, all wrong colors are shown as gray.
<img width="537" alt="Screen Shot 2020-12-25 at 6 22 51 PM" src="https://user-images.githubusercontent.com/68364890/103132106-594f8600-46de-11eb-967c-e7bee7b3063c.png">
<img width="937" alt="Screen Shot 2020-12-25 at 6 23 34 PM" src="https://user-images.githubusercontent.com/68364890/103132113-59e81c80-46de-11eb-953f-94da6fda9aa7.png">

**Comment by maniarathi** [comment]
Thank you for the bug! We are taking a look at it!

**Comment by MDunitz** [comment]
@z5ouyang I'm having some trouble reproducing the bug. When I run through the steps you list the colors appear to match.
![Screen Shot 2021-01-14 at 14.42.51.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/15767ca7-41e4-40d9-b5de-bb15509c22de)

Could you run `pip freeze` and post the results here?

I also noticed you are running python 3.8. We've had some issues with that release in the past. Could you try running with python 3.7 and confirm that you are still seeing the problem?

**Comment by MDunitz** [comment]
I tried launching with python 3.8.7 and I'm still unable to reproduce the problem. Could you also tell me what version of chrome you are using?

**Comment by z5ouyang** [comment]
Hi MDunitz,
thanks for checking this out. You are correct about the browser version plays a role in this. 
1. I update the chrome to the latest "Version 87.0.4280.141 (Official Build) (x86_64)" on my mac, and the color is correct. 
2. I tried the Chrome version "87.0.4280.88" on my other mac, the color is NOT match. 
3. I tried the latest Chrome on Windows 10 Enterprise (build 17763.1637), the color is NOT match.
4. I tried the latest Chrome on Windows 10 Pro (build 19041.685) the color is correctly matched.

I did clear the cache.
I will do some investigate as well.

thanks again!
O'Young

**Comment by MDunitz** [comment]
Thank you! This is extremely helpful

**Comment by grst** [comment]
Same issue here, left is Firefox (84.0.2), right is Google Chrome (87.0.4280.141 (Official Build))

![image](https://user-images.githubusercontent.com/7051479/105191514-73428400-5b37-11eb-85ef-f164a05f7cc5.png)

cellxgene v0.16.6

**Comment by bkmartinjr** [comment]
Likely webgl-related front-end rendering issue.

**Comment by MDunitz** [comment]
@grst it looks like some people are reporting webgl issues with firefox 84.0.2 can you check that webgl is enabled and your video drivers are updated? https://www.interplaylearning.com/help/how-to-enable-webgl-in-firefox

**Comment by z5ouyang** [comment]
Just enabled webGL2.0 which was disabled for Chrome 87.0.4280.141 on Windows 10 Enterprise (build 17763.1637), and the color is still not match.
