### ISSUE TITLE
[QUESTION] how can i specify a port number for cellxgene?

### ISSUE THREAD

**Issue by chansigit** [chanzuckerberg/cellxgene#2017]
When using jupyter notebook, we often specify a port number like this: jupyter notebook --port=12345

how could we specify a port number when using cellxgene?

Thank you for your help.

**Comment by prete** [comment]
cellxgene has the same option to specify a port number:
`cellxgene launch data.h5ad --port=PORT_YOU_WANT`

**Comment by chansigit** [comment]
thank you
