### ISSUE TITLE
Separate local and hosted backends

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#2027]
One of our [technical objectives](https://docs.google.com/spreadsheets/d/10lCUkdXHRG101nIVwAdPOka5LfH72ravkpnQULgv65A/edit#gid=0&range=B34) for Q1 is to split the implementations for the local and hosted cellxgene backends. The two backends are pretty different and don't even share much code, so splitting them up should let us move faster and be clearer about what features are supported in each environment.

There are a few steps needed before that can be done:
1. We need to be clear about which features should be supported by each backend.
2. We need to update the [API definition](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/REST_API.md) to match reality so each backend can continue to support it.
3. Break the `server/` directory in two: one for local and one for hosted.
4. Do a round of pruning in each to simplify.
5. Make sure that pypi, setup.py, and local tests continue to work with the local backend and single-cell-infra and happy path continue to work with hosted.

**Comment by bkmartinjr** [comment]
this has been completed in recent PRs
