### ISSUE TITLE
Prevent layout thrash

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2030]
We use a good deal of API's listed [here](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

We could possibly see some easy performance boosts by switching out some of these instances for non-reflow API's

Notes:

https://kellegous.com/j/2013/01/26/layout-performance/

**Comment by maniarathi** [comment]
Likely a spike to see if this is something that we even need to worry about.

**Comment by seve** [comment]
After doing some digging with chrome dev tools, there doesn't appear to be any major layout thrash causing large compute times.  Closing the issue.
