### ISSUE TITLE
Document genesets REST API

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2047]
Waiting on Marcus' REST API spec

**Comment by bkmartinjr** [comment]
@signechambers1 - is this task for the entire REST API or just the gene set related additions?

**Comment by signechambers1** [comment]
@bkmartinjr oops sorry unclear, just clarified for gene sets. If you or @mckinsel think a more general REST API documentation would also be helpful feel free to make an additional ticket for that

**Comment by bkmartinjr** [comment]
this is done and published as a gdoc
