### ISSUE TITLE
consider migrating from OBO to JSON for ontology support 

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2054]
The CL folks suggest that we migrate from OBJ to JSON for ontology support as "OBO is a legacy format".  See comment in [cell-ontology#930](https://github.com/obophenotype/cell-ontology/issues/930#issuecomment-774650790)

If we could also move the CLI (local file) format to JSON, this would remove the `fastobo` dependency, which would be a win for overall simplicity.

This would include changing our default ontology from http://purl.obolibrary.org/obo/cl.obo to http://purl.obolibrary.org/obo/cl/cl-simple.json

@aopisco - do you have any opinion/concerns on migrating from OBO to JSON?

**Comment by signechambers1** [comment]
@bkmartinjr this seems like a good idea if the lift is relatively small and Angela has no concerns. Do you have an estimate for how long this might take?

**Comment by bkmartinjr** [comment]
~1 person*day

**Comment by brianraymor** [comment]
Closing per discussion with Bruce.
