### ISSUE TITLE
Gene sets doubles the effort for a user to color by an individual gene

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2059]
“Add gene” or similar search bar in the right side bar. A user can add a single gene and color by, plot on x or y, expand and brush on.

The single gene stays in the upper right side bar until another gene is added, the gene is cleared, or the session ends (ie the single gene is not persisted). 

Future: Gene can be added to a gene set w/o retyping the gene name, we discussed dragging or add button. I do not think this is something we need to incorporate for the desktop release (they can retype the gene name to add to a gene set if they want. We can add this and optimize the flow for hosted later.

final figma: https://www.figma.com/file/OmZwf8p1qa4nG32sbfOfc5/Add-Gene?node-id=58%3A27

Design Due Date: 6/11

**Comment by hthomas-czi** [comment]
@signechambers1 I can't update the issue itself but here's the [up-to-date Figma](https://www.figma.com/file/OmZwf8p1qa4nG32sbfOfc5/Add-Gene?node-id=58%3A27).

**Comment by signechambers1** [comment]
Thans @hthomas-czi I updated the description with the new figma link.
