### ISSUE TITLE
Separate user-specific schema elements from immutable dataset-specific elements

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#2060]
Right now, fields that can be changed by the user are commingled with fields that come from the immutable underlying dataset. It would be better if these were served separately or in a way the clearly distinguished between the two.

This will be less of an issue once user annotations are turned off on hosted cellxgene but may become an issue again with gene sets.

See the comment [here](https://github.com/chanzuckerberg/cellxgene/blob/main/server/app/app.py#L242)

**Comment by signechambers1** [comment]
Closing as a low priority, fyi @maniarathi if you want to reopen.
