### ISSUE TITLE
[QUESTION] Scanpy requirement

### ISSUE THREAD

**Issue by adamgayoso** [chanzuckerberg/cellxgene#2067]
Hi cellxgene team,

Is there a timeline on updating the scanpy/anndata requirements?

Thanks!

**Comment by MaximilianLombardo** [comment]
Hey Adam,

Thank you submitting your question and for using cellxgene!

With respect to updating scanpy/anndata requirements- we do not have a specific timeline in mind for updating those requirements. We had not seen an urgent need from the community and the upgrade requires that we also work to ensure compatibility with other dependencies that the newest version of scanpy/anndata depend on.

That being said, what was your motivation for requiring the latest versions of scanpy/anndata. Do they offer new versions with features that you feel would be useful?

**Comment by adamgayoso** [comment]
> That being said, what was your motivation for requiring the latest versions of scanpy/anndata. Do they offer new versions with features that you feel would be useful?

Well for example, 1.6 includes "seurat_v3" highly variable gene flavor, which would be a great addition to cellxgene prepare. Also the pinned version is almost one year old now, and it makes it difficult to use `cellxgene` without having a separate virtualenv.

**Comment by MaximilianLombardo** [comment]
I understand. I guess the current workaround would be to generate your anndata objects using a newer version of scanpy and they should still be compatible with cellxgene (and potentially forego using cellxgene prepare if you are interested in the latest functionality of scanpy). 

We definitely appreciate your feedback on needing separate environments.  There is however, some benefit to using them and we haven't heard of many issues with using environments and cellxgene (to date). We will continue to look for feedback on this subject.

**Comment by adamgayoso** [comment]
Is `cellxgene prepare` the only functionality of cellxgene that breaks? Based on your pinned requirements it seems like most issues have already been addressed if you set tighter lower bounds on versions.

**Comment by MaximilianLombardo** [comment]
Hey Adam,

No, anndata and (sometimes) scanpy (depending on which feature flags you enable) are both required for the launch subcommand, so there are effects beyond the prepare subcommand.
