### ISSUE TITLE
Remove H5AD support from hosted server

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2071]
**Why**: the hosted server does not need to support reading from H5AD anymore since the local server has been split out to be able to read from H5AD. We only store CXGs for the hosted server to read on the backend and that is the plan moving forward.

**Definition of Done**:
- Remove `AnndataAdaptor` class and its usages from `server`.
- Remove peripheral code as well, such as `diffexp_generic.py` that is related to processing anndata files.
- Delete tests accordingly.
- Fix the unit tests and smoke tests in `server` to use CXG test files instead of H5AD test files.
- Delete H5AD fixtures from the `server` test directory.

**Comment by MDunitz** [comment]
Duplicate
