### ISSUE TITLE
Document REST API specs

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2073]
**Why**: In order to ensure that we can develop both the hosted and local servers in parallel, sharing the same APIs since we have opted to share the frontend, we need to document the current REST API specs of the system and enforce that the local_server and hosted server both adhere to the same spec.

**Definition of Done**:
TBD. I think there is some discussion to be had about how to accomplish this. Arathi's idea is to use OpenAPI spec to help enforce the API spec as well as creating an abstract class that connects to the OpenAPI doc via `operationId` and is implemented independently by the two servers. Think there should be a meeting about this first.

**Comment by signechambers1** [comment]
@maniarathi closing this since rest API is documented [here](https://docs.google.com/document/d/12Wce-r2OvLGnuUWm9abAiZuj-kELz_LYTEvv6KZLXXo/edit#heading=h.wm3l0scc2cy5) but please reopen if there is more to do here.
