### ISSUE TITLE
feat: depreciate collection information in dataset drawer

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene#2085]
## Need
As we move forward with updating a collection in the data portal, the collection metadata in the CXG file will no longer be current. To avoid confusion, we will not display the collection information in dataset drawer.

## Approach
- Disable collection information in the dataset draw of cellxgene explorer

## Dod
- The dataset drawer of the Explorer no longer displays DOI links or other collection relation information.
- Single value categories found on the obs column should still be pulled out of the left sidebar and be shown in the dataset drawer

**Comment by brianraymor** [comment]
Product has decided to deprecate the entire dataset drawer. I will create a new issue for that purpose.
