### ISSUE TITLE
feature request: choose rep as basis for umap re-embedding

### ISSUE THREAD

**Issue by LisaSikkema** [chanzuckerberg/cellxgene#2091]
Hi,

I really like the recompute umap embedding in cellxgene. However, I'm using data that was integrated/batch-corrected (with scANVI, in our case), and so I want to generate a umap of my data based on the integrated embedding rather than on a PCA embedding.

scANVI outputs a low-dimensional embedding (e.g. of 30 dimensions), while not changing the count matrix. Therefore, if the umap re-embedding is based on a PCA of the count matrix, it undoes the integration. Would it be possible to add a choice of "rep" in the "recompute umap embedding" feature, that is passed to the `sc.pp.neighbors()` function, such that it does e.g. `sc.pp.neighbors(adata, use_rep="X_scanvi")` ? Then, instead of building the neighbor graph based on the PCA I can feed it the scanvi embedding.

Best,
Lisa

**Comment by signechambers1** [comment]
@LisaSikkema I'm sorry, we are no longer supporting the experimental reembedding feature. I'm closing this issue for now but we will take this into consideration if we support reembedding again in the future! Thank you for filing this issue.
