### ISSUE TITLE
[BUG] documentation incorrect on how to launch cellxgene

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2104]
**Describe the bug**
The "Launching Cellxgene" docs [here](https://chanzuckerberg.github.io/cellxgene/posts/launch) has an incorrect URL.

It says:
```
cellxgene launch https://github.com/chanzuckerberg/cellxgene/blob/main/example-dataset/pbmc3k.h5ad
```

it should say:
```
cellxgene launch https://github.com/chanzuckerberg/cellxgene/raw/main/example-dataset/pbmc3k.h5ad
```

The `raw` github URL will return the H5AD.  The `blob` URL returns an HTML page.

**Comment by signechambers1** [comment]
@MaximilianLombardo same question here, can you fix this in your new version of the docs?

**Comment by brianraymor** [comment]
This appears to be correct in the [new site](https://docs.cellxgene.cziscience.com/desktop/launch). @signechambers1 - can this be closed? 

`cellxgene launch https://github.com/chanzuckerberg/cellxgene/raw/main/example-dataset/pbmc3k.h5ad

**Comment by signechambers1** [comment]
Yes, closing.
