### ISSUE TITLE
[BUG] Documentation outdated for building and installing locally

### ISSUE THREAD

**Issue by wflynny** [chanzuckerberg/cellxgene#2113]
**Describe the bug**
Following the documentation [here](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/developer_guidelines.md), running `make build-for-server-dev && make install-dev` and launching cellxgene results in a broken build (missing Jinja2 templates).  The correct build commands are
```
make build-for-server-dev-local && make install-dev
```
as described in [this slack thread](https://cziscience.slack.com/archives/CCTA8DF1T/p1616081710016400?thread_ts=1615991780.003900&cid=CCTA8DF1T). 

**To Reproduce**
1. On a system wtih docker and node installed, clone the repo.
2. From the project root, `make dev-env`.
3. Make any changes to the source.
4. From project root, `make build-for-server-dev && make install-dev`
5. Launch cellxgene, e.g. `$(which cellxgene) launch path/to/data.h5ad --port 8000 --host $(hostname -i) --disable-annotations`
6. Open `$(hostname -i):8000` in the browser and get a 500 error in the browser and Jinja2 missing template tracebacks.

**Version (please complete the following information):**
 - Desktop or hosted?: Local server (VM)
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: 0.16.7 (current master)

**Comment by signechambers1** [comment]
@MaximilianLombardo would you mind reproducing and letting me know if you run into this as well?

**Comment by MaximilianLombardo** [comment]
Hey yes - I was able to reproduce and fix with the proposed change above - I think the documentation got out of sync after the refactor (splitting local backend + hosted backend)

**Comment by MaximilianLombardo** [comment]
@signechambers1  I think this section of the dev docs may also need to be updated (not 100% sure) because of the split: [reloading](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/developer_guidelines.md#reloading)

**Comment by signechambers1** [comment]
@MaximilianLombardo can we fix this in the latest version of your new docs?

**Comment by maniarathi** [comment]
@signechambers1 I think this issue may no longer be relevant since we removed the hosted code and so the command reverted back to the original.

**Comment by MaximilianLombardo** [comment]
Is this issue ok to be closed then?
