### ISSUE TITLE
Verify CXG conversion works for certain datasets

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2142]
Link to Collection with errored dataset: https://cellxgene.cziscience.com/collections/60358420-6055-411d-ba4f-e8ac80682a2e/private

Logs link: https://us-west-2.console.aws.amazon.com/batch/v2/home?region=us-west-2#jobs/detail/8e7ff995-3b20-48e5-83a1-8247873ff414

Stack trace:
```
File "/usr/local/lib/python3.8/dist-packages/backend/czi_hosted/common/utils/cxg_generation_utils.py", line 75, in convert_dataframe_to_cxg_array
array[:] = value\n  File "tiledb/libtiledb.pyx", line 4885, in tiledb.libtiledb.DenseArrayImpl.__setitem__
File "tiledb/libtiledb.pyx", line 415, in tiledb.libtiledb._write_array
File "tiledb/libtiledb.pyx", line 479, in tiledb.libtiledb._raise_ctx_err
File "tiledb/libtiledb.pyx", line 464, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::IO] Error: Cannot open file \'/local.cxg/obs/__1617759016805_1617759016805_a11917d04be346c2a937ba82cbd16ae8_6/BEST4/OTOP2 Cells.tdb\'; No such file or directory
```

TEAM COMMENTS:
* Old tileDB version didn't process slashes correctly.
* tileDB just put out 0.19, which fixes this issue. Other tickets in this epic upgrade the version, this ticket is to verify that it worked for this dataset.
* In scope: add a test with a slash in the observation, make sure it uploads successfully.

**Comment by maniarathi** [comment]
The issue is that some of the obs columns in that dataset have "forbidden" characters in them. For example the problematic one above is "BEST4/OTOP2 Cells". 

We should be doing sanitization of the column names but Arathi forgot to add back the sanitization code when she refactored the CXG conversion tool back last August. This should be added back in.

Faulty PR: https://github.com/chanzuckerberg/cellxgene/pull/1701/files

**Comment by maniarathi** [comment]
Quick update.. I was about to fix my bug but I noticed that the issue that we filed with tileDB got tagged for release 10 days ago so hoping that we can remove our internal sanitization code and instead upgrade to tileDB 0.9. 

Thread here: https://chanzuckerbergteam.slack.com/archives/C013K0JB8F8/p1617855347006400

**Comment by maniarathi** [comment]
Max was able to change the name of the column manually and upload the dataset. Given that the tileDB version bump is upcoming, moving this to Disorder for now as a low priority bug. If we have time, we can address it, but otherwise, wait for a release and then close this issue.

**Comment by brianraymor** [comment]
The UCSC curator [reported a similar failure](https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1620928817362000). Again, this is being manually corrected with the assistance of @MaximilianLombardo.

**Comment by maesen** [comment]
@leslieypark @metakuni @seve Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/2142?planning-poker)

**Comment by maesen** [comment]
@MDunitz @tihuan @danieljhegeman @blrnw3 Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/2142?planning-poker)

**Comment by maesen** [comment]
@maniarathi Please migrate to the new repo

**Comment by metakuni** [comment]
Having trouble reproducing the bug, so switching to #1243 to get this week's release out and will circle back to this story later.

**Comment by metakuni** [comment]
_Finally_ managed to reproduce the error using repro test script from https://github.com/TileDB-Inc/TileDB-Py/issues/294.

The test seems to fail only for tiledb versions <0.8.1. tiledb 0.8.1+ appears to work fine, so perhaps the fixed version quoted in the [bug comment](https://github.com/TileDB-Inc/TileDB-Py/issues/294#issuecomment-869813372) was incorrect.

**Comment by nguyenv** [comment]
Hi @metakuni, I was able to reproduce your findings. It looks like this was in fact initially supported by [this PR](https://github.com/TileDB-Inc/TileDB/pull/2047) in TileDB Embedded 2.2.
