### ISSUE TITLE
[FEATURE REQUEST] Tutorial deploy on Heroku website

### ISSUE THREAD

**Issue by sinnamone** [chanzuckerberg/cellxgene#2151]
Hi,

I'd like to share the cell-explorer with some collaborator, I'm not expert of website deploying. 

Could you release a tutorial or video-tutorial with friendly steps in order to use Heroku to deploy cellxgene?

Best regards,

Simone

**Comment by MaximilianLombardo** [comment]
Hey Simone!

Thanks for using cellxgene!

You can find a tutorial for self-hosting cellxgene with heroku [here](https://chanzuckerberg.github.io/cellxgene/posts/hosted).

Let me know if you have any more questions!

Max

**Comment by sinnamone** [comment]
Hi Maximilian,

thank you I will follow the instructions. 

Thanks

**Comment by kishansripada** [comment]
Is there still a tutorial on how to self-host? The link is broken
