### ISSUE TITLE
Update `husky` package (+ frontend package bump)

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2170]
Please update the `husky` package to the latest/greatest version. Please also bump up other frontend packages to the latest/greatest if addressing a security vulnerability or addresses some sort of instability issue only.

~We have webpack major bump. Try to center the package updates around that. Ask @seve for help :)~

**Comment by MDunitz** [comment]
Alternative approach
- remove husky
- port over pre commit linting from data portal
