### ISSUE TITLE
[Explorer] update czi_hosted python package requirements

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2171]
czi_hosted requirements should be updated to require latest/greatest packages where possible (ie, where we do not have an incompatibility).

Note: there is a separate ticket for desktop variant (#2163), which does not want to be pinned to latest.

**Comment by maniarathi** [comment]
Make sure we pin all requirements so that we don't accidentally break due to unexpected package updates.

**Comment by MDunitz** [comment]
See ways of working in single-cell repo for more details
Pin in single-cell-infra
in explorer repo we want the latest to be warned if something will break

**Comment by maniarathi** [comment]
Closing as no longer relevant.
