### ISSUE TITLE
Update backend routes to support differential expression returning two lists of differentially expressed genes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2179]
### Need

We want to be able to show two gene sets in the front end, one with top differentially expressed genes upregulated in group A and one with top differentially expressed genes upregulated in group B. We can determine these groups by the sign on log fold change, and then sorting by p-value. In other words, return both the 25 genes with the smallest p-values and positive log fold change, and 25 genes with the smallest p-values and negative log fold change.

### Approach

Today, we:
1. compute the t-statistic and other metrics
2. sort genes by the absolute value of that t-stat
3. grab the "top N"
4. put them in a poorly designed JSON response. It is just a flat array, which makes it super hard to debug

Instead, what we should do:
1. same, no change
2. sort genes by the actual value of that t-stat
3. grab the "top N" and "bottom N"
4. return both top N and bottom N in an improved JSON object, which is just easier to understand (ie, isn't a flat array)

Add a temporary mode switch so that the frontend can either choose to receive one or two.
Please also enable this for both hosted and desktop server implementations.

~There will also be a small amount of frontend work required to shape the response into the reducer into a format that Colin's current code understands (i.e. fakes the creation of the merged old-style data structure too).~ This work will be completed in #2180.

**Comment by maniarathi** [comment]
Instructions to implement the backend:

Today, we:
1. compute the t-statistic and other metrics
2. sort genes by the absolute value of that t-stat
3. grab the "top N"
4. put them in a poorly designed JSON response. It is just a flat array, which makes it super hard to debug

Instead, what we should do:
1. same, no change
2. sort genes by the **actual** value of that t-stat
3. grab the "top N" and "bottom N"
4. return both top N and bottom N  in an improved JSON object, which is just easier to understand (ie, isn't a flat array)

There will also be a small amount of frontend work required to shape the response into the reducer into a format that Colin's current code understands (i.e. fakes the creation of the merged old-style data structure too).

**Comment by maniarathi** [comment]
Hey @MDunitz -- I am assigning you this ticket. We'd like for this to complete before June 1st so if we end up finish up the sprint early, would you be able to take this on please? If not, I will help make time for it in the next sprint.

**Comment by maniarathi** [comment]
Add a temporary mode switch so that the frontend can either choose to receive one or two.
