### ISSUE TITLE
Diffexp returns two gene sets in the front end

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2180]
### Need

We want to be able to show two gene sets in the front end, one with top differentially expressed genes up-regulated in group A and one with top differentially expressed genes up-regulated in group B. We can determine these groups by the sign on log fold change, and then sorting by test statistic. 

### Approach

Dependent on #2179 completing, or agreement on API interface. Changes will be required in the reducer to accommodate the new data structure.

**Comment by bkmartinjr** [comment]
we currently sort by the test statistic, not the p-val.  Can you confirm this change?  and do you want the p-val or the adjusted p-val?
