### ISSUE TITLE
[BUG] ImportError when running latest version

### ISSUE THREAD

**Issue by rl1987** [chanzuckerberg/cellxgene#2197]
**Describe the bug**

Cellxgene crashes on startup.

**To Reproduce**
1. `pip3 install cellxgene`
2. `cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad`

**Expected behavior**

Cellxgene should not crash.

**Error log**

```
$ cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad

Traceback (most recent call last):
  File "/usr/local/bin/cellxgene", line 5, in <module>
    from server.cli.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/server/cli/cli.py", line 4, in <module>
    from .launch import launch
  File "/usr/local/lib/python3.8/dist-packages/server/cli/launch.py", line 12, in <module>
    from server.app.app import Server
  File "/usr/local/lib/python3.8/dist-packages/server/app/app.py", line 20, in <module>
    from flask_restful import Api, Resource
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 14, in <module>
    from flask.helpers import _endpoint_from_view_func
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/usr/local/lib/python3.8/dist-packages/flask/helpers.py)
```

**Version (please complete the following information):**
 - Version [e.g. 0.13.0]: 0.16.7

**Additional context**

As official Dockerfile depends on pulling cellxgene through PIP, the same error happens inside Docker/Kubernetes deployments.

**Comment by MaximilianLombardo** [comment]
Hey thank you for using cellxgene and for your question. 

We had a couple other users who had the same problem (find the discussion [here](https://chanzuckerbergteam.slack.com/archives/CCTA8DF1T/p1620778370038500)) and it appears to be because a couple of cellxgene's dependencies had major releases yesterday. We are still looking at the issue, but could you try installing these specific versions of your dependencies: 

`pip install -U flask==1.1.2 flatbuffers==1.12`

Let me know if this solves your problem!

**Comment by Fougere87** [comment]
Had the same issue, your tip worked for me !

**Comment by rl1987** [comment]
Yes that works outside Docker container. Can we adjust Dockerfile to include that command for time (until a better fix is available)?

**Comment by MaximilianLombardo** [comment]
Great @Fougere87!

@rl1987 which dockerfile are you referring to? We are working on a fix and should have a patch released early next week. In the meantime I am updating the readme to alert people to this issue - thank you everyone for surfacing this issue :)

**Comment by rl1987** [comment]
For Dockerfile change I am proposing see: https://github.com/chanzuckerberg/cellxgene/pull/2203

**Comment by MaximilianLombardo** [comment]
Hi all, this issue has been fixed with the latest release, closing this issue
