### ISSUE TITLE
gene expression count returning unexpected cell name

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#22]
on the t. muris end point, the single gene expression count request is returning a cell that was not present in the original /cells response.

See command line example below. There are 2446 of these "new" cell names returned by a POST to /expression, of which P3.D042103.3_11_M.1 is but one example.

```
# curl -s -d '{"genelist":["Anxa5"]}'  -H "Content-Type: application/json" -X POST http://tabulamuris.cxg.czi.technology/api/v0.1/expression | grep P3.D042103.3_11_M.1
        "cellname": "P3.D042103.3_11_M.1",
# curl -s http://tabulamuris.cxg.czi.technology/api/v0.1/cells | grep P3.D042103.3_11_M.1
#
```

Note: added code to the front-end to defend against this:  see `src/actions/index.js:cleanupExpressionResponse()`

**Comment by csweaver** [comment]
I'm going to keep this one, since it seems like it is likely to rise agian with the EM2 engine.

**Comment by bkmartinjr** [comment]
No need to fix - this backend will be obsolete shortly.

**Comment by bkmartinjr** [comment]
obsolete - closing
