### ISSUE TITLE
Incorrect version number assigned to cellxgene deployment

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2212]
The current staging and dev versions of cellxgene SAAS deployment don't show the correct version number of cellxgene -- they show 0.16.7 instead of the commit revision. This has something to do with Python package imports:

- In `backend/common/utils/utils.py` the function `import_plugins` is used to import the plugins that are injected by the cellxgene deploy script in `single-cell-infra`. It is fed the input of `backend.czi_hosted.plugins` and ends up with a ModuleNotFound error instead of actually importing the modules.
- The above function is called by `backend/czi_hosted/__init__.py`. This is also where the default is set to be 0.16.7 so when the call to `import_plugins` fails (i.e. returns nothing), the defaults become the value that is displayed. This is maybe where the fix could be. Perhaps something other than `backend.czi_hosted.plugins` should be the input.
- It _could_ be possible that there is some weird circular dependency thing happening as well. Just to note it down, we create the plugin file to override the version value in `single-cell-infra/terraform/modules/hosted-cellxgene/deploy` lines 186-187. Fix could potentially be here as well.

**Comment by maniarathi** [comment]
This will probably be easier to implement later in Q3. We could consider removing displaying the version number from the czi-hosted deployment and instead returns the SHA via an API or the like.

**Comment by signechambers1** [comment]
@maniarathi is this still a priority? Maybe to add to the Cool Down epic for this year?

**Comment by maniarathi** [comment]
This is not a problem anymore, so closing.
