### ISSUE TITLE
Update Data Adaptor to use metadata api endpoint

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#2234]
## Need
A way to connect the explorer url (`https://cellxgene.staging.single-cell.czi.technology/e/8b9068e6-0dc9-465e-9e7a-acd6ed49a39b.cxg/`) to identifying information (dataset_id, collection_id, tombstone status and s3_uri) stored in the data portal

## Approach
Use the data adaptor class to call the meta endpoint with the explorer url and then store the dataset/location in the MatrixDataCache. 

In the case where there is no information stored about the dataset in the data portal the DataAdaptor should fall back to building the data location  from the url as it currently does

## DOD
Changes to where a dataset is stored in s3 (for revisions) does not force a change to the explorer url. Links are permanent but it is possible to edit the underlying dataset without copying over the original s3_uri

**Comment by maniarathi** [comment]
@MDunitz to add status update.

**Comment by tihuan** [comment]
@MDunitz update please! Thank you :D

**Comment by MDunitz** [comment]
@bkmartinjr and I determined that this work requires creating a new cache to store the dataset metadata in (to avoid repeated api calls to the data portal). To cleanly create the cache I am working on refactoring the existing MatrixDataLoader cache to make in generalizable and updating the relevant tests. Currently the refactoring work is done, I'm just working on cleaning up the code a little bit and getting the tests to pass. There is currently a bug with the test config set up code that is causing 50 tests to fail. I am working on determining the root cause.

**Comment by MDunitz** [comment]
Down to 4 failing tests. Hoping to have a pr out for @maniarathi to review by the end of the day.
@maniarathi and I discussed the review approach (due to the time constraint/Bruce being ooo). She is going to do an initial review and we will plan on doing a post merge review with Bruce when he gets back.

**Comment by MDunitz** [comment]
Update 8/5
I found the root cause of the failing tests! I was storing the dataset cache with its location as the key. And the location cache with the explorer url as the key. BUT we store the dataset config info on the dataset cache object. So when it was assigning multiple configs to one dataset the cache was getting written once based on the location so whatever was set/accessed first was just what it was.

This normally wouldnt be an issue but we reuse the same dataset over and over in the tests so weird race conditions were showing up.

Should be ready for review by EOD

**Comment by tihuan** [comment]
@ebezzi will help deploy this to staging for QA @MDunitz will help!

**Comment by tihuan** [comment]
@atolopko-czi and @danieljhegeman will shadow

**Comment by tihuan** [comment]
@MDunitz is this ticket ready for QA now? Looking at the [commit history](https://github.com/chanzuckerberg/single-cell-explorer/commits/main) it seems to be ready?

https://github.com/chanzuckerberg/single-cell-explorer/pull/3

Thank you!

**Comment by tihuan** [comment]
^ @brianraymor this is QA ready! Thank you!
