### ISSUE TITLE
Remove cookie banner from Portal and Explorer

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2235]
- Remove cookie banner from Portal, Explorer, and original cellxgene repo
- Also update Datadog to remove the step of "clicking on the cookie banner" on the tests.
- Some smoketests will need to be deleted.

**Comment by atolopko-czi** [comment]
we should move this issue to single-cell-data-portal, correct?

**Comment by tihuan** [comment]
Oh great catch, @atolopko-czi !

Hmm this one is tricky, since it spans three repos 😆 

Not sure which repo we use to capture cross repo work 🤔

CC: @maesen @brianraymor 

Thank you!

**Comment by tihuan** [comment]
Also do we need to update Terms of Service and Privacy pages now that we're removing the cookie banner? Thanks!

CC: @brianraymor

**Comment by brianraymor** [comment]
Good question. This change should have no impact on the Terms of Service only the Privacy Policy?

We had approval from Shawn to move to plausible.io but did not receive an updated privacy policy. Let me see if they've already done this for napari.

**Comment by brianraymor** [comment]
> Hmm this one is tricky, since it spans three repos 😆
> 
> Not sure which repo we use to capture cross repo work 🤔


It should be modeled as an epic in single-cell with child Dev issues from each repo.

**Comment by tihuan** [comment]
Ahh that makes sense! Thanks so much, Brian 🚀!

**Comment by tihuan** [comment]
NOTE TO SELF: Update Datadog once deployed to prod

> Also update Datadog to remove the step of "clicking on the cookie banner" on the tests.

**Comment by tihuan** [comment]
DP: Done! No more cookie banner in prod
Explorer: Staging no cookie banner, not deployed to prod yet
