### ISSUE TITLE
Create a script to manually move large datasets to correct S3 bucket and update database to override failed conversion statuses

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2242]
### Definition of Done

Modify the cxg_admin CLI script to manually move large datasets to correct S3 bucket and update database to override failed conversion statuses and update the correct s3_uri values to point to the S3 object locations.

TODO: have a conversation with Pablo to see if he can use an EC2 instance in the prod account which will allow him to upload the dataset to prod S3. Otherwise this issue becomes harder because we need to transfer the datasets between the dev and prod accounts.

Once this is done, there are two high priority datasets to transfer (check in with Pablo).

**Comment by brianraymor** [comment]
Closing per conversation with @maniarathi ...
