### ISSUE TITLE
accommodate tiledb 0.9

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2248]
tiledb 0.9 was just released and triggers some failures backend/czi_hosted unit test.  As a temporary workaround, #2241 pins the dependency to <0.9.

this pin needs to be removed once we fix the unit test and whatever incompatibility it is tripping over...

CC: @maniarathi

**Comment by MDunitz** [comment]
This is also captured in [ticket 1212](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1212)

**Comment by maniarathi** [comment]
Closing as PR #2249 fixes the failing tests.
