### ISSUE TITLE
Upgrade cellxgene czi-hosted's tiledb version to be >= 0.9

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2251]
## Need

In order to support tiledb 0.9 which has native handling of special characters, we need the hosted cellxgene to be on the latest version of tiledb as well. The Portal will be upgrade to convert to CXG using tiledb 0.9 but this means that Explorer also needs to be on the latest as well (i.e. a CXG that is created using tiledb 0.9 cannot be read on an Explorer deployment on tiledb say 0.8).

## Definition of Done

- [x] `backend/czi_hosted/requirements.txt` is updated to pin tiledb>=0.9.
- [x] Work on #1212 at the same time as this issue.

**Comment by maniarathi** [comment]
Do #1212 at the same time.

**Comment by metakuni** [comment]
For 'definition of done', checking off `Work on #1212 at the same time as this issue.` since that PR has already been merged.

**Comment by metakuni** [comment]
Moving this back into in-progress to try the [workaround suggested by TileDB](https://czi-sci.slack.com/archives/C013K0JB8F8/p1631314319012700).

If TileDB won't have a fix imminent (i.e. this week) and this workaround doesn't incur any substantial performance degradation, we may be able to release.

**Comment by metakuni** [comment]
Also, going to upgrade to TileDB-Py 0.10.0 instead of 0.9.5.
