### ISSUE TITLE
how to rename the cell annotation using  lasso tool to select the cell that i want to rename  

### ISSUE THREAD

**Issue by honghh2018** [chanzuckerberg/cellxgene#2252]
Hi, 
    Thanks to develop the great tools.
     In my case, i want to use the cellxgene to adjust the cell annotation that some barcode that i want to rename it, so how to do this?
    Any advices would be appreciated.
Best,
Hanhuihong

**Comment by MaximilianLombardo** [comment]
Hey Alec,

If i understand your question correctly, you cannot change how the cells are named in cellxgene, but you can create custom annotations of groups of cells like this: https://chanzuckerberg.github.io/cellxgene/posts/annotations

**Comment by signechambers1** [comment]
Hi @honghh2018 !

I'm closing this issue now but please reach out if you have any additional questions!
