### ISSUE TITLE
decide on and test demo datasets

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#227]
likely: PBMC, T. Muris, scanpy "big" demo set, 10X neuron, ?

**Comment by bkmartinjr** [comment]
Also need to move all of the test data sets to a location that has public read-only access (so other people can pull and demo them)

**Comment by fionagriffin** [comment]
I will create an S3 bucket and add them there once we have validated the science across cellxgene and my pre-processing plots.

**Comment by bkmartinjr** [comment]
@fionagriffin - can this be closed, or is there additional review required?  (the 1.3M 10X dataset worked great!)

**Comment by fionagriffin** [comment]
I think we are all good now that the 1.3M dataset is up. Will move on!
