### ISSUE TITLE
UI feature validation by subject matter expert on a single platform

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#228]
End-to-end UI feature validation by subject-matter expert (eg, Sidney), on a single platform.  
- [ ] testing done

**Comment by fionagriffin** [comment]
@freeman-lab Would Genevieve be interested in/ available to do this?

**Comment by bkmartinjr** [comment]
This needs to be higher priority - we should execute it as soon as we have feature/UX freeze, ahead of stability & perf work.   

@freeman-lab - need your team to have someone do this relatively soon.

**Comment by fionagriffin** [comment]
I am planning on Ambrose doing a second UI review, using 2 different datasets (T muris and immune). Once he has scientifically validated them in cellxgene I will post them to the main repo as demos.
