### ISSUE TITLE
Remove support for --experimental-reembedding on desktop

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2286]
Remove support for --experimental-reembedding on desktop

**Comment by bkmartinjr** [comment]
@signechambers1 - do you want to _retain_ this on the czi hosted platform, and only remove on desktop?  Or remote entirely?

**Comment by bkmartinjr** [comment]
CC @MaximilianLombardo - FYI, in case you need to remove from pending documentation improvements.

**Comment by signechambers1** [comment]
@MDunitz and I discussed removing reembedding functionality entirely since it would take additional work to support reembedding on hosted and thats at least 12-18 months out as it is not currently prioritized on the roadmap.
