### ISSUE TITLE
Migrate cellxgene to Typescript

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2288]
Per the plan outlined [here](https://docs.google.com/document/d/1zN-x6LxA3krR-PiOO_OFuIwKOOWLGcEb-ChjkTpsg1c/edit#heading=h.44vqg821e4b5), migrate the cellxgene frontend code to Typescript.

**Comment by tihuan** [comment]
@MillenniumFalconMechanic maybe we can close this now? Thank you!

**Comment by tihuan** [comment]
Changing this to closed, since it's been migrated 👌
