### ISSUE TITLE
Selection on gene or gene set histograms not working in 0.17.0

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/cellxgene#2291]
**The performance issue**
On the Azimuth dataset, which has approximately 1 million cells and 77,000 genes, the following two use cases do not work: 

1. I can brush over the mean expression of a gene set to select a range of expression values
2. I can brush over an individual gene to select a range of expression values

Brushing over the quantitative metadata, which have been moved to the left sidebar, **does** work. 

**To Reproduce**
1. Download the [azimuth dataset](https://cellxgene.cziscience.com/collections/2f75d249-1bec-459b-bf2b-b86221097ced)
2. Download the [hallmark.csv](https://czi-sci.slack.com/archives/C02450V6L59/p1625709669042500) file containing hallmark gene sets in cellxgene format. 
3. `cellxgene launch local.h5ad --gene-sets-file hallmark.csv`
4. Expand `HALLMARK_IL6_JAK_STAT3_SIGNALING` 
5. Attempt to color by the average
6. Expand a gene within the gene set
7. Attempt to color by the gene

**Version (please complete the following information):**
 - Desktop
 - Version 0.17.0

**Comment by bkmartinjr** [comment]
See also #2309
