### ISSUE TITLE
Improve --max-category-items functionality

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2296]
Proposed refinement to the max-category issues for near term.

Background:  if a metadata category has to many values (in Anndata terms, `len(adata.obs['cat_name'].dtype.categories)`), the front-end rendering will be very slow and/or fail completely.  Typically, hundreds of values are fine, and failure can occur on some platforms over a thousand.  The current UI preferentially displays categories that are the most used (ie, highest frequency), and _hides_ the remainder.  

There are currently two issues:
* #2225 - a regression.  The CLI config no longer controls the front-end behavior, ie, the CLI argument `--max-category-value` has no effect.
* The front-end _hides_ category values beyond the number allowed by `--max-category-value`, making the cells inaccessible in certain parts of the UI (eg, you can't select/deselect them in that category).

Proposed changes:
* fix the regression reported in #2225 so the user can control the cut-off value for maximum categories to display
* modify the front-end behavior.  Rather than hiding the excess category values (above and beyond the maximum), it will _consolidate_ these multiple categories into a single "overflow" category.  This will provide the user with the standard UI - eg, the number of cells in the overflow will be summarized, the overflow cells as a group can be selected/deselected, etc.

This resolves a very confusing part of the UI, while still retaining performance in the edge case where a category has an excessively large cardinality.

Concrete example, using Pandas API for short-hand, using the standard test dataset `pbmc3k`:
```
In [5]: ad.obs['louvain'].value_counts()
Out[5]: 
CD4 T cells          1144
CD14+ Monocytes       480
B cells               342
CD8 T cells           316
NK cells              154
FCGR3A+ Monocytes     150
Dendritic cells        37
Megakaryocytes         15
Name: louvain, dtype: int64
```

If `--max-category-items` is set to a value of 5, then the UI would display the top 5 category values, PLUS an overflow category that contained the cells labelled with  the remaining 3 category values (`Dendritic cells`, `FCGR3A+ Monocytes` and `Megakaryocytes`).  In other words, the LSB `louvain` category would contain the following:
* CD4 T cells [1144]
* CD14+ Monocytes [480]
* B cells [342]
* CD8 T cells [316]
* NK cells [154]
* Other [202]

(note: the name for the `Other` aka overflow category value is TBD).

**Comment by bkmartinjr** [comment]
@signechambers1 - did you intend that this change only occur in the desktop (pip installable) variant? Or did you want the change made to the front-end generally, for all deployments?
