### ISSUE TITLE
Support python 3.9 in the desktop

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2299]
* [ ] Python 3.9 support
* [ ] Add to compatibility matrix in Github workflow

**Comment by MDunitz** [comment]
Bruce has investigated and thinks this should be straightforward 
(if we bump up package dependencies to not support older versions of anndata)

**Comment by bkmartinjr** [comment]
Partial fixes have been added to #2318

**Comment by maniarathi** [comment]
Dupe of #2410.
