### ISSUE TITLE
Back-end compatibility smoke tests

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#230]
Back-end platform test: build, install, run on test data set
* [ ] Write [test plan](https://github.com/chanzuckerberg/cellxgene/wiki/Release-Validation-Recipe#backend-test)
* [ ] test: MacOS, Mojave
* [ ] test: Win10 latest using WSL/Ubuntu 16.04

**Comment by bkmartinjr** [comment]
@csweaver - I think this is obsolete.  Any concerns if I close?
