### ISSUE TITLE
[BUG] support float64 .X for cell selection from gene expression histogram.

### ISSUE THREAD

**Issue by Jon-bioinfo** [chanzuckerberg/cellxgene#2309]
Copying the comment I made [here](https://github.com/chanzuckerberg/cellxgene/issues/2303#issuecomment-883095375) as a fresh issue.

Using the demo data at https://cellxgene-example-data.czi.technology/pbmc3k.h5ad if I run
```
import scanpy as sc
import numpy as np
import scipy
adata = sc.read('pbmc3k.h5ad')
adata.X = scipy.sparse.csr_matrix(adata.X, dtype=np.float32)
adata.write('pbmc3k_32.h5ad')

adata = sc.read('pbmc3k.h5ad')
adata.X = scipy.sparse.csr_matrix(adata.X, dtype=np.float64)
adata.write('pbmc3k_64.h5ad')
```

Then the highlighting and selection as a group of cells by selecting a region of the gene expression histogram only works for pbmc3k_32.h5ad in cellxgene v0.17.0

This is a problem because h5ad files produced by [SeuratDisk](https://mojaveazure.github.io/seurat-disk/) seem to use float.64

Which is probably also the cause of https://github.com/chanzuckerberg/cellxgene/issues/2291 since the Azimuth data h5ad file was likely produced with SeuratDisk and this file looks like:
```
adata = sc.read('local.h5ad')
adata.X
<982538x77521 sparse matrix of type '<class 'numpy.float64'>'
	with 1748651019 stored elements in Compressed Sparse Row format>
```

**Screenshots**
<img width="484" alt="Screen Shot 2021-07-20 at 23 06 49" src="https://user-images.githubusercontent.com/40158588/126338506-95b1fdf0-a668-4114-abf9-f2ac34d7a5a0.png">

**Expected behavior**
cellxgene supports this function for float64 .X matrix

**Comment by bkmartinjr** [comment]
@Jon-bioinfo - thanks for the issue.

Could you take a look at the Browser console and report any error messages you see there?

FYI, I am able to reproduce, and the console shows:

```
Warning - unknown metadata schema (float64) for field X 1278.
_getObsDimensionParams @ crossfilter.js:279
crossfilter.js:247 Uncaught (in promise) TypeError: o is not iterable (cannot read property undefined)
    at AM._addObsCrossfilterDimension (crossfilter.js:247)
    at crossfilter.js:166
    at Generator.next (<anonymous>)
    at Cr (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
```

Likely scenario: the back-end is failing to down-cast to float32 correctly (the front-end _only_ accepts float32).

**Comment by Jon-bioinfo** [comment]
I see the same error.
```
crossfilter.js:279 Warning - unknown metadata schema (float64) for field X 1480.
crossfilter.js:247 Uncaught (in promise) TypeError: o is not iterable (cannot read property undefined)
    at AM._addObsCrossfilterDimension (crossfilter.js:247)
    at crossfilter.js:166
    at Generator.next (<anonymous>)
    at Cr (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
```

**Comment by bkmartinjr** [comment]
FYI, there is some bogus code in the AnnData adaptor, inside get_schema_type_hint_from_dtype():
```
    if dtype_kind == "f" and not can_cast_to_float32(dtype, array_values):
        return {"type": "float64"}
```
Not sure when / how this was added, but it is incorrect.

**Comment by bkmartinjr** [comment]
See also #2291

**Comment by bkmartinjr** [comment]
Related (source of regression): #1779 #1782

When fixing this, need:
* 64 bit (X and obs) H5AD test cases
* validate that it does not regress #1779
