### ISSUE TITLE
Front-end compatibility smoke tests

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#231]
Front-end compatibility smoke tests:
- [X] Write [test plan](https://github.com/chanzuckerberg/cellxgene/wiki/Release-Validation-Recipe#frontend-compatibility-test)
- [ ] test: Firefox, latest version, Win10
- [ ] test: Chrome, latest version, Mac
- [ ] test: Chrome, latest version, Win10

**Comment by bkmartinjr** [comment]
reassign to @csweaver who is working on a f/e test framework that we can use for this.

**Comment by csweaver** [comment]
fixed
