### ISSUE TITLE
Remove unused code from desktop application

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/cellxgene#2310]
## Need
To remove unused code from the desktop application

## Approach
- [x] remove cxg support
~- [ ] remove multidataset support (and update config to remove as option)~ @signechambers1 will check if this can be removed
- [x] remove dead code (schema)
~- [ ] remove oauth support~ Dupe of #2311
- [x] remove unused dependencies
- [x] remove utils module
- [x] update and remove affected tests
~- [ ] remove compatibility tests~

## DOD
- there is no dead code in the cellxgene repo.

**Comment by MDunitz** [comment]
Recommend splitting this into multiple prs (suggestion for splitting it up)
- remove the desktop code
- refactor the remaining code
- update the make commands
- update the github actions

**Comment by blrnw3** [comment]
@MDunitz 
1. "remove utils module" - utils module seems heavily used, why are we removing it?
2. "remove dead code (schema) " - this refers to the schema cli tool and converters module? does this functionality exist elsewhere, is that why we can delete it?

**Comment by blrnw3** [comment]
2 is solved, i forgot about this repo https://github.com/chanzuckerberg/single-cell-curation

**Comment by MDunitz** [comment]
Re 1. I think it should be remove unused code from the utils module. From a quick look I think the aws_secrets_utils.py and corpora_constants are no longer necessary, as is the import_plugins function in utils.py
