### ISSUE TITLE
Review and confirm repo docs

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#232]
- [x] Review and confirm repo docs:
    - [x] Readme
    - [x] Install / getting started
    - [x] Contact / issue / help information
    - [x] License
    - [x] Contribution guidelines
    - [x] Clean, reviewed & validated REST API documentation and Swagger spec

**Comment by bkmartinjr** [comment]
duplicate of #131?

**Comment by fionagriffin** [comment]
The only difference I see from #131 is "Clean, reviewed & validated REST API documentation and Swagger spec". @csweaver do we want to change this issue?
