### ISSUE TITLE
Update and move CXG spec

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2326]
## Need

The written CXG specification may not currently reflect the actual CXG format today. 

## Definition of Done

- [ ] The contents of the [CXG specification](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/cxg.md) are updated to reflect the true code.
- [ ] The CXG specification is removed from the desktop repo and moved to the hosted repo.

**Comment by atolopko-czi** [comment]
Should `cxg.md` (the cxg spec doc) stay in `single-cell-explorer` repo or perhaps be moved to `single-cell-data-portal`? I see that `single-cell-explorer/backend/czi_hosted/converters/h5ad_data_file.py` has been _copied_ to `single-cell-data-portal` so it can be invoked directly there. And the `explorer` repo only uses the `h5ad_data_file.py` to support CLI-based conversion of h5ad to cxg format. Will this CLI command persist?  So I'm just wondering which repo should be considered the rightful "owner" of the cxg format and its respective spec doc. If there's no good answer, will leave where it is.

**Comment by atolopko-czi** [comment]
The `main` branch of `single-cell-explorer` and `corpora-data-portal` are both at schema 1.1.0.  In particular, the `h5ad_data_file.py` code and `cxg.md` docs refer to copying the h5ad file's version info props `corpora_schema_version` and `corpora_encoding_version`, both of which are only valid in schema 1.1.0.  The newer schema 2.0.0 just has `schema_version` now. 

1. Should I maintain 1.1.0 "awareness" for now while reviewing/editing `cxg.md`?
2. Or should I be doing this story off a 2.0.0-compliant branch perhaps?

**Comment by atolopko-czi** [comment]
Discussed via mtg:
* Will have `cxg.md` live on `single-cell-explorer` repo (only)
* The `cxg.md` file should be updated to reflect current code changes for 2.0.0 schema support, per bchanges in branch https://github.com/chanzuckerberg/single-cell-data-portal/tree/212-schema2.0.0-feature-branch.

**Comment by atolopko-czi** [comment]
This [PR](https://github.com/chanzuckerberg/single-cell-curation/pull/125/) renamed schema file, and so this branch will need to updated its file references.
