### ISSUE TITLE
CLI code cleanliness

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#234]
- [ ] code cleanliness
    - [ ] `npm run lint` clean
    - [ ] `npm run build` clean
    - [ ] `pip install` clean
    - [ ] `flake8` clean
    - [ ] Documented build & install process is clean
    - [ ] Remove dead branches from github repo

**Comment by neuromusic** [comment]
is this issue still an issue? @colinmegill @csweaver

**Comment by bkmartinjr** [comment]
@neuromusic @csweaver - I think this is resolved.  Any issues if I close it?

**Comment by csweaver** [comment]
yes, this is done
