### ISSUE TITLE
Populate dataset info drawer with schema 2.0.0 fields

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2341]
Reintroduce dataset metadata population to the dataset info drawer using new/updated schema 2.0.0 fields.

UX needs:

What fields do we want to expose on the dataset info drawer and in what hierarchy.

Note: 

Consider how all 1.0.0, 1.1.0, and 2.0.0 versions are managed in the time between the activation of 2.0.0 and the sunsetting of 1.x.x

**Comment by maesen** [comment]
@MillenniumFalconMechanic I am closing out this ticket so we don't duplicate work with CC. You can still view it for reference. When you're ready, you can create your own ticket to update the dataset info drawer to the new schema as part of the Seamless work.
