### ISSUE TITLE
compatibility tests fail in smoke-test/smoke-test-annotations

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2346]
The smoke tests fail for most of the compatibility tests.  The unit tests all pass. 

See for example: https://github.com/chanzuckerberg/cellxgene/actions/workflows/compatibility_tests.yml

**Comment by signechambers1** [comment]
@maniarathi is there anyone who can take a look prior to 0.18 and determine if this is a bug or if the smoke tests need to be updated?

**Comment by tihuan** [comment]
@seve I see a PR merged for this, is it still WIP? Thanks!

**Comment by tihuan** [comment]
Still a pending PR!
