### ISSUE TITLE
Enable schema version 2.0.0 in dataset info drawer

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2360]
The 2.0.0 version number needs to be added to the allowed version in the dataset info drawer code to allow population based on `corpora_props`

https://github.com/chanzuckerberg/cellxgene/blob/01d34580b9819c92980cde24686a6a3ffa57703b/client/src/components/infoDrawer/infoFormat.tsx#L187-L193

TEAM COMMENTS:
* This is just accepting 2.0.0 
* Other work to make the drawer display the right props will be handled in a separate ticket

**Comment by maesen** [comment]
@MillenniumFalconMechanic I am closing out this ticket so we don't duplicate work with CC. You can still view it for reference. When you're ready, you can create your own ticket to update the dataset info drawer to the new schema as part of the Seamless work.
