### ISSUE TITLE
Type src/annoMatrix

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/cellxgene#2365]
type src/annoMatrix

Mim + Fran + Seve

**Comment by tihuan** [comment]
I think Bruce said to keep it in PR until other types are updated!

**Comment by bkmartinjr** [comment]
that is certainly my _suggestion_, as it will change a lot once we type the underlying dependencies.

**Comment by tihuan** [comment]
Closing this ticket, since it's now merged! Thanks so much for the awesome work, Mim 🙌
