### ISSUE TITLE
redux residual issue 1: cache variable name

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#239]
client/src/reducers/controls.js:
```
// jshint esversion: 6
 import _ from "lodash";
import { World, kvCache } from "../util/stateManager";
```

  @colinmegill
colinmegill an hour ago  Collaborator
Prefer keyValueCache or, even better, use the same name:

const worldCache = new WorldCache();

  @colinmegill
colinmegill an hour ago  Collaborator
The latter, more ideal pattern likely doesn't apply here as it is being instantiated twice it looks like - once for world and once for universe.

  @bkmartinjr
bkmartinjr 36 minutes ago  Member
Yeah, KeyValueCache is simple a utility class. Can hold anything (it is an Object under the covers). So I named it by the data that it holds - in this case it caches expression data (or more accurately in our new terminology, responses from /data/var - so varDataCache).

if you have a better name, lets fix it.

**Comment by bkmartinjr** [comment]
@colinmegill - how you feeling about this now that you have had some time to read/review the code?   Do you have a proposal for another name, or should we close this?

**Comment by colinmegill** [comment]
I understand now, this can be closed. So long as we have the convention of
giving it a specific name on creation, like varDataCache, it makes sense to
keep the constructor general as it doesn't know much.
