### ISSUE TITLE
Update GH compatibility workflow

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2410]
The compatibility test matrix in the GH workflow should be updated to add tests of:
* [x] Python 3.9 (see #2299)
~* [ ] Python 3.10 (at least RC1, but use a later version if available)~
* [x] MacOS

Please also update the compatibility matrix to substitute the `latest` version of `anndata` in the matrix instead of anndata `master`.

**Comment by maesen** [comment]
TEAM COMMENTS:
* 3.9 tests should pass. We don't need to fix all the tests.
* Open question: are we promising 3.10 compatibility for Desktop 1.0? Do we need to add this to the compatibility to the workflow if we aren't making promises about it?

**Comment by atolopko-czi** [comment]
At weekly kickoff squad meeting, We agreed _not_ to pin anndata (or any package for that matter).  I _think_ we also decided that we do not need to test the anndata `main` branch explicitly. @maniarathi Can you confirm?

**Comment by maniarathi** [comment]
Confirmed! No pinning of anndata and we will verify both the minimum version of anndata (today that is 0.7.6) and the latest released version of anndata (today that also happens to be 0.7.6, but we should make the test automatically pull whatever is the latest).
