### ISSUE TITLE
Fix compatibility tests so they pass

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2415]
We're adding tests in [#2410](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/2410); this ticket covers the work needed to make these tests pass and fix any other issues.

**Comment by maniarathi** [comment]
The compatibility tests were largely passing before [this run](https://github.com/chanzuckerberg/cellxgene/actions/runs/1172203997), so this may be the culprit [PR](https://github.com/chanzuckerberg/cellxgene/pull/2411/files).
