### ISSUE TITLE
Spike: can we pin the AnnData version for desktop?

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2416]
If we pin the AnnData version fixing compatibility tests would be easier. We could revisit this as AnnData updates and possibly release a new version of Desktop with updated pinned version.

**Comment by signechambers1** [comment]
@bkmartinjr what is your opinion of pinning the anndata version?

**Comment by bkmartinjr** [comment]
I think it is a bad idea.  For users who install globally, or in a virtual environment shared with other apps, it increases the likelihood of package version dependency conflicts.  Historically, we have intentionally avoided pinning, and instead tried to accurately represent the dep verisons we are truly compatible with.

**Comment by signechambers1** [comment]
Thanks @bkmartinjr ! Talked to @maniarathi too and she agrees. Closing this issue.
