### ISSUE TITLE
[FEATURE REQUEST] Just wondering if there's a way to set user_ids and passwords to this browser

### ISSUE THREAD

**Issue by lijxug** [chanzuckerberg/cellxgene#2422]
**Is your feature request related to a problem? Please describe.**
I would like to share my analysis with some cooperators. The data is not published yet, I can't just released it on the internet. However, I do like the idea that offereing them a browser to check anytime they want.

**Describe the solution you'd like**
So I am curious if you provide such solution and where to find them. I search for the keyword 'password' through out the project and no luck.

**Describe alternatives you've considered**
As for alternatives, I guess IP restriction would be also nice?

**Comment by MaximilianLombardo** [comment]
Hey Li,

Thanks for your question! We don't offer password protection for cellxgene explorer within the app itself. If you would be willing to self-host your app you could add authentication add restrict IPs from your server. Does this give you a sense of what direction to go in?

**Comment by lijxug** [comment]
Thanks for the reply. I'll try your solution.
Still, user-/password-based authentication would be more flexible.

**Comment by MaximilianLombardo** [comment]
Thanks Li - we will keep this in mind!

**Comment by Fougere87** [comment]
Hi cellxgene team,
Thank you for the package it's great   
We have to the same issue with unpublished data to share with collaborators or reviewers, and I was wondering if someone had a solution ?
If needed how could we contribute to create this feature ? 
Thank you !

**Comment by MaximilianLombardo** [comment]
Hey @Fougere87 thanks for the interest and question!

If the dataset is still in its early stages (and being updated frequently), it may make sense to create your own self-hosting setup. We don't have official guidance on this, but offer a [gallery of community contributed self-hosting 'recipes' ](https://github.com/chanzuckerberg/cellxgene-documentation/tree/main/desktop/self-hosting)that should help you get started.

If the dataset is stable (i.e. this is the form that will be published) and is suitable for submission to the cellxgene data portal, then you could also submit the dataset without publishing it (i.e. making it publicly available). This way you can share the private link with your collaborators (anyone with the link can access the dataset and cellxgene explorer instance) and after you have submitted/published your paper, you can make the dataset publicly available.
