### ISSUE TITLE
Remove schema conversion code from cellxgene Desktop CLI

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#2424]
The cellxgene CLI still contains the `schema` command which was initially designed to do what the CLI tool developed in `single-cell-curation` does today. This should be removed from the Desktop.

**Comment by atolopko-czi** [comment]
Seems like the `schema` and `prepare` commands in the `single-cell-explorer` CLI could be removed as well now, correct?

**Comment by atolopko-czi** [comment]
Ha, looks like this work was already done on https://github.com/chanzuckerberg/cellxgene/pull/2430!
