### ISSUE TITLE
How to submit cellxgene with specified port

### ISSUE THREAD

**Issue by sean1sun** [chanzuckerberg/cellxgene#2437]
I want to submit "cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad" with my specified port. How can I do? Thanks.

**Comment by MaximilianLombardo** [comment]
Hey Sean,

Thanks for your question!

You can do this by using `cellxgene launch` with the `-p` or `--port` flag followed by the port you wish to use. Does that resolve your question?

**Comment by sean1sun** [comment]
Hi,

Yes. That is what I want. Thanks for your prompt reply.

Best Regards,
Sean




________________________________

**Comment by MaximilianLombardo** [comment]
Perfect!

**Comment by MaximilianLombardo** [comment]
also check out `cellxgene launch --help` for a peak into other option flags you can run the app with
