### ISSUE TITLE
[BUG] Centroid interactions no longer working on centroid hover

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2454]
At some point, we broke the functionality attached to centroid labels, where hovering over the label itself no longer dilates the cells or category labels on the left sidebar.

I think this has to do with a typo that is semi fixed, breaking some places, but not others

https://user-images.githubusercontent.com/8716829/135317730-40e2ce01-23d6-4225-8b6b-7c260997381a.mov

**Comment by colinmegill** [comment]
@seve could you elaborate on 

> I think this has to do with a typo that is semi fixed, breaking some places, but not others

**Comment by seve** [comment]
The name of the reducer vs places where its imported/used @colinmegill

**Comment by colinmegill** [comment]
@seve thanks!

**Comment by colinmegill** [comment]
For posterity, this happened because the left hand sidebar is sending `categoryIndex` (correct), and the centroid label is sending `categoryValue`. 

![image](https://user-images.githubusercontent.com/1770265/135689862-4619271b-2944-44a4-a2ec-39562088073e.png)
