### ISSUE TITLE
Desktop - Update text in the hover over for diffexp

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2458]
Hover over should read "See top differentially expressed genes" instead of "See top 10 differentially expressed genes".
![Screen Shot 2021-09-29 at 11.13.39 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/3535edc1-eb47-4450-a07a-7cd390d64e6a)

**Comment by maniarathi** [comment]
Fixed in 2461
