### ISSUE TITLE
Cannot download sfn-workshop-mac.yml - Glitch? 

### ISSUE THREAD

**Issue by cobrien486** [chanzuckerberg/cellxgene#2465]
After installing Python via Anaconda, I'm trying to download the course config file as instructed in https://chanzuckerberg.github.io/scRNA-python-workshop/intro/setup.html . However, when I click to download I'm brought to a Google Drive page where it cannot open the file, and there is no option to download the file. 

I have the file now in my Google Drive, but unlike the other files in my Drive, there is no option to download - maybe the permissions have been revoked?

**Comment by DavidCousinsLeicester** [comment]
Same problem here. Has this been fixed?

**Comment by ambrosejcarr** [comment]
Thank you for your inquiry. We've fixed the permissions issue and this file should be downloadable. 

Please note that this tutorial is not supported, so we may not be able to fix future issues that occur.
