### ISSUE TITLE
cellxgene compatibility tests failing

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene#2473]
https://github.com/chanzuckerberg/cellxgene/runs/4364384094?check_suite_focus=true
3 matrix jobs failing due to:
```
ERROR: Could not find a version that satisfies the requirement louvain>=0.6 (from versions: 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2a1, 0.6.2, 0.7.0)
```
`cxg:latest os:macos-latest py:3.7 anndata:latest` job failing with:
```
cd client && /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/make ci
npm ci
npm ERR! cb() never called!
```

**Comment by maniarathi** [comment]
Based on the latest fails, seems like this is out of date and #2494 may be capturing the latest error?

**Comment by atolopko-czi** [comment]
Just as long as we have _one_ story to get the compat tests working again, regardless of what the latest root causes of failure may be, I think that's fine! I'll close this one.
