### ISSUE TITLE
Local browser caching not respecting immutable flag

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene#2476]
While CloudFront-level caching is working as intended, the local browser cache is not being used for `immutable` endpoint responses. 

For Google Chrome (96.0.4664.93, Mac) , it is not clear whether `immutable` cache directive is supported, per [this](https://stackoverflow.com/questions/41936772/which-browsers-support-cache-control-immutable) and [this](https://bugs.chromium.org/p/chromium/issues/detail?id=611416).

Firefox (95.0, Mac) also seems to making live requests for `immutable` responses.

Investigate and fix. We may just need to add `max-age` as an additional cache directive headers in the response, since `The immutable response directive indicates that the response will not be updated while it's fresh.` [ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control). If so, setting to 1 year seems reasonable.

Should be able to test initially in an rdev env, as CloudFront caching is not needed for this. But we should re-verify once in dev env, to ensure CloudFront is not modifying requests in some way that is affecting browser caching behavior.

**Comment by seve** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#browser_compatibility

![image](https://user-images.githubusercontent.com/8716829/145863802-98aa1e90-4d21-481c-9ce8-80aa5646128d.png)

**Comment by atolopko-czi** [comment]
Issue moved to [chanzuckerberg/single-cell-explorer #206](https://github.com/chanzuckerberg/single-cell-explorer/issues/206) via [**ZenHub**](https://www.zenhub.com/)
