### ISSUE TITLE
how to stop the cellxgene servers?

### ISSUE THREAD

**Issue by s1sun** [chanzuckerberg/cellxgene#2479]
I want to stop same cellxgene servers that aren't used. How can I do? Thanks.

**Comment by MaximilianLombardo** [comment]
@s1sun are you running cellxgene locally or in a self-hosted environment? Can you provide more context to your question?

**Comment by s1sun** [comment]
I used the command "ps axuww | grep cell" and find several cellxgene servers that aren't being used.  How to stop these cellxgene servers that were launched by program or other users?

**Comment by MaximilianLombardo** [comment]
if you have the process ids, then you can use the `kill` command with either the `-1` or `-9` feature flags to ask the process to close itself or force close the process respectively.

**Comment by s1sun** [comment]
thanks
