### ISSUE TITLE
Is there a way to remove a category from a dataset on the cellxgene Desktop? [QUESTION]

### ISSUE THREAD

**Issue by val23n** [chanzuckerberg/cellxgene#2502]
We are analyzing our cellxgene dataset with the .h5ad file. There are certain categories that we do not want to have as options for viewing (such as "sex", "identity", etc.), and we were wondering if there is a way to completely remove these categories from the .h5ad file. 

Additionally, we were wondering if there is a way to rename some of the existing categories for the purpose of our analyses.

Thank you in advance!

**Comment by MaximilianLombardo** [comment]
Hey @val23n - I think you asked this question on slack as well - but I'll post the answer here for completeness and discoverability:

> to remove categories you do not want to visualize, then you can simply remove those fields from the obs dataframe in your anndata object (.h5ad file). To rename the other categories, simply change the column name in the obs dataframe of the anndata object.

**Comment by signechambers1** [comment]
Closing, please let us know if you have any additional questions!
