### ISSUE TITLE
Unexpected HTTP error

### ISSUE THREAD

**Issue by kgurova** [chanzuckerberg/cellxgene#2505]
Hi I just started working with cellxgene and opened my_adata.h5ad file. Everything looked and worked good until I started looking for genes. Every attempt to load gene was finished with "failure loading gene x" message and emergence of "unexpected HTTP error". Please advise.

**Comment by MaximilianLombardo** [comment]
Hey @kgurova can you provide some additional information - more specifically the version of cellxgene you are using and the output from the terminal when you encounter the error?

**Comment by kgurova** [comment]
I am sorry, but when I restarted cellxgene the issue was gone.
Thank you!

**Comment by MaximilianLombardo** [comment]
Thats great - no worries!
