### ISSUE TITLE
[QUESTION] How to provide config file?

### ISSUE THREAD

**Issue by romanhaa** [chanzuckerberg/cellxgene#2527]
Is there a way to provide a config file that contains settings for dataset, port, etc. (similar to the [`default_config.py`](https://github.com/chanzuckerberg/cellxgene/blob/main/server/default_config.py) file) when launching cellxgene? E.g. through a parameter `--config /path/to/config.yaml`.

**Comment by MaximilianLombardo** [comment]
Good to see you've solved the issue @romanhaa!
