### ISSUE TITLE
Can not switch embedding after upgrading to the commit 8b4c1e418e1a28b571eb7c93226873514d2487b0

### ISSUE THREAD

**Issue by lijinbio** [chanzuckerberg/cellxgene#2535]
Hi,

I tried to install cellxgene from the source code using the below command.

```
git clone https://github.com/chanzuckerberg/cellxgene.git
cd cellxgene
make pydist
pip install dist/*.gz
```

However, after launching a .h5ad using the installed cellxgene, scatterplots can not be selected as usual. After reverting back to the commit (f2bd6ebce1df00ee2724bfc892accf25e9e1157a), the code works fine. So, the error might arise from the latest commit (8b4c1e418e1a28b571eb7c93226873514d2487b0). Thanks.

**Comment by seve** [comment]
If you're able, a screen capture of the behavior you're seeing would be super helpful too!

**Comment by lijinbio** [comment]
Hi @roaga, I am not sure about stack traces. Could you please help point out where I can grab them? I also tried to install cellxgene by using the steps you mentioned. But unfortunately, the issue still occurs.

Hi @seve, please find the screen capture at https://bcm.box.com/s/wbllwfirc1fnwoscpecko1pvxamsegpg. Thanks.

**Comment by roaga** [comment]
@lijinbio Thank you for the screen capture--that definitely helps clarify the issue! I'm afraid I'm still not able to reproduce this, so I wonder if it has to do with your dataset in particular (or some edge case that your dataset embedding hits).

Does this issue still occur for you using a different dataset? You can download datasets from https://cellxgene.cziscience.com/ if you need another.

If it doesn't occur on other datasets, it would be very helpful if you could share your dataset with us. If you need my email to do so, it's ragarwal@chanzuckerberg.com. Thanks!

**Comment by lijinbio** [comment]
Hi @roaga, thanks for your quick reply. Yes, I tried another dataset at the link, but unfortunately, the problem persists. So, I believe it is not due to the edge case in a dataset. Both datasets work fine by installing it by `pip install cellxgene`. Thanks.

BTW, I might forget to mention my environment. My OS is Mac OS X (version 12.3.1). The Chip is M1. The python is installed by conda. Please let me know if any other info might be helpful. Thanks.

**Comment by roaga** [comment]
I'm on an M1 Mac too, so I doubt that's the issue. Could you open up the browser console and show us any logs, errors, warnings, etc. that pop up as you open cellxgene and then try to switch the embedding?

**Comment by lijinbio** [comment]
![Screen Shot 2022-07-07 at 4 28 56 PM](https://user-images.githubusercontent.com/16247242/177874487-87eaad6a-8104-4281-883e-bb32d505fcdf.png)

Hi @roaga, I saw the "Uncaught (in promise) TypeError" when I tried to switch the embedding. (Several other errors occur even before switching embeddings. Not so sure if they are relevant.) Thanks.

**Comment by lijinbio** [comment]
> 

Hi @roaga, may I ask if you might have any comments about the error message when switching embeddings? Thanks.

**Comment by lijinbio** [comment]
> Hi - could you send me the dataset? At this point I'm still not sure what the cause of the error is.

Hi @roaga , I have just sent you the .h5ad that I am using. Please let me know if you might have any other suggestions. Thanks.

**Comment by lijinbio** [comment]
Hi @roaga, may I ask if you might have any update on this tissue? Thanks.

**Comment by lijinbio** [comment]
Hi @roaga, may I ask one more question about selecting a default embedding when launching a service. The current default embedding seems to be "UMAP". How could I change this default to another embedding in the .h5ad file? Thanks.
