### ISSUE TITLE
annotate command to support reuse of ref embedding for multiple classifier runs

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene#2547]
The cli `annotate` command should support reuse of the reference embedding when the user wants to perform prediction using multiple classifier levels. The reference embedding is stored in `obs` and can be reused to just run an alternate classifier.

**Comment by MaximilianLombardo** [comment]
will revisit this if it comes up, currently the `annotate` subcommand can make predict multiple levels of annotation provided that the corresponding models are available

**Comment by atolopko-czi** [comment]
Noting that this is an optimization, as it would allow the expensive ref embedding step to be performed once for multiple classifier runs.

**Comment by maniarathi** [comment]
Closing this a will not fix for now.
