### ISSUE TITLE
Convert REST 0.2 spec to markdown and put in cellxgene repo

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#255]

**Comment by bkmartinjr** [comment]
https://lifehacker.com/this-script-converts-google-documents-to-markdown-for-e-511746113

**Comment by bkmartinjr** [comment]
Andrey recommends: https://github.com/mangini/gdocs2md

**Comment by bkmartinjr** [comment]
Ambrose recommends http://docutils.sourceforge.net/rst.html instead of md

**Comment by colinmegill** [comment]
Markdown +1 :)

**Comment by bkmartinjr** [comment]
Better solution: https://github.com/evbacher/gd2md-html

**Comment by bkmartinjr** [comment]
PR #265
