### ISSUE TITLE
update logo

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2555]
We need to update the logo (and favicon?) to reflect branding changes.

https://drive.google.com/drive/folders/1J-Dqc_SWLpkA9gQxYOeKiYzuTikfNXrr

**Comment by ashin-czi** [comment]
This is approved and good to go, but still running into the unit test errors which is preventing merging. Currently trying to find out what's causing these errors

**Comment by ashin-czi** [comment]
Alec fixed the unit test issue so now this PR is good to be merged

**Comment by metakuni** [comment]
@ashin-czi : To which epic should this issue belong?
