### ISSUE TITLE
Move everything from the cellxgene wiki into the main repo

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#256]

**Comment by fionagriffin** [comment]
@bkmartinjr all pages are now in docs and I deleted all the pages. I don't have permissions to delete the wiki repo - can you do this for me?

**Comment by fionagriffin** [comment]
I did delete the content because it was 1.) relatively minimal and 2.) now in the docs, so it seemed pointless to have redundancy. If the repo can't be deleted then I will consider this issue "done"?

**Comment by bkmartinjr** [comment]
Agree!
