### ISSUE TITLE
[BUG] cellxgene presents scrambled UMAP, post-conversion

### ISSUE THREAD

**Issue by aseyedia** [chanzuckerberg/cellxgene#2563]
I am trying to convert a Seurat object whose metadata I've edited to h5ad for use with cellxgene. The Seurat object itself produces a normal UMAP within R: 

![image](https://user-images.githubusercontent.com/43455034/186925438-436428eb-f50a-4388-ae90-df2d5f8be95d.png)

But once I convert it to `h5Seurat` and then to `h5ad`, apparently the barcodes get scrambled along the way:

```r
SaveH5Seurat(
  rpca_umap,
  filename = "processed/02-annotation/rpca_umap.h5Seurat",
  verbose = TRUE,
  overwrite = TRUE
)

Convert(
  source = "processed/02-annotation/rpca_umap.h5Seurat",
  dest = "h5ad",
  assay = "RNA",
  verbose = TRUE,
  overwrite = TRUE
)
```

![image](https://user-images.githubusercontent.com/43455034/186925713-ea6ed951-59b4-46c2-a407-c94d4bf0a8bb.png)

If I load the h5ad into Python, I can clearly see that metadata columns become reordered in their relation to the index, because I stored the barcodes into a column early into processing, and they no longer match up:

```python
>>> scrna.obs['orig.bc']
AAACCCACAAGGCTTT-1_1     AAACCCAAGACCATAA-1_2
AAACCCAGTTGCCAAT-1_1     AAACCCAAGACCATTC-1_6
AAACCCATCCAGCACG-1_1     AAACCCAAGAGTGTGC-1_6
AAACCCATCGACATAC-1_1     AAACCCAAGCCTATCA-1_6
AAACCCATCGATACAC-1_1     AAACCCAAGCCTCAAT-1_3
                                 ...         
TTTGTCAAGAGGGCTT-1_12    TTTGTTGTCATCTATC-1_5
TTTGTCAAGGCGCTCT-1_12    TTTGTTGTCCGGACTG-1_6
TTTGTCAAGGGCTTGA-1_12    TTTGTTGTCGCAGTCG-1_4
TTTGTCAAGTCCGTAT-1_12    TTTGTTGTCGGTCTGG-1_2
TTTGTCACATTGGTAC-1_12    TTTGTTGTCGTACCTC-1_1
Name: orig.bc, Length: 69179, dtype: object
```

But I don't know why.

I have spent hours poking and prodding this file in different ways to see what the issue is. I've tried converting different assays, different ways of editing the metadata, loading the h5ad into Python to examine the object. None of this seems to work. So now I'm at a complete loss. Let me know if you have any ideas.

**Version (please complete the following information):**
 - Desktop:
  - Version 1.1.0

**Additional context**
I understand that this may not be a cellxgene problem but instead a SeuratDisk problem, but I am at wit's end, because `sceasy` does not work for me at all (cannot detect `anndata` package in conda environment) and this has never happened before.

**Comment by aseyedia** [comment]
Just found out that this was because the order of the meta data columns in Seurat was different from the order of `Seurat::Cells`, and somewhere along the conversion process, SeuratDisk assumes that the order of the meta data columns **is** the order of the barcodes of the UMAP coordinates.

**Comment by seve** [comment]
@aseyedia Thank you for the detailed issue, as well as coming back with the solution to the problem!
