### ISSUE TITLE
[BUG] Seurat v3 objects missing "key" in assays

### ISSUE THREAD

**Issue by zdebruine** [chanzuckerberg/cellxgene#2575]
See https://github.com/satijalab/seurat/issues/6408.

You may want to assign a value for the `key` in all `@assays`.  This is causing issues with running Seurat functions "out of the box".

**Comment by MaximilianLombardo** [comment]
Thanks for flagging @zdebruine - I'll forward to the relevant team members!

**Comment by brianraymor** [comment]
Please see [Use assay-specific naming for expression matrices in Seurat object](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2776).

**Comment by MaximilianLombardo** [comment]
@zdebruine This issue should no longer occur after the updates in October/November. Closing for now, but feel free to check back in or report your experience after the update.

**Comment by zdebruine** [comment]
@brianraymor @MaximilianLombardo Thanks all for this fast resolution!  Looking forward to the updates in the next 1-2 months.
