### ISSUE TITLE
Investigate options for app installers [SPIKE]

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene#2577]
Determine options for providing a cross-platform app installer to allowing simper installation of CELLxGENE Annotate for users that are not familiar with Python and pip-based installation steps.

**Comment by atolopko-czi** [comment]
@MaximilianLombardo Linux packages (.rpm, .deb) and OS X (.pkg) is assumed, but is Windows on or off the table here?

**Comment by atolopko-czi** [comment]
Successfully used `pyinstaller` to build a single-file executable for cellxgene desktop. So far, only tested `launch`, and not `annotate` command, which may require more troubleshooting (though unlikely, since MLflow takes on most of the complexity of model invocation).

Minor code changes & build command in this [PR](https://github.com/chanzuckerberg/cellxgene/pull/2578).

Also required patches to "vendor" packages code `anndata` and `flatbuffers` to address python package dynamic import logics, which otherwise breaks the executable at run-time.
* `flatbuffers.compat.import_numpy`
* `anndata/_metadata.py`
Will need to address this complexity with a clean solution.

[Notes](https://docs.google.com/document/d/14jOeAfHsDxurDvXupbEJjI93vSsIrltZpRHkd6SeCA0/edit)

**Comment by ambrosejcarr** [comment]
Windows should be in-scope: ![image.png](https://images.zenhubusercontent.com/5b2bd089a26e500c78d1a809/ad18ecac-90eb-46cc-9305-2b2c3f13f8e6)

**Comment by atolopko-czi** [comment]
@MaximilianLombardo How much further do we want to take this, if at all? Trying to create a Windows exe? Building pkg/deb/rpm?

**Comment by atolopko-czi** [comment]
Saving work in progress so we can delete the branch:
[patch.txt](https://github.com/chanzuckerberg/cellxgene/files/12016760/patch.txt)
