### ISSUE TITLE
More export options from web interface

### ISSUE THREAD

**Issue by royfrancis** [chanzuckerberg/cellxgene#2583]
Please add more export options from web interface rather than just h5ad. A simple tsv or csv would be great and the option to download raw counts and metadata. Optionally, dim red would be nice too.

**Comment by MaximilianLombardo** [comment]
Hey @royfrancis

Can you clarify the question? Are you referring to the hosted data portal where you can download datasets in either `h5ad` or `seurat`?

If referring to the portal, we will not likely be able to follow up on this based on current roadmap priorities.
