### ISSUE TITLE
[BUG] cells not able to be subset by specific annotations

### ISSUE THREAD

**Issue by Pointillomic** [chanzuckerberg/cellxgene#2657]
Hello,

I seem to be observing a strange behavior where the cells can with certain annotations can not be selected. When I hover over a certain feature, the cells are highlighted, but when I try to use that feature to select the cells, they are not recognized. As the data I am using unfortunately can't be shared, I've included some screenshots of the behavior. Interestingly this seems to only affect a small number of labels in the same category.

The version cellxgene being used is v1.1.1 and it is cellxgene VIP

Screenshots:
When I hover over an annotation:
![Screenshot 2024-01-31 at 1 05 58 PM](https://github.com/chanzuckerberg/cellxgene/assets/122571920/98adbe21-703e-495c-885c-a978bf5aa0d6)

When I try to select cells by that annotation
![Screenshot 2024-01-31 at 1 06 14 PM](https://github.com/chanzuckerberg/cellxgene/assets/122571920/ec508bbd-b610-4c17-8fe0-cf2eea79ce46)

If this is a rare problem, I can try to replicate the impact on a public dataset, but I thought I would see if this is a known problem

Thank you in advance and also for the great tool!

**Comment by MaximilianLombardo** [comment]
Hey @Pointillomic CELLxGENE VIP is actually a distinct project and is not maintained by CZI. You should file your issue with the project developers [here](https://github.com/interactivereport/cellxgene_VIP/issues) to get help with your issue.

**Comment by Pointillomic** [comment]
Thank you for the prompt reply - however, I just replicated the problem in cellxgene itself (v1.0.1) and it happens to persist in cellxgene VIP. Would it be possible to reopen this issue since it seems to occur in cellxgene itself?
