### ISSUE TITLE
cell ontology visualize

### ISSUE THREAD

**Issue by onmyojiyys** [chanzuckerberg/cellxgene#2673]
Inquiry question: How can the cell ontology database be transformed into a web-visualized hierarchical diagram? What is the technical route to achieve this? Just like the one on this webpage: https://cellxgene.cziscience.com/cellguide/CL_4028006.

**Comment by MaximilianLombardo** [comment]
Hi @onmyojiyys - thanks for the question!

CZI is not a maintainer of the CL cell ontology, so this question is a bit outside of our purview and what we are able to provide user support for. There are quite a few resources that dive into visualization of OBO graph ontolgoy format to a graph visualization, so I'd suggest doing a search for some of those resources to see what fits your needs ([ex1](https://github.com/INCATools/obographviz), [ex2](https://synaptica.com/visualizing-ontologies/))
