### ISSUE TITLE
Regraph UX does not recompute layout

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#286]
In the current implementation, regraph does not trigger a recompute of the world layout.

need to consider:
* [ ] what happens if the b/e can't do it at interactive speed (eg, it would hang)?
* [ ] how does the b/e CLI determine if it will be fast enough?
* [ ] do we need to provide CLI tools to pre-compute the slow bits (eg, nearest neighbors...)

Once we sort out this design and implement the back-end support, hooking up the f/e UI is easy.

**Comment by sidneymbell** [comment]
I believe (although I should triple check this) that all of the above would also apply to recomputing clusters, which was also flagged as a highly desired feature.

**Comment by sidneymbell** [comment]
Awesome find by @neuromusic that may help if we decide to implement this:
https://nicola17.github.io/tfjs-tsne-demo/

**Comment by signechambers1** [comment]
Closing as a low priority for 2021, labeling with reembedding so we can find related issues in the future if needed.
