### ISSUE TITLE
Propose package and installation strategy

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#297]
- pypi
- versions of python
- prepackaged downloads?
- how to include clientside code

**Comment by ttung** [comment]
prepackaged downloads is probably hard, but you could conceivably use [pex](https://github.com/pantsbuild/pex) to package cellxgene.

**Comment by csweaver** [comment]
Notes from Jeremy on installation:
## installation
- [ ] js client side build is slow with lots of scary warnings, assume once we put this on pypi we'll just bundle the prebuilt js with the package? maybe even worth distributing a prebuilt version of the client-side js with the repo for python devs (e.g. the scanpy developers) that want to play around with the python / analysis side but not deal with bundling the js
- [ ] why are we pinning explicit python versions? this is somewhat user hostile for someone who is adding this on top of some generic python data science environment
