### ISSUE TITLE
server should return 501 for routes/features not implemented

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#302]
see comments in PR #299

**Comment by neuromusic** [comment]
is this an active issue @bkmartinjr @csweaver?

do you have an example of a "bad" route I can test against?

**Comment by bkmartinjr** [comment]
Example:  `curl -v -X GET http://localhost:5005/api/v0.2/layout/var`

All of these route-related issues boil down to two things:
* per the API spec, optional routes not implemented need to return a 501 (rather than a 404). 
* all unhandled errors (eg, issue #276) should be caught and redirected to another reporting method that is more useful for reporting and doesn't splash random errors on the UI.  Put another way, I think we should not be relying on the default Flask error handler.

The first item seems low priority at the moment - I think it can be done as time permits (knowing that some of the optional routes might be removed from the spec as part of an API cleanup).

The second seems like it should be combined with a broader error on crash/error logging and crash reporting.   Ideally we would enable an easy mechanism for end users to report this stuff to us (eg, `cellxgene errorreport`).

**Comment by bkmartinjr** [comment]
@neuromusic @csweaver -- given our current design center, where the b/e only exists to serve the f/e, are these really defects?  Ie, how important is this kind of error handling given that the f/e has a known set of routes that it uses?

I'm thinking we should close these (and not fix).

**Comment by csweaver** [comment]
totally agree

**Comment by bkmartinjr** [comment]
OK, I will close out related issues. TY

**Comment by neuromusic** [comment]
endorse
