### ISSUE TITLE
De-hack uns for single gene

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#309]
data.uns = cell_data.uns fails if there is a single gene. Need to fix.

**Comment by csweaver** [comment]
This may be a scanpy error, get Alex minimal test case.

**Comment by csweaver** [comment]
Submitted issue to scanpy: https://github.com/theislab/scanpy/issues/323

**Comment by falexwolf** [comment]
Fixed in https://github.com/theislab/anndata/commit/ae8a1d04f0bc81fa1caeb4d460c6955b71ee7e60. Thank you!

**Comment by bkmartinjr** [comment]
FYI I'm also seeing a non-trivial performance cost to the `.uns` deepcopy() on each slice of an anndata object.   Still digging into why, but given that the cellxgene back-end has no dependency on this, we may just want to clobber `.uns` upon load

The code in question:  anndata/base.py:_init_as_view(), lines 689::
```
        uns_new = deepcopy(self._adata_ref._uns)
```

**Comment by bkmartinjr** [comment]
Very related issue, just filed on scanpy -- you can't slice both dimensions if one of the results is single-valued.  There appears to be an internal inconsistency with how dimension flattening is done in AnnData.

https://github.com/theislab/scanpy/issues/332

**Comment by bkmartinjr** [comment]
@csweaver - I will clean up the `uns` work-around as part of the work I'm doing on slicing performance.   It is closely related to the issue I just filed against scanpy.

**Comment by falexwolf** [comment]
> FYI I'm also seeing a non-trivial performance cost to the .uns deepcopy() on each slice of an anndata object. Still digging into why, but given that the cellxgene back-end has no dependency on this, we may just want to clobber .uns upon load

Sorry about the late response: `.uns` also stores the graph of cells that is used in the embeddings. This graph is sliced when slicing along the observations dimension. It is just copied when slicing along the variables dimension.

I see that this is an efficient solution if you want to extract single genes, etc.

Maybe one should find a more light-weight solution for that? But I'd need to know a bit more...

**Comment by bkmartinjr** [comment]
wrt `.uns` copy time -- our current use case boils down to slicing, on both axis using boolean array selectors, to access either annotations or X.   We do not (yet) expose/use the info stored in `.uns` to the visualization.

So the "need" is to slice and access X or annotations, without the overhead of copying `.uns`.    

I'm not sure this is a high priority item, especially as it may require API changes, and isn't our largest time sink.  Hence the air quotes.

**Comment by falexwolf** [comment]
We should have a better way for serving this case in the future, agreed!
