### ISSUE TITLE
Selection UI for "brush" (color by) differs between histogram and diff exp table

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#335]
In the LSB, there are two tabs:  Metadata and Expression.  They both contain widgets that allow the user to color by value (the "brush" icon).    However, the brush icon selection state differs by tab:
* in Metadata, it turns from black to blue when selected
* in Expression, it reverse highlights

We should have a consistent UI for selection state.

**Comment by colinmegill** [comment]
Propose removing the heatmap, and moving the information it displayed to the histograms.
