### ISSUE TITLE
fonts are not locally served

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#344]
the CLI aspires to bundle and serve all front-end assets locally.  However, there are currently fonts (Roboto) pulled from a CDN.   At some point, need to install and bundle.

**Comment by neuromusic** [comment]
When implementing this, we'll need to pay attention to licensing, too.

**Comment by bkmartinjr** [comment]
@csweaver - this will need to be fixed for the native (stand-alone) UI packaging.
