### ISSUE TITLE
Out of memory crash due to large metadata cardinality

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#349]
If a data set contains an annotation (metadata) field with large cardinality, the application will attempt to display *every* possible category in the Categorical Metadata selection UI.   This may cause the browser to crash (out of memory) as a very large number of DOM elements are created.   Best case, it also hangs the UI for an unacceptably large period of time while the DOM is populated.

A better solution would be to cap the number of categories displayed for any given categorical metadata field (say ~30). 

^ @colinmegill - please add any thoughts and I can fix this once we agree on approach.

**Comment by colinmegill** [comment]
Capping the number of categories shown is fine, but suggest boosting to 300. This allows for high numbers of clusters and ontologies, which have been seen in various datasets.

**Comment by colinmegill** [comment]
There are ~100 cell ontology classes in Tabula Muris, for instance, and while it's a lot it feels wrong to suppress any of it.

<img width="365" alt="screen shot 2018-10-18 at 4 19 05 pm" src="https://user-images.githubusercontent.com/1770265/47181644-91363400-d2f1-11e8-8306-ce1ba4cffa7c.png">

**Comment by bkmartinjr** [comment]
OK, will do this with a cap of 100.

**Comment by colinmegill** [comment]
Are we communicating to the client / user that there are fields suppressed
