### ISSUE TITLE
Do we need set -eo pipefail in travis?

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#373]
https://docs.travis-ci.com/user/common-build-problems/#my-build-fails-unexpectedly

Check by removing the line in travis.yaml and breaking flake8

**Comment by ttung** [comment]
I think you want this because any failures in any of the commands (`set -e`) should stop travis, and if you have a sequence of commands joined by unix pipes (`set -o pipefail`), you want any failures to stop travis as well.

**Comment by neuromusic** [comment]
It looks like this is resolved.

https://github.com/chanzuckerberg/cellxgene/blob/master/.travis.yml#L9
