### ISSUE TITLE
Reset always active

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#382]
* un-subset and go 'home'
* returns to initial state 
* not just for when data has been subset, always active, resets brushes and categorical metadata
* ‘reset’ still works as a name

**Comment by bkmartinjr** [comment]
Yes, it should clear:
* diff exp and user selected gene lists
* graph zoom/pan state
* selection (already done)
* colors (already done)

**Comment by bkmartinjr** [comment]
this is done.  closing.
