### ISSUE TITLE
launch UX message suggestion

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#387]
Currently, at launch, a messaging indicating data loading is printed.  This message contains the full file path, which may be cumbersome (see below), and not all that informative.  Suggest truncating it.

Example:
```
Loading data from ../cellxgene-datasets/cellxgene-prepare/immune_bone_marrow/immune_bone_marrow_processed.h5ad (this may take a while)
```

This would look better as:
```
Loading data from immune_bone_marrow_processed.h5ad (this may take a while)
```

**Comment by bkmartinjr** [comment]
@freeman-lab may have already implemented this - need to confirm.

**Comment by freeman-lab** [comment]
yes, done
