### ISSUE TITLE
Cell set buttons are still in an active state and clickable (but nothing happens) when disabled

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#391]
If the app is currently displaying diffexp histograms,  and the user lassos another set of cells, they can't save them by clicking on cell set 1 button or cell set 2 button.

It appears that the UI only allows the cell sets to be saved when there is no actively displayed differentially expressed genes.  

Suggest fixing by either:
* disable cell set / save buttons when the app is displaying differentially expressed genes
* or, "clear" the diffexp (ie, clear this mode) when the user saves a different cell set 1 or cell set 2

^ @freeman-lab - I know you have an opinion.

**Comment by colinmegill** [comment]
This is intentional - users must first clear diffexp, and the buttons are disabled. I believe your first case is already implemented, unless I'm misunderstanding: 

`disable cell set / save buttons when the app is displaying differentially expressed genes` is the current UX, is it not?

**Comment by bkmartinjr** [comment]
There are two issues with the current UI:

- Buttons (when disabled) are still in an active state and clickable (but nothing happens).   At a minimum, need to set their state to inactive so they don't look clickable.
- @freeman-lab and I both found the UI confusing, as we expected that picking another cell set would clear the diffexp.

I think only the first needs to be fixed for ship

**Comment by bkmartinjr** [comment]
Discussed with Colin - this is simply a bug in button active/inactive state.

**Comment by neuromusic** [comment]
updated title to better reflect the identified bug
