### ISSUE TITLE
no error for diffexp failure

### ISSUE THREAD

**Issue by freeman-lab** [chanzuckerberg/cellxgene#404]
Encountered this one while doing some CLI development -- if you launch the app, then kill the server, you can keep interacting with the client (as expected), but if you try to compute differential expression, it doesn't surface an error on the client, it just doesn't do anything, and it's unclear if it failed or what. Maybe the answer is just better error handing around the diffexp request.

**Comment by bkmartinjr** [comment]
@freeman-lab have you confirmed this since I put the HTTP error handling in (2-3 days ago)?

**Comment by freeman-lab** [comment]
pretty sure, i'm getting it on master (and double checked that i rebuilt the js), and i have seen those handled errors in other cases, so for some reason they aren't getting caught here?

**Comment by bkmartinjr** [comment]
I have confirmed that this is still a bug.

**Comment by neuromusic** [comment]
this is still a bug.

FWIW, I like how Jupyter handles this when the server is shut down & the client is still open...

![image](https://user-images.githubusercontent.com/1245615/58653853-7be3a800-82cb-11e9-9178-fb4d5a3ed47b.png)
