### ISSUE TITLE
Diffexp after regraph color scale error

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#405]
To repro: 

* Load up 33k
* Regraph 
* try diffexp
* set x & y on scatter
* color by x

**Comment by bkmartinjr** [comment]
> Colin Megill [12:49 PM]
> @bruce when you get a moment, can you see if you repro the following:
> On master, on 33k dataset, subset to part of the data and run diffexp
> plot x and y and color
> Data seems to be random?
> jeremy [2:02 PM]
> @Colin Megill try on 3k? or happening on both?
> i'm confirming some things look weird on 33k, but i wouldn't call it random
> Colin Megill [2:06 PM]
> The color scales aren’t right
> @jeremy without regraphing, try plotting x and y and making color scale the x and y genes
> it should be a smooth gradient in the scatterplot, that’s the ‘identity’ color scale for the axis right
> jeremy [2:07 PM]
> Screen Shot 2018-11-02 at 5.06.24 PM.png 

![image](https://user-images.githubusercontent.com/3740062/47942458-4569ba00-deaf-11e8-9580-4c8ab34f0173.png)

> 
> that's after diffexp between two clusters of cells near the top and bottom
> Colin Megill [2:07 PM]
> Perfect, exactly as it should look
> Try doing that same thing after a regraph
> jeremy [2:07 PM]
> and that's on master
> bruce [2:08 PM]
> @Colin Megill - am back.   this only occurs after a regraph, right?    (could easily be a bug in my slicing for "world").   Pls confirm test case and I'll look.
> jeremy [2:10 PM]
> yup, confirmed
> Screen Shot 2018-11-02 at 5.10.10 PM.png 

![image](https://user-images.githubusercontent.com/3740062/47942474-561a3000-deaf-11e8-9bfb-0b2c0288a065.png)

> 
> i subselected to the cells on the right
> and that's coloring by the same gene
> simpler way to repo: color by a gene (say GNLY), then subset selection, and color by the gene again
> colors are different
>
