### ISSUE TITLE
TM_Droplet name nan

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#409]
This seems like an error worth a sanity check on the metadata parsing:

![image.png](https://images.zenhubusercontent.com/5588c9564f7a08fbb7f35803/4b8d9ccc-5e39-4fac-a3fb-f136ca844169)

**Comment by bkmartinjr** [comment]
I'll fix this - I know the cause and resolution. It is a result of how pandas categorical dataframes handle unassigned values.

**Comment by bkmartinjr** [comment]
duplicate of #410
