### ISSUE TITLE
Issue with launching cellxgene when anndata object has boolean metadata

### ISSUE THREAD

**Issue by shayanhoss** [chanzuckerberg/cellxgene#457]
![cellxgene_error](https://user-images.githubusercontent.com/34040104/48654283-6b6b8000-e9c0-11e8-974c-5e018fa7df91.png)

Issue with launching cellxgene when anndata object has boolean metadata

**Comment by bkmartinjr** [comment]
If it is feasible, we would love to have a test dataset that triggers this issue.

You may want to join the cziscience slack (#cellxgene-users or #cellxgene-dev).  Link is in the readme.

**Comment by fidelram** [comment]
The problem can be solved by either dropping any adata.obs columns that are
boolean or by setting those columns as categorical.

To reproduce, simple add an adata.obs column as boolean. For example:

adata.obs['test'] = adata.obs.n_counts < 10
