### ISSUE TITLE
Readme clarification

### ISSUE THREAD

**Issue by shayanhoss** [chanzuckerberg/cellxgene#458]
What part of the anndata objects does the program pull in for visualization? Is it only pulling in the .Obs array from the object or using the entire object (including the continuous variables like tsne and umap calculations?) 

.... we spend a lot of time on scanpy.

**Comment by bkmartinjr** [comment]
@fionagriffin - could you propose a README update?   Some of this information is in the "assumptions" section, but not all...

@shayanhoss - the current usage (may change in the future as we expand functionality):
- `.obs` and `. var` annotation are use to extract metadata for filtering
- `.X` is used to display expression (histograms, scatterplot & colorscale), and to compute differential expression
- `.obsm` is used for layout

There is partial info in https://github.com/chanzuckerberg/cellxgene#assumptions     We would welcome additional prose that you think others would find helpful!
