### ISSUE TITLE
Top differentially expressed gene view

### ISSUE THREAD

**Issue by shayanhoss** [chanzuckerberg/cellxgene#460]
What are the differentially expressed genes ranked by? At the moment it looks like its by fold change. It would be really useful to sort the top differentially expressed genes (cluster x vs cluster y) by rank and view them not in a scrollable list, but as a matrix or dotplot/heatmap.

**Comment by bkmartinjr** [comment]
Current algo:
- rank genes using Welch's ttest statistic
- return top N (currently 10) genes where absolute value of log fold change is greater than 0.01 

The cutoff threshold for the second step can be controlled with the `--diffexp-lfc-cutoff` command line parameter

**Comment by neuromusic** [comment]
@shayanhoss Since I hope @bkmartinjr answered your question about how we are ranking genes, I'm going to close this issue. I just created a new one to track your feature request, which you can follow at #528
