### ISSUE TITLE
n-dim summary cube

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#462]
On startup and subset to current selection, summarize how categorical metadata is broken down by other categorical metadata, add the results of that calculation to world in the following format:

![image](https://user-images.githubusercontent.com/1770265/48742939-df529600-ec15-11e8-951f-82d791f8cb78.png)

Use case:

![image](https://user-images.githubusercontent.com/1770265/48742963-f42f2980-ec15-11e8-9182-b9626d338be4.png)

**Comment by bkmartinjr** [comment]
@colinmegill - PR #478 implements the functions to do the counting (and the cache management required to make it fast).   Should be ready for your use in crafting the UI....
