### ISSUE TITLE
Starting with 10x cellranger output?

### ISSUE THREAD

**Issue by IanCodes** [chanzuckerberg/cellxgene#463]
I saw the FAQ regarding the analysis using a 10x 'data' directory, but I am interested in knowing whether I can start cellxgene from the output of cellranger?  I have run cellranger 'count' and 'aggr', so is it possible to input/convert the output of 'aggr' 'outs' directory, which appears to be the starting point for other pipelines?

Thank you.

**Comment by fionagriffin** [comment]
Hey @IanCodes! 

Sorry that this is unclear. If you use cellranger `count` and `aggr` you should be able to load one of the output folders that contains the cell by gene count matrix. 
If you look at this example:

- https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/overview

 the `Filtered feature-barcodes matrices` is the part of the output that should be an acceptable input for `cellxgene prepare`. 

Some caveats: 

- If you are using v3 of cellranger you will need to update to the latest version of scanpy (v1.3.3). Cellranger recently changed their matrix output formats, but scanpy has updated to handle it.
- We can definitely explore supporting other cellranger output file types such as .h5 in the future, it will just require some tweaks to `cellxgene prepare`.
- Once we make sure this is working for you, we'll update the README to make it more clear!

**Comment by fionagriffin** [comment]
Hi @IanCodes - please reopen this issue if anything is still unclear. Thank you!
