### ISSUE TITLE
Typeahead improvements

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#474]
- [ ] make letters bold, highlight them in list items
- [ ] remove letters when click off, click back on search bar, with out selecting?
- [ ] consider proper number of list items, 5 or other

**Comment by bkmartinjr** [comment]
@colinmegill - which typeahead is this referring to?  Gene names, or annotation category/label names?

**Comment by colinmegill** [comment]
This was 2018, so the typeahead for gene names.

**Comment by bkmartinjr** [comment]
Could you either close, or morph this into current needs?
