### ISSUE TITLE
Show summary stats for each gene in dataset

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#483]
The new fuzzy gene name search attempts to access a variable annotation called `n_counts`, and assumes that this field contains some sort of  metric related to the gene (count == cells with expression above some baseline?).

Currently, the meaning and semantics of any annotation field (other than `name`) is completely dependent on the data set, and should not be used in this way.   Ie, the current server API has no concept of summary metrics for genes.

I've commented out the code and am filing this issue so @colinmegill is aware and can take any necessary actions.

Code in question, from `components/geneExpression/index.js`
```
    <MenuItem
      active={modifiers.active}
      disabled={modifiers.disabled}
      label={gene.n_counts}
      key={gene.name}
      onClick={g => {
        /* this fires when user clicks a menu item */
        handleClick(g);
      }}
      text={text}
    />
```

**Comment by bkmartinjr** [comment]
@neuromusic @colinmegill - this issue was "FYI" in case Colin wanted to fix it in some other way.  If not, we should close it.

**Comment by colinmegill** [comment]
It's been a long running thread to allow users to explore genes / see the
shape of that space at a high level. Probably the biggest omission in the
interface re: allowing user to see shape of dataset, and one I'd like to
eventually correct. It would make sense to send summary information ie.,
`[[gene_name: count], ...] `. If we feel like that's an API we want to
support, we could use that info to fill this in.

I'm for adding this to initialize, I think it's a good step.

**Comment by bkmartinjr** [comment]
To add this feature, we would need to come up with a way to count obs/cells with the gene, which requires having an opinion about what constitutes expressing the gene.  That is a bit of a step into having an opinion about how to interpret the data (similar to the current half-baked differential expression feature).

@neuromusic - maybe this need should be included in your efforts to think through marker gene exploration.

@GenevieveHaliburton - also curious on your take, as this is starting to get into "doing science" rather than just presenting data.  Is there a consensus way to allocate cells to genes (ie, what Colin asks for above), without making an opinionated decision?
