### ISSUE TITLE
Allow user to point to a secondary gene name

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#485]
User story: The ids used in the index are not standard gene names that users would search for in cellxgene. The user may have a secondary gene name in their matrix that should be used as the gene label. For example, expression matrices coming out of the HCA are indexed on gencode identifiers (i.e. ENSG00000115263.14), rather than the gene symbol (GCG). We would like to give users the ability during `cellxgene --launch` to point to a secondary column that contains the gene symbol so they can work in cellxgene with the more user-friendly gene symbol. [note: as downloaded, the HCA expression matrices do NOT have this secondary column with a gene symbol, but a user could append this]

cc: @GenevieveHaliburton

**Comment by csweaver** [comment]
Do the users want to work with both GCG and gencode in the search box? Is that what this user story is about? Or just GCG? If it is just GCG, they should be able to point to that column on launch using the `--var-names` flag

**Comment by GenevieveHaliburton** [comment]
I imagine users would only want to work with the gene symbols (i.e. GCG) so in that case the `--var-names` flag already addresses this issue! That's great, I didn't know about that one.

**Comment by bkmartinjr** [comment]
--obs-names similarly will alias the obs index column (not something the UI exposes in any significant way, but it may in the future)

**Comment by neuromusic** [comment]
closing this b/c `--var-name` already provides a solution, per @csweaver
