### ISSUE TITLE
No module named '_tkinter' error on OS X

### ISSUE THREAD

**Issue by jlew826** [chanzuckerberg/cellxgene#491]
I'm receiving the following error when trying to launch the example dataset on my OS X:

> $ cellxgene launch pbmc3k.h5ad --open
> [cellxgene] Starting the CLI...
> [cellxgene] Loading data from pbmc3k.h5ad, this may take awhile...
> ModuleNotFoundError: No module named '_tkinter'

I saw that there's a closed issue  #140 that mentioned this error on Win10/WSL/Ubuntu, but I wasn't able to find anything about this issue on OS X.

Thanks!

**Comment by csweaver** [comment]
Hi! Could you give me a few more details? Which version of OSX are you using? Which version of python?

**Comment by ttung** [comment]
Are you by any chance using a virtualenv?

**Comment by jlew826** [comment]
Hi, I'm using OSX 10.13.6 and python 3.7.0. 

No, I'm not using a virtualenv

Thanks!

**Comment by csweaver** [comment]
Hi, we aren't currently supporting python 3.7 yet, only python 3.6. Could you try again using a virtualenv with python 3.6 and let me know if the issue still persists?

**Comment by neuromusic** [comment]
I'm going to close this, assuming it's a Python 3.7 specific issue.

Feel free to reopen @jlew826 if you see this problem under Python 3.6!
