### ISSUE TITLE
subset to current selection fails when done twice

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#495]
The `subset to current selection` function will fail to correctly subset in a number of circumstances.

Test case:
1. Load pbmc3k test data set
2. Lasso a bunch of the cells
3. Click `subset to current selection`
4. Open the `louvain`  categorical metadata picker
5. Deselect one of the louvain values (eg, `B cells`)
6. Click `subset to current selection` again

At step 6, the app does the wrong thing and resets the World some random subset that I can't quite understand.  I expected that the final result would be World eq the intersection between all of the selected items (the contents of the lasso, excluding B cells).

**Comment by colinmegill** [comment]
This is still the case as of 1/17/2019

![multiple subset bug](https://user-images.githubusercontent.com/1770265/51353758-7d7ca400-1a7f-11e9-85ce-ebc315ce393e.gif)

**Comment by bkmartinjr** [comment]
No longer a bug - this appears to have been fixed in the Dataframe refactoring.
