### ISSUE TITLE
Add quick download feature to export cluster occupancy numbers as a table.

### ISSUE THREAD

**Issue by Loyale** [chanzuckerberg/cellxgene#514]
Cluster occupancy feature creates a visual representation of the association between categorical variables.  Since its being calculated anyway, can the values used to draw these components be quickly downloaded as a contingency table (e.g. csv?) for statistical analysis?

**Comment by neuromusic** [comment]
Thanks for the idea!

To clarify, do you envision for a given categorical annotation (we'll call "cat a") when colored by another categorical ("cat b"), the user can download a csv with "cat a" as rows and "cat b" as columns with counts as the values?

**Comment by Loyale** [comment]
That is what I had envisioned, yes. We use this type of contingency table from time to time to assess the independence of categorical variables.  Alternatively, if it's not too trivial, perhaps this could be calculated on the fly (chi-sq test of independence), and an asterisk placed next to any "cat a" category that is 'not' independent with respect to "cat b".  Here, the null hypothesis would be that there is no association between the two variables, and the asterisk could indicate the alternative that there is a significant relationship between the two categories. Not sure of the overhead required for something like that, but this is in our 'workflow' for exploring whether or not, for example, "Batch" is not biasing an interpretation of another feature like 'Cell Type'

**Comment by Loyale** [comment]
Perhaps using this:
https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html

**Comment by signechambers1** [comment]
This is an interesting idea but closing as a low priority now, if we get more requests similar to this in the future we will reevaluate.
