### ISSUE TITLE
jinja template not found

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#515]
Trying to load up the demo data on master, I get an internal server error in the browser and a jinja error on the command line.

On master (https://github.com/chanzuckerberg/cellxgene/commit/46ad346df1221a41cf017c6e9b37c7f0dd260e25), Installed in a conda environment with `pip install ./`

```
(cellxgene-dev) czirwc1osx1002:cellxgene-explore justinkiggins$ cellxgene launch pbmc3k.h5ad --open
[cellxgene] Starting the CLI...
[cellxgene] Loading data from pbmc3k.h5ad, this may take awhile...
[cellxgene] Launching! Opening your browser to http://127.0.0.1:5005 now.
[cellxgene] Type CTRL-C at any time to exit.
[2018-12-14 08:01:41,474] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
jinja2.exceptions.TemplateNotFound: index.html
```

**Comment by neuromusic** [comment]
fixed. solution: follow the [developer guide](https://github.com/chanzuckerberg/cellxgene#developer-guide) instructions in the README

**Comment by gokceneraslan** [comment]
This means `pip install git+https://github.com/chanzuckerberg/cellxgene` doesn't work, right? It fails with same error.
