### ISSUE TITLE
gene histogram scrub, then remove, does not reset selection state for that gene

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#517]
The histogram select (what Colin calls "scrub") and "remove" functions do not correctly interact with selection state.

Test case:
1. Load a data set and add a gene (you should see the gene expression histogram)
2. sub-select a range of expression in the histogram (ie, "scrub"), so that a subset of cells are highlighted in the main graph.
3. Remove the histogram by clicking the 'remove' link

This leaves the selection state as it was prior to the Remove (unchanged from step 2).  I expected that it would deselect the filter for the removed histogram, as if the user deselected the scrub from step 2.

Once you remove the gene, there is no way to deselect this state, other than using "Reset" or adding the gene again.

**Comment by colinmegill** [comment]
@bkmartinjr I don't reproduce this, could you confirm you are seeing this behavior on master? Here's what I see:

![jan-09-2019 11-50-11](https://user-images.githubusercontent.com/1770265/50914535-c475f400-1404-11e9-9439-253cb2a325da.gif)

**Comment by bkmartinjr** [comment]
I can no longer reproduce this.   I am comfortable closing it.
