### ISSUE TITLE
improve error when `build-client` has not been run

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#521]
Currently, if a power user or developer installs from source, they must build the assets for the web client first with `./bin/build-client`

If they do not do this, the web client returns a 501 error and the server spits out an error about `index.html` missing. (see #515)

We should improve the error that is returned so that these users can be directed to the appropriate course of action (e.g. ` try: except ...: print("Did you run build-client?")` h/t @mckinsel)

**Comment by neuromusic** [comment]
alternatively...

I ran into #515 by making the (incorrect) assumption, based on the pypi deployment and top level structure of the repo (e.g. setup.py) that I could simply do a `pip install -e ./` and it would work out of the box.

The solution here might not be to improve the error handling here, but prevent folks who "know too much, but not enough" like me from getting into trouble. This would mean a slight reorg of the repo, isolating all of the python components under "server" (incl setup.py) and using a Makefile or INSTALL.sh or something at the top level that does the full build of both the client and server.

**Comment by bkmartinjr** [comment]
largely addressed via documentation and improved makefiles.
