### ISSUE TITLE
User can add categorical metadata (annotations)

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#524]
A frequent request in cellxgene has been the addition of custom categorical metadata when something interesting is found, ie., building up ontologies. Many considerations, namely interaction with filesystem and integration with subsequent analysis and workflows.  

Opening this issue for tracking & discussion.

**Comment by colinmegill** [comment]
1. Scientist runs clustering, gets clusters 1-10
2. Scientist runs differential expression on cluster 1 vs rest of cells
3. Scientist sees upregulated gene identifying cluster 1 as a cell type 'heart'
4. Scientist clicks `+ add categorical metadata field` and types in 'Tissue'
5. Scientist clicks `+ add category` within newly created categorical metadata field and types 'heart'
6. Scientist uses multi select functionality (cluster 1 and > n expression level for marker gene) to select a group of cells
7. Scientist presses `enter` and labels group of cells as 'heart' (this is persisted to file system)

**Comment by neuromusic** [comment]
annotations <- so I can search for this issue better 🤣

**Comment by bkmartinjr** [comment]
@colinmegill @sidneymbell - I think this feature, at least as described in this issue, is implemented.  Please close if you agree, or further annotate if not.
