### ISSUE TITLE
develop "data" page in docs

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#529]
Under our new plan for documentation, we identified the need for a "data" page, highlighting example datasets that users can work with to explore cellxgene.

This page needs created.

Current page: https://chanzuckerberg.github.io/cellxgene/data.html

**Comment by neuromusic** [comment]
First pass by @fionagriffin in #540 

@GenevieveHaliburton to add a vignette, then we can close this.

**Comment by bkmartinjr** [comment]
@neuromusic - this is tagged with 0.5 milestone.  Is it fixed, or should it be re-targeted to another milestone?

**Comment by neuromusic** [comment]
not fixed, pushing this down the backlog
