### ISSUE TITLE
improve content on landing page in docs

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#530]
Goals

1. Users should know what cellxgene does
2. Users should know how to quickly install cellxgene
3. Users should know where to go for help

Current landing page is here: https://chanzuckerberg.github.io/cellxgene/

**Comment by GenevieveHaliburton** [comment]
@neuromusic I have a few comments on the landing page content -- should I edit directly or do you have a working doc where you are gathering notes?

**Comment by neuromusic** [comment]
Feel free to edit directly. We aren't linking to it yet, so I'm happy to
consider it a working document until then.

**Comment by neuromusic** [comment]
#537 added GIFs
