### ISSUE TITLE
select from all genes in dataset

### ISSUE THREAD

**Issue by Marius1311** [chanzuckerberg/cellxgene#542]
Hi all!

I have been using cellxgene browsers for a while now and I really like them. One feature I am missing is access to the .raw attribute of AnnData objects. When I use an AnnData object for a cellxgene browser, I only have access to genes which are contained in the .X layer of the object. However, we usually filter our AnnData objects to only contain highly variable genes before computing embeddings - meaning that I won't be able to color in the majority of genes via the cellxgene broweser because they are not in the .X layer, but also in the .raw layer which I initialise before filtering. This is a really important feature when working with biological cooperation partners who would like to color in genes they know. Currently, my cooperation partners cannot find these genes because they have been filtered out and there is no .raw access. 

All the best,
Marius

**Comment by csweaver** [comment]
Hi @Marius1311! I'm happy to hear that you've been using cellxgene! Thank you for the feedback, we will be sure to discuss this at our team meeting this week. 

A couple of questions: 1. When you are accessing a gene from `.raw` do you want to see the original observations or would you like the observations normalized in some way? 2. If you want to see the original observations, would you ever want to be able to access these for the genes that appear in .X as well?

**Comment by Marius1311** [comment]
Hi @csweaver, and thanks for your quick reply!
At which step in the process of normalisation and filtering one would like to set the .raw attribute is still up for debate, but I think most scanpy users first do some very basic filtering (remove a couple of cells which are very likely to be dead), normalise per cell and log transform. When the data is in this state, we save to adata.raw, which is what we use later on to visualise individual genes and also for statistical testing like differential gene expression because we would usually not want to use the batch corrected data for that. Please see this scanpy tutorial [Clustering 3K PBMCs](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html) for an illustration of what I just said. Saving to .raw happens in line 15.

Regarding your second point: When I color in genes, I would always like to see their expression colored in according to their values in adata.raw, regardless of whether they appear in adata.X as well or have been filtered out.

**Comment by Marius1311** [comment]
Hi @GenevieveHaliburton ! Thanks for your message. There aren't really any other features from .raw I would like to vizualise, it is manly really the filtered out genes. Filtered cells would be difficult I guess, because where would they appear in the embedding? In a PCA, one could just project them into the embedding but that's not possible in a tsne and at least not trivial in a UMAP. 

When I visualise gene expression, I would usually use normalised, but not batch corrected data - that's what I usually store in .raw

**Comment by GenevieveHaliburton** [comment]
Thanks @Marius1311 ! Super helpful! 

> Filtered cells would be difficult I guess, because where would they appear in the embedding? 

I was imagining maybe a separate plot where you could visualize some kind of euclidean distance, would that be useful at all or not really? 

> When I visualise gene expression, I would usually use normalised, but not batch corrected data - that's what I usually store in .raw

In the meantime, there could be a workaround here if you add the values from .raw as metadata to .X. It's pretty hacky but might get part of the way there? 

Thanks so much for your feedback!

**Comment by neuromusic** [comment]
@Marius1311 I updated the title of this issue since a different solution (using latest scanpy) might be the best fix here

**Comment by wangjiawen2013** [comment]
It would be cool to show .raw data of a scanpy object. Looking forward to that new feature. And, could you add some functions to export the differentail expressing genes in csv format ?

**Comment by ambrosejcarr** [comment]
While it is true that the highly variable filter is now auto-detected, the newest version of scanpy still recommends hard filtering of cells with low transcript counts and genes with low detection rates. In their tutorial this results in the removal of 19024 genes. As pointed out here, biological experts will have specific genes they want to review; filtering the available genes results in a _missing_ value which is less informative to a researcher than a low expression value. 

I also agree with Marius that cells (observations) with low counts are less interesting because it's unlikely that a researcher would be specifically searching for them.

It's worth us thinking about whether there is a way to expose the full feature set in the GUI. My preference would be for upstream workflows to filter features by _masking_ them, as `scanpy` has implemented with the `highly_variable_genes` method, rather than us fitting cellxgene to a scanpy-specific formalism wherein unfiltered features are stored in a raw layer.

**Comment by signechambers1** [comment]
As there is an upstream workaround, we will not support this feature request at this time. Thank you!
