### ISSUE TITLE
Divergent color scale for differential expression

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#546]
For log fold change below zero and above zero. 

https://github.com/d3/d3-scale-chromatic#interpolateRdBu

**Comment by neuromusic** [comment]
my one concern about RdBu on a white background is that cells near 0 will be effectively invisible. something with isoluminance would be ideal, I think

**Comment by fidelram** [comment]
I think that many colormaps are similar to python's matplotlib. Thus, this reference can be used to find a relevant colormap: https://matplotlib.org/users/colormaps.html

**Comment by michaeljmalone** [comment]
I haven't been able to find a color scheme for it, but what I like for my expression data with ggplot is:

There's probably a more sophisticated way, but something like:

`ggplot(df,aes(x=UMAP1,y=UMAP2))+geom_point(aes(color=Gene2))+theme_bw()+scale_color_gradientn(colors = c('navy','blue','cyan','green','yellow','orange','red','red3'))`


![UMAP_color_gradient](https://user-images.githubusercontent.com/49416308/61909090-dded1200-aef6-11e9-805a-01fcd67c9993.PNG)

**Comment by signechambers1** [comment]
Closing as a low priority
