### ISSUE TITLE
Identify candidate demo dataset

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#547]

**Comment by neuromusic** [comment]
Can we rename this to "identify candidate demo dataset" so we can take some time to identify what the features are that we want in a demo dataset before zero-ing in too quickly?

Needs:
- large-ish number of cells (in the 10s of thousands)
- multiple categorical variables (3+)
- at least one continuous variable?

Candidates:
- Tabula Muris

**Comment by colinmegill** [comment]
👍🏻

**Comment by sidneymbell** [comment]
I'll reprocess tabula muris and talk to the biohub folks this week
