### ISSUE TITLE
Reconsider naming of cell sets used in differential expression

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#553]
Is "Cell set 1" and "Cell set 2" the most intuitive labelling here?

- Group A and Group B
- Target and Comparison

**Comment by bkmartinjr** [comment]
Other ideas:
* Set A, Set B
* Selection A, Selection B

**Comment by colinmegill** [comment]
`selection` is a nice idea!

**Comment by bkmartinjr** [comment]
Assigning to @liaprins-czi for UI idea generation/proposal.

**Comment by colinmegill** [comment]
This can be wrapped up in work on #994, and this issue can be closed IMO

**Comment by liaprins-czi** [comment]
I agree with Colin, this will be solved inherently by #994 so I am closing this one.
