### ISSUE TITLE
long category values mess up UI

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#554]
Example from the Tabula Muris dataset, on master

![screen shot 2019-01-11 at 4 38 37 pm](https://user-images.githubusercontent.com/1245615/51066842-c0430580-15c1-11e9-9d8c-6d40ccd136af.png)

**Comment by neuromusic** [comment]
another example:

![image](https://user-images.githubusercontent.com/1245615/51950854-0f24d380-23e7-11e9-9378-2c7c00f18bc1.png)

**Comment by mckinsel** [comment]
It turns out that the `short_name` thing above isn't a cellxgene issue. It's getting truncated in the creation of the h5ad.

**Comment by neuromusic** [comment]
@mckinsel ohhhhh, ok.

**Comment by colinmegill** [comment]
Great catch on "ForelimbandHindlimb" however!

**Comment by colinmegill** [comment]
Resolved via text-break

![image](https://user-images.githubusercontent.com/1770265/64206087-588e4300-ce4e-11e9-967b-2d645ec5235a.png)

**Comment by seve** [comment]
Fixed in #827 (e4cdcad)
