### ISSUE TITLE
Show top expressed genes option

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#557]
Assuming user has zoomed into a selection of cells (ie., Lung & T Cells) they may want to see top genes expressed for current `world`

cc && thank you @AMaynard10

![image](https://user-images.githubusercontent.com/1770265/51353543-f2031300-1a7e-11e9-9df6-4c81cbe6ca30.png)

**Comment by neuromusic** [comment]
is this top relative to everything else in universe? or raw expression of world?

**Comment by colinmegill** [comment]
Great question... if we're not doing diffexp, it's probably going to just be noise. We should probably close this issue.
