### ISSUE TITLE
Categorical metadata shows numbers for world & current selection

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#559]
Louvain
0                            258 / 4478
1                          3245 / 3868

![image](https://user-images.githubusercontent.com/1770265/51356367-5080bf00-1a88-11e9-95e7-c041a03fd4ef.png)

**Comment by colinmegill** [comment]
cc @neuromusic @AMaynard10

**Comment by colinmegill** [comment]
From @neuromusic: "What are the implications here for updating cluster occupancy - does occupancy distribution lock to world or to current selection?"

**Comment by bkmartinjr** [comment]
This will be relatively expensive to compute at 30+fps (ie, to not introduce selection lasso jank).   LMK if you want to collaborate on possible ways to do that.   I suspect it will require both debounce and careful compute of the stats (to only recompute affected values, a la crossfilter groups).  May want to do this after I land dataframe.

**Comment by bkmartinjr** [comment]
@colinmegill - is this still a thing?  Could you update, if it is, or close as will-not-fix.  TY.
