### ISSUE TITLE
Color by multiple genes simultaneously

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#561]
One gene as mono red, one as mono green, one as mono blue

![image](https://user-images.githubusercontent.com/1770265/51400148-a5b6e200-1b15-11e9-9100-db71ea409167.png)

**Comment by neuromusic** [comment]
relevant: http://www.joshuastevens.net/cartography/make-a-bivariate-choropleth-map/

**Comment by Loyale** [comment]
FWIW, I’ve also tried ternary plots for this type of viz style/component as well.

E.g.
http://decon.fas.harvard.edu/pyramidal/geneset/Vsx2+Epha1+Epha2+Epha3+Epha4+Epha5+Epha6+Epha7+Epha8+Epha10

**Comment by colinmegill** [comment]
Thanks for that @Loyale!

**Comment by colinmegill** [comment]
@neuromusic yes, definitely, if we're showing absolute counts not proportion we'll need to use something like that. Something to hit the viz literature on. @mathisonian any ideas here?

**Comment by mathisonian** [comment]
I don't have a lot of context for what problem you're trying to solve here, but bivariate maps have a lot of issues, see e.g. https://www.jstor.org/stable/pdf/2684111.pdf. 

In general its very hard to overload the color channel successfully, you might consider reaching for other encoding methods before resorting to that.

**Comment by sdarmanis** [comment]
Something like this: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6047899/figure/F1/
Looking for a more down-to-earth RGB example.

**Comment by colinmegill** [comment]
Thanks @sdarmanis, pasting in here to save everyone the click:

![image](https://user-images.githubusercontent.com/1770265/51452380-1160a100-1d08-11e9-9ab9-4caebadf18b6.png)

This feels perhaps more possible in a paper where you have a solid grip on the expression of the clusters, but significantly more tenuous in an app where we will have all sorts of patterns/co-expression of genes between clusters. Hard to imagine the legend that accounts for the potential color mixing / combinatorics there in more than 2d (ie., @neuromusic's link), and even there it's pretty tough to tell. 

If there's no overlap in expression between the two populations, and we always know that, we could do this, but we don't in the application setting.

**Comment by colinmegill** [comment]
Thank you @mathisonian!

**Comment by signechambers1** [comment]
Closing as a low priority
