### ISSUE TITLE
Diffexp histograms show distributions for both cell sets 

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#569]
This could look something like: 

![image](https://user-images.githubusercontent.com/1770265/52013064-224ca780-24aa-11e9-97c5-570f03f15b22.png)

**Comment by dburkhardt** [comment]
Would like to advocate for this, it's really confusing that this doesn't happen currently. I thought that I hadn't selected my two groups for differential expression properly.

**Comment by colinmegill** [comment]
Closing as this will be supported by #729 and existing mini histograms on categories.
