### ISSUE TITLE
Appropriately handle zero heavy data in histograms & color ramps

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#570]
Skewed distribution makes it hard to see detail in remaining values: 

![image](https://user-images.githubusercontent.com/1770265/52013250-896a5c00-24aa-11e9-95e7-2ed007363a7a.png)

**Comment by colinmegill** [comment]
@freeman-lab's idea was to remove the bar and show "Percent 0" on the bottom, along with log fold change. I like this, generally.

**Comment by colinmegill** [comment]
@freeman-lab also suggested clamping the color ramp at 95%, everything greater than that value simply gets 'max' color to avoid outlier skew.

**Comment by sidneymbell** [comment]
I'm totally in favor of both of the above suggestions! A couple of related ideas:

**1 - Remove the bar, show "Proportion >0" alongside log fold change.**
This could enable us to also lump non-finite values into this bin (should discuss if desirable behavior). Thinking was that as @neuromusic points out in the roadmap docs, we visually surface the number of cells in the dataset, but not the number of genes. Building on this, I'd also suggest that we also try to find a way to surface the extent of dropout overall (i.e., how "rich" is the dataset -- the number of nonzero, real-valued measurements is often much lower than _m x n_). This wouldn't be a full solution, but could move us in that direction.

**2 -** I really like the idea of clamping the color ramp at the (0.01, 0.99) percentiles. Agree anything above upperbound should be the "max" color. **Should anything below the lowerbound be the "min" color, or should it be gray/ed out?** Should zero or non-finite values? This might also help make it obvious where there is actual _data_ suggesting low expression versus where there's uncertainty.

**Comment by colinmegill** [comment]
A suggestion from Roshan Sharma of @dpeerlab: user should be able to customize what range is shown on the colorscale / on the histogram. Ie., show .5% to 95%, but allow user to change.

**Comment by colinmegill** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/1770265/54375503-86d95580-4657-11e9-8cd0-4e34e5bb38aa.png)
