### ISSUE TITLE
Reset UI function does not clear Toasts

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#578]
If there are error toasts on screen, a Reset does not clear them.  Seems like it should, as it clears all other UI state.

Test case:
- enter a bad gene name, and get a error toast
- click Reset

**Comment by colinmegill** [comment]
To accomplish this, we'll need to call `.dismiss()` on the instance, an API which can be found here:

https://blueprintjs.com/docs/#core/components/toast.static-usage 

But we don't have access to the instance from reset. Most (but not all) instances are all stored together, in `src/components/framework/toasters.js`, and called in the components, like this one in actions: 

```
import { postNetworkErrorToast } from "../components/framework/toasters";

/*
dispatch an action error to the user.   Currently we use
async toasts.
*/
export const dispatchNetworkErrorMessageToUser = message =>
  postNetworkErrorToast(message);
/*
Catch unexpected errors and make sure we don't lose them!
*/
export function catchErrorsWrap(fn, dispatchToUser = false) {
  return (dispatch, getState) => {
    fn(dispatch, getState).catch(error => {
      console.error(error);
      if (dispatchToUser) {
        dispatchNetworkErrorMessageToUser(error.message);
      }
      dispatch({ type: "UNEXPECTED ERROR", error });
    });
  };
}
```

Note that we do not store a reference. I think it would work to fire an action with the reference every time we fire one, store it in the reducer as an array, loop over that array and call dismiss on each when we call reset.

Thoughts?

**Comment by bkmartinjr** [comment]
How would you remove the toast references from the redux store if the user manually dismisses or they timeout?   Without this, we will leak a lot of objects (ie, they will be retained in the store).

I _think_ (not confirmed) that this can be accomplished by using the `onDismiss` toast callback, and having that also dispatch an action that removes the toast from the store.

Assuming this works, the plan sounds fine, and could be done in a small stand-alone reducer.

**Comment by bkmartinjr** [comment]
obsolete, closing as we don't intend to change this.
