### ISSUE TITLE
Document what is required by cellxgene frontend for each endpoint

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#58]

**Comment by bkmartinjr** [comment]
@csweaver - is this simply to document in the REST API which routes & filter options are used by the current f/e?  If so, I can do that easily.   Please re-assign to me if this is the task (or clarify the issue).

**Comment by csweaver** [comment]
Yes, that was it

**Comment by bkmartinjr** [comment]
PR #328
