### ISSUE TITLE
View projections (umap/t-sne) side by side for comparison 

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#593]
Either: 
* one projection is the main graph layout and the other is in a pull-out tray like `plot genes`
* full dual monitor using local storage or https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API to communicate between the browser tabs to keep `currentSelection` synced

Thanks to @dpeerlab for the suggestion to do dual monitor workflows for detailed comparisons of embeddings

**Comment by colinmegill** [comment]
![image](https://user-images.githubusercontent.com/1770265/56930284-0187f400-6a91-11e9-8786-49796d874084.png)

Sleepwalk also an inspiration here: https://anders-biostat.github.io/sleepwalk/

![image](https://user-images.githubusercontent.com/1770265/56930647-3a749880-6a92-11e9-97a0-8ca52600d81f.png)

**Comment by signechambers1** [comment]
Closing as a low priority
