### ISSUE TITLE
Switch layouts from client

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#594]
Switch back and forth between t-sne & umap, for instance

Thanks to @dpeerlab for the suggestion

**Comment by sidneymbell** [comment]
I love this. I think it could buy us a lot of additional functionality, too (e.g., trajectories via diffmap layout, spatial via coordinate layout, etc.)

**Comment by neuromusic** [comment]
In the scanpy-centric version of this, it would be "switch between any embedding in `obs.X_<embedding>` from client"

**Comment by sidneymbell** [comment]
Many thanks to  Loyal Goff for his input!
"I go back and forth between these different views of the data, being able to see them side by side would be a game changer." 

E.g., showing umap in the main viz, with tsne / diffmap / etc. in tray(s).

His request was to have a dropdown that enables assignment of embeddings to the main visualization or to any of 1-3 trays at the bottom (in place of the scatterplot). Selecting/brushing in one shows the same cells in all others.

**Comment by colinmegill** [comment]
![image](https://user-images.githubusercontent.com/1770265/56929733-44e16300-6a8f-11e9-9b29-6db4778c5a36.png)

**Comment by neuromusic** [comment]
omg @colinmegill that icon is amazing

**Comment by Loyale** [comment]
I’m so jazzed for this.

**Comment by colinmegill** [comment]
See also #593

**Comment by sidneymbell** [comment]
@colinmegill - Love it! At one point, we'd also talked about potentially putting this in the 'visualization settings' menu? 

![image](https://user-images.githubusercontent.com/12618847/56931147-e10d6900-6a93-11e9-82e6-5bc020eda383.png)

**Comment by colinmegill** [comment]
Yes, but I think in a submenu. Ie.: 

Visualization settings
     histograms
          clipping
     graph
          switch embeddings

**Comment by colinmegill** [comment]
I think this is a larger issue, and earlier opened #736

**Comment by colinmegill** [comment]
For now, we'll implement as its own button, as a radio, to emphasize discoverability

**Comment by neuromusic** [comment]
I think the radio button makes sense. Much of the desire for this feature comes from wanting to toggle between layouts during the exploration process, whereas the visualization menu strikes me as more appropriate for settings that we expect the user to set once and forget.

**Comment by bkmartinjr** [comment]
@neuromusic - I was with you until the final comment.  I don't think we expect percentile clipping to be set-and-forget....    Do we need to rename that button - currently it is "Visualization settings" which seems kind of opaque, when it is really "Clip" or "Percentiles" or something like that.

We still have time to fix this for 0.9 if we decide quickly.

**Comment by neuromusic** [comment]
you're right @bkmartinjr ... I overstated it. still, users aren't going to be changing the clipping bounds as frequently as they change which metadata colors the plot. my point was not about the name of the drop-down menu, but that it's a sensible place to put something that is not going to be changed super frequently
