### ISSUE TITLE
Collapse histograms when adding 100's of genes

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#596]
![image](https://user-images.githubusercontent.com/1770265/52595844-df30f380-2e1c-11e9-99ae-3de9e4df15ae.png)

Thanks to @dpeerlab for the suggestion

**Comment by neuromusic** [comment]
This feature should be extended to differential expression genes and continuous metadata. The UI should match that for categorical metadata: (check box which indicates whether selection has occurred on field, color droplet allows coloring when collapsed)

**Comment by signechambers1** [comment]
Closing in favor of gene sets
