### ISSUE TITLE
status indicator needed during costly operations

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#6]
During high latency operations (eg, calculation of differential expression), the UI would benefit from a busy status indicator (eg, a 'computing....' footer or some such signal).    Given that we render each canvas asynchronously, may need one per canvas (eg, a red dot in the corner when it is being re-rendered)

**Comment by bkmartinjr** [comment]
@colinmegill - do we need this for the CLI MVP?   It primarily occurs in a) initial data load, and b) when loading expression data during very large data sets.    

I suggest we push it till after the CLI MVP, and then look at reworking loading/busy status.

**Comment by bkmartinjr** [comment]
Thinking about this more, we may need this for the MVP.   Differential Expression calculation on large data sets will almost always be slow (perhaps minutes in some cases).   Without some sort of async handling in the UI, it is going to be confusing....

For sparse Scanpy data sets, the following will be slow (> 2 sec for large data):
* differential expression calculations (could be minutes in worst case - ~300K cell set in CSC format is currently ~30 seconds)
* pulling expression data for a gene (eg, add a gene) - could be handful of seconds.   (on 300K cell set, in CSC format, currently ~6 seconds)

**Comment by colinmegill** [comment]
Operations: 

- [ ] Add a gene
- [ ] diff exp
- [ ] reset interface
