### ISSUE TITLE
add help menu to cellxgene

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#600]
add a simple help menu to give users outbound links for help from the UI

menu items:
- **About**: popup with version, copyright, links to repo & homepage, etc
- **FAQ**: link to FAQ in new tab
- **Chat**: link to slack signup

**Comment by colinmegill** [comment]
I like this as an addition to the app, propose surfacing content in `about` 

![image](https://user-images.githubusercontent.com/1770265/52806956-4686b780-3058-11e9-9424-8004dd5a7d34.png)

**Comment by neuromusic** [comment]
I dig it
