### ISSUE TITLE
Roadmap doc

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#605]
Add new doc for community roadmap
- support/experimental/unsupported definitions and modes
- current targets, planned features, future modes, and timeline

**Comment by neuromusic** [comment]
Partially complete with #712. Need to add supported/experimental modes

**Comment by bkmartinjr** [comment]
@neuromusic - can you finish, close or hand-off this?  TY

**Comment by bkmartinjr** [comment]
closing.  we plan to revisit/revise the roadmap every ~ 6 months
