### ISSUE TITLE
Add testing data attributes

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#606]
Add `data-testid` for unique identifiers and `data-testclass` for group identifiers to UI elements that are either a) Input (listen for user interaction) or b) (Output) UI elements that are important to view or are created/changed in response to user actions.

**Comment by bkmartinjr** [comment]
@csweaver @colinmegill is this issue still open, or did you already implement.

**Comment by csweaver** [comment]
fixed
