### ISSUE TITLE
"reset" slow on large datasets

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#610]
h/t @mckinsel 

reproduce:
1. load a large dataset (~1M)
2. color based on metadata
3. click "reset"

cellxgene take a few seconds to clear selection of points... much longer than re-coloring based on another piece of metadata

**Comment by neuromusic** [comment]
my guess is that this is because "reset" always re-draws the points, even if all of the points are already active. does that sound right, @colinmegill?

**Comment by bkmartinjr** [comment]
It isn't the redraw - I know the core issue, but haven't fixed it yet.   I'll add to the perf pile.   Keep filing these - very helpful!

**Comment by bkmartinjr** [comment]
@neuromusic - one more question...  In which version of cellxgene did you find this issue?

**Comment by mckinsel** [comment]
I believe this is 0.5.1

**Comment by bkmartinjr** [comment]
Thanks.

I have very large improvements coming in 0.7 (PR already merged into master if you want to try it out).    I'll take a look and see if I missed any other easy improvements.

**Comment by bkmartinjr** [comment]
fixed by PR #576
