### ISSUE TITLE
Without running the build process, the server errors.

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#612]
Without running the build process, the server errors.

![image](https://user-images.githubusercontent.com/12618847/53441204-22619980-39bb-11e9-89de-e9eb856d58fc.png)

`jinja2.exceptions.TemplateNotFound: index.html`

**Comment by bkmartinjr** [comment]
this isn't a bug....the build is required.

**Comment by csweaver** [comment]
@bkmartinjr : not for client development. You should be able to just run the rest api, without having to build the app

**Comment by bkmartinjr** [comment]
OK.  IMHO, it is nice to have, but not essential (ie, if we have to add code to support this, I'm not sure it is worth it, as it is trivial to do the build).

**Comment by csweaver** [comment]
I misunderstood what was happening, this is not actually an issue anymore.
