### ISSUE TITLE
Visualize how continuous & categorical metadata values relate

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#616]
The current app does a great job of showing how categorical metadata values relate to one another via "cluster occupancy". For example, I can see how `mouse.id` varies by `louvain` cluster assignment.

However, I frequently want to visualize how _continuous_ metadata values relate to categorical metadata values. For example, how does expression of `myfavoritegene` vary by louvain cluster assignment?

**Comment by sidneymbell** [comment]
Some of the visualizations recently implemented in scanpy do a really beautiful job of this: 

https://github.com/theislab/scanpy/pull/175

**Comment by gokceneraslan** [comment]
Here is a more comprehensive overview of similar plots in scanpy: https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html

**Comment by sidneymbell** [comment]
UI proposal from @colinmegill 
![image](https://user-images.githubusercontent.com/12618847/57728648-442cfd00-7649-11e9-902d-b31ccb0a4895.png)

**Comment by cakirb** [comment]
Hi, in which release do you plan to implement this feature? Thanks...

**Comment by colinmegill** [comment]
Hi @cakirb! We're really excited to get this feature in an upcoming release. We're about to release v0.10.0, and our hope is that we'll have this feature included in either v0.11.0, or v0.12.0. This will likely be by mid-June or mid-July 2019.
