### ISSUE TITLE
For select continuous params, 'use as color scale' button not working 

### ISSUE THREAD

**Issue by Loyale** [chanzuckerberg/cellxgene#617]
I have a dataset with a (relatively) large number of continuous parameters (not sure if this is related).  But several of the params, when I click on 'use as color scale', nothing happens.  The button is not toggled, and cells are not re-colored.  

Example here:
http://m9seq.mouse.gofflab.org/
- Clicking on 'cluster' param appropriately colors cells with the continuous cluster assignment
- Clicking on ['Pattern_1','Pattern_14','Pattern_17','Pattern_21'] as e.g. does not recolor.

Is this related to the distribution of the values for the param?  Looks like it might be specific to params more zeros or generally lower values?

**Comment by Loyale** [comment]
Oh!  Figured out what the relationship is...these params have (meaningful) negative values.  Apparently being truncated to 0, but apparently still affecting ability to draw color scale.

**Comment by bkmartinjr** [comment]
@Loyale - any chance you can send me a test data set (email or slack is fine)?

**Comment by bkmartinjr** [comment]
Partial fixes in #618 and #620 related to front-end handling of negative values in annotations.
