### ISSUE TITLE
"subset to current selection" clears differential expression results

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#621]
what I was doing...

1. made two selections and ran differential expression
2. colored by a gene
3. selected a new subset
4. clicked "subset to current selection"

what happened...

- the plot was no longer colored by the gene
- the differential expression results were gone

what I expected...

- plot would maintain my color selection on subset
- differential expression results would still be available for selecting additional genes to color by

**Comment by neuromusic** [comment]
This is closely related to #424, @colinmegill @bkmartinjr, but is it a dupe?

What I was expecting was that the scatterplot and coloring and diff exp results would remain when subsetting. What is the intended behavior?

**Comment by bkmartinjr** [comment]
yeah, it is as coded (ie, expected).  But I don't think it is "right" from a UI perspective.

My suggestion - if I can have someone provide me with the full list of desired UI behavior, we can fix it all in one pass (I'm happy to volunteer).   Probably doable for 0.8 if we get the spec soonish.    Looking for basic info, eg,
- Reset "clears":  ...
- Subset "clears" ..., but does not affect ....

**Comment by sidneymbell** [comment]
FWIW, I actually think the current behavior is appropriate.

My understanding is that all visible values should reflect the scope of `world`. Otherwise it can be really tricky to keep track of which cell populations are represented by displayed values, potentially leading to inadvertently deceptive results.

Subsetting to selection (in many cases) changes the range of gene expression values. IMO, it's not appropriate to keep the old scale of the expression values, which necessitates resetting the scale of the color bar. It's important to make it super obvious to the user that the scale of these values has potentially changed.

I think the same logic applies to the DE results. In many cases, subsetting to selection excludes some of the cells used in the previous DE analysis from `world`. Leaving the old DE values would introduce a disconnect between the cell populations that are visible and the cell populations that generated the DE output values (inappropriate IMO).

**Comment by neuromusic** [comment]
@sidneymbell that makes sense re: scaling, but in this case, I totally lost the genes I was looking at in "world" when going to "universe" via "reset" & had not memorized them and had no easy way to get back to them.

**Comment by bkmartinjr** [comment]
@sidneymbell - I think @neuromusic assumption is that all graphs/histograms and other widgets would update to match World. In other words, the bin ranges and bin counts for histograms would change, the number of dots on the scatterplot would update, etc.

We already do this for many things, but inconsistently.  For example, the categorical metadata lables change based upon World, as do the continuous data histogram ranges/bins counts.

There are really three options:
- loose everything - all views/widgets/graphs go away, and you are reset to "default" view
- maintain everything, but repaint to match World
- something in between, eg, drop some views, maintain others.

**Comment by sidneymbell** [comment]
Ahh this makes more sense, thanks for clarifying! :)

My concern is just making it *super* clear to the user that those values have changed.

**Comment by bkmartinjr** [comment]
Agree!  Lets use this thread to document want we want.   Can someone UX-minded please do a first draft?  TY!

**Comment by bkmartinjr** [comment]
Concrete proposal (from a offline conversation with @colinmegill).

Summary: subset operation should have no effect on the display visibility state of *any* other component, but should cause their contents to update to reflect the new world subset.

In more detail, when the user subsets to selection:
* all histograms should re-bin to match the new "world"
* all categorical pick lists should refresh to display only those labels present in the new world
* embedding (main) graph should refresh to show only the subset

What does not change / unaffected by this operation:
* user-defined and diffexp histograms should remain visible (ie, they are not removed, but they are re-binned)
* scatterplot visibility remains as is (ie, not removed, x/y not changed, but data will refresh to match new world)
* embedding graph - does not pan/zoom, etc

**Comment by colinmegill** [comment]
After speaking with @bkmartinjr re: this, propose we implement the UI such that there is no change to the user interface when we click `subset`

**Comment by sidneymbell** [comment]
This generally sounds good. My only concerns:
* Changing values in-place makes me nervous. It needs to be made *very* obvious to the user that these values are changing.   
* The diffexp results should really be removed upon subset as the selected cells used to generate these results may no longer be present in `world`.
