### ISSUE TITLE
Makefile has a couple of typos

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#624]
I was running `make release-stage-2` and it did a bunch of strange things, including trying to upload to production pypi.org (stage-2 is supposed to only upload to test.pypi.org).

Looks like there are typos - use of back-ticks - in the `echo` commands in that target, which cause the text in the echos to be executed in a subshell.

```
release-stage-2 : dev-env pydist twine
	@echo "Dist built and uploaded to test.pypi.org"
	@echo "Test the install `make install-release-test` and then upload to Pypi prod"
	@echo "`make twine-prod`"
```

The second two echos will cause sub-shells to run, including the production install.  Need to remove the back-ticks

**Comment by csweaver** [comment]
fixed
