### ISSUE TITLE
Weird data values in scatterplot

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#641]
@MarkAZhang very helpfully pointed us to a possible bug last week. 

In exploring the scanpy demo dataset `paul15`, he encountered some very odd values that are suspiciously grid-like. He reports that he did not run any normalization in `prepare`. 

![Screen Shot 2019-03-07 at 8 53 52 AM](https://user-images.githubusercontent.com/12618847/54160958-0f64b580-440e-11e9-8acd-2ffc7baf4641.png)

I can reproduce a very similar set of odd points from the raw dataset, suggesting that the suspicious _pattern_ in the values is not a cellxgene artefact: 

![image](https://user-images.githubusercontent.com/12618847/54161048-3f13bd80-440e-11e9-9b2e-45a73df1c7bf.png)

But, as @csweaver noted, the axes do seem oddly truncated in the cellxgene scatterplot, and the values are a bit shifted (compressed?). I'll poke around a bit more today.

**Comment by bkmartinjr** [comment]
my eyeballs suggest the Y legend is different, but it is otherwise the same?

**Comment by sidneymbell** [comment]
@bkmartinjr - Yeah. Just want to figure out _why_ they're different (they really should be identical).

**Comment by sidneymbell** [comment]
I was originally concerned that cellxgene was somehow doing something extremely silly to make such a distinct(ly broken looking) pattern, but it appears to be a data issue. Axes should still match, however.

**Comment by sidneymbell** [comment]
Still not sure where this came from, but `master` branch of cellxgene now produces the correct plot with appropriate axes. Closing.


![image](https://user-images.githubusercontent.com/12618847/54162746-dfb8ac00-4413-11e9-9a5d-27deccb2c939.png)

**Comment by bkmartinjr** [comment]
@sidneymbell - what version did you originally see the bug on?

**Comment by csweaver** [comment]
This was @MarkAZhang who initially identified the problem, he installed on March 5th  from pypi so version 0.7.0

**Comment by bkmartinjr** [comment]
The current release has a complete rewrite of the code that generates the dataframe extents (as part of Dataframe), so it is entirely possible that we fixed it...

**Comment by sidneymbell** [comment]
Hooray for free accidentafixes? \o/
