### ISSUE TITLE
Improve contributor docs

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#643]
Topics to include
- style guide
- setting up development environment for client
- setting up development environment server
- how to run tests locally
- guide to cellxgene's CI integration
- how to develop in docker
- link to how to test networked apps
- link to PR guidelines
- link to roadmap
- creating issue guidelines

**Comment by bkmartinjr** [comment]
@csweaver - there is a CONTRIBUTING.md in the tree.   Is this issue resolved?

**Comment by sidneymbell** [comment]
I think it's partially resolved; could use some additional content.

**Comment by sidneymbell** [comment]
Fixed via #1030
