### ISSUE TITLE
Many cells out of frame on load

### ISSUE THREAD

**Issue by batson** [chanzuckerberg/cellxgene#655]
It would be great if all cells were visible (at least on load) regardless of aspect ratio.
@colinmegill is showing me that this squishes when you decrease height but clips when you decrease x.

I have the dataset if you want it. 

<img width="947" alt="Screen Shot 2019-03-20 at 1 43 17 PM" src="https://user-images.githubusercontent.com/1261162/54717805-4590ec00-4b16-11e9-9edc-f50b0f737f2e.png">
<img width="898" alt="Screen Shot 2019-03-20 at 1 43 04 PM" src="https://user-images.githubusercontent.com/1261162/54717806-4590ec00-4b16-11e9-845e-bd3df3fdba6a.png">

**Comment by bkmartinjr** [comment]
@batson - I'm working on a fix.  I am happy to test it on your data if you send it over...
