### ISSUE TITLE
Scaling options for scatterplot

### ISSUE THREAD

**Issue by batson** [chanzuckerberg/cellxgene#656]
Would be great to toggle from counts to counts/10k, and to sqrt(counts) or sqrt(counts/10k).

If i had to pick one it would be toggle to sqrt(counts), just so outliers chill out.

@sidneymbell

**Comment by sidneymbell** [comment]
Awesome. That would be super useful!

I'd love to brainstorm about how to make this generalizable, given the bazillion different ways folks have normalized their data before it lands in cellxgene. See you tomorrow at biohub @batson?

**Comment by batson** [comment]
Ah, people have different preprocessing. At the min people might have .X and .raw.X, with the latter being counts

I'm not sure what normalizations would be sensible to do in the browser...in my mind, I was working on raw count data.

**Comment by signechambers1** [comment]
Closing as a low priority for now, if we get more feedback around this issue we will reconsider! Thank you!
