### ISSUE TITLE
let user select cells in scatterplot

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#665]
feature request from Angela:

When plotting genes against one another, want to select (lasso) genes in the scatterplot to see where they lie in the main layout.

**Comment by sidneymbell** [comment]
Context for this request: for experimental scientists who are used to working with flow cytometry data, they expect affordances for dual selection based on thresholds like this

![image](https://user-images.githubusercontent.com/12618847/65715122-584e2580-e051-11e9-86c5-6f65f9defdd5.png)

**Comment by signechambers1** [comment]
Users can do this by plotting one gene on x, one gene on y, and then brushing on both genes to select cells in different areas of the scatterplot. Closing this issue but flagging as a potential tutorial.
