### ISSUE TITLE
keep selection when resetting

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#666]
When the user has selected some cells after subsetting, (especially based on gene expression), they want to see where this selection lies in the context of the full dataset. The only way to get back to the full dataset is "reset", which clears the selection.

**Comment by bkmartinjr** [comment]
From an implementation point of view, this would add *significant* complexity and some performance hit (on reset).   The selection state is very much tied to the current dataset.

Given the current user story (purpose) for Reset (same as re-init, ie, return to launch state), I'm not clear on why retaining selection makes sense.   

@liaprins-czi @colinmegill - can we consolidate this with other discussions regarding the purpose / value of reset?

**Comment by liaprins-czi** [comment]
That makes sense to me, to consolidate with other reset-related discussions.

**Comment by bkmartinjr** [comment]
Related issues #280, #578

**Comment by liaprins-czi** [comment]
This is covered by #1192
