### ISSUE TITLE
expose `.var` values as metadata on gene tooltip

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#668]
We currently do not have a way to expose additional gene metadata stored in `.var` of the h5ad to users.

#96 proposes augmenting genes with info from external services. Alternatively (or in addition), we can expose any metadata stored in `.var` using the "toolip" approach suggested in #96

**Comment by neuromusic** [comment]
@mckinsel - this would be a way for cellxgene to expose some of the gene metadata you packed into your h5ad files, right?

**Comment by sidneymbell** [comment]
Interesting idea! How many users have we talked to who use the `.var` slot to store metadata about genes?

**Comment by neuromusic** [comment]
@mckinsel does :D

also @simone-codeluppi stores experimental metadata in the equivalent structure in their loom files: http://linnarssonlab.org/osmFISH/availability/

**Comment by bkmartinjr** [comment]
Assigning to @liaprins-czi and @sidneymbell to integrate into the upcoming gene enhancements.

**Comment by signechambers1** [comment]
Closing as a low priority, if we get more feedback here we'll reconsider!

**Comment by ambrosejcarr** [comment]
This is more general, but related to #96. We're consolidating in that issue due to the amount of community feedback it's accrued, but will keep in mind that many users leverage information that does not fall in standard databases and will want to be able to use their own `var` metadata to annotate genes.
