### ISSUE TITLE
Stating which values are visualized: .X or raw.X

### ISSUE THREAD

**Issue by gokceneraslan** [chanzuckerberg/cellxgene#676]
Thanks a lot for this amazing project! One small suggestion, it'd be nice to write somewhere in the UI which values (`adata.X` or `adata.raw.X`) are used as expression. I guess it's `.X` by default but for example`sc.tl.rank_genes_groups` function uses .raw.X by default, therefore what is shown as expression may not be used by the DE button in the interface.

Additionally, it'd be great to be able to select X or raw.X and also`adata.layers[]` in the interface.

**Comment by bkmartinjr** [comment]
closely related to #542

**Comment by neuromusic** [comment]
Thanks @gokceneraslan!

See @sidneymbell's #689 for your second proposal.

To be clear, our DE implementation uses `.X` (see https://github.com/chanzuckerberg/cellxgene/blob/master/server/app/scanpy_engine/diffexp.py#L40)

**Comment by neuromusic** [comment]
Since we don't touch raw currently, I think it doesn't make sense to expose this in the UI. We should update the docs to clarify which expression matrix we use & consider exposing in the UI if we pursue #689

**Comment by sidneymbell** [comment]
Fixed via #1030
