### ISSUE TITLE
N top genes for differential expression

### ISSUE THREAD

**Issue by michalk8** [chanzuckerberg/cellxgene#681]
Small feature request: it would be very helpful if user could select number of top diff. expressed genes, rather that being shown the default 10, by e.g. filling a field near the cell selection buttons.

**Comment by Marius1311** [comment]
I second this initiative, thanks @michalk8 for pointing this out! For a biologist, it is very hard to identify a group of cells just based on the top 10 markers. It would be really important to have a way to select the number of genes that should be returned when running the test.

**Comment by neuromusic** [comment]
Thanks for the feedback @michalk8 & @Marius1311!! This is closely related to #95

**Comment by signechambers1** [comment]
We have increased the number of differentially expressed genes to 50 highly expressed genes in each selection in the cellxgene 0.17.0 release. We hope this is helpful! We aren't planning to prioritize allowing a user to specify the cutoff at this point so I am closing this issue but please let us know if the latest functionality in 0.17.0 does not meet your needs.
