### ISSUE TITLE
provide notification when there is a newer version of cellxgene available

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#683]
If a newer version of cellxgene has been released, give the user a gentle notification that there is a new version of cellxgene available, with a link to update instructions.

**Comment by colinmegill** [comment]
I don't think this update notice should appear in a hosted context — ie., user seeing the message can't take any action. @liaprins-czi any ideas?

**Comment by liaprins-czi** [comment]
@colinmegill Are you talking about the publication sort of usecase? If so, then I agree. Would there be a way to prevent these users from getting the update message?

**Comment by seve** [comment]
With `prepare` being proposed as our fully supported method of hosting, could we just disable the checks when it is in the static mode?

**Comment by bkmartinjr** [comment]
Suggest that we have a CLI param that disables this feature.    There are other features that the user may wish to disable in a hosted context (eg, diffexp).
