### ISSUE TITLE
Add native user experience for install and launch

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#687]
Goal: ease the barrier of use for cellxgene by adding a OS-native app as a new usage mode. Targeting support for Windows and MacOS. (Linux will be still be supported with the CLI mode)

Motivation: the CLI mode in cellxgene is a significant barrier of entry for non-computational users (ex. wet-lab experimentalists, medical researchers). 

User story example: Erin an experimental biologist is in collaboration with Cary a computational biologist. Cary has prepared the dataset into the format required by cellxgene. Cary sends Erin a link to the dataset as well as the installer for cellxgene. Erin is able to download cellxgene and install and launch cellxgene without having to have experience with python or the command line. Then Erin can use the native file browser to find the dataset to load and explore the data. 

- [x] Installer for cellxgene and all of its Python dependencies (ie, excluding Chrome)
- [ ] Native launch ui (applications folder, start menu entry, etc.) 
- [x] Native load and save (file dialogue box, drag and drop, etc.)

Current usage modes will still be supported (pip installable CLI, Docker container)

**Comment by ttung** [comment]
Possibly detect new versions? :)

**Comment by neuromusic** [comment]
@ttung yes! #683

**Comment by csweaver** [comment]
- [ ] ensure a user can `import cellxgene` 

(Make sure the namespace is set to cellxgene)

**Comment by csweaver** [comment]
- [ ] Better naming of "server" related issues in general

See Bruce's comment from #730 
> I find the naming confusing as there are several "servers" all doing different things (and the term is super generic). `Server` is really a `RESTDataServer` (or something similar), as it serves up the r/o data to the front-end. Maybe make the names more descriptive.
