### ISSUE TITLE
fix slack signup link

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#706]
1. Fix the https://join-cellxgene-users.herokuapp.com/ app. Submitting an email triggers an error saying that the #cellxgene-users channel doesn't exist.

2. There are two different sign up links: https://join-cellxgene-users.herokuapp.com/ on README.md and https://join-cziscience-slack.herokuapp.com/ on docs/index.md and client/src/components/graph/graph.js

**Comment by neuromusic** [comment]
Hmm. Trying to figure out why `join-cellxgene-users` is broken.

Ideas:
1. It's a shared channel, so the slack API works differently
2. We've hit some limit based on signups vs number pf paid users: https://github.com/rauchg/slackin/blob/e41687b286c4dcaa24538383bd8a191d8e1b0871/app.json#L29

**Comment by neuromusic** [comment]
ok, toggled the config to add signups to #imaging and that works fine, so the problem appears to be with the shared channels...

![image](https://user-images.githubusercontent.com/1245615/55994676-301b6780-5c67-11e9-8f2f-39decff255ea.png)

**Comment by neuromusic** [comment]
issue added to slackin: https://github.com/rauchg/slackin/issues/398

**Comment by neuromusic** [comment]
solution: get rid of channel signup.

**Comment by neuromusic** [comment]
fixed
