### ISSUE TITLE
slow querying of gene expression values

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#719]
1M+ cell dataset. `.X` is a sparse array of uint16 values.

I want to visualize the expression of a specific gene. Autosuggest is snappy and helps me type "Vip". I hit "enter" and get a spinning wheel for 4m05s before the histogram appears. Once it appears, the UI snappy again.

**Comment by neuromusic** [comment]
Issue persists on same dataset, transformed to float32 (b/c I wanted log-scaled data, fwiw)

**Comment by neuromusic** [comment]
like #718, it seems likely this issue is due to the matrix being stored in CSR format 🤦‍♂️

going to try CSC and close this issue if that's the cause

**Comment by bkmartinjr** [comment]
The core issue is that we have a regression on the handling of sparse data types.  CSC sparse arrays should be fast.   Tagged for 0.10.
