### ISSUE TITLE
[RFC] QOTD for loader

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#720]
currently, cellxgene displays "cellxgene loading" in the browser window on launch.

We should replace it with a "quote of the day" that presents the user with a fun, useful, or insightful quote for users :D 

If you have a quote you think would be a good candidate, add it here :D Vote on your favorites with some "thumbs up" emojis

**Comment by neuromusic** [comment]
I'll start ...

> To deal with a 14-dimensional space, visualize a 3-D space and say ‘fourteen’ to yourself very loudly. Everyone does it. ~Geoff Hinton

**Comment by neuromusic** [comment]
> Nothing in biology makes sense except in light of evolution. ~ Theodosius Dobzhansky

**Comment by neuromusic** [comment]
> Distress not yourself if you cannot at first understand the deeper mysteries of Spaceland. By degrees they will dawn upon you. ~ Edwin A. Abbott, Flatland: A Romance of Many Dimensions

**Comment by neuromusic** [comment]
> On two occasions I have been asked, — "Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?" ... I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question. ~ Charles Babbage

**Comment by bkmartinjr** [comment]
will not fix
