### ISSUE TITLE
main embedding pan does not have 1:1 drag with cursor

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#722]
in pan/zoom mode, if you drag the main embedding, it will not move 1:1 with the cursor.  Underlying view move is scaled differently (slightly less on my machine).

found by @colinmegill 

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/f98db499-9f71-4f40-b580-9fad122f97e2)

**Comment by bkmartinjr** [comment]
@colinmegill - FYI, this is caused a configuration setting in our camera code (I'm in there fixing other issues and found it).  Currently it is set to move at 40% of mouse speed (eg, if the mouse moves 100 pixels, the canvas will translate 40 pixels).

This is a UX decision.  Per this bug report, I'll change it to a 1:1 pan.   If this is too jumpy, we can change it back.  For reference, it is controlled by the `panSpeed` constant in `util/camera.js`

Change will be in an upcoming PR.

**Comment by liaprins-czi** [comment]
This issue is still happening in master: Visualization does not match/keep up with speed of mouse.

**Comment by bkmartinjr** [comment]
Thanks @liaprins-czi  - I'll dig into it.
