### ISSUE TITLE
add guardrails to launch for non-CSC sparse datasets

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#723]
for performance when querying genes, cellxgene needs column-optimized expression matrix. Practically, this means that `.X` needs to be either a dense format or CSC-structured sparse array.

If the user tries to launch with another format (for example, CSR, DIA, DOK), they will hit performance issues like in #718 and #719 

We should add some guardrails to prevent users from doing this.

On launch, check the format of `.X`. If it is neither dense or CSC, then we should prevent cellxgene from launching, tell the user why, and give them a way to launch nonetheless. I'm open to either `click.prompt`/`click.confirm` or a command line flag to "force" the file to load.

**Comment by bkmartinjr** [comment]
Additional note:  for small datasets, the performance impact of non-CSC (or non-dense) is likely not significant enough to inconvenience users, and it may be better to simply issue a warning (rather than prohibiting non-columnar formats).  This allows users to change their data format only if they feel it is warranted.

**Comment by neuromusic** [comment]
@bkmartinjr that sounds good to me

**Comment by bkmartinjr** [comment]
One follow-on thought: the user needs to have a way to escape out of  large/slow operations.  For the CLI, this is easy (control-C).  For other UI (eg, native), there may need to be a cancellation UI.  

^ @csweaver

**Comment by csweaver** [comment]
@bkmartinjr outside of the close button on the app? I'm trying to figure out which actions you would want to cancel but not close the app.
