### ISSUE TITLE
add information on sparse array support to docs

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#724]
add documentation on supported sparse array formats (that is, only dense or CSC)

**Comment by bkmartinjr** [comment]
@neuromusic - I believe this was documented in 0.9 release (as part of PR #742).   Can you either close this issue if that was sufficient, or add some thoughts about additional information you would like to see addressed?  TY!

**Comment by neuromusic** [comment]
Perfect, thanks @bkmartinjr!
