### ISSUE TITLE
support loading arbitrary layouts

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#725]
currently, `cellxgene launch` allows the user to select from the standard layouts that scanpy uses, each of which is stored in `.obsm` and prefaced with `X_`.

If a user has another layout (e.g. spatial), they cannot load it into cellxgene.

suggested change: allow the user to use any layout stored in an `.obsm` key with the syntax `X_<layout>`

preferred UX:

1. let user pass layout to use into CLI
2. if requested layout does not exist or no layout is passed in, inspect file and give user prompt with available layouts

**Comment by sidneymbell** [comment]
Awesome! We also need to validate that the new layout is valid (e.g., no `NaN`s) and slice it to 2 dimensions.

**Comment by bkmartinjr** [comment]
Based upon further conversation with @neuromusic and @sidneymbell, the UX proposal is now:

1. CLI will accept an zero or more `--layout` arguments, e,g, `--layout X_tsne --layout X_umap`.   
2. Any layouts specified from the CLI will be presented to the user via drop-down menu (see #594)
3. If no `--layout` CLI argument is specified, any field in `.obsm` with the name `X_*` will be treated as a layout for presentation to the user.

All candidate layouts (`.obsm[foo]`) data must conform to the following or it will be ignored:
- data is an ndarray of shape (n_obs, >=2) and dtype float or int
- data contains only finite values (if float)

As with the current implementation, all layout data will be coerced to float32 for transmission to the front-end.

**Comment by sidneymbell** [comment]
This sounds good to me! Two small additions:

* If we are loading all `.obsm[X_*]` layouts, perhaps set a cap for the maximum number we import (e.g., 30 or however many the front end UI accommodates). I don't expect us to run into this -- my guess is still that most users will have between 1 - 15 layouts. But, this is one way that the app could break.

* Also verify that the data does not have any missing values (i.e., no `NaN`s).

**Comment by bkmartinjr** [comment]
Agree with "max layouts" limit.   Great addition.

On: 

> * Also verify that the data does not have any missing values (i.e., no `NaN`s).

How is this different than "only finite values"?     For dtype float, finite == (!NaN && !Inf)

**Comment by sidneymbell** [comment]
Cool. I recognize “finite” validation technically captures “not `NaN`“, but wanted to call it out explicitly.

**Comment by bkmartinjr** [comment]
It implies more than !NaN which is why I was trying to be more precise in our terminology.   We have to handle +/- Inf as well.

**Comment by sidneymbell** [comment]
Open to discussion (lots of reasonable interpretations here). 

Unless specified by the user, I would try and default to (take the first one available):
`X_umap` > `X_tsne` > `X_pca`

**Comment by bkmartinjr** [comment]
Clarifying from discussion with @sidneymbell - the defaults above are for selecting a layout to display by default (ie, without any user input), not which layouts are *available* for user-selection.
