### ISSUE TITLE
package dependency updates

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#727]
Our NPM package dependencies are getting stale, and the unit tests are starting to generate warnings (eg, "Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`").    Need to do an update pass over all dependencies.

**Comment by LuciaWL001** [comment]
I run the command 'npm update caniuse-lite browserslist', but still get the warning...
I cannot build the distribution.
