### ISSUE TITLE
inconsistent selection of truncated category labels

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#737]
The truncation of labels in categories with many labels makes selection using these labels inconsistent with the rest of the UI.

1. Un-checking one label removes this label from the selection AND all truncated labels

![image](https://user-images.githubusercontent.com/1245615/56930629-2d57a980-6a92-11e9-9b54-c50230662158.png)

2. Re-checking the label adds the cells assigned to the checked label back in to the selection and populated the category check box (indicated everything in this category is selected), but the cells assigned to the truncated labels remain unselected.

![image](https://user-images.githubusercontent.com/1245615/56930643-347eb780-6a92-11e9-9c9f-a8957a666e01.png)

3. Un-selecting then re-selecting the category check box selects all of the truncated cells (as expected)

**Comment by bkmartinjr** [comment]
@neuromusic - seems like a candidate for 0.10.   If you agree, add to milestone and assign to me.
