### ISSUE TITLE
add CLI guardrails for large files

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#739]
Currently cellxgene CLI prints a warning when started, letting the user know that it may "take a while" to load the data.

Two issues with this:
* it is printed indiscriminately, even when the file is small
* it fails to detect cases where load may succeed, but the file is larger than main memory and therefore may perform badly post-load (eg, diffexp on a dataset that exceeds main memory is going to be very, very slow).

Two proposed changes for discussion:
- [ ] Print the loading "take a while" warning only when the file size exceeds some threshold (say 100MB).
- [ ] If the file size exceeds total host RAM, print a warning that interactive performance may be slow (if we can't calculate RAM, which may be tricky on some platforms, default to something reasonable, eg, 16GB).

**Comment by bkmartinjr** [comment]
Related to this issue:  with our current architecture (optimized for dense and CSC matrixes), we can load and browse data sets that are quite large, in some cases exceeding main memory size.   But we can not practically support differential expression calculation at interactive speeds on arbitrary cell sets, where the total anndata.X object size exceeds main memory.

Longer term, there may be approaches that solve for this.  But near term, should diffexp calculation be available in the UI when we "know" a priori that it will not work?

**Comment by falexwolf** [comment]
Just a note: Loading an `.h5ad` from disk into memory hugely depends on whether the file has been written using compression or not. Obviously, this can also influence file size quite dramatically.

**Comment by bkmartinjr** [comment]
@falexwolf - great point.   If you have any advice on the best approach for a "data set may be too large"  test, would love to hear your ideas.   There have been a few users who were tripped up by various out-of-memory conditions (literally running out of VM and crashing, as well as thrashing due to exceeding main memory).

**Comment by falexwolf** [comment]
Ah, sorry. I don't have much advice. It depends so much on where you run cellxgene. And it also depends on the kind of operations that you want. One solution for really large datasets would also to open them in `backed` mode (`sc.read(..., backed='r')`), so that only those genes are read into memory that are actually needed. But it's probably buggy and relatively slow. But then, evidently, you don't have any memory problems at all anymore. I wrote a little post about the basic functionality [here](https://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/). In principle, it could also work out of the box (`Cmd + F: Indexing in "backed" mode`). Often times, I guess, the first pass in computational analysis is done by a computational person and the data is then locally viewed by a biologist.

**Comment by bkmartinjr** [comment]
Hi @falexwolf - thanks for the pointers on backed mode.   That would help our startup time (wouldn't need to read the X matrix), but unfortunately won't help when the user asks for differential expression across arbitrary rows...   I am thinking that our best approach now is to warn/advise the user when things are likely to be slow, but otherwise let them decide on their course of action.

Question: by "compressed" file, are you referring to an h5ad with a SciPy sparse array in it (eg, CSC or CSR), or some other format?

**Comment by cakirb** [comment]
Most probably, he means writing `.h5ad` file by `sc.write(..., compression = 'gzip')`. I'm on to test the performance of cellxgene regarding to the compression.

**Comment by bkmartinjr** [comment]
Thanks @cakirb & @falexwolf - I appreciate the advice, and will explore `backed` & `compressed` to get a sense of behavior for our use case.   

Our current implementation is pretty simple.  As Alex noted, we load all data into memory at startup, and hope it fits :-).  Our primary optimization is interactive (UI) performance, and we have biased towards using cached data to get post-loading interactive speed.   There are three primary data access patterns.   Unpacking these patterns a bit, and including some observations from recent testing:
* initial data loading at startup (via `sc.read`) appears very roughly the same for CSR and CSC (I suspect file IO is the primary constraint, but I have not yet confirmed this). 
* access to data for display/exploration is the app's primary pattern (excluding diffexp, detailed below), and is always a full-column read (no row slice).  We use this to access both `obs` and `X`, eg, to display expression histograms.  For large sparse data sets, column slicing `X` appears much faster when CSC encoded.  For example, I have a sparse 1M cell X 30K gene data set (nnz ~= 4B) that has interactive speed column slicing out of X when encoded as CSC, but is unusable (slow) when CSR encoded.
* for our current "differential expression" feature (a simple t-test), we let the user specify an arbitrary set of rows (cells), but do not allow constraint on columns/vars.   So the typical use is essentially a "random" row slice across all columns.   Initial performance tests show what I would have guessed: dense matrices which fit in memory are fast, and any sparse encoding pays some penalty (anecdotally, I think slightly less for CSR, but I have not yet confirmed this)

Net/net - for a given dataset and host, and our current UI assumptions, only the X column extraction seems to show significant performance changes based on matrix encoding. This doesn't seem all that surprising given the underlying data structure.  My comment to @cakirb (in #754) about the performance of CSC vs CSR was in regard to this particular case.   This is also why we are currently recommending CSC over CSR in our docs (I realize this is in conflict with the ScanPy documentation).

@falexwolf - I am still unclear how `backed` will going to help our differential expression, given our current UI assumptions (ie, a user-specified row slice across all columns).  But I will explore it and clarify where I'm confused.

I need to quantify behavior more exhaustively (benchmarking in progress), and I hope that some of your suggestions lead to startup/load or interactive perf improvements.  Thanks again!

**Comment by bkmartinjr** [comment]
@falexwolf - I have dug into the code base quite a bit more.  Recent bug fixes help a lot, but there are still problems with backed mode that prevent its straight-forward use.  TL;DR:
* backed mode loads significantly faster, as expected
* full column slicing (`adata.X[:,0]`), which is a critical pattern for us, loads the entire X from file even if  a single column is requested (and this seems to be significantly slower than initialization-time loading into memory using non-backed mode).

I believe this is due to the `__getitem__` implementation in CSC matrices -- it lacks the optimizations of CSR (the CSC `__getitem__` is slow even for in-memory data).  Historically, I worked around it by using the CSC `getcol()` method, when `X` is sparse CSC.

Short of implementing improving the CSC sparse class to implement all of the indexing optimizations, a simple solution would be to add `getrow()` and `getcol()` to the SparseDataset class in h5sparse.   Thoughts?  (I would be happy to provide a PR)

**Comment by falexwolf** [comment]
> full column slicing (adata.X[:,0]), ...

Ok, wow, it's not supposed to do this and I honestly wasn't aware. 

> a simple solution would be to add getrow() and getcol() to the SparseDataset class in h5sparse. 

Yes, sounds very meaningful! A PR is highly welcome!
