### ISSUE TITLE
Histogram y axis cuts off large numbers

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#753]
20,000 --> 20,00

![image](https://user-images.githubusercontent.com/1770265/57249714-837c9d80-6ffa-11e9-89d9-8645cef2436a.png)

**Comment by colinmegill** [comment]
This is an issue of margins, and this affects left, right & top (I don't think it affects the bottom)

![image](https://user-images.githubusercontent.com/1770265/57250484-621cb100-6ffc-11e9-8c22-8d7346820786.png)

**Comment by colinmegill** [comment]
While we're dealing with axis optimizations, D3 axis has parameters for solving this case as well: 

![image](https://user-images.githubusercontent.com/1770265/57250692-eb33e800-6ffc-11e9-875d-00ec61d7df4d.png)

**Comment by bkmartinjr** [comment]
@colinmegill - I did a very naive implementation of label generation.  If you want to fix, go right ahead.  If not, would appreciate pointers to samples and/or guidance on best practices to solving this.

**Comment by colinmegill** [comment]
Leaving this here for posterity, for either you or I:

Margin Convention: https://bl.ocks.org/mbostock/3019563

**Comment by bkmartinjr** [comment]
One idea for posterity:  we could also improve this by using other formats for large numbers.

For example, `20,000` could be written as `20K` or `2e4`
