### ISSUE TITLE
Internal Error in computing differential expression

### ISSUE THREAD

**Issue by cakirb** [chanzuckerberg/cellxgene#754]
I have an internal server error while computing differential expression. When I select two groups of cells and click compute, it shows this error:
![image](https://user-images.githubusercontent.com/39408202/57284911-03ae0c00-70aa-11e9-8e55-02c930239a34.png)

And in the terminal, this message appears:
```
[2019-05-07 09:25:01,167] ERROR in app: Exception on /api/v0.2/data/var [PUT]
Traceback (most recent call last):
TypeError: 'coo_matrix' object is not subscriptable
```

I didn't have this problem before, started to see with v0.9.1, tried with the same files I'm working with and having same error.
This is one of the datasets that I'm working with: https://drive.google.com/open?id=14LCnlBRwz_gZRvd0p9NzNp_kuHylbcms

**Comment by bkmartinjr** [comment]
Thank you @cakirb -- really appreciate the test data set.

While I am debugging this, you may be able to work around the bug by using a CSC (columnar) sparse format for the expression data (X), instead of a CSR format.  cellxgene is generally faster if you use formats that allow fast columnar access, as most of the data access is along that axis.

**Comment by csweaver** [comment]
Hi @cakirb! I've just created release 0.9.2 which should fix your issue. I've done some light testing on the dataset you provided and differential expression worked. LMK if you are still having issues.

**Comment by bkmartinjr** [comment]
One note for posterity - cellxgene is primarily accesses data in a columnar manner.  Performance will be better when dense or CSC encoded matrices are used.   CSR will be slow for mid-sized data sets(eg, 50K+ cells), and will be extremely slow for large data sets.

**Comment by cakirb** [comment]
Hi, thanks for the fix! By performance, you probably mean computing differential expression only, am I right? @bkmartinjr - At the beginning, I thought the loading times don't differ that much, because we mainly see the UMAP plot and other metadata other than the matrix. After you said CSR is much slower in large data sets, I tested the loading speed of the same dataset with CSC and CSR formats, and CSC was not that fast and actually a bit slower to load.

```
time cellxgene launch embryo2m_1m_CSR.h5ad
[cellxgene] Starting the CLI...
..
..
[cellxgene] Type CTRL-C at any time to exit.
^C
real	0m21.916s
user	0m6.528s
sys	0m6.327s

------------------------------

time cellxgene launch embryo2m_1m_CSC.h5ad
[cellxgene] Starting the CLI...
..
..
[cellxgene] Type CTRL-C at any time to exit.
^C
real	0m23.857s
user	0m10.217s
sys	0m7.477s
```

**Comment by bkmartinjr** [comment]
I added performance-related background info in #739 if you want details.  TL;DR: in the current cellxgene, startup data loading is roughly the same for any encoding (except gzip'ed, which is always slower).   Where we see speed differences based upon encoding is in the fetch & display of expression histograms (data from the X matrix), which is substantially faster in ndarray/dense or CSC encoding.   Of course, for smaller datasets, anything works fine, as decoding overhead does not dominate.  So in the above test dataset, the CSC speed win is measurable, but perhaps not enough to warrant the bother of re-encoding the dataset.  I have test datasets (~1M cells, 10K's of genes), where CSC is the only usable encoding.

**Comment by cakirb** [comment]
Many thanks for the details @bkmartinjr. It seems better to convert the matrices into CSC. Gonna be doing that for the other datasets I'll work on. Thanks again...

**Comment by bkmartinjr** [comment]
@cakirb - very happy to help.  The only caveat I'll add is that I am currently trying to better characterize our advice, and will update the [FAQ ](https://chanzuckerberg.github.io/cellxgene/faq.html)as more info is available.  If you find any interesting performance observations, please let me know (either on github, or feel free to join our slack channel).
