### ISSUE TITLE
Add sparse dataset to testing

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#756]
Add a small sparse formatted dataset and ensure related scanpy engine tests run against it. Add tests as needed.

**Comment by bkmartinjr** [comment]
@csweaver - suggest assigning to @seve 
Would be very good to get this into our test pipeline.

**Comment by sidneymbell** [comment]
LMK if you need a hand locating a suitable dataset.

**Comment by csweaver** [comment]
Oh, I had this almost done, I just dropped the ball trying to do it more elegantly. I'll submit what I had.
