### ISSUE TITLE
support for violin plots

### ISSUE THREAD

**Issue by fidelram** [chanzuckerberg/cellxgene#762]
Frequently, the distribution of the expression of a gene wants to be compared across samples, tissues, cell types etc. (any categorical data). I would like to know if support for such visualizations would be possible for cellxgene. Particularly, violin plots to show gene expression across  categorical values are common.

Using scanpy, such a plot is produced as follows:
```PYTHON
# load sample data
adata = sc.datasets.pbmc68k_reduced()
sc.pl.violin(adata, 'CST3', groupby='bulk_labels', rotation=90)
```
![image](https://user-images.githubusercontent.com/4964309/57521968-da97b080-7321-11e9-9b3c-5cbb21b63d3d.png)

My suggestion would be that if the user selects a gene for coloring, then, next to each of the categorical metadata an option would appear to show a violin plot for that category and the actual gene being colored.

**Comment by colinmegill** [comment]
Thank you for this! In fact, I believe we have a circular reference here as @sidneymbell is linking back to you in issue #616 :)

**Comment by colinmegill** [comment]
@gokceneraslan and I spoke about categorical vs continuous heatmaps - as in seeing 100 diffexp genes * 40 clusters. Perhaps both features - heatmap & violin - are accessed in a similar manner to what you describe.

**Comment by neuromusic** [comment]
> My suggestion would be that if the user selects a gene for coloring, then, next to each of the categorical metadata an option would appear to show a violin plot for that category and the actual gene being colored.

Isn't this violin plot a gene plotted on the y-axis and a categorical variable on the x? This strikes me as very similar to our existing UI for making scatterplots between genes...

We could extend the "plot x" / "plot y"  buttons that appear on genes to categorical metadata such that  the user would click "plot x" on the categorical field and "plot y" on the gene to render this kind of plot.

**Comment by colinmegill** [comment]
It is indeed.
