### ISSUE TITLE
psutil has no wheel on MacOs

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#771]
the introduction of psutil as dependency (in 0.10) break the MacOs install, as there is no pre-built macos wheel.  We need to make the dependency optional or platform specific, and make the warning that depends upon it conditional.

h/t to @csweaver for diagnosing this

**Comment by csweaver** [comment]
See https://github.com/giampaolo/psutil/issues/824 for more info

**Comment by bkmartinjr** [comment]
Resolved in 0.11 by removing the feature.
