### ISSUE TITLE
Document way(s) for users to deploy cellxgene to the web

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#791]
Deploying cellxgene to the web is often requested by users who wish to share their data and visualization with others (which we totally encourage :), but [this is not a core functionality of cellxgene](https://github.com/chanzuckerberg/cellxgene/blob/master/ROADMAP.md). Several groups have developed effective solutions for doing this on their own, and it would be great to document these methods in (an) easy to follow, step-by-step tutorial(s) for the community's benefit.

_It should be noted that this documentation will be provided as a guide for interested users, but **the cellxgene team does not officially support / troubleshoot / maintain any web deployments at this time**. Furthermore, there are many potential and valid approaches to cellxgene web deployment; inclusion in the tutorial is not necessarily an endorsement of any one approach, but simply provided as a pointer to one/some effective way(s) to do so._

**Comment by maximilianh** [comment]
Hmm... random thought: we could provide a single-command converter to save
a cellxgene view to a static cell browser instance...?

**Comment by sidneymbell** [comment]
This was requested by 3 different potential / current users at the ISMB poster session tonight. 

These were computational folks, so they were mostly OK with doing it themselves, but wanted some guidance. The heroku solution was of interest to 2 of them, the last one wanted a different solution suitable for private datasets.

**Comment by bkmartinjr** [comment]
See issue #875
