### ISSUE TITLE
exporting data

### ISSUE THREAD

**Issue by aopisco** [chanzuckerberg/cellxgene#798]
It would be incredibly useful to be able to export the figures as pngs or vectorial figures. I've shared our dataset with collaborators and they are either taking screenshots or asking me for hi-res/vectorial pictures. The figure export is of critical importance to our current project. On the topic, if we could save the differential expressed genes to a file (csv?) that would also be highly appreciated!

**Comment by colinmegill** [comment]
Hi @aopisco, thanks so much for this. It would be super helpful, as a start to the conversation, if you could share (by pasting into this issue would be fine) what the scientific collaborators are screenshotting. Would you mind sharing a few examples? Feel free to comment, as well, on how you think the images could be better - ie., 'we really need an axis label to show it's umap'. This could be a 'figure mode' which toggles those on and off, ie., #136 

This is perhaps two issues - we might break out the diffexp export into its own issue for continued discussion and rename this issue to reflect hi-res image capture for figures.

Related: #461, #607, #97, #136

**Comment by ambrosejcarr** [comment]
This is not a priority at present, but interested users can check out the [cellgene-vip](https://github.com/interactivereport/cellxgene_VIP) extension, which provides some of this functionality.

**Comment by colinmegill** [comment]
Reopen to reassess in 2023 per user request

**Comment by pratarora** [comment]
it would be instrumental to have the feature as it also helps reuse data from published data directly without installing it locally.

**Comment by MaximilianLombardo** [comment]
Hey @pratarora - were you referring to this suggested feature?

> export the figures as pngs or vectorial figures

or this one?

> save the differential expressed genes to a file (csv?)

Can you let us know a little bit more about how this would help your workflow?

**Comment by pratarora** [comment]
I had more PNGs in mind. There are published datasets and it doesn't make sense to download the data and run cellxgene locally just to get an expression pattern for one/two genes when you can already see them on the app.  For example - you want to make a point that a certain gene is expressed in this cell type- it has been shown in this, this and this dataset. You don't want to reanalyse all the datasets just to make this statement, but making this can save so much time.

**Comment by MaximilianLombardo** [comment]
This is on the roadmap and is being worked on! We are currently planning to have this feature available by the end of July (2024) in our [CELLxGENE Explorer](https://github.com/chanzuckerberg/single-cell-explorer). Keep a lookout for a tool in the toolbar around that time!

**Comment by ernohanninen** [comment]
I am hosting cellxgene (version 1.3.0) on our lab's server. The functionality of saving graphs as PNGs is not implemented in the most recent pypi cellxgene version. I can see that datasets hosted directly on cellxgene platform (https://cellxgene.cziscience.com/e/dbb4e1ed-d820-4e83-981f-88ef7eb55a35.cxg/) have the functionality (camera icon) to save the figures as png
