### ISSUE TITLE
Hosted Docker image 

### ISSUE THREAD

**Issue by anton-khodak** [chanzuckerberg/cellxgene#799]
Hello,

it would be great if cellxgene had a maintained Docker image on Dockerhub or other public Docker repository, so that each PyPI version had a correspondent image. We have our own image build: https://quay.io/repository/cellgeni/cellxgene, but it would be perfect to hand over the maintenance to the core team.

**Comment by csweaver** [comment]
Hi @anton-khodak good idea, I'll bring this up to the team to see about adding that to releases.

**Comment by mckinsel** [comment]
@ambrosejcarr fyi we're not publishing images to dockerhub anymore. The two approved options are Github Package Registry or AWS ECR.
