### ISSUE TITLE
Further communicate the cell population a centroid represents

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#811]
Currently centroids are only displaying the categorical value the centroid represents as a text label.  The app may further benefit from additional representations of the categorical value.

Final implementation:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/8716829/61008340-1c45d700-a324-11e9-91e6-e10d16ef493d.gif)

Potential methods include:

- Popping the cells forward on the z-axis
- Draw an encompassing circle around the cells
   - A concave hull
   - Ellipse with width/height showing max/min x and y
   - Radius displaying the value's population
- Grow the represented cells
- Shrink the non-represented cells
- Indicate the displayed value on the sidebar via styling

Screenshots showing a circle label based on population with sidebar styling:
![Screen Shot 2019-06-11 at 3 16 36 PM](https://user-images.githubusercontent.com/8716829/59310702-180e9700-8c5c-11e9-8520-7e89fe894140.png)
![Screen Shot 2019-06-11 at 3 16 27 PM](https://user-images.githubusercontent.com/8716829/59310703-180e9700-8c5c-11e9-9f43-cfdd1b32370d.png)

**Comment by sidneymbell** [comment]
I'm good with the centroid labels (PR809) going into a release as-is, on the condition that this issue needs to be slated for one of the next two-ish releases. 

If a group of cells is scattered, the label being placed in the middle of them can be actively deceptive as seen in this example (e.g., none of the orange cells directly under the label "Fat" actually belong to that group).
![deceptive-label](https://user-images.githubusercontent.com/12618847/59634201-0f5a0d00-9103-11e9-8c68-992985c6110c.gif)
