### ISSUE TITLE
Allow launch to accept url too

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#815]
Allow cellxgene launch to accept a URL to a h5ad file, currently it only accepts file paths. This would simply be a convenience as it would just read the whole file from the url and not fancy streaming, etc. 

(came from H2 planning)

**Comment by sidneymbell** [comment]
Jonah was chatting with a user this week, and they mentioned that this would be a big win. They have sensitive data that cannot be removed from the server, but that they would like to be able to explore by pointing cellxgene at the relevant URL.

**Comment by colinmegill** [comment]
+ @ambrosejcarr

**Comment by seve** [comment]
Unless @bkmartinjr can complete this, I'd like to push this to a further release.  I self-assigned this due to its potential grouping with #875

**Comment by bkmartinjr** [comment]
@sidneymbell - you said:

> ... sensitive data that cannot be removed from the server, but that they would like to be able to explore by pointing cellxgene at the relevant URL.

How would this work in practice?   At a minimum, any data cellxgene presents to the user must be available in the browser -- with our current implementation, that also means the necessary data is proxied by the CLI/back-end.   This means that it must be pulled (read) from the server by the CLI/backend, and sent to the browser/front-end.

Is the assumption that the sensitive parts of the data are not needed by cellxgene (for exploration)?   Or simply did you mean "remove" as in "delete"?    Or am I misunderstanding?  TY!
