### ISSUE TITLE
Be clever about the z-stack

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#817]
I believe the current z-position of the cells is random. In the future, we could think about a few "clever-er" ways to leverage this. For example:

1) Rank cells based on the 3rd component of the embedding and use the rankings as z-position
2) Rank clusters by size, bring smaller clusters to the front
3) Push NaN's (both clipped values and NaN in the data) to back

**Comment by bkmartinjr** [comment]
Assigning to Lia.  Please define what we want, or close if no change required.
