### ISSUE TITLE
Document Front-end UI Features

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#818]
We do a good job documenting file format and launching the app, however there is a lack of documentation on the UI features on the front end. 

Lets create a page on the website to show the major front-end features and how to use them. Bias should be on stable features to avoid stale documentation.

**Comment by liaprins-czi** [comment]
@sidneymbell @colinmegill Here is a link to my proposal for the Gallery GIFs:
https://docs.google.com/document/d/1L9PFv1M7TjiSiP_6yQKJzX10OEwmJye0tdDMUcqiTWU/edit?usp=sharing

I have added comments to that doc that explain some of the reasoning. I can update the gallery docs page if we agree on this direction.

**Comment by sidneymbell** [comment]
Lia --

These are FANTASTIC, thank you so much for putting these together!!

SB


Sidney Bell, PhD
Computational Biology
Chan Zuckerberg Initiative

she, her | twitter <https://twitter.com/sidneymbell> | github
<https://github.com/sidneymbell> | calendar
<https://calendly.com/sidneymbell>

**Comment by sidneymbell** [comment]
Fixed via #1030
