### ISSUE TITLE
Security dependency update

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#828]
Fix security warning for JS dependency.

**Comment by bkmartinjr** [comment]
@csweaver, @seve - I believe this is fixed.  Please close if you agree.

**Comment by csweaver** [comment]
![Screen Shot 2019-08-14 at 10 25 56 AM](https://user-images.githubusercontent.com/1517263/63041993-f4dfae00-be7d-11e9-8d2d-887ff05e8c40.png)
