### ISSUE TITLE
sort the categories

### ISSUE THREAD

**Issue by aopisco** [chanzuckerberg/cellxgene#830]
given a given gene, sort the categories according to the number of cells that express the marker

this should be optional

**Comment by colinmegill** [comment]
Thanks so much @aopisco. For clarity from the meeting, we might say that given the category tissue and the gene Apod, we want to sort the labels (heart, lung etc.) by mean/median expression level - does that capture it?

**Comment by signechambers1** [comment]
Closing as a low priority but if we get more asks for this functionality we can revisit. Thank you!
