### ISSUE TITLE
add code of conduct to repo

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#832]
Add a code of conduct (Contributor Covenant is the recommendation)

**Comment by neuromusic** [comment]
can we assign this to @nacin? :D

**Comment by nacin** [comment]
This is actually "done" thanks to this [org-wide file](https://github.com/chanzuckerberg/.github/blob/master/CODE_OF_CONDUCT.md). But we should:

 - [ ] Add a note to the "contributing" section in the README.md, like done [here](https://github.com/chanzuckerberg/sorbet-rails#contributing)
 - [ ] move/copy the bulk of the "contributing" section to a CONTRIBUTING.md

GitHub picks up both the code of conduct and CONTRIBUTING.md files and does various special things with them, like this when creating an issue:

![screenshot of new issue notice linking to these files](https://user-images.githubusercontent.com/272784/60549622-4111cd00-9cda-11e9-9dc1-f593477309cc.png)
