### ISSUE TITLE
Add toggle for mini histogram y axis scaling

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#836]
@seve and @colinmegill did beautiful work implementing mini histograms to visualize continuous distributions stratified by categorical values! 
Just documenting the discussion re: y axes and a suggested future enhancement.

We were debating whether to set the ymax of each histogram to either:
1) the tallest bin in _each_ category (in theory, better for visualizing each mini histogram; current implementation)  
2) the tallest bin in _any_ category (in theory, better for comparing between mini histograms)

As a simple example, we can look at `Eif2s3y`, a gene expressed mostly in male mice, clipped to the (80,100) percentiles in tabula muris. 

When we scale the y axis to each category (option 1), we get:
![image](https://user-images.githubusercontent.com/12618847/60824400-63826b00-a15e-11e9-98b1-c336a5a173ef.png)
Here, we see that this gene is strongly expressed in a subset of male mice, but not in any female mice. 

However, this option does discard context within the overall dataset.

When we force the y axes to be the same for all categories (option 1), we get:
![image](https://user-images.githubusercontent.com/12618847/60824427-6c733c80-a15e-11e9-8c7b-0ccb08562538.png)
This is less informative in that it would be easy to miss the small subset of cells from male mice that express this gene. However, it does highlight the fact in the first set of plots above, it would be easy to miss the fact that the y axes differ by two orders of magnitude. 

To address this, I concur with the biohub folks' suggestion of a toggle (perhaps living within the `visualization options` menu, alongside the clipping option). 

That said, I don't feel it's super urgent. Here, the most important scale is the x axis, which is already uniform between plots.

**Comment by colinmegill** [comment]
Thank you @sidneymbell. A classy way to implement this is in text, since we're already explaining the axes in the popover:

![image](https://user-images.githubusercontent.com/1770265/60847769-d1e41f00-a198-11e9-8fde-e735ae98e963.png)

After the explanation of y axis, we might add the text, as a blue link button: `normalize the y axis to the maximum value across all categories for uniformity`, or something shorter that still gets the point across.

**Comment by signechambers1** [comment]
Closing as a low priority
