### ISSUE TITLE
Include histogram data in popup

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#846]
It would be nice to include data about the x and y axis in the mini-histogram popups.

Possible implementation:
![image](https://user-images.githubusercontent.com/8716829/61161919-0585b880-a4bb-11e9-8c84-5d26818dad52.png)

This is probably going to require refactoring of the occupancy component to allow for data flow.

**Comment by bkmartinjr** [comment]
@liaprins-czi - can you and @seve decide if this warrants a UI change?  Close if not, or assign to 0.13 if it does.

**Comment by liaprins-czi** [comment]
I think I want to look at the formatting of these tooltips when we get to the gene function tooltips that @sidneymbell has brought up recently (#96 ). I want to make sure these two tooltips (if that is what we use for the gene function as well) have compatible designs. If these need to change, I will document here and work with @seve .

**Comment by seve** [comment]
I'm looking at starting this up soon.  Any design updates @liaprins-czi ?

**Comment by liaprins-czi** [comment]
@seve Colin and I decided this is not important enough of an issue to be in 0.13.

**Comment by liaprins-czi** [comment]
Just FTI, here is where I started design explorations (even though we took this out of 0.13):
https://www.figma.com/file/JB7QiFCdAQpMrdFhNt5Wpi/846-Histogram-data-in-tooltip?node-id=0%3A1

**Comment by signechambers1** [comment]
Closing as a low priority, the current histograms meet the core user need.
