### ISSUE TITLE
Add arbitrary genes 

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#85]
to evaluate expression and use as selection mechanism (continuous metadata)

![image](https://user-images.githubusercontent.com/1770265/41437135-965f128e-6fd8-11e8-8bfa-00afbb2cdda9.png)

**Comment by sidneymbell** [comment]
Awesome. I believe this addresses the core functionality of Ben Humphrey's comment below: 
>I spend alot of time trying to figure what what cell clusters are by doing differential expression. But in some cases, it would be more helpful to ask what gene expression similarities exist between clusters. This would help me determine whether a particular cluster is a new cell state and an entirely different cell type.

**Comment by sidneymbell** [comment]
Hmm. I guess my concern is that the number of non-differentially-expressed genes is super, super long (depending on where you put the cutoff). I'm not sure that's actually helpful. 

I _suspect_ that what he was wanting to do was to see whether known marker genes were expressed at similar levels in two clusters as a heuristic for cell type/state. If this is the case, then being able to directly color by those genes should satisfy the underlying need. But yes, good to get more clarity on this; I'll follow up to ask when we're ready for the next round of feedback.
