### ISSUE TITLE
Visualize additional embedding components as continuous data

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#859]
Currently, we take the first two components of a given embedding to specify the layout, discarding additional components.

Loyal made the excellent suggestion to instead transfer these additional component(s) to continuous metadata to enable visualization via color scale. 

Levels of possible implementation:
0 - On load, automatically take the 3rd component of an embedding and add it to `adata.obs` as `embeddingName[:,2]` or something similar.
1 - Add CLI arg to specify how many additional components to transfer over to `adata.obs`
2 - Actually look by default for extra available dimensions in each embedding in `adata.obsm[X_foo]` and display these alongside continuous metadata, bypassing the `adata.obs` hack.

**Comment by Loyale** [comment]
Another tangiential thought. First 2 dims by default seems to make sense for 2D embeddings or things like PCA where the order has meaning.  But for other embeddings (e.g. latent space embeddings w/ >3 dims) it would be nice to allow/select a different set of dims for the X,Y points on the scatterplot as well.

**Comment by signechambers1** [comment]
Closing as a low priority, if we get more similar feedback we will reconsider. Thank you!

**Comment by ambrosejcarr** [comment]
Worth noting that there is a hack that can be accomplish this ask by creating additional embeddings in the adata file. It does not enable _selection_ of dimensions to visualize in an embedding with `d > 2`, but you could create `adata.obsm["X_pca_2_4"] = pca[[:, [2, 4]]` to view pca components 2 & 4, if that were important. You would need to pre-discover this outside cellxgene, however.
