### ISSUE TITLE
reset graph button should be disabled if nothing has changed

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#86]
Unsure as of yet what the flag is, cc @bkmartinjr

**Comment by bkmartinjr** [comment]
Clarification:  by "nothing changed", do you mean no selection/filter, or do you mean world !== universe?

**Comment by bkmartinjr** [comment]
this is pretty easy - just enable if world !== universe.

**Comment by bkmartinjr** [comment]
@colinmegill - is this now obsolete due to the UI change?

**Comment by colinmegill** [comment]
I don't think so - we're changing it to `clear selection`, correct? So can't clear selection if there isn't one?

**Comment by bkmartinjr** [comment]
oh, right.   You are correct.

So if you want to disable it, just use `worldEqUniverse()` in world.js (will need to be exported and added to the tests for world).

**Comment by colinmegill** [comment]
@bkmartinjr we may have had this, but I think it's regressed with the world universe changes

**Comment by bkmartinjr** [comment]
I'll fix.
