### ISSUE TITLE
Integration/interconnection with JupyterLab (as an extension?)

### ISSUE THREAD

**Issue by jamestwebber** [chanzuckerberg/cellxgene#860]
Ben Zaitlen from NVIDIA was showing @colinmegill and I the [pangeo.io](pangeo.io) computational infrastructure and we were discussing how a similar approach would be useful for HCA-type projects. Colin requested that I write this up as an issue for posterity.

In our discussion we talked about three major use-cases for cellxgene:
1.  Data visualization/exploration for researchers with tissue expertise.
2. Interactive exploration for computational researchers who are iterating on analysis methods.
3. Finally, the publication use case of sharing datasets, à la the [Tabula Muris Senis](https://tabula-muris-senis.ds.czbiohub.org) website.

I think the last two (and potentially all three) of these use-cases would be strengthened by interoperability with JupyterLab and it's worth a close look into what that would entail. It's built with JS extensions in mind, so I think it's viable.

In the context of 1 and 2, I think having a really nice interactive viewer integrated with a jupyter notebook would have been very useful for analysis with Tabula Muris data. And if we had such notebooks, we definitely would share them as part of the publications, similar to how we shared annotation notebooks and figure notebooks before, but with the addition of interactive visualization that allows people to tweak parameters.

**Comment by jamestwebber** [comment]
Bumping this issue because I'm in a call with @bkmartinjr and @aopisco and it reminded me.

**Comment by signechambers1** [comment]
This has also come up with the creators of FASTGenomics and Cellxgene VIP

**Comment by ambrosejcarr** [comment]
Thanks for this write-up @jamestwebber! Closing since this is not currently a priority for the team.
