### ISSUE TITLE
Automatically validate categorical metadata against ontology reference

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#864]
Thanks to Angela Pisco of BioHub. Ontology lookup for validation: https://www.ebi.ac.uk/ols/ontologies/cl, 

* this could `lint` categorical metadata on load as a warning/suggestion in terminal or UI
* this could be integrated into the UI for just new annotations
* this could be integrated into the UI for all categorical metadata

**Comment by colinmegill** [comment]
http://www.obofoundry.org/
http://www.obofoundry.org/ontology/cl.html
https://raw.githubusercontent.com/obophenotype/cell-ontology/master/cl.owl

**Comment by bkmartinjr** [comment]
@colinmegill - could you update or close this given the current state of our experimental ontology work?   Is it resolved as of #1179?

**Comment by colinmegill** [comment]
Resolved as of #1179
