### ISSUE TITLE
Wait to surface "No matching genes" warning until at least one character is typed

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#865]
...and if it’s a letter character, there probably _will_ be a gene found.

<img width="237" alt="shouldn't scold me when first input cursor" src="https://user-images.githubusercontent.com/53277128/62385648-852b0400-b50a-11e9-885e-011aa4bb9020.png">

**Comment by seve** [comment]
@liaprins-czi any suggestions on what should be in the results when there is nothing in the query?

**Comment by seve** [comment]
I could just default to nothing being shown

**Comment by liaprins-czi** [comment]
Yes, I think there should not even be that little flyout at all, until the user types something.
