### ISSUE TITLE
“Bulk add genes” should recognize lowercase inputs

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#866]
“Bulk add genes” doesn’t recognize lowercase, but “Autosuggest genes” does. We shoul make it consistent, and in favor of the more inclusive experience: “Bulk add genes” should recognize lowercase inputs.
![Bulk add genes  doesn't recognize lowercase inputs, but  Autosuggest genes  does](https://user-images.githubusercontent.com/53277128/62385878-19956680-b50b-11e9-8fc2-510a880f76cd.png)

**Comment by seve** [comment]
`autosuggest genes` actually does not accept lowercase gene names, but it will suggest the correct gene from lowercase entries.

Looking into brought into light that the equivalent of that error for `autosuggest genes` does not exist and clicking add on a non-existent gene just clears the query with no error.

Should we mark #866 as not a bug and create a new issue for the aforementioned bug? @colinmegill

**Comment by seve** [comment]
This issue has brought to light the following bug:
* `Add gene` button on autosuggest genes does not properly work

**Comment by seve** [comment]
Instead of creating a new issue this issue will also address the `add gene` button not properly working
