### ISSUE TITLE
Add color mapping to the bar chart itself (the one that is selected to control the color of the main vis)

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#867]
Current bar chart, selected to apply color to main vis, but not colored itself
![color should apply to the graphs too](https://user-images.githubusercontent.com/53277128/62400580-8d983480-b534-11e9-964b-c33ce43f68c1.png)

Example link to colored bar chart, from Colin:
https://community.plot.ly/t/colorscale-in-bar-chart/15509

**Comment by Donaldpherman** [comment]
I believe this can be closed out.
