### ISSUE TITLE
Update pan and zoom button's tooltip text to be more instructive

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#868]
Change tooltip text to "Drag to pan and zoom to scroll" to help explain to users about how the zoom functionality works.

**Comment by bkmartinjr** [comment]
@liaprins-czi - can you propose text?

**Comment by liaprins-czi** [comment]
Would "Drag to pan and zoom to scroll" work?

**Comment by bkmartinjr** [comment]
@liaprins-czi - is this final, ie, should I make the change?

**Comment by liaprins-czi** [comment]
Actually I just realized got the last half of the phrase backwards; it should be:
*Drag to pan, scroll to zoom*
And yes you can make the change.
