### ISSUE TITLE
Create and organize cellxgene logos + wordmarks

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#884]
Currently logos + wordmarks live in this Google Drive folder:
Shared Drives/Technology/Science Tools & Platforms (STP)/cellxgene/Design/Logos
and some more one level deeper in .../Logos/cellxgene iconography

- [x] Get Photoshop (Lia)
- [ ] Verify sizes + color combos (and transparent BG or note, etc) needed for logos, and for wordmarks
- [ ] Create and/or find originals to modify if needed
- [ ] Export
- [ ] Organize where they live
- [ ] Look across everywhere a cellxgene logo or wordmark might live and see whether it's using the correct version; document those that are not
- [ ] Figure out how to update to correct version

**Comment by signechambers1** [comment]
Closing as low priority
