### ISSUE TITLE
color-by mode switch changes left side bar layout unecessarily

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#891]
If I change the color-by mode (of a gene), it changes the layout of categorical items, causing the left side bar vertical size to change.  This bouncing of size (bigger, smaller, bigger, ...) is super distracting.

root cause seems to be the layout of the continuous occupancy histogram in the categorical items.

without color-by:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/2ff15b46-6cdf-4e14-b0eb-cada687717f7)

clicking color-by on the second gene:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/74b13d5e-edb7-416c-8648-4135af947095)

Note the wrapping of text in the louvain category "FCGR3A+ Monocytes".  This causes the entire column to be bigger. 

Ideally, the vertical height of the side bar would not change due to view modes like color-by or what items are selected.

My suggestion is that we clip / truncate the category label names in some way, and perhaps use a tooltip to show their entire name if clipped.

**Comment by colinmegill** [comment]
Currently we render/hide the canvas on which we render occupancy & histograms. We can keep it and `ctx.clearRect(x, y, width, height)` instead

**Comment by bkmartinjr** [comment]
in the particular example above, the issue is caused by the label height increasing/descreasing, rather than an issue with the histo canvas visibility.

**Comment by colinmegill** [comment]
I believe it is the case that the label changes size because of the lack of presence, and then presence, of the canvas.

**Comment by liaprins-czi** [comment]
I just had the `feature-annotations` branch open and it was not doing this issue; instead the characters that would have been forced to run down to the next line in the presence of the tiny histogram were already down on the next line. In master branch, however, it is doing the jumping.

What I think would be ideal though, is if the sub-label's name filled the entire length until I color by a gene and the tiny histograms need to appear, in which case the sub-label's name shortens with an ellipsis at the end to make room for the tiny histogram.

Here are some quick mocks:

Not coloring by gene, full sub-label shown (note the hovered on sub-label to compare to next image)
![color-by-gene off](https://user-images.githubusercontent.com/53277128/63533324-67294180-c4c1-11e9-91a9-60a75ed1c6d2.png)

Now, coloring by gene is on, and sub-label truncates with ellipsis (again, note the hovered on sub-label to compare to previous image)
![color-by-gene on](https://user-images.githubusercontent.com/53277128/63533438-ace60a00-c4c1-11e9-9cfc-94483bda7558.png)

I don't know how difficult it would be to implement this sort of dependent behavior, though?

**Comment by colinmegill** [comment]
Love it! This may actually be CSS3, though I've never tried it. For posterity:

`text-overflow: clip|ellipsis|string|initial|inherit;` 

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by colinmegill** [comment]
@liaprins-czi thinking about implementations... here's an edge case: very long titles, in which the beginnings are very similar:

![image](https://user-images.githubusercontent.com/1770265/64207117-d05d6d00-ce50-11e9-8b94-188720242082.png)

**Comment by colinmegill** [comment]
The annotation branch now always breaks the words, so there's no 'bouncing' effect on color by. I'm not against leaving it like this, so the whole word is always visible, and it never moves when we show occupancy or mini histograms.

**Comment by liaprins-czi** [comment]
What about the idea of the ellipsis being in the middle of the label, so they can see the beginning and end of the label? But I think this could work in the interim and is better than the jumping.

**Comment by seve** [comment]
@liaprins-czi I'm in favor of this idea, but it could just move the problem from having the sole unique values in the trailing characters to having it in the middle.

I am leaning towards truncating over wrapping to keep a standard distance between checkboxes, but I may be creeping out of UX and into aesthetic.

**Comment by liaprins-czi** [comment]
Haha "I may be creeping out of UX and into aesthetic", me too, Seve...

Now here's what I'm thinking is a compromise for both aesthetic and UX:
- We show the full name all the way across, including the space where the minisparkline histograms will appear, and on multiple lines if needed for long names.
- When color-by is turned on, the name truncates with ellipsis in the middle, but name is still allowed to take up as many lines as it was pre-color-by (to prevent jumping, and this way it seems like it should have more room than just one line, at least if it had started with more than one line).

**Comment by seve** [comment]
@liaprins-czi to prevent the solution from getting too complicated I think middle ellipses + a tooltip with full name on hover will solve the issue

**Comment by liaprins-czi** [comment]
Good call @seve (also I completely forgot about the tooltip aspect somehow; agree that should work). Thanks!
