### ISSUE TITLE
add in-app "updates"

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#898]
We should consider adding in-app updates to share critical information and solicit feedback from users.

Example from Slack: 

1. birthday present icon appears when there are unread updates
2. clicking reveals recent updates, each with a link back to a blog post for the announcement

![image](https://user-images.githubusercontent.com/1245615/63557404-74fcb800-c4fd-11e9-852f-79eaddd28b75.png)

**Comment by signechambers1** [comment]
Closing this in favor of new landing page
