### ISSUE TITLE
zoom/pan should constrain extent of pan to maintain data visibility

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#899]
Ideally the pan UI would constrain the extent of the user's ability to pan the graph view such that the graph was always visible.  This prevents the situation where the user pans the plot offscreen, and is "lost" in whitespace.

Alternatively we could add a "recenter" UI function.

**Comment by cornhundred** [comment]
Hi @bkmartinjr we implemented zooming/panning restraints similar to what you're describing in our [Clustergrammer-GL](https://github.com/ismms-himc/clustergrammer-gl) visualization (which also uses regl). Feel free to check out our implementation: https://github.com/ismms-himc/clustergrammer-gl/blob/master/src/zoom/run_zoom_restrictions.js. Let us know if you would like to discuss as we'll be continuing to improve our zooming/panning camera functionality.

**Comment by bkmartinjr** [comment]
@cornhundred - cool, thank you for the pointer!  Cool project.
