### ISSUE TITLE
Using predetermined clusters

### ISSUE THREAD

**Issue by whelena** [chanzuckerberg/cellxgene#901]
I am trying to visualize a dataset that has been clustered and processed using seurat. The data merges 3 different biological replicates and cellxgene seems to be clustering them based on the donor (the cells from each donor are clustered separately). I am wondering if it is possible to use a cluster obtain via seurat and visualize it using cellxgene.

**Comment by bkmartinjr** [comment]
@sidneymbell - could you determine if we need any FAQ updates in this area, and close the issue when that determination is made?  TY!

**Comment by sidneymbell** [comment]
Fixed via #1030
