### ISSUE TITLE
Provide an online sample instance

### ISSUE THREAD

**Issue by grst** [chanzuckerberg/cellxgene#906]
As a user that is comparing different cell browsers and considers using cellxgene, I would find 
it useful if you provided a running online sample instance where I can play around and convince myself that it has the required functionality. 

Similar to http://cells.ucsc.edu/ for the [cellBrowser](https://github.com/maximilianh/cellBrowser).

**Comment by colinmegill** [comment]
Thanks @grst! This is a great idea. 

To solve your immediate problem, see: 

* https://tabula-muris-senis.ds.czbiohub.org/
* especially: https://tabula-muris-senis.ds.czbiohub.org/all/droplet/

I think a reasonable course of action would be to link to the mouse dataset and other featured deployments (like https://www.kidneycellatlas.org/) from our homepage and FAQ. 

We might also feature sample datasets like those included in the repository itself. See: https://github.com/chanzuckerberg/cellxgene/tree/master/example-dataset

**Comment by grst** [comment]
Hi Colin, 

thanks for the links! 
Including them into the FAQ/README would be perfect! 

Cheers, 
Gregor

**Comment by bkmartinjr** [comment]
@sidneymbell - could you add the example sites to the docs.  They provide 90% of the need (example site), and provide a really great showcase for teams publishing data.   Perhaps we could maintain an ongoing list?

**Comment by sidneymbell** [comment]
Fixed via #1030
