### ISSUE TITLE
Developer's guide for adding components

### ISSUE THREAD

**Issue by grst** [chanzuckerberg/cellxgene#908]
A customer asked me to install cellxgene on their server and add additional UI elements to the sidebar. 
I have (a little) experience with react. I looked in the source code of cellxgene and think it's doable. 

However, to make it easier for me and others that want to accomplish something similar in the future, it would be great if you could provide some guidance in a sort of "Developer's guide to add new components". In particular, this should contain: 

- how to add UI elements
- how to access cell metadata
- how to access gene expression
- how to change cell color

I believe a good way to demonstrate this would be to provide a tutorial for the implementation of a "minimal working component", e.g.
- add a slider to the left sidebar that defines a cutoff value
- color all cells with `#detected genes > cutoff` in red and all others in black.

Let me know what you think! 

Cheers, 
Gregor

**Comment by colinmegill** [comment]
Hi Gregor! Thanks for your comment and it's exciting you're thinking about modifying cellxgene — we'll be excited to see what you launch. 

Unfortunately, we're not able to support custom development at the moment. Your suggestions are good, this would be a great way to start supporting that activity, but would be quite a ways out on our present roadmap.

If you pass through the feature request by creating a new issue, and it seems like it's core functionality for computational biology workflows, we could of course consider implementing it. We do try to prioritize user features to make sure we are responsive to immediate needs.

**Comment by bkmartinjr** [comment]
One additional thought to add to Colin's:  we would also be happy to have a conversation with both you and your customer if it helps think through their requirements/use cases, and how we might slate improvements for the roadmap.

**Comment by grst** [comment]
Hi @bkmartinjr, 

I am happy to discuss their use-case with you in private and I probably can also set you in contact with my end-users. Feel free to reach out to me by e-mail (mail at gregor-sturm.de)

**Comment by signechambers1** [comment]
Closing for now since supporting this functionality is not part of our near term roadmap, but if we get similar requests in the future we will reconsider!
