### ISSUE TITLE
Compute enrichment of color scale categories within a group

### ISSUE THREAD

**Issue by joshua-gould** [chanzuckerberg/cellxgene#915]
For example, in the attached image, I would like a p-value (e.g. fisher exact for 2 categories or chi-square for > 2) shown that indicates whether a category in the current color scale is overrepresented in a louvain cluster.
![image](https://user-images.githubusercontent.com/5237151/64708838-40887600-d483-11e9-9f34-c50292f52c1d.png)

**Comment by sidneymbell** [comment]
Thanks so much for the suggestion, @joshua-gould! This is a cool idea. 

A first step could be just making the contingency table available for download (#514); would this help at all?

**Comment by joshua-gould** [comment]
Yes, I think this is a good 1st step. Thanks.

**Comment by signechambers1** [comment]
Closing as a low priority for 2021, if we receive more feedback asking for this functionality we may reconsider!
