### ISSUE TITLE
Combine "Autosuggest genes"  and "Bulk add genes"

### ISSUE THREAD

**Issue by joshua-gould** [chanzuckerberg/cellxgene#923]
Ideally, there would be one input that does autosuggest with comma separated genes.

**Comment by bkmartinjr** [comment]
assigning to Lia for design, Seve for implementation

**Comment by liaprins-czi** [comment]
Here are some sketches where I've outlined how this could work to put these two gene input types together:
https://www.figma.com/file/KWScB4iSEmtedm0Pwfa3ez/Gene-add?node-id=265%3A265

**Comment by signechambers1** [comment]
Closing, this will be replaced with "Create a gene set" as part of [this ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/15)
