### ISSUE TITLE
enable one cellxgene instance to serve more than one dataset

### ISSUE THREAD

**Issue by joshua-gould** [chanzuckerberg/cellxgene#924]

**Comment by bkmartinjr** [comment]
Hi @joshua-gould - could you provide more details on the requirement?   We deliberately did not do this as it is so simple to start cellxgene multiple times.   What is the user story/requirement that makes this useful?

Thanks!

**Comment by joshua-gould** [comment]
Hosting an instance of cellxgene for an entire lab

**Comment by bkmartinjr** [comment]
To clarify - do you want a single view onto multiple data sets, eg, for comparative analysis?    Or are you simply looking for a way to host multiple single-dataset instances of cellxgene?

**Comment by joshua-gould** [comment]
The latter

**Comment by bkmartinjr** [comment]
@joshua-gould - this is in progress.  If wouldn't mind chatting with you about the direction.  If you have time and interest, DM me on the cziscience slack channel and we'll set up a call.

**Comment by bkmartinjr** [comment]
this will be in the next major release with the adoption of the tiledb backend and multi-dataset routes.
