### ISSUE TITLE
layout problems with annotations

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#927]
I've found that some of the manually created annotation categories do not layout correctly in the new UI

Example:

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/41a53543-5f66-463c-bcd2-8c7d0a3c374a)

**Comment by colinmegill** [comment]
Interesting — I see: 

<img width="363" alt="Screen Shot 2019-09-18 at 3 48 27 PM" src="https://user-images.githubusercontent.com/1770265/65192400-d300ba80-da2b-11e9-9ce2-4e9ead19772f.png">

Steps to reproduce what you're seeing there?

**Comment by bkmartinjr** [comment]
Steps to reproduce:
1. start cellxgene with the `10x_mouse_13MM_processed` dataset.  I use:  
> cellxgene launch ../cellxgene-datasets/10x_mouse_13MM/10x_mouse_13MM_processed.h5ad --experimental-label-file foo.csv

2. add a new category called `test`, which duplicates the existing `louvain` category
3. color by `louvain`
4. expand/open the `test` category

and you see:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/777180fd-ceb2-4127-ac40-90b66c8cabc1)

**Comment by colinmegill** [comment]
I believe this can be resolved in @seve's PR. In the file `src/components/categorical/value`, there is a line: 

`width: globals.leftSidebarWidth - 240,`

Changing that to 250 will decrease the width of the label. Now that we're collapsing the name and handling long values more gracefully, it should matter less. We could also move the checkbox to the left by 5 pixels without losing much as well.

**Comment by seve** [comment]
Close in #911
