### ISSUE TITLE
Annotations: Editing a sub-label name within a long list jumps it instantaneously out of sight

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#931]
Maybe this is okay, but I'd expect some sort of communicative reaction / interaction that indicates where it is going (due to alphabetization).

**Comment by colinmegill** [comment]
My first/only idea here is that we animate the scroll position of the left sidebar to the new position of the element.

**Comment by liaprins-czi** [comment]
Here is a link to a screenshot video I took that show my initial idea of how animation could help:
https://drive.google.com/open?id=1pLkhlPcpMcd_CLIkceFV2P0TdSLCRX7j

**Comment by colinmegill** [comment]
Be it resolved... we shall employ a flipper. https://github.com/aholachek/react-flip-toolkit
