### ISSUE TITLE
Annotations: pin `unassigned` to the bottom of the list

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#933]
![image](https://user-images.githubusercontent.com/12618847/65193704-e82c1800-da30-11e9-8829-0de6971fb2d8.png)

**Comment by bkmartinjr** [comment]
@liaprins-czi, @colinmegill  - can you confirm this UI design is what you desire?  It makes a lot of sense to me.

**Comment by liaprins-czi** [comment]
Yes,this is what I want!

**Comment by bkmartinjr** [comment]
Great - will do.
