### ISSUE TITLE
Add metadata header to label CSV

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#936]
Sidney's proposal for a metadata header, to be in the label CSV before the column headers:

```
# Annotations generated on $DATE:$TIME using cellxgene version $VERSION
# Input data file was $NAME.h5ad, which was last modified on $DATE:$TIME
```

@sidneymbell - the only practical "modification" date is the file system mod time, which simply reflects when the file was last copied/modified by the local user (it doesn't mean the contents of the file changed).    I'm not clear how useful this is -- can you clarify what value you think mod time has?

**Comment by sidneymbell** [comment]
>file system mod time, which simply reflects when the file was last copied/modified by the local user (it doesn't mean the contents of the file changed)
Yup. Not a perfect proxy, certainly. But, if I downloaded different versions of the h5ad file from my collaborator on different days (common), this can still be a useful pointer.

**Comment by bkmartinjr** [comment]
One caveat on this design - we support data locators that may not point at data on the local file system (URLs). In some of these cases, it is not possible to determine the last modification time of the H5AD.   The header will omit this information if it is not available.
