### ISSUE TITLE
Long file names cause header to wrap and cover controls

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#940]
As you can see in the attached screenshot, the controls for the pbmc3k file are obscured when the file is renamed to seriously_is_this_a_filename_or_a_journal_entry.h5ad
<img width="399" alt="longfilename" src="https://user-images.githubusercontent.com/789030/65268527-56321700-dae5-11e9-93f3-8292f3838305.png">

**Comment by bkmartinjr** [comment]
I believe this is a duplicate of #871.

**Comment by seve** [comment]
Closed in #909
