### ISSUE TITLE
Keyboard accelerators lacking/not consistently applied

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#941]
I am looking across cellxgene to make sure the keyboard accelerator behavior is applied, expected, and consistent. Related: #1101 Here are areas it is not:

- [ ] "Clip" button: the "return" keyboard key should activate the clip button _only when it is enabled (not disabled)_, see #1101

There are many other ways that keyboard maneuvers can and should be used for accessibility purposes to help users navigate our UI:

- [ ] The `return` key should enable/activate the button or action currently in focus (e.g. pop open the embedding choices dropdown). 

The arrow keys should navigate selection up and down within a currently activated action, 
- [ ] the Embedding Choices list 
- [ ] and the Info menu.

The `escape` key should close any open/focused action: 
- [ ] Close the Embedding Choices list if it was open
- [ ] Close the info menu if it was open
- [ ] Close the Clip tool flyout if it was open

Additionally, the `tab` key should allow focus to jump from one button/action to the next, i.e. across the top bar and then over to the gene search. But it also needs to and through jump to the category/label list, as well as the genes' plot x and plot y buttons. I am going to say don't worry about these right now, I am going to work through the exact steps in more detail and get feedback at the upcoming accessibility workshop, and **I will create a separate issue(s) specifically for:**
- The path of the tab key
- Keyboard accelerators specific to the category/label list
- Keyboard accelerators specific to the genes list (will likely wait until I finalize reformatting + redesign of interactions of this area and take into account nesting for gene lists, etc)

**Comment by signechambers1** [comment]
Closing as a low priority
