### ISSUE TITLE
add useful / complementary tools & systems to our docs

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#942]
There are tools & apps built on top of, or which are complimentary to, cellxgene.  Would be good to highlight these on our docs pages.  For example, [cellxgene gateway](https://github.com/Novartis/cellxgene-gateway) is a possibly useful link out.

**Comment by liaprins-czi** [comment]
I wonder if this could combine into the "Gallery" page (#818 )?
