### ISSUE TITLE
Clipping one histogram at a time

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#946]
![clip](https://user-images.githubusercontent.com/1770265/65716368-dc091180-e053-11e9-9356-cb1797ffbe6c.gif)

https://bl.ocks.org/anonymous/raw/9f8c2edcb5950cac61f1bc3873886ec5/

Thanks to @aopisco

**Comment by liaprins-czi** [comment]
Also related to clipping (from Angela): 
"Can you change the histogram clipping from `int` to `float`? When looking for genes expressed in less than 5% of the cells that would be really helpful."

**Comment by signechambers1** [comment]
This is an issue but closing as a low priority for 2021. If we receive more feedback asking for this functionality we may reconsider!
