### ISSUE TITLE
Clarify which differentially expressed genes are being displayed

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#95]
[Currently](https://github.com/chanzuckerberg/cellxgene-rest-api/blob/master/application.py#L746), we run a ttest and return the N genes most enriched in cell set 1 AND the N genes most enriched in cell set 2. 

While a reasonable approach, this isn't super obvious to the user:
My notes
>Is this showing the N genes enriched in set1 and the N genes enriched in set 2 (yes; unclear), or simply the N genes that differ the most overall?

Ben Humphrey's notes
>When I compute DEG, there are generally relatively few genes that come up - like about 15 or so. Is there a constraint on how many genes are listed? Seems like there should be more.

Potential solutions:  
* Label "top N genes enriched in set 1", "top N genes enriched in set 2"  
* Add a "show more" button to load the next N from each set  
* Add an "export all results" button to save all genes with p-val < alpha to csv

**Comment by bkmartinjr** [comment]
FYI, the current implementation no longer computes the top N from *both* sets, but rather the top N differentially expressed between the data sets.

**Comment by bkmartinjr** [comment]
@colinmegill @sidneymbell - this has been in the active pipeline for a year. Can you update: close, set a milestone, move to backlog, etc?  TY.

**Comment by sidneymbell** [comment]
@bkmartinjr -- this is actually next on my to-do list after docs. Eyeballing 0.14.

**Comment by likejie** [comment]
curious what the status of the development of the "N top genes for differential expression". It would be great to have that. Thanks a lot!

**Comment by sidneymbell** [comment]
@likejie -- This is on my agenda this week! Stay tuned :)

**Comment by signechambers1** [comment]
Closing, we have addressed this issue in the latest cellxgene 0.17.0 release. Check it out! :)
