### ISSUE TITLE
Annotations: When adding a new sub-label, cursor should automatically go into the modal's text bar

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#952]
If I click to "Add a new label to this category", when the modal pops up to name the label, and I start typing, nothing happens! This is because by default the cursor does not appear within the textbox in the modal. This is inconsistent because the cursor does appear automatically in the textbox when creating a new _category_.

**Comment by liaprins-czi** [comment]
Related: when _editing_ a sub-label's name, the cursor should also automatically appear at the end of the textbox, and the the textbox should appear in focus (like it does when I edit the category name inline).

**Comment by colinmegill** [comment]
@liaprins-czi see #959, believe this was resolved without reference to these issues. If solved, can be closed

**Comment by liaprins-czi** [comment]
Yep, this is fixed for me on master now!
