### ISSUE TITLE
Same gene name entered in autosuggest & bulk mode - one works, one fails

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#953]
If I enter a legal gene name in autosuggest widget, it works.  If I enter same name in Bulk widget, it tells me there is no such gene name.

To reproduce:
1. load the 10X_mouse_13MM dataset
2. In bulk, try to load "Sox17" gene -- you get a failure
3. Try same name in Autosuggest and it works

After step 2 (note error toast):
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/94d27791-7e50-4654-9010-d8dd87ec96d5)

After step 3 (note histogram):
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/2e34ea58-69ca-4b6f-b5f1-f8faa9645b42)

**Comment by seve** [comment]
Found the issue:

index of `Sox17` === 0
0 == false

writing PR now
