### ISSUE TITLE
manual labels/annotations need e2e smoke tests

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#969]
Implement e2e (puppeteer) smoke tests for all new UI features.

**Comment by colinmegill** [comment]
- [ ] make sure the system works with anno turned off (experimental labels flag off)
- [ ] with flags on, do the normal tests pass
- [ ] create a couple category 
- [ ] some labels
- [ ] assign cells to labels and make sure numbers are right
- [ ] delete labels 
- [ ] delete categories
- [ ] rename labels
- [ ] rename categories
- [ ] if a label has cells, select a different set and assign it
- [ ] make sure that the stuff saved in the file is what you expect, was everything saved
- [ ] checks that you load the file correctly on startup 
- [ ] all the above tests, but throw in some undo redo, (add a category, undo, then redo)
- [ ] subset the world, all the same tests, but where universe is not equal to world

**Comment by mweiden** [comment]
Update: I just discovered that annotations features do not play nicely with undo/redo. I've documented the issues here https://github.com/chanzuckerberg/cellxgene/issues/1153
