### ISSUE TITLE
Annotations: Need warning message if user tries to name/edit name of category or label to be same as an existing one

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#970]
Nothing happens when I have edited a category name, or edited a label name to match an existing category or label name, respectively. I try to click the check button to save the new name, but nothing happens, because we don't allow two of the same names, which is fine, we just need to communicate why they are not allowed to save it. 

- [x] Warning for _creating_ new *category* with an existing name
- [x] Warning for _creating_ new *label* with an existing name
- [x] Warning for _editing_ new *category* with an existing name
- [x] Warning for _editing_ new *label* with an existing name

When attempt to edit name, and it matches an existing one, could look something like this instead (but for labels, replace "category" with "label", or whatever we call them in the docs/UI...):
 
![Screen Shot 2019-10-03 at 3 32 27 PM](https://user-images.githubusercontent.com/53277128/66168772-0bd78c80-e5f3-11e9-8cd0-0492dd90269f.png)

Also the checkmark button should appear disabled.

When attempting to create a new category or new label it could be the same idea, with orange outline on form field and inserted helper text explaining the error. For the modal, probably could make it a bit taller at all times by default to better accommodate this potential text, so it doesn't "jump" the height of the modal when it inserts).

**Comment by colinmegill** [comment]
> Checkmark should appear disabled

Could you clarify when & where on that bit

**Comment by liaprins-czi** [comment]
Here is the *where* (sorry for confusion for just calling it "checkmark" since there are a lot of those in this part fo the UI):
![Screen Shot 2019-11-06 at 9 39 26 AM](https://user-images.githubusercontent.com/53277128/68323056-7c9e1880-0079-11ea-8a36-68da5141b820.png)

The *when* would be: at the point that the edited name exactly matches an existing label's name (within that same category). 

According to Blueprint, this is how an icon-button might look when it is disabled (so this would be just that little checkmark icon area):
![Screen Shot 2019-11-06 at 9 43 20 AM](https://user-images.githubusercontent.com/53277128/68323272-fa622400-0079-11ea-9131-5903d0975ca1.png)

**Comment by liaprins-czi** [comment]
To be consistent with the warnings that occur when a user tries to create a label or category with an existing name, I think the same style of warning should occur when they try to edit one to have an existing name:
![label edit warning](https://user-images.githubusercontent.com/53277128/68439307-f9192000-017b-11ea-8ce7-d3f0354ba591.png)

Yes, this does require the labels below to "jump" downward slightly to make room for the warning, but I mocked it up to see how jarring it would be and I think it is not a problem at all, as far as I am concerned:
https://www.figma.com/proto/CstDhizlOiQr3dqkkq2KOW/Label-edit-warning?node-id=1%3A2&viewport=1553%2C983%2C1&scaling=min-zoom
If anything it subtley helps to draw attention to the issue.
