### ISSUE TITLE
Annotations: Backgrounds behind new category modal and new label modal are different

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#971]
The background behind the "create new label" modal is much darker than that of the "create new category" modal, making it nearly impossible to see the names of existing labels (which can be important to avoid accidentally trying to name the new label the same as an existing one). It would be great to match the "create new category" modal's background.

![Screen Shot 2019-10-03 at 3 21 54 PM](https://user-images.githubusercontent.com/53277128/66168945-93250000-e5f3-11e9-8476-bfa65f20698c.png)
![Screen Shot 2019-10-03 at 3 21 47 PM](https://user-images.githubusercontent.com/53277128/66168946-93250000-e5f3-11e9-9157-7552a3d3aa8e.png)

**Comment by colinmegill** [comment]
@liaprins-czi I don't repro this, could you check on master that this hasn't been resolved incidentally?

**Comment by liaprins-czi** [comment]
@colinmegill I just checked and this seems to have been fixed somehow! Closing now
