### ISSUE TITLE
Allow multiple scRNAseq assays from same project to be uploaded to CellxGene

### ISSUE THREAD

**Issue by rosalinamae** [chanzuckerberg/cellxgene#975]
Hi all,

I am a computational biologists who recently started adding my departments scRNAseq datasets into CellxGene to share with wet lab biologists. One of the key issues for single cell data has been getting wet lab biologists easier access to the data, so CellxGene has filled a great need!

One of the major suggestions I had for the tool was to allow multiple scRNAseq assays from same project to be uploaded to CellxGene. For instance, using Seurat (a scRNASeq analysis R package) the standard workflow will lead to 3 major data matrices (aka assays) for the project:
1. Raw UMI counts
2. LogNormalized UMI counts (to normalize for sequencing depth)
3. Scaled LogNormalized UMI counts (calculate z-scores so all genes carry equal weight for the downstream analyses)

I assume CellxGene is only displaying the z-scores of the workflow, as the clustering analysis is run on this data. In visualizing these relative expression values, I think it is great for comparing the expression of a gene (or genes) across clusters (cell types). 

However, there are times where the wet lab biologists are interested in looking at absolute expression values, to compare whether gene x is double the expression of gene y. Or to see if the gene x they are looking at is a low expresser (has very few absolute UMI counts).  For this instance, it would be great to be able to switch which assay they are looking at. Potentially other types of graphs may be useful for looking at these absolute values such as violin plots or heatmaps.

I understand this suggestion will entail a lot of work and may be far off the current CellxGene Roadmap, but I thought I would include it here. The ability to look at absolute expression levels seems to be a re-occurring ask from scientists in my department.

**Comment by bkmartinjr** [comment]
Thanks for the idea!

Question about your example: are these different assays, or the same data processed in different ways?   If the latter, cexllgene support for [AnnData layers](https://anndata.readthedocs.io/en/stable/anndata.AnnData.layers.html#anndata.AnnData.layers) might be a more useful approach.  Appreciate your thoughts on this...

**Comment by angelabanks7417** [comment]
Hi Bruce,

It is the same data processed in different ways. One is the raw data, another is normalized on sequencing depth, and another is normalized on sequencing depth + scaled by z-score. I’m unfamiliar with the Anndata layers. If we added different layers to this, how can these be viewed in CellxGene?

Thanks so much for your help.

**Comment by sidneymbell** [comment]
Thanks for sharing! Yes, I think this issue would be resolved in the same way as #689 :)

**Comment by bkmartinjr** [comment]
Unfortunately we do not currently support switching between different views of the same underlying data.  We are considering support for this in a future release, and would welcome any additional input.

FYI, #676 is also related to this underlying need.

**Comment by signechambers1** [comment]
Closing here, linking this use case to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/23
