### ISSUE TITLE
tabula-muris-senis.h5ad file within cxg docs will not download properly

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#979]
Something is wrong with the tabula-muris-senis.h5ad file (the last file in the list on the cellxgene docs' [Data page](https://chanzuckerberg.github.io/cellxgene/data.html)). When I run the `curl` command listed it appears to download but it will not let me unzip it once I locate the supposed file on my machine. When I follow the link within the `curl` command shown (https://cellxgene-example-data.czi.technology/tabula-muris-senis.h5ad.zip) it goes to a strange page with XML and does not begin to auto-download the file (which it should do instead, and that is what happens when I go to the other two files' URLs: https://cellxgene-example-data.czi.technology/pbmc3k.h5ad.zip and https://cellxgene-example-data.czi.technology/tabula-muris.h5ad.zip). 

Also, since we are enabling datasets to be run directly from a URL once we release 0.12, we could consider updating the docs to instead instruct the user to just link to the URLs we provide, rather than running the `curl` command to download the files.

**Comment by sidneymbell** [comment]
Fixed via #1030
