### ISSUE TITLE
Visualize uncertainty

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#98]
Initial ideas as a starting point for iteration:

* Diffexp: run a negative control and report the false discovery rate above the results (don't return any results with p-vals > min observed p-val in the neg. control)
E.g., as Ambrose and others have suggested, randomly subset a single cluster or class of cells into two groups, A and B. Run diffexp on A and B. We expect to see no differentially expressed genes. In reality, these methods (esp. ttests) often have high false discovery rates, and we'll probably get some "hits" back. But, presenting this information provides an opportunity to contextualize how "significant" the user's actual results are.

* Clustering: when coloring by cluster assignment, "gray out" saturation based on certainty of assignment. I'm exploring a few ways to quantify this.

**Comment by signechambers1** [comment]
Closing, not a priority.
