### ISSUE TITLE
Visualising genes from .raw attribute

### ISSUE THREAD

**Issue by arutik** [chanzuckerberg/cellxgene#980]
Hi!

Is it possible to visualise not only the genes in the object but also all of the genes in .raw attribute?

Thank you.

**Comment by bkmartinjr** [comment]
Related to #676 and #689

**Comment by arutik** [comment]
Actually just figured it out, all you need to do is save the full object in the following way:
```
adata_full = anndata.AnnData(X=adata.raw.X,
                            obs=adata.obs,
                            var=adata.raw.var,
                            obsm=adata.obsm)
```

This way the umap coordinates will be preserved and this is equivalent to doing use_raw=True in sc.pl.umap(adata, color=gene, use_raw=True)
