### ISSUE TITLE
Gallery to showcase publicly available datasets for cellxgene

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#983]
Add another page to the [cellxgene docs](https://chanzuckerberg.github.io/cellxgene/) to house a collection of the users/organizations using cellxgene with publicly available datasets, similar in concept to the image gallery in the [napari docs](http://napari.org/gallery/gallery.html).

Things to do + determine:
- Create the list of users/orgs + dataset(s)
- Decide how to display/present on gallery page (screenshots? GIFs of switching between embeddings and/or zooming in?)
- Will we link to the URL of the dataset so that users can directly reference it when launching their own instance of cxg (now that we have the URL method for files)?
- Is the point of this to showcase any _hosted instances_ of cellxgene (e.g. [Sanger](https://developmentcellatlas.cellgeni.sanger.ac.uk), [Kidney Cell Atlas](https://www.kidneycellatlas.org/mature-kidney-immune), [droplet](https://tabula-muris-senis.ds.czbiohub.org/all/droplet/), etc? Or any _dataset_ that is public (but user needs their own instance of cxg to launch and view)?

**Comment by liaprins-czi** [comment]
Idea from Colin:
- Allow ppl to contribute (e.g. via Google Form which can be included)

**Comment by ambrosejcarr** [comment]
Relevant: https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com

Separately, I get lots of questions of the form "has cellxgene been used to visualize ____ data type?" It would be great for the gallery to clearly demonstrate how cellxgene can be used to explore different types of data.

Some common assays I get questions about: 

1. Protein data (either spatial, like CODEX, or non-spatial, like cite-seq, or cytof) 
2. Accessibility data (such as scATAC-seq)
3. Spatial data (spooted like visium, or in-situ like MERFISH). We have some examples that load into cellxgene and can be explored [here](https://starspace.readthedocs.io/en/latest/) but they're not hosted, so there are some barriers to use. 

As far as I can tell, cellxgene is fully compatible with all these data types so long as they're summarized in an observations x features matrix. It would be great to have demonstrations to point to!

**Comment by ambrosejcarr** [comment]
I have candidate spatial datasets. However, I made some curation decisions that I'd be made by original authors. I or Jonah could make some connections. 

I don't have leads for CITE-seq or epigenetics, but Jonah would. 

We will need to make some suggestions about which spatial representations are best for visual exploration in cellxgene. For example, this CODEX dataset projects all replicates into the same global coordinate space centered at zero. As a result, they clobber each other. https://github.com/chanzuckerberg/spatial-warehouse/blob/master/analysis_examples/codex.ipynb

In contrast, this MERFISH dataset embeds the 6 replicates in a global space so they are offset in a 2 x 3 grid, which I find makes them easy to compare (but limits the number you can visually interrogate at one time). https://starspace.readthedocs.io/en/latest/conversion_examples/merfish_moffit_2018_science_hypothalamic-preoptic.html#sphx-glr-conversion-examples-merfish-moffit-2018-science-hypothalamic-preoptic-py

It would be a small but non-trivial amount of pre-work to get this done and should be subject to prioritization. there could be similar "gotchas" in epigenetics work that I'm not aware of, having not been as deeply embedded into those assay types.

**Comment by ambrosejcarr** [comment]
The original purpose of this issue will be fulfilled by the data portal. My comment, on tutorials for single cell data modalities, is now captured in chanzuckerberg/single-cell#59.
