### ISSUE TITLE
Annotations suggestion: have an info.txt as changelog, adjacent to the CSV files

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#988]
Idea from Bruce Aranow to have an `info.txt` (or similarly named) file that logs all changes to the annotations CSVs (e.g. new/deleted categories, new/deleted labels, cell changes within each label.

**Comment by sidneymbell** [comment]
Similar suggestion from Alejandro Sanchez (Pe'er lab) to move the autosave backups to a separate directory called `temp-annotations-backup` or something similar. He was also fine with the idea of deleting these files when the app quits. 

Angela, Alejandro, myself and Lia have all experienced confusion about what the autosaved csv copies (file-1.csv, file-2.csv, ...) mean and find them rather cluttering :)

**Comment by bkmartinjr** [comment]
@sidneymbell - are you planning to roll all of these up into a single proposal / tracking issue?   There are some choices to be made here around UX.

**Comment by bkmartinjr** [comment]
@sidneymbell - could you update this with an indication of which parts are still open?  I think we may have resolved this with the 0.13 rework.

**Comment by sidneymbell** [comment]
@bkmartinjr -- agreed and closed. Thanks.
